---
title: "Cotton - Chinatex Travel"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "May 03, 1979"
editor: visual
cable-date: "May 03, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "AmEmbassy Beijing"
cable-info: "Oct-01 Ara-15 Ads-00 Com-04 Ea-12 /040 W ------------------035911 042039z /66 R 031325z May 79"
cable-subject: "Cotton - Chinatex Travel"
cable-tags: "EAGR, CH, BL, CO"
cable-ref: "PEKING 939"
cable-doc-number: "1979LAPAZ03861"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "COTTON, VISITS, TRADE AGREEMENTS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. **Summary:** In late March the delegation from the Cotton Import Department of CHINATEX (REFTEL) visited Bolivia. The delegation did not purchase any Bolivian cotton but indicated interest in future purchases. Also, the delegation did invite several members from the Bolivian Cotton Producers Association, ADEPA, to visit the PRC in the immediate future.
2. **Comment:** Recent, severe flooding had an adverse impact on Bolivia's 1979 cotton crop. Because of the resulting low yields, the CHINATEX delegation probably decided to postpone purchases of Bolivian cotton.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ03861

- **Date:** May 03, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** COTTON, VISITS, TRADE AGREEMENTS