---
title: "Economic Reporting: Cerp 5711 - Production, Assembly And Registration Of Motor Vehicles, Cy1973."
author: "Stedman"
date: "September 09, 1974"
editor: visual
cable-date: "September 09, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 4163"
cable-info: "Oct-01 Ara-16 Iso-00 Eb-11 Drc-01 Rsc-01 Dote-00 /030 W --------------------- 076984 R 091829z Sep 74"
cable-subject: "Economic Reporting: Cerp 5711 - Production, Assembly And Registration Of Motor Vehicles, Cy1973."
cable-tags: "ETRN, ECRP"
cable-ref: ""
cable-doc-number: "1974LAPAZ05828"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PRODUCTION, CERP 5711, GROUND VEHICLES, ECONOMIC REPORTS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


Message Text




 091944Z


64
ACTION COME-00


INFO OCT-01 ARA-16 ISO-00 EB-11 DRC-01 RSC-01 DOTE-00 /030 W
            --------------------- 076984
R 091829Z SEP 74
FM AMEMBASSY LA PAZ
TO SECSTATE WASHDC 4163


UNCLAS LA PAZ 5828


SUBJ: ECONOMIC REPORTING: CERP 5711 - PRODUCTION,
ASSEMBLY AND REGISTRATION OF MOTOR VEHICLES, CY1973.


REF: A-4876
UNITS NOT PRODUCED OR ASSEMBLED IN BOLIVIA. REGISTRATION
OF MOTOR VEHICLES AS DEC. 13, 1973 IS:
PASSENGER CARS UP 11,502 TOTAL 24,510
COMMERCIAL VEHICLES US 13,380 TOTAL 34,380
TRUCK TRAILERS. STATISTICS NOT AVAILABLE.
STEDMAN








NNN




                     

                     


                                                   Message Attributes
Automatic Decaptioning: X
Capture Date: 01 JAN 1994
Channel Indicators: n/a
Current Classification: 
Concepts: PRODUCTION, CERP 5711, GROUND VEHICLES, ECONOMIC REPORTS
Control Number: n/a
Copy: SINGLE
Draft Date: 09 SEP 1974
Decaption Date: 01 JAN 1960
Decaption Note:
Disposition Action: n/a
Disposition Approved on Date:
Disposition Authority: n/a
Disposition Case Number: n/a
Disposition Comment:
Disposition Date: 01 JAN 1960
Disposition Event:
Disposition History: n/a
Disposition Reason:
Disposition Remarks:
Document Number: 1974LAPAZ05828
Document Source: CORE
Document Unique ID: 00
Drafter: n/a
Enclosure: n/a
Executive Order: N/A
Errors: N/A
Film Number: D740250-0921
From: LA PAZ
Handling Restrictions: n/a
Image Path:
ISecure: 1
Legacy Key: link1974/newtext/t19740964/aaaaccbo.tel
Line Count: 34
Locator: TEXT ON-LINE, ON MICROFILM
Office: ACTION COME
Original Classification: 
Original Handling Restrictions: n/a
Original Previous Classification: n/a
Original Previous Handling Restrictions: n/a
Page Count: 1
Previous Channel Indicators:
Previous Classification: n/a
Previous Handling Restrictions: n/a
Reference: A-4876
Review Action: RELEASED, APPROVED
Review Authority: boyleja
Review Comment: n/a
Review Content Flags:
Review Date: 05 APR 2002
Review Event:
Review Exemptions: n/a
Review History: RELEASED <05 APR 2002 by maustmc>; APPROVED <29 JAN 2003 by boyleja>
Review Markings:


US Department of State

30 JUN 2005


Review Media Identifier:
Review Referrals: n/a
Review Release Date: n/a
Review Release Event: n/a
Review Transfer Date:
Review Withdrawn Fields: n/a
Secure: OPEN
Status: NATIVE
Subject: ECONOMIC REPORTING: CERP 5711 - PRODUCTION, ASSEMBLY AND REGISTRATION OF MOTOR VEHICLES, CY1973.
TAGS: ETRN, ECRP
To: STATE
Type: TE
Markings:

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05828

- **Date:** September 09, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PRODUCTION, CERP 5711, GROUND VEHICLES, ECONOMIC REPORTS
