---
title: "Gob Request For Small Arms Ammunition"
author: "Stedman"
date: "January 31, 1974"
editor: visual
cable-date: "January 31, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 2122"
cable-info: "Oct-01 Ara-16 Iso-00 Sso-00 Nsce-00 Inre-00 Nsc-10 Spc-03 Sam-01 Ss-20 Rsc-01 Mc-02 Omb-01 Aid-20 Iga-02 Eb-11 Come-00 Trse-00 L-03 Ciae-00 Inr-10 Nsae-00 Prs-01 Drc-01 /110 W --------------------- 026708"
cable-subject: "Gob Request For Small Arms Ammunition"
cable-tags: "PFOR MASS BL"
cable-ref: "LA PAZ 638 BINNS/AMBASSADOR TELECON JAN 31"
cable-doc-number: "1974LAPAZ00673"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "MILITARY EQUIPMENT, MILITARY ASSISTANCE, ARMS, AMMUNITION, GOVERNMENT PROCUREMENT, MILITARY AIRLIFTS,"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Points embodied in Binns/Ambassador telecon Jan 31 have been passed to appropriate Bolivian authorities. I did not raise transportation problems with President Banzer when I spoke to him at 2:30 p.m. this afternoon. We have informed GOB that we wish to help in request for ammunition and that sale is approved. We have informed authorities of difficulties in arranging official US air transportation. We have told them that if US transports material payment would have to be arranged for by Bolivian authorities.

2. Bolivians have informed US they are unable to airlift cargo from Canal Zone to La Paz. Apart from normal problems in flying from La Paz to Panama with older aircraft, they have unfulfilled internal airlift requirements in present emergency. They have repeated their request for our assistance in bringing the cargo in and have assured us again that there will be no publicity.

3. Chief US Air Force mission believes airlift of cargo from Zone to Bolivia is beyond Bolivian Air Force capability. In his opinion it would probably take more than two weeks for Bolivia to bring in ammunition and it would have to be done on a slow shuttle basis. He also reports Bolivians might have difficulties in acquiring clearances in neighboring countries for landing for refueling purposes with an ammunition cargo.

4. In view of foregoing would appreciate assistance from State and Defense on arrangements for official US transport of cargo to La Paz.
Stedman

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00673

- **Date:** January 31, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** MILITARY EQUIPMENT, MILITARY ASSISTANCE, ARMS, AMMUNITION, GOVERNMENT PROCUREMENT, MILITARY AIRLIFTS,