---
title: "Pereda Making Headway On His Election Plan"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "August 03, 1978"
editor: visual
cable-date: "August 03, 1978"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 1973"
cable-info: "Oct-01 Iso-00 /001 W ------------------076696 031628z /41 O 031445z Aug 78"
cable-subject: "Pereda Making Headway On His Election Plan"
cable-tags: "PINT BL"
cable-ref: "LA PAZ 6172, LA PAZ 6107"
cable-doc-number: "1978LAPAZ06188"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "GOVERNMENT REFORM, REPORTS, NATIONAL ELECTIONS, CAT-B"
---


# DEPARTMENT OF STATE TELEGRAM

**UNCLASSIFIED**

::: {.cable-meta}
:::


1.  Natush Busch told me evening of August 2 that Pereda's meeting with the La Paz garrisons, which Natush attended, went quite well. The garrisons asked for six days to give their response in writing, but Pereda was still hoping that all needed approvals could be obtained in time for an August 6 announcement of new elections. Natush said Carlos Iturralde (GOB ambassador in Washington) had been sent to see Banzer in Santa Cruz to solicit a nod of approval from him to Banzer loyalists in the military on the election plan. Natush thought that if Banzer would cooperate this would assure success but he was optimistic in any case. Pereda, he said was meeting his commitments to US.

2.  This morning Edwin Tapia called me to say that Pereda's meetings with garrisons in La Paz, Cochabamba, and Santa Cruz had gone well and it looked good for approval of elections in late 1979 or very early 1980. He too was optimistic that Pereda could make his speech on August 6 or, at the latest, one or two days later. Tapia asked whether we could now proceed with affirmation of continuing US-Bolivian relations. I told him I would see what I could do.

3.  Comment. Nothing in Bolivia is ever certain until it happens. But it is clear that Pereda is making progress, that he is now on the right side of the election issue, and a little boost to him now would probably help both our objectives--new elections and maintenance of peace and, ergo, the human rights environment in Bolivia. Therefore, I recommend we now acknowledge receipt of the Foreign Minister's note and that I be authorized subsequently to request an appointment with the Foreign Minister to discuss on-going business, such as the prisoner exchange treaty.

------------------------------------------------------------------------

#### Message Attributes

-   **Document Number:** 1978LAPAZ06188

-   **Date:** August 03, 1978

-   **Classification:** UNCLASSIFIED

-   **Declassified:** 01 jan 1960

-   **Concepts:** GOVERNMENT REFORM, REPORTS, NATIONAL ELECTIONS, CAT-B
