---
title: "South American Placers Inc."
author: "Stedman"
date: "January 25, 1974"
editor: visual
cable-date: "January 25, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 2055"
cable-info: "Oct-01 Ara-16 Iso-00 Aid-20 Ciae-00 Come-00 Frb-02 Inr-10 Nsae-00 Rsc-01 Trse-00 Xmb-07 Opic-12 Spc-03 Ciep-02 Lab-06 Sil-01 Omb-01 L-03 Nsc-10 Ss-20 Str-08 Cea-02 Int-08 Drc-01 /145 W --------------------- 092148 P 252011z Jan 74"
cable-subject: "South American Placers Inc."
cable-tags: "EMIN, BDIS, BL."
cable-ref: "LA PAZ 0359, STATE 14198."
cable-doc-number: "1974LAPAZ00548"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "TIN, LAND, MEETINGS, MINING INDUSTRY, JOINT VENTURES, NEGOTIATIONS, TAXES"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. In hour and half meeting with Emboffs Minmines agreed to prudent postponement of automatic revision of January 26, 1974 to Gob of Sapi's unworked concessions about (12,000 hectares) as ordered by Law Decree No. 10998 of July 26, 1973. Embassy believes postponement may be one month.

2. Minmines insists that Sapi end delaying tactics and not try to bargain reversion of concession issue with settlement of old tax problems not yet settled by Ministry which now matter for Controller General as well. He acknowledged Sapi right in some of old tax problems but wrong in others.

3. Despite position on tax matter as reported Para 2, Minmines stated three separate issues are involved and wants three issues settled in package deal. Issues are (A) unresolved tax matters pending for over ten years, (B) reversion of 12,000 hectares of concessions which Minister thought Sapi would never mine, and (C) future of Sapi in Bolivia involving Sapi's plans to participate in joint venture operation with Bolivian private capital to work on part of old Bolinca concession.

4. Minister asked for guarantee of USG that these three matters would be resolved and that Sapi would end delaying tactics. Emboffs replied that to our knowledge Sapi had tried to resolve problem at least as early as October, 1973 and that USG could not offer guarantees but that Mission would use its best offices toward finding rapid solution.

5. Asked whether O'Neill's presence in Bolivia required, Minister said not necessary until package deal is ready to sign.

6. FYI. Minmines blamed most of ill will between Sapi and Gob on Sapi's lawyer, Rene Rojas, who always waited to very end before trying to settle issue. End FYI. Remarked Sapi contract very bad one for Bolivia. Stated for 15 years Sapi only worked 700 hectares and Gob unwilling to wait for another ten years to get land back which Sapi had indicated it does not intend to work.

7. Minmines stated old tax question had been referred to Bolivia's Internal Revenue Department (Direccion Nacional de la Renta, DNR), and to Controller General. Said commission formed by Ministry of Mines to look into tax question, mostly involving taxes paid on redredging of tailings, will visit Sapi's old working sites and would be accompanied by representatives of Controller General, DNR, and Banco Minero. Minister added that under Bolivian law tax claims could not be a matter of negotiation and compromise as is often the case in the U.S. He said this especially true at present due to intensive "moralization campaign" being conducted by Minister of State Curruto which bringing out number of old unresolved tax issues.

8. Comment: Minmines seemed disposed to grant new gold mining concession to Echazu Group which would have connection with Sapi, but it was obvious that Minister prefers concession to be in national hands.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00548

- **Date:** January 25, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** TIN, LAND, MEETINGS, MINING INDUSTRY, JOINT VENTURES, NEGOTIATIONS, TAXES
