---
title: "Klockner Lead-Silver Smelter Project"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "January 08, 1979"
editor: visual
cable-date: "January 08, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "AmEmbassy Bonn"
cable-info: "Oct-01 Ara-11 Iso-00 Int-05 Eur-12 Eb-08 /041 W ------------------098311 090740z /14 R 082015z Jan 79"
cable-subject: "Klockner Lead-Silver Smelter Project"
cable-tags: "EMIN, EIND, BL"
cable-ref: "BONN 00279"
cable-doc-number: "1979LAPAZ00177"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "SILVER, CONSTRUCTION, FOREIGN INVESTMENT, LEAD, PROGRAMS (PROJECTS), PROPOSALS (BID)"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. The Lead-Silver Smelter project being promoted by Klockner is now being reviewed by the GOB. Perhaps because of its size, this project has been the subject of considerable public controversy in recent months. During October the president of Bolivia's Central Bank stated publicly that he did not believe the price increases demanded by Klockner (most recently from $137 to $150 million) were justified, or that the internal rate of return expected from the investment was sufficient to support the expenditure. Rather than sign the guarantee required for the project, the Central Bank president resigned.

2. From what we know of evaluations made of the Klockner proposal, which offers Soviet technology that apparently has not yet been applied on a commercial scale, there are grounds for questioning the profitability of this sizeable investment. As Bolivia is now facing a severe financial crunch (debt service may rise to 34 percent of exports in 1979, and the balance of payments deficit in 1978 is estimated at over $100 million, with exports growing at about five percent and imports at 20 percent per year), it is understandable that the new government would wish to examine the project with care.

3. FYI. It has been widely rumored that substantial financial payments have been made by Klockner or its local representatives to secure approval of this project.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ00177

- **Date:** January 08, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** SILVER, CONSTRUCTION, FOREIGN INVESTMENT, LEAD, PROGRAMS (PROJECTS), PROPOSALS (BID)
