---
title: "Pl-480 Wheat And Bolivia"
author: "Stedman"
date: "January 09, 1974"
editor: visual
cable-date: "January 09, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 1073"
cable-info: "Oct-01 Iso-00 Aid-20 Iga-02 Agr-20 Eb-11 Come-00 Trse-00 Omb-01 Ss-20 Nsc-10 Spc-03 L-03 Ciae-00 Inr-10 Nsae-00 Rsc-01 Inre-00 Nsce-00 Sso-00 Drc-01 /123 W --------------------- 056470 O 092143z Jan 74"
cable-subject: "Pl-480 Wheat And Bolivia"
cable-tags: "EAID BL"
cable-ref: "LA PAZ 15"
cable-doc-number: "1974LAPAZ00173"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "FOOD SHORTAGE, WHEAT, AGRICULTURAL AGREEMENTS, PL 480 TITLE 1, NEGOTIATIONS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Minister of Agriculture, Lt. Col. Natusch Busch, has arranged to call on me Monday, January 14, at 10 a.m. to discuss a matter of great importance. I can only conclude that he wishes to talk about the critical wheat and flour problem in Bolivia. Accordingly, I would very much appreciate having an official position to be able to give him during next week's meeting.

2. This morning, January 9, during a courtesy call on the Foreign Minister by Congressman Whalen, I was told by the Foreign Minister how important U.S. cooperation in helping Bolivia with wheat will be in the present critical situation. On January 8, the Subsecretary of the Foreign Ministry, Dr. Cespedes, telephoned me to inquire whether there was any current information on Bolivia's request for PL-480 wheat. In reply both to the Foreign Minister and the Subsecretary, I said that I had no official reply but I had preliminary indications that the chances were unlikely that there would be any new agreements during the balance of FY 74.

3. In addition to an official position which I can present to the Minister of Agriculture on January 14, which I hope will provide some help to Bolivia at this critical time, I would like to know what the facts are with regard to supply and demand for US wheat and whether there will be any PL-480 programs at all in this fiscal year and if so, which countries will be receiving allocations. I do not intend to convey this information to Bolivians but would like to have the information for our own understanding of the situation. We recognize the difficulties confronting the agencies in Washington in making determinations under present circumstances but we here feel woefully short of statistics and facts. In another vein, I trust that sympathetic consideration is being given to Bolivia's request so that helpful alternatives to PL-480 can be offered, if necessary, such as suitable credit.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00173

- **Date:** January 09, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** FOOD SHORTAGE, WHEAT, AGRICULTURAL AGREEMENTS, PL 480 TITLE 1, NEGOTIATIONS