---
title: "Bolivia's Foreign Debt"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "October 04, 1979"
editor: visual
cable-date: "October 04, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 8476"
cable-info: "Oct-01 Ads-00 Aid-05 Ciae-00 Com-02 Eb-08 Frb-03 Inr-10 Nsae-00 Ica-11 Trse-00 Xmb-02 Opic-07 Sp-02 Lab-04 Sil-01 Omb-01 Nsc-05 Ss-15 Str-08 Cea-01 /101 W ------------------036888 071024z /14 R 042115z Oct 79"
cable-subject: "Bolivia's Foreign Debt"
cable-tags: "ECON, EFIN, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ08442"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "DEBT DATA, GOVERNMENT DEBTS, DEBT REPAYMENTS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. As of June 30, 1979, total GOB contracted external debt amounted to $US 3,381,342,000, an increase of 15 percent from December 30, 1978. Total disbursements were $US 1,867,350,000 as of June 30, 1979; $US 386.3 million was disbursed in 1978 and $US 186.0 million during the first six months of 1979.

2. The Central Government's contracted debt represents the largest portion, 50 percent or $US 1,690.7 million, of the GOB's total. Second largest is YPFB, the state oil company, with 12 percent or $US 409.8 million. COMIBOL, the state mining company, has 3 percent or $US 116.8 million and CBF, the state development corporation, $US 112.6 million.

3. Private foreign bank loans averaging 11.8 percent for 7.1 years represent 28.1 percent or $US 951.2 million of the GOB's total contracted debt. The Central Government and YPFB have the greatest proportion, 30.5 and 23.3 percent respectively, of GOB total private foreign bank loans of which the largest part, $US 517.7 million or 54 percent, is placed with the mining, hydrocarbon and metallurgical sectors.

4. Although the GOB's total contracted debt climbed by 21 percent from 1977 to 1978, debt service payments climbed by 40 percent to total $US 223.7 million in 1978. This year Bolivia's debt service payments are estimated to total $US 272.4 million and are expected to reach $US 313.9 million in 1980 and $US 372.4 million in 1981. The debt service ratio increased from 25 percent in 1977 to 35 percent in 1978.

5. Bolivian public sector debt (millions of $US):
        Year   Total Contracted Debt   Total Disbursements   Debt Service Payments
        1970   743.9                   524.3                 28.9
        1971   815.5                   593.8                 33.6
        1972   962.8                   680.8                 41.5
        1973   1024.8                  707.8                 53.4
        1974   1209.8                  786.2                 78.0
        1975   1549.1                  882.7                 91.5
        1976   1978.1                  1106.8                111.3
        1977   2441.6                  1457.7                160.3
        1978   2946.8                  1761.5                223.7

6. FYI, more complete data will be transmitted in separate airgram.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ08442

- **Date:** October 04, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** DEBT DATA, GOVERNMENT DEBTS, DEBT REPAYMENTS
