---
title: "Impc/Embosa"
author: "Brewin"
date: "June 12, 1974"
editor: visual
cable-date: "June 12, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3375"
cable-info: "Oct-01 Iso-00 Opic-12 L-03 Aid-20 Eb-11 Come-00 Int-08 Omb-01 Trse-00 Ciae-00 Inr-10 Nsae-00 Rsc-01 Drc-01 H-03 /091 W --------------------- 128599 R 121246z Jun 74"
cable-subject: "Impc/Embosa"
cable-tags: "BDIS, BL"
cable-ref: "LA PAZ 3641 OF JUNE 5, 1974 SUMMARY. TYE PHONE MIN ATT FROM SUCRE HOTEL AND ASKED IF EMBOFFS HAD SEEN BOLIVIAN OFFICIALS REGARDING EMBOSA'S CASE AND WHAT WERE RESULT. MIN ATT TOLD HIM AMBASSADOR, CHARGE AND A/DCM HAD SEEN BOLIVIAN OFFICIALS AND LAST MEETING WITH MIN MINING HAD PROVED COMPLETELY NEGATIVE. END SUMMARY."
cable-doc-number: "1974LAPAZ03800"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. ON BOLIVIAN PRESENT POLITICAL SITUATION, TYE COMMENTED IF
RECENT REVOLT TRY BY DISSIDENT OFFICERS HAD SUCEEDED, ITS GOVERN-
MENT COULD NOT BE WORSE THAN THE PRESENT ONE. MIN ATT ASKED IF
HE ATTEMPTING TO SEE MIN MINING OR IF HE WOULD CALL AT EMBASSY.
TYE REPLIED THERE WAS NO USE TO SEE EITHER EMBASSY OFFICIALS OR
MIN MINING.


2. TYE ASKED MIN ATT FOR VIEWPOINT IN EMBOSA CASE AND MIN ATT
STATED HIS OWN PERSONAL OPINION THAT TYE HAD MADE MISTAKE
SIGNING QUIT CLAIM IN ORDER TO RECEIVE US 1.45 MILLION COMPEN-
SATION. TYE REPLIED HE DID NOT THINK THAT VALID REASON BECAUSE
CONTRACTS BETWEEN TWO PEOPLE BASED IN GOOD FAITH. ADDED WORLD BANK
WILLING AT TIME TO HAVE ENLARGED PLANT BY HEAVY INVESTMENT BUT
MIN MINING HAD REFUSED TO SIGN LOAN. SAID MIN MINING ACTED FROM






 121621Z


POLITICAL BASIS TO SUIT "GENTE" (PEOPLE) AS MIRANDA HAD ACTED




                        

                  

WHEN MAKING AND SIGNING EMBOSA CONTRACT.


3. TYE SAID HE OWED TOO MUCH MONEY AND FELT HE HAD BEEN TAKEN IN
BOLIVIA. MIN ATT CAUTIONED HIM NOT TO BE TOO AGGRESSIVE AND OUT-
SPOKEN WHILE IN BOLIVIA.


4. ON MORNING OF JUNE 11 EMBOFFS BY CHANCE MET TYE AND GENERAL
JUAN LECHIN (WHO HAD ACCIDENTALLY MET), EX-AMBASSADOR TO BRITAIN,
TALKING TO EACH OTHER IN STREET. LECHIN PROMISED TYE TO SEEK
MEETING WITH PRESIDENT BANZER.
BREWIN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03800

- **Date:** June 12, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a
