---
title: "Letter From Secretary Kissinger To Bolivian Foreign Minister"
author: "Stedman"
date: "March 01, 1974"
editor: visual
cable-date: "March 01, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2384"
cable-info: "Oct-01 Iso-00 Sso-00 /031 W --------------------- 083320 R 011339z Mar 74"
cable-subject: "Letter From Secretary Kissinger To Bolivian Foreign Minister"
cable-tags: "PFOR BL"
cable-ref: "STATE 038863"
cable-doc-number: "1974LAPAZ01251"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "28 MAY 2004"
cable-concepts: "PFOR BL"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. SECRETARY KISSINGER'S LETTER WAS DELIVERED PERSONALLY BY
ME TO BOLIVIAN FOREIGN MINISTER GUZMAN THE AFTERNOON OF FEBRUARY 28,
SHORTLY AFTER THE FOREIGN MINISTER RETURNED TO LA PAZ FROM THE
MEXICO CITY MEETING. HE READ A TRANSLATION IN SPANISH, WHICH
WE HAD PROVIDED, AND EXPRESSED HIS GREAT APPRECIATION FOR THE
SECRETARY'S LETTER. HE ANTICIPATED SEEING THE PRESIDENT THIS
AFTERNOON AND IS DELIGHTED THAT HE HAS THE LETTER TO SHOW TO
PRESIDENT BANZER.


2. THE FOREIGN MINISTER EXPRESSED HIS GREAT ADMIRATION FOR THE
MANNER IN WHICH SECRETARY KISSINGER CONDUCTED HIMSELF AT THE
MEXICO CITY MEETING. HE SAID HE WAS COMPLETELY SATISFIED WITH
THE RESULT OF THE CONFERENCE AND FELT THAT A POSITIVE AND SOUND
BASIS HAD BEEN LAID FOR OPENING A NEW CHAPTER IN U.S. - LATIN
AMERICAN RELATIONS AND ALSO BETWEEN LATIN AMERICAN THEMSELVES.
HE SAID THAT HE HAD NOT ATTENDED PRIOR CONFERENCES AS HE IS A
MILITARY MAN, BUT WAS DELIGHTED WITH THE FRANK, INFORMAL EXCHANGE
OF VIEWS DURING THIS PARTICULAR MEETING.


3. HE INDICATED THAT THE BOLIVIAN DELEGATION HAD A CHANCE TO HAVE
A BRIEF CONVERSATION WITH SECRETARY KISSINGER DURING WHICH THE






 011703Z


FOREIGN MINISTER WAS ABLE TO NOTE THE GOB'S INTEREST IN FINANCIAL




                       

                 

ASSISTANCE FOR RECONSTRUCTION OF FLOOD DAMAGE AND FINANCIAL AID
FOR THE SUBSTITUTION OF COCA PRODUCTION IN BOLIVIA. THE FOREIGN
MINISTER SAID THAT SECRETARY KISSINGER EXPRESSED INTEREST IN THE
PROPOSALS BUT WAS QUITE NATURALLY NOT ABLE TO RESPOND AT THE
TIME OF THAT CONVERSATION. THE FOREIGN MINISTER IS OF THE BELIEF
THAT THE REQUESTS THAT HE RAISED WITH THE SECRETARY WILL BE
PURSUED IIN DUE COURSE BY THE DEPARTMENT.


4. THE FOREIGN MINISTER SAID THAT HE HAD HAD A VERY FRIENDLY
MEETING WITH THE CHILEAN FOREIGN MINISTER WHOM HE HAD KNOWN
PREVIOUSLY AS A FELLOW MILITARY MAN. THE MINISTER GAVE HIS
OPINION THAT PROSPECTS ARE GOOD FOR IMPROVING BOLIVIAN-CHILEAN
RELATIONS, AND THE PANAMA CANAL UNDERSTANDING WITH THE US RAISES
HIS HOPES FOR RESOLUTION OF OUTSTANDING ISSUES WITH CHILE.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01251

- **Date:** March 01, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 28 MAY 2004

- **Concepts:** PFOR BL
