---
title: "Political Tensions Rise Over Relations With Brazil"
author: "Brewin"
date: "May 22, 1974"
editor: visual
cable-date: "May 22, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 3163"
cable-info: "Oct-01 Iso-00 Sso-00 Nsce-00 Inre-00 Usie-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-07 Pa-04 Rsc-01 Prs-01 Sp-03 Ss-20 Aid-20 Eb-11 Fea-02 Ciep-02 Come-00 Omb-01 Trse-00 Sci-06 Drc-01 /123 W --------------------- 126017"
cable-subject: "Political Tensions Rise Over Relations With Brazil"
cable-tags: "PINS, PINT, PFOR, BL"
cable-ref: "LA PAZ 3187"
cable-doc-number: "1974LAPAZ03295"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "NATURAL GAS, OPPOSITION PARTIES, PARTY ALLIANCE, CHIEF OF STATE VISITS, CONTRACTS, POPULAR RESENTMENT,"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. TENSIONS ARE RUNNING HIGH IN POLITICAL AND MILITARY
CIRCLES ON THE EVE OF THE GEISEL VISIT AND THE SCHEDULED
SIGNING OF THE GAS SALES CONTRACT BETWEEN BRAZIL AND BOLIVIA.


2. THE LATTER, WITH ITS COROLLARY PROSPECTS FOR CREATING
A SOUTHEASTERN REGIONAL DEVELOPMENT POLE, DEBATED IN PUBLIC FORA
(INCLUDING ESPECIALLY THE PRESS) OVER THE PAST MONTH. IT IS
THE KIND OF ISSUE AROUND WHICH PUBLIC OPINION CAN AND WILL
POLARIZE, AND IT HAS ALREADY HELPED TO BRING TOGETHER A NUMBER
OF HERETOFORE DISPARATE GROUPS OPPOSED TO THE BANZER REGIME.


3. TENSIONS HAVE BEEN AGGRAVATED IN THE PAST FOUR DAYS BY THE
LARGELY UNRELATED DISTURBANCES AT THE UNIVERSITY IN LA PAZ
WHERE PROTEST DEMONSTRATIONS INVOLVING THE NAMING OF A
NEW RECTOR WERE DISBANDED BY TEAR GAS AND POLICE DOGS (AND
POSSIBLY GUNFIRE). A SMALL NUMBER OF STUDENTS HAVE BEEN






 221547Z


ARRESTED, AND THE UNIVERSITY HAS BEEN CLOSED INDEFINITELY.




                      

                  


4. GIVEN THE EXTRAORDINARY SECURITY PRECAUTIONS RELATED TO THE
GEISEL VISIT AND THE ALREADY EXISTING STATE OF SIEGE, THE
GOVERNMENT IS NOT IN A TOLERANT MOOD AND HAS OVERREACTED TO
CRITICISM OF THE PROPOSED GAS SALES CONTRACT. YESTERDAY,
FOR INSTANCE, PRA AND PDC CHIEFS WALTER GUEVARA ARZE AND
BENJAMIN MIGUEL AND LOCAL MNRI REPRESENTATIVE WERE EXILED
FOR THEIR OPEN CRITICISM OF THE CONTRACT. THE MILITARY ARE
DIVIDED ON THE ISSUE AND FEELINGS ARE RUNNING HIGH, PARTICULARLY
AMONG SUCH INFLUENTIAL YOUNGER ARMY OFFICERS AS LTC RAUL LOPEZ
LEYTON, WHO SEE THE CONTRACT AS A SELL-OUT TO BRAZIL.


5. ALTHOUGH THE SIGNING NO DOUBT WILL TAKE PLACE AS SCHEDULED
AND ORDER WILL BE MAINTAINED, THE ISSUE WILL REMAIN. BANZER
MAY HAVE TO MAKE SOME OTHER CONCESSIONS TO THE MILITARY TO
FORESTALL A SERIOUS WEAKENING OF HIS POWER BASE OVER THIS ISSUE,
WHICH HAS SUCH SIGNIFICANT IMPLICATIONS FOR BOLIVIA'S NATIONAL
SECURITY.
BREWIN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03295

- **Date:** May 22, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** NATURAL GAS, OPPOSITION PARTIES, PARTY ALLIANCE, CHIEF OF STATE VISITS, CONTRACTS, POPULAR RESENTMENT,
