---
title: "Bolivian Tariff Schedule Refs: (A) State 060395; (B) State 092708"
author: "Stedman"
date: "May 08, 1974"
editor: visual
cable-date: "May 08, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3025"
cable-info: "Oct-01 Ara-16 Iso-00 Eb-11 Ciae-00 Inr-10 Nsae-00 Pa-04 Rsc-01 Usia-15 Prs-01 Sp-03 Tar-02 Trse-00 Agr-20 Drc-01 /085 W --------------------- 115423 R 082011z May 74 Zfd"
cable-subject: "Bolivian Tariff Schedule Refs: (A) State 060395; (B) State 092708"
cable-tags: "ETRD, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ02947"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PRESS COMMENTS, IMPORTS, LAW, CUSTOMS DUTIES, TARIFF SCHEDULES, FEES, SALES TAXES"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. PRESS REPORT CITED REFTEL A NOT RPT NOT CORRECT. GOB "ARANCEL
ADUANERO DE IMPORTACIONES 1972" STILL IN EFFECT AND ADDENDUM OF
FEBRUARY 28, 1973 HAS EXPIRED.


2. TWO TEMPORARY EXCEPTIONS TO 1972 ARANCEL HAVE BEEN PUT IN EFFECT
IN 1974. FIRST, SUPREME DECREE NO. 11345 OF FEBRUARY 13, 1974
CREATED SLIDING PERCENTAGE REDUCTIONS OF NORMAL CUSTOMS RATES
FOR RAW MATERIALS AND PARTS NEEDED BY BOLIVIAN INDUSTRIES.
EACH EXEMPTION MUST BE APPROVED SEPARATELY. SECOND, SUPREME DECREE
11358 OF FEBRUARY 22, 1974 SUSPENDED DUTIES (BUT NOT ALL FEES)
ON IMPORTATION CERTAIN BASIC FOOD COMMODITIES INCLUDIING
POWDERED MILK, RICE, VEGETABLE OIL, LARD, WHEAT FLOUR, TUNA FISH,
SALMON AND SARDINES. ORIGINAL DECREE WAS FOR 90 DAYS WHICH WAS
SUBSEQUENTLY EXTENDED ANOTHER 180 DAYS, THAT IS TO NOVEMBER 18, 1974.


3. THREE TO FIVE PERCENT SALES TAX ON IMPORTS STILL IN EFFECT BUT
ALSO SUSPENDED FOR THESE BASIC FOOD ITEMS. CONSULAR FEES DO NOT
APPEAR IN TARIFF COLUMNS. EMBASSY POUCHING ABOVE DECREES AND






 110030Z


CONSULAR FEE SCHEDULE.




                       

                   


4. BOLIVIA'S TARIFF REGIME WILL BE DESCRIBED IN GREATER DETAIL
IN POST'S ANSWER TO DEPARTMENT'S A-3164 OF APRIL 19 WHICH
NOW BEING PREPARED.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02947

- **Date:** May 08, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PRESS COMMENTS, IMPORTS, LAW, CUSTOMS DUTIES, TARIFF SCHEDULES, FEES, SALES TAXES