---
title: "Pdc-Pra And Mnri Form New Opposition Alliance"
author: "Stedman"
date: "May 16, 1974"
editor: visual
cable-date: "May 16, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3111"
cable-info: "Oct-01 Iso-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-07 Pa-04 Rsc-01 Prs-01 Sp-03 Ss-20 Usia-15 Io-14 Acda-19 Eb-11 Omb-01 Drc-01 /141 W --------------------- 049321 R 162037z May 74"
cable-subject: "Pdc-Pra And Mnri Form New Opposition Alliance"
cable-tags: "PINT, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ03187"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "OPPOSITION PARTIES, PARTY ALLIANCE, PARTY ORGANIZATION"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. PDC-PRA AND MNRI ANNOUNCED FORMATIONOF NEW OPPOSITION
POLITICAL ALLIANCE MAY 15 WHICH BRINGS TOGETHER SMALL CHRISTIAN
DEMOCRATIC AND AUTHENTIC REVOLUTIONARY PARTIES WITH GROUP HEADED
BY EXILED MNR LEADER SILES ZUAZO. NEW ALLIANCE WAS ANNOUNCED
AT PRESS CONFERENCE CALLED BY MNRI SECRETARY OF ORGANIZATION
RAMON CLAURE, PDC CHIEF BENJAMIN MIGUEL AND PRA LEADER WALTER
GUERVARA ARCE, WHO ACTED AS SPOKESMAN FOR THE TRIO. STATED
PURPOSE OF NEW POLITICAL GROUPING IS TO UNITE THREE CURRENTS
OF "DEMOCRATIC AND POPULAR NATIONALISM OF THE LEFT" IN A
COMMON FRONT WITH OTHER PARTIES AND ORGANIZATIONS OF SIMILAR
TENDENCY. PDC-PARA-MNRI ALLIANCE PLANS TO CAMPAIGN FOR FREEING
OF POLITICAL PRISONERS, RETURN OF POLITICAL EXILES AND CONSTI-
TUTIONALIZATION OF THE COUNTRY VIA NATIONAL, MUNICIPAL AND
UNIVERSITY-LEVEL ELECTIONS.


2. ADMINISTRATIVELY, ALLIANCE WILL BE DIRECTED BY
COMMITTEE COMPOSED OF CHIEF, SUB-CHIEFS AND EXECUTIVE
SECRETARIES OF THREE PARTIES. PRESIDENCY OF THIS NATIONAL
COMMITTEE WILL BE EXERCIZED ON ROTATING BASIS FOR THREE
MONTHS EACH DURING FIRST YEAR OF ALLIANCE, FOLLOWING ALPHA-
BETICAL ORDER OF INITIALS OF THE PARTIES (E.E., MNRI, PDC,
PRA). IN THEORY, THIS ALLIANCE WILL BE OF INDEFINITE






 162203Z


DURATION, BUT IN PRACTICAL TERMS GUEVARA ADMITTED THAT ALLIANCE




                      

                  

WILL LAST AT LEAST THROUGH 1975, AS PDC-PRA AND MNRI VIEW THIS
PERIOD AS CRUCIAL TIME FOR DESIRED RETURN TO CONSTITUTIONAL
GOVERNMENT.


3. COMMENT: MOST INTERESTING ASPECT OF THIS NEW OPPOSITION
GROUPING, WHICH JOINS ESTABLISHED PDC-PRA ALLIANCE WITH SEMI-
CLANDESTINE MNRI, IS PUBLIC REEMERGENCE OF PARTY OF SILES ZUAZO.
DECISION OF THIS MAJOR LEFTIST POLITICAL FORCE TO UNITE WITH
ITS SMALL, WEAK PDC-PRA ALLIES IS A SIGNIFICANT POLITICAL BREAK-
THROUGH FOR ANTI-REGIME OPPOSITION AND WILL INEVITABLY DRAW RE-
ACTION FROM BANZER GOVERMENT. CLAURE, WHO HAS BEEN TESTING
GROUND WITH SEVERAL PUBLIC STATEMENTS IN RECENT MONTHS, WAS
CAREFUL TO ASSURE PRESS THAT DOCUMENT SIGNED BY SILES IN BUENOS
AIRES RECENTLY (TOGETHER WITH JUAN LECHIN AND EX-
PRESIDENT TORRES) HAS NO RELATIONSHIP TO NEW PDC-PRA-MNRI PACT.
HE FURTHER ADMITTED THAT NATIONAL EXECUTIVE COMMITTEE OF MNRI
WITHIN BOLIVIA NOT YET FORMED.


4. GOVERNMENT REACTION TO THIS DEVELOPMENT WILL PROVIDE
IMPORTANT INDICATOR OF BANZER'S WILLINGESS TO ALLOW
MODERATE LEFTIST PARTIES TO OPERATE OPENLY WITHIN NEW
DOMESTIC POLITICAL ORDER. INITIAL GOB REACTION IS LIKELY
TO BE CAUTIOUS, UNLESS MINISTRY OF INTERIOR DECIDES TO
LAUNCH CRACKDOWN ON MNRI USING SILES-LECHIN-TORRES STATEMENT
AS PRETEXT. SUCH A HASTY MOVE WOULD, HOWEVER, VIRTUALLY
ELIMINATE ANY PROSPECT THAT MODERATE OPPOSITIONISTS CAN BE
WOOED BY GOVERNMENT INTO PARTICIPATION IN FORTHCOMING NATIONAL
CONSULTATIVE COUNCIL.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03187

- **Date:** May 16, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** OPPOSITION PARTIES, PARTY ALLIANCE, PARTY ORGANIZATION