---
title: "Ambassador's Comments On Ara/Ecp Paper On Bolivian Economy And Us Lending Options"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "March 14, 1979"
editor: visual
cable-date: "March 14, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 5237"
cable-info: "Oct-01 Iso-00 Eb-08 Ss-15 L-03 Inr-10 Sp-02 /054 W ------------------033450 150204z /62 P 142052z Mar 79"
cable-subject: "Ambassador's Comments On Ara/Ecp Paper On Bolivian Economy And Us Lending Options"
cable-tags: "PFOR, EFIN, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ02233"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "20 Mar 2014"
cable-concepts: "PAPERS, AMBASSADORS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. **C - Entire Text**

2. While ARA/ECP paper is a good, professional job, its analysis of Bolivia's economic problem is too sanguine and its prescription of remedial measures, therefore, too mild.

3. Recent data indicate that the Bolivian financial situation is deteriorating faster than indicated in ECP paper. Paper uses semi-official estimate of eight percent increase for imports in '79, whereas '78 increase was 23 percent (FOB) and preliminary data indicate January '79 imports soared more than 50 percent above same month last year. On '79 exports paper uses 10 percent increase for B/P estimates and 8-12 percent for calculating debt service rations, whereas we now expect no increase in '79 exports (as result continuing fall in tin production, delays in gas pipeline expansion, to Argentina, and impact of flooding on agricultural exports). These trends indicate a very large current account deficit this year in range of $500-$550 million and an over-all deficit of maybe $250-$300 million. Reserve loss in first two months of '79 was $20 million, but would have been much higher but for special factors. Liquid reserves are nearing rock bottom and government will probably increase its arrears on official debt significantly in March. Separate cable covers recent economic picture in more detail.

4. The financial situation is, therefore, likely to reach critical stage by July to September timeframe, not 1980, as cited in ECP paper. There are some factors associated with the July/August election and change of government which will themselves accelerate deterioration. Some banks are now holding up on new loans to GOB, pending clarification of political prospects. Proverbial uncertainty with political change in Bolivia should also lead to more capital flight. Very large peso deposits with (shaky) maintenance of value guarantee are a potential source of large capital flight whenever psychological worm turns. The military's rushing to take care of itself in dying days of military government will aggravate B/P situation (DOLS 100 million in arms purchases being most blatant example).

5. Equally important political factors argue clearly for a stabilization program shortly after August inauguration. The elected government, as Vic Paz indicated to me, will want to try to survive the popular backlash to economic stabilization measures by 1) fixing the blame squarely on previous governments and 2) making use of its fresh electoral mandate. That government will want to weather this storm at a time when the military is not yet ready to challenge it and hope to be on the up side of "J" curve before the military begins to look critically at the civilian government's record.

6. A US program loan can play an important part in this--not because of the amount, which is helpful but not critical, but because of the timing and politics. A US program loan early in the period of the elected government, close in time to a stabilization program, lends significant international blessing and, therefore, domestic weight to that government and its program. What the US thinks and does still carries great clout in Bolivia, and a program will be easier to adopt, at the right time, with overt US support. There are undoubtedly a dozen Latin American countries where this is not true, but Bolivia is different.

7. In considering US program lending, we should consider both FY79 and FY80 funds. As far as I am concerned, only one project in these two years is untouchable--the Chapare agricultural development loan; that we need to do for our own interests.

8. As regards the content of a stabilization program, it is not correct to view the IMF's October 1978 program as an on-the-shelf program, ready to go in August 1979 or whenever. With the continuing deterioration of the financial situation, the corrective measures needed have changed and may change further. The IMF's program of "de-dollarization" of guaranteed deposits is totally unfeasible at this point. With the existing state of low confidence a ten percentage point differential in interest rates would not move investors out of dollar-guaranteed deposits. New, more drastic solutions are needed, such as a succession of exchange rate changes, with the guarantee not renewed after the initial change and pay-off. Regardless of monetary consequences, exchange rate reform can no longer be avoided. With a debt service ration headed past 40 percent, I do not see how debt rescheduling can be avoided either. The ceilings on new borrowings, Central Bank credit to the public sector, etc., have to be reworked as well. We should encourage the IMF and IBRD on one hand, and the leading Bolivian electoral candidates on the other, to start developing the elements of a new program for August/September.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ02233

- **Date:** March 14, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 20 Mar 2014

- **Concepts:** PAPERS, AMBASSADORS
