---
title: "Pl-480 Title I: Possible Further Use Of Authority To Exchange Pl 480 Wheat For Peruvian Flour."
author: "Stedman"
date: "January 09, 1974"
editor: visual
cable-date: "January 09, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Niact Immediate 1887"
cable-info: "Oct-01 Iso-00 Agr-20 Aid-20 Ciae-00 Come-00 Eb-11 Frb-02 Inr-10 Nsae-00 Rsc-01 Trse-00 Xmb-07 Opic-12 Spc-03 Ciep-02 Lab-06 Sil-01 Omb-01 L-03 Ss-20 Nsc-10 Nsce-00 Sso-00 Str-08 Drc-01 Inre-00 /159 W --------------------- 054019 O 091647z Jan 74"
cable-subject: "Pl-480 Title I: Possible Further Use Of Authority To Exchange Pl 480 Wheat For Peruvian Flour."
cable-tags: "EAID,"
cable-ref: "(A) LA PAZ 2698; (B) STATE 195756"
cable-doc-number: "1974LAPAZ00156"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "WHEAT, PL 480 TITLE 1, FLOUR, TRADE AGREEMENTS, PROPOSALS (BID)"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. Subsec Minind/Com Zamorano made oral request for our acquiescence in utilizing remaining authority under arrangement exchange PL 480 wheat for Peruvian flour authorized Ref (B). Stated only 175 M.T. flour remained on hand in La Paz although there are about 12,000 M.T. PL 480 wheat still in Pacific ports enroute to Bolivia. Noted that limiting factor for flour again is Bolivian milling capacity.

2. Zamorano said he wished bring in 3,500 M.T. Peruvian flour under proposed arrangement. As noted Reftel (A) there is balance of 5,176.3 M.T. wheat available to exchange for 3,932.2 M.T. flour under authority granted Ref (B).

3. Action requested: Inform by COB January 10 whether authority granted Ref (B) still extant.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00156

- **Date:** January 09, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** WHEAT, PL 480 TITLE 1, FLOUR, TRADE AGREEMENTS, PROPOSALS (BID)
