---
title: "Ciap Meeting Mincoord Capriles Told Charge And Adcm He Would Head Gob"
author: "Brewin"
date: "May 24, 1974"
editor: visual
cable-date: "May 24, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3202"
cable-info: "Oct-01 Iso-00 Aid-20 Ciae-00 Come-00 Eb-11 Frb-02 Inr-10 Nsae-00 Rsc-01 Trse-00 Xmb-07 Opic-12 Sp-03 Ciep-02 Lab-06 Sil-01 Omb-01 Pa-04 Prs-01 Usia-15 Iga-02 Oic-04 Io-14 Drc-01 /138 W --------------------- 031615 R 241939z May 74"
cable-subject: "Ciap Meeting Mincoord Capriles Told Charge And Adcm He Would Head Gob"
cable-tags: "EAID, ECON, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ03382"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "MEETINGS, MEETING DELEGATIONS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

Message Text




 242050Z


11
ACTION ARA-20


INFO OCT-01 ISO-00 AID-20 CIAE-00 COME-00 EB-11 FRB-02


   INR-10 NSAE-00 RSC-01 TRSE-00 XMB-07 OPIC-12 SP-03


   CIEP-02 LAB-06 SIL-01 OMB-01 PA-04 PRS-01 USIA-15


   IGA-02 OIC-04 IO-14 DRC-01 /138 W
           --------------------- 031615
R 241939Z MAY 74
FM AMEMBASSY LA PAZ
TO SECSTATE WASHDC 3202


UNCLAS LA PAZ 3382


E.O. 11652: N/A
TAGS: EAID, ECON, BL
SUBJ: CIAP MEETING


MINCOORD CAPRILES TOLD CHARGE AND ADCM HE WOULD HEAD GOB
DELEGATION TO CIAP MEETING ON BOLIVIA SCHEDULED FOR JUNE
2 OR 3. HE SAID DELEGATION WOULD INCLUDE HECTOR ORMACHEA,
DIRECTOR DESIGNATE OF SOON-TO BE ESTABLISHED EXTERNAL FINANCE
INSTITUTE, SERGIO OTERO, MINISTER OF CONEPLAN AND ONE OR
TWO OTHERS.
BREWIN








NNN




                      

                     


                                                    Message Attributes
Automatic Decaptioning: X
Capture Date: 01 JAN 1994
Channel Indicators: n/a
Current Classification: 
Concepts: MEETINGS, MEETING DELEGATIONS
Control Number: n/a
Copy: SINGLE
Draft Date: 24 MAY 1974
Decaption Date: 01 JAN 1960
Decaption Note:
Disposition Action: n/a
Disposition Approved on Date:
Disposition Authority: n/a
Disposition Case Number: n/a
Disposition Comment:
Disposition Date: 01 JAN 1960
Disposition Event:
Disposition History: n/a
Disposition Reason:
Disposition Remarks:
Document Number: 1974LAPAZ03382
Document Source: CORE
Document Unique ID: 00
Drafter: n/a
Enclosure: n/a
Executive Order: N/A
Errors: N/A
Film Number: D740131-0919
From: LA PAZ
Handling Restrictions: n/a
Image Path:
ISecure: 1
Legacy Key: link1974/newtext/t19740520/aaaaarmf.tel
Line Count: 41
Locator: TEXT ON-LINE, ON MICROFILM
Office: ACTION ARA
Original Classification: 
Original Handling Restrictions: n/a
Original Previous Classification: n/a
Original Previous Handling Restrictions: n/a
Page Count: 1
Previous Channel Indicators: n/a
Previous Classification: n/a
Previous Handling Restrictions: n/a
Reference: n/a
Review Action: RELEASED, APPROVED
Review Authority: martinjw
Review Comment: n/a
Review Content Flags:
Review Date: 30 OCT 2002
Review Event:
Review Exemptions: n/a
Review History: RELEASED <30 OCT 2002 by boyleja>; APPROVED <07 JAN 2003 by martinjw>
Review Markings:


US Department of State

30 JUN 2005


Review Media Identifier:
Review Referrals: n/a
Review Release Date: n/a
Review Release Event: n/a
Review Transfer Date:
Review Withdrawn Fields: n/a
Secure: OPEN
Status: NATIVE
Subject: CIAP MEETING MINCOORD CAPRILES TOLD CHARGE AND ADCM HE WOULD HEAD GOB
TAGS: EAID, ECON, BL, CIAP, (CAPRILES GUTIERREZ, ROBERTO), (ORMACHEA, HECTOR), (OTERO, SERGIO)
To: STATE
Type: TE
Markings:

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03382

- **Date:** May 24, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** MEETINGS, MEETING DELEGATIONS