---
title: "1979 Gsp Product Review Hearings"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "September 12, 1979"
editor: visual
cable-date: "September 12, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 8124"
cable-info: "Oct-01 Ara-15 Ads-00 Agr-01 Cea-01 Ciae-00 Com-04 Dode-00 Frb-01 H-02 Inr-10 Int-05 L-03 Lab-04 Nsae-00 Nsc-05 Pa-02 Ctme-00 Aid-05 Ss-15 Str-08 Itc-01 Trse-00 Ica-15 Sp-02 Soe-02 Omb-01 Doe-15 Oic-02 /128 W ------------------005578 160055z /21 R 121709z Sep 79"
cable-subject: "1979 Gsp Product Review Hearings"
cable-tags: "ETRD, GSP"
cable-ref: "A) STATE 224372, B) STATE 209964 COMMERCIAL ATTACHE HAS CONVEYED INFORMATION REGARDING GSP PRODUCT REVIEW HEARING AT A NUMBER OF MEETINGS WITH MINISTRY OF INDUSTRY AND COMMERCE OFFICIALS INCLUDING UNDER SECRETARY OF COMMERCE. MOST RECENT MEETING, SEPTEMBER 10, WITH NEW DIRECTOR GENERAL OF FOREIGN TRADE RESULTED IN FOLLOWING POINTS:"
cable-doc-number: "1979LAPAZ07746"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "GENERALIZED PREFERENCES (TARIFFS), MEETING DELEGATIONS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. GOB will send a team to subject hearings scheduled week of September 24 to present three petitions (wall hangings, pillow covers, and men's outerwear of llama hair) in effort to have these products included in the GSP.
2. Bolivian team will consist of:
    (A) Antonio Aldunate, Director of Bolivia's Small Industry and Crafts Institute (IMBOPIA), phone: 367452, Ave. Camacho Esquina Calle Bueno, La Paz, Bolivia;
    (B) Senior Bolivian Embassy official (possibly Ambassador);
    (C) Daisy Wende, General Manager of Artesanias Titicaca (private sector representative), telephone: 321148, Ave. Sanchez Lima, La Paz, Bolivia.
3. GOB official and private sector representative wish to give oral testimony (ten minutes) on each product petition. Private sector representative Wende has sent written briefs as requested in REFTEL and GOB official will submit his this week.
4. Bolivian team wishes to be advised the day and hour of their hearing.
5. Please reserve two rooms at Park Central Hotel near STR offices for appropriate days of hearing.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ07746

- **Date:** September 12, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** GENERALIZED PREFERENCES (TARIFFS), MEETING DELEGATIONS