---
title: "Inopportune Drop In 1979 Bolivian Cotton Production"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "May 08, 1979"
editor: visual
cable-date: "May 08, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "AmEmbassy Lima"
cable-info: "Oct-01 Ara-15 Ads-00 Com-04 Agre-00 Ciae-00 Inr-10 Labe-00 Nsae-00 Sp-02 Str-08 Trse-00 Frb-01 Omb-01 Mmo-01 /051 W ------------------102908 090721z /14 R 081350z May 79"
cable-subject: "Inopportune Drop In 1979 Bolivian Cotton Production"
cable-tags: "EAGR, EPAP BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ04006"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "COTTON, CROP DESTRUCTION, PRODUCTION DATA"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. Jose Justiniano, general manager of ADEPA, the Bolivian cotton grower's association, has provided US with information indicating that recent floods have caused more damage to the 1979 cotton crop than originally suspected.

2. **PRODUCTION:** The 1979 cotton crop is estimated to total 293,250 QQ (quintal) as compared with 378,633 QQ for 1978, a decrease of 22.6 percent. Yields per hectare should average 8.5 QQ, which compares with 12.0 QQ for 1978. ADEPA estimates that 34,500 hectares were planted for this 1979 season.

3. **EXPORTATION:** ADEPA estimates that 195,304 QQ of cotton will be exported and that Bolivia will receive $US 9,677,250. In 1978 exports totaled 304,279 QQ, which represented export revenues of $US 14,317,248. To this date, ADEPA has sold 15,000 bales to Bunge, an English firm, at a price of $US 50/QQ FOB Santa Cruz. Higher transportation costs will increase export costs of this year's cotton crop. The railroad link between Santa Cruz, the center of cotton production, and the port of Santos, Brazil was severely damaged by flooding and has not been repaired. Cotton exports will begin in early May and must go through Rosario, Argentina until the Brazilian railroad link is temporarily restored sometime in early June.

4. **DOMESTIC DEMAND:** This is estimated to increase from 73,655 QQ in 1978 to 97,946 QQ and generating US$ 4,897,300.

5. **COMMENT:** The untimely fall in cotton production will aggravate Bolivia's already serious balance of payments problems. An important non-traditional export, cotton represented 2 percent of total exports and 17 percent of non-traditional exports in 1978.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ04006

- **Date:** May 08, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** COTTON, CROP DESTRUCTION, PRODUCTION DATA
