---
title: "Socialist International Statement On Bolivia"
author: "Weissman"
date: "November 15, 1979"
editor: visual
cable-date: "November 15, 1979"
cable-from: "AmEmbassy San Jose"
cable-to: "SecState WashDC 6707"
cable-info: "Oct-01 Eur-12 Ads-00 Pm-06 Nsc-05 Sp-02 Ss-15 Ciae-00 Dode-00 Inr-10 Nsae-00 Pa-02 Ica-15 Ha-05 /088 W ------------------081650 181504z /15 R 151354z Nov 79"
cable-subject: "Socialist International Statement On Bolivia"
cable-tags: "PINT, PEPR, PORG, BL"
cable-ref: "SAN JOSE 5164 (NOTAL)"
cable-doc-number: "1979SANJO05291"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "GOVERNMENT OVERTHROW, JUNTA, PRESS RELEASES, POLITICAL PARTIES"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. ON THE CHANCE THAT IT HAS NOT BEEN REPORTED FROM OTHER
SOURCES, FOLLOWING IS STATEMENT RELEASED NOVEMBER 9 BY
BERNT CARLSSON, GENERAL SECRETARY OF THE SOCIALIST INTER-
NATIONAL (SI) AS SI PRESS RELEASE NO. 25/79.


2. BEGIN TEXT: THE ACTION OF COLONEL ALBERTO NATUSCH BUSCH
IN LA PAZ ON NOVEMBER 1, 1979 IN TRYING TO SEIZE POWER IN
BOLIVIA AND PUT AN END TO THE INTERIM PRESIDENCY OF WALTER
GUEVARA ARZE HAS BEEN DEPLORED BY DEMOCRATS WORLDWIDE.
PRESIDENT GUEVARA HAD ASSUMED THE OFFICE OF HEAD OF STATE
FOR ONE YEAR ON AUGUST 8, 1979 AT THE DULY EXPRESSED WISH OF
THE BOLIVIAN CONGRESS. HIS PRESIDENCY MARKED A STEP ALONG
THE ROAD TO EFFECTIVE DEMOCRACY IN BOLIVIA.


3. THE SOCIALIST INTERNATIONAL DEPLORES THE BLATANT INTER-
FERENCE WITH THE DEMOCRATIC GOVERNMENT OF BOLIVIA BY A SEC-
TION OF THE ARMED FORCES, AND REGRETS THE DEATHS WHICH HAVE






 181400Z


FOLLOWED IN ITS WAKE.


4. THE SOCIALIST INTERNATIONAL EXPRESSES ITS SUPPORT FOR
AND SOLIDARITY WITH THE TRADE UNIONS AND THE DEMOCRATIC
SOCIALIST PARTIES IN BOLIVIA. IT URGES AN IMMEDIATE RESTOR-
ATION OF FULL POWER TO DEMOCRATICALLY ELECTED LEGISLATURE
AND THE CONSTITUTIONAL PRESIDENT.




          Sheryl P. Walter 

         Sheryl P. Walter 


5. THE SOCIALIST INTERNATIONAL CALLS UPON ALL ITS MEMBER
PARTIES AND THE INTERNATIONAL COMMUNITY AS A WHOLE TO
EXPRESS THEIR UNEQUIVOCAL REJECTION OF THIS ATTEMPT TO
USURP POWER BY THE MILITARY FACTION LED BY COLONEL ALBERTO
NATUSCH AND TO BRING ALL POSSIBLE PRESSURE TO BEAR FOR THE
REINSTATEMENT OF CIVIL GOVERNMENT. END TEXT.


6. ACTION REQUESTED: EMBASSY REQUESTS DEPARTMENT'S GUIDANCE
AS TO WHETHER IT SHOULD CONTINUE TO FORWARD SUCH SI STATE-
MENTS (AS WAS DONE WITH THE SI PRESS RELEASE ON THE COUP IN
EL SALVADOR, REFTEL).
WEISSMAN

***

#### Message Attributes

- **Document Number:** 1979SANJO05291

- **Date:** November 15, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** GOVERNMENT OVERTHROW, JUNTA, PRESS RELEASES, POLITICAL PARTIES