---
title: "Implementation Of Narcotics Program In Fy 80 - Extension Of University Of Florida Contract"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "October 05, 1979"
editor: visual
cable-date: "October 05, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 8501"
cable-info: "Oct-01 Ara-11 Ads-00 Aid-05 Agr-01 Deae-00 Ciae-00 Inr-10 Io-14 Jus-01 Nsae-00 Ctme-00 Sp-02 Trse-00 Ica-11 Nsc-05 Oes-09 Omb-01 Dode-00 /076 W ------------------042685 081422z /47 R 052208z Oct 79"
cable-subject: "Implementation Of Narcotics Program In Fy 80 - Extension Of University Of Florida Contract"
cable-tags: "SNAR, BL"
cable-ref: "(A) LA PAZ 8308, (B) LA PAZ 7516"
cable-doc-number: "1979LAPAZ08493"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "REPORTS, DRUG CONTROL, PROGRAMS (PROJECTS), INTERGOVERNMENTAL COOPERATION"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. WITH THE ADDITIONAL $700,000 FOR FY 79 PROVIDED BY THE DEPARTMENT
(REF A); THE APPOINTMENT OF A NEW, ENERGETIC, POLITICALLY WELL-
CONNECTED DIRECTOR OF BOLIVIAN CUSTOMS (WALTER ROBLES); AND
A FIRST-RATE TEAM (RODOLFO TAPIA PACHECO AND
JOSE ANTONIO VILLEGAS IBANEZ) NAMED TO REPLACE VICTOR
AMELLER AND NESTOR DELFIN BALDIEVIESO AS DIRECTOR AND INS-
PECTOR GENERAL OF THE NATIONAL DIRECTORATE FOR THE CONTROL OF
DANGEROUS SUBSTANCES (DNSP); THE COCA CONTROL ASPECT OF
OUR NARCOTICS PROGRAM IN BOLIVIA SHOULD GO FORWARD EFFECTIVELY,
PROVIDED QUALIFIED INDIVIDUALS ARE ASSIGNED VERY SOON TO THE
TWO VACANT POSITIONS IN THE EMBASSY'S NARCOTICS CONTROL UNIT.
EFFECTIVE CONTROL OF THE TRANSPORTATION AND COMMERCIALIZATION
OF COCA SHOULD PUT PRESSURE ON THE COCAINE FABRICATORS AND
TRAFFICKERS AS WELL AS ON THE COCA PRODUCERS.








 081213Z


2. INITIALLY NARCOTICS CONTROL EFFECTS WILL BE CONCENTRATED IN
THE CHAPARE AREA OF COCHABAMBA AS OUTLINED IN REF B. THE EFFEC-
TIVENESS OF THESE EFFORTS WILL DEPEND IN LARGE PART ON THE PRO-
GRESS WHICH IS MADE IN OUR CROP SUBSTITUTION PROGRAM. WE
EXPECT THAT AID WILL ASSUME THE MAJOR RESPONSIBILITY FOR THIS
PROGRAM IN THE FUTURE. IT IS THE MISSSION'S CONSENSUS, HOWEVER,
THAT THERE WILL BE A LAG OF AT LEAST A YEAR FROM JANUARY 1980,




           Sheryl P. Walter 

          Sheryl P. Walter 

WHEN WE EXPECT TO SUBMIT OUR CHAPARE DEVELOPMENT PROPOSAL TO
AID/W, UNTIL NEW CONTRACTS FOR TECHNICAL ASSISTANCE CAN BE
AWARDED AND IMPLEMENTATION OF THE PROGRAM CAN BEGIN. IT IS
PARTICULARLY IMPORTANT THAT OVER THE NEXT YEAR WE NOT DISSI-
PATE THE MOMENTUM WHICH HAS BEEN ACHIEVED THUS FAR BY PRODES
AND THE UNIVERSITY OF FLORIDA TECHNICIANS UNDER THEIR CONTRACT
WITH INM.


3. THE UNIVERSITY OF FLORIDA CONTRACT EXPIRES FEBRUARY 5,
1980. FOUR FLORIDA TECHNICIANS ARE IN THE MIDDLE OF THEIR
RESIDENT TOURS AND HAVE ONLY PARTIALLY COMPLETED THEIR WORK.
THEY ARE AS FOLLOWS:


(A) MR LOY VAN CROWDER, EXTENSION COMMUNICATIONS SPECIALIST--
ASSUMED ASSIGNMENT SEPTEMBER 8, 1978;


(B) DR E.C. FRENCH, MULTIPLE CROPPING SPECIALIST--ASSUMED
ASSIGNMENT SEPTEMBER 30, 1978;


(C) DR RALPH SCORZA, CITRUS AND TROPICAL FRUITS HORTICULTRUIST
-- ASSUMED ASSIGNMENT FEBRUARY 8, 1979;


(D) DR JOSEPH GOODWIN, AGRICULTURAL ECONOMICS--ASSUMED
ASSIGNMENT MARCH 12, 1979.


MISSION BELIEVES THE MOST EFFECTIVE AND LEAST COSTLY WAY TO CON-






 081213Z


TINUE THIS RESEARCH UNTIL THE AID PROGRAM CAN BE IMPLEMENTED IS TO
EXTEND THE U OF FLORIDA CONTRACT. THEREFORE, WE RECOMMEND THAT
INM AMEND AND EXTEND THE U OF FLORIDA CONTRACT (511-107T) FROM
FEBRUARY 6, 1980 THROUGH FEBRUARY 5, 1981 (AGRICULTURAL DEVELOP-
MENT IN COCA ZONES GRANT PROJECT 104-0-02-02) TO ENABLE THE FOUR
TECHNICIANS TO COMPLETE THE WORK IN PROGRESS AND THEIR TWO-YEAR
RESIDENT ASSIGNEMENTS.


4. OUR ESTIMATE OF THE TOTAL COST OF THIS WORK FOR THE PERIOD
FEBRUARY 6, 1980 THROUGH FEBRUARY 5, 1981 IS $356,000. THIS
WILL COVER ALL COSTS FOR THE TECHNICIANS AND THEIR SUPPORT, IN-
CLUDING THE SERVICES OF A SKILLED LOCAL ADMINISTRATIVE ASSISTANT.
WITH THE HIRING OF AN ADMINISTRATIVE ASSISTANT, ONE MEMBER OF
THE FLORIDA TEAM MAY BE DESIGNATED AS RESEARCH COORDINATOR AND
THE NEED TO REPLACE FOR ONE YEAR THE CURRENT "CHIEF OF PARTY"
(WHO WILL DEPART IN FEBRUARY WHETHER THE CONTRACT IS RENEWED
OR NOT) WILL BE OBVIATED.


5. PIPLEINE FUNDS NOW AVAILABLE FOR THE U OF FLORIDA WORK
FROM PROW/AG 80019 AND 90002 SHOW THAT AN ESTIMATED $400,280
WILL BE AVAILABLE AS OF THE COMPLETION OF THE PRESENT CONTRACT
ON FEBRUARY 6, 1980 FOR FUTURE DISBURSEMENT. THE ESTIMATED




          Sheryl P. Walter 

          Sheryl P. Walter 

CONTRACT EXTENSION COST OF $356,000 PLUS $125,000 FOR FIVE SETS
OF FURNITURE PLUS TRANSPORT (AS APPROVED BY STATE 241645) BRINGS
THE TOTAL COST TO $481,000. THUS $81,000 WILL BE NEEDED FROM
FYL1980 FUNDS TO COMPLETE THESE COMMITMENTS.


6. IT IS ESSENTIAL THAT THERE NOT BE A GAP OR DELAY IN THE
CONTINUATION OF THIS AGRONOMIC AND AGROECONOMIC RESEARCH AND
EXTENSION WORK WHICH IS VITAL TO THE SUCCESS OF OUR EFFORTS IN
THE CHAPARE. THEREFORE, IT IS ALSO ESSENTIAL THAT THE DECISION
TO RENEW THE CONTRACT BE MADE AS SOON AS POSSIBLE TO PRECLUDE
A WINDING DOWN OF THE RESEARCH AND SUBSEQUENT DELAYS AS IT IS
BEGUN AGAIN.
BOEKER

***

#### Message Attributes

- **Document Number:** 1979LAPAZ08493

- **Date:** October 05, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** REPORTS, DRUG CONTROL, PROGRAMS (PROJECTS), INTERGOVERNMENTAL COOPERATION
