---
title: "Bolivian Tariff Schedule"
author: "Stedman"
date: "July 15, 1974"
editor: visual
cable-date: "July 15, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3649"
cable-info: "Oct-01 Ara-16 Iso-00 Eb-11 Drc-01 Rsc-01 /030 W --------------------- 122210 R 151425z Jul 74"
cable-subject: "Bolivian Tariff Schedule"
cable-tags: "EIRD, BL"
cable-ref: "STATE 132666: LA PAZ 2947"
cable-doc-number: "1974LAPAZ04562"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "LAW, TARIFF SCHEDULES"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. NEW BOLIVIAN CUSTOM'S TARIFF SCHEDULE "ARANCEL ADUANERO DE
IMPORTACIONES" ISSUED BY DECREE LAW 11126 OF OCTOBER 19, 1973
WAS EFFECTIVE ON DECEMBER 1, 1973. AUTHORITIES OF DEPARTMENT
POLITICA ARANCELARIA, OF MINISTRY FINANCE, CONFIRMED TO EMBASSY
RESTRUCTED TARIFF SCHEDULE AS INDICATED IN POINT ONE OF STATE
REFTEL.


2. SOME MODIFICATIONS TO "ARACEL ADUANERO DE IMPORTACIONES"
DECREE LAW 11126 WERE INTRODUCED ON JUNE 28, 1974 BY SUPREME
DECREE 11551.


3. BOLIVIA'S ARACEL DE IMPORTACIONES WAS MADE ON BASIS OF
NABANDINA (ANDEAN GROUP CUSTOMS NOMENCLATURE) WHICH IS BASED ON
1972 BRUSSELS NOMENCLATURE.


4. COPIES OF NEW ARANCEL AND ITS MODIFICATIONS UNDER DECREE 11551
WILL BE POUCHED BY EMBASSY ASAP.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04562

- **Date:** July 15, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** LAW, TARIFF SCHEDULES