---
title: "Pl-480 Title I Lima For Agatt"
author: "Stedman"
date: "May 14, 1974"
editor: visual
cable-date: "May 14, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 3088"
cable-info: "Oct-01 Iso-00 Aid-20 Iga-02 Eb-11 Agr-20 L-03 Trse-00 Come-00 Drc-01 Rsc-01 /079 W --------------------- 018954"
cable-subject: "Pl-480 Title I Lima For Agatt"
cable-tags: "EAID, EAGR, ECON, BL"
cable-ref: "STATE 092148 AND LA PAZ A-023. SUMMARY: WE ESTIMATE THAT EVEN IF PRESENT COMMERCIAL WHEAT/FLOUR IMPORT ARRANGEMENTS IMPLEMENTED BOLIVIA WILL HAVE SUPPLY GAP OF ABOUT 40,000 M.T. OF WHEAT WHICH SHOULD BE MET BY PL-480. WE BELIEVE FURTHER AGREEMENT JUSTIFIED ON BASIS POOR BALANCE OF PAYMENTS PROSPECTS FOR 1975, AS INTEGRAL ELEMENT USG ASSISTANCE STRATEGY FOR AGRRICULTURE SECTOR AND OTHER DEVELOPMENT SECTORS IN WHICH USG DIRECTING ITS EFFORTS. WE ALSO SEE POSSIBILITY THAT PL-480 GENERATIONS MIGHT BE USED TO HELP FINANCE LOCAL CURRENCY COSTS LATER PHASES RECONSTRUCTION FLOOD DAMAGED AREAS. WE JUDGE PL-480 HAS HIGH GOB PRIORITY, IS POLITICALLY IMPORTANT AND THAT USG HAS RESPONSIBILITY TO USE THIS FLEXIBLE TOOL IN HELPING SOLVE BOLIVIA'S GRAIN SUPPLY PROBLEM AND TO AVOID JOLTING CHANGE FROM SUBSTANTIAL WHEAT CREDIT PROGRAM TO NO WHEAT CREDIT PROGRAM AT ALL. END SUMMARY:"
cable-doc-number: "1974LAPAZ03128"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "WHEAT, DATA, PL 480 TITLE 1, BALANCE OF PAYMENTS DEFICITS, CREDIT AGREEMENTS, FOREIGN ASSISTANCE PROGRAMS,"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. TABLE 1. WHEAT. FY 1974 ESTIMATE. AGREEMENTS: 0; SHIPMENTS:
93,600 M.T.; CARRYOVER TO FY 1975: 3,500 M.T.


2. FY 1975 ESTIMATE. AGREEMENTS: 36,778 M.T. (US$ 5.0 MILLION);






 01 OF 02 142301Z


SHIPMENTS: 40,278 M.T. (US$ 5.5 MILLION); CARRYOVER TO FY 1976: 0.




                      

                    


3. TABLE 2. WHEAT.
               FY 1973 FY 1974 FY 1975
SUPPLY              ACTUAL ESTIMATE PROJECTED
A. BEGINNING STOCK           50,800     6,000 0
B. PRODUCTION             54,000 57,200 58,700
C. IMPORTS           163,100 194,100 236,278
  1. COMMERCIAL           123,200 97,200 182,700
  2. PL-480        39,900 96,900 43,578
   A. SALES         37,700 93,600 40,278
   B. DONATIONS           2,200    3,300 3,300
  3. OTHER DONATIONS           0        0    10,000
TOTAL SUPPLY             267,900 257,300 294,978
DISTRIBUTION
A. CONSUMPTION             250,400 244,900 270,800
B. FEED/SEED/WASTE            11,500 12,400 12,400
C. EXPORTS             --     --     --
D. ENDING STOCKS            6,000 0         1,778
E. TOTAL DISTRIBUTION          267,900 257,300 294,978
4. FOREGOING TABLES REQUIRE SOME EXPLANATION. CONSUMPTION WAS
CURTAILED IN FY 1974 BY (A) FAILURE OF ARGENTINA TO DELIVER ON
COMMITMENTS AND OF GOB TO MAKE TIMELY ALTERNATIVE ARRANGEMENTS;
(B) TRASNPORTATION DIFFICULTIES THAT AFFECTED ARGENTINA, BOLIVIAN,
CHILEAN AND PERUVIAN RAILWAYS (MAINLY BECAUSE OF INSUFFICIENT
RAILWAY CARS, STRIKES, LANDSLIDES AND FLOODING) AND THAT AFFECTED
INTERNAL DISTRIBUTION IN BOLIVIA WHETHER BY RAIL OR TRUCK (MAINLY
DUE TO LANDSLIDES AND FLOODING); AND (C) RISING PRICES OF WHEAT,
FLOUR AND BREAD. OUR PROJECTION FOR FY 1975 ASSUMES CONSUMPTION
WILL RETURN TO AT LEAST FOUR PERCENT ANNUAL GROWTH TRACK TAKING
FY 1973 AS BASE YEAR. (HISTORICAL CONSUMPTION TREND FROM 1968 TO
1972 WAS SLIGHTLY MORE THAN 5 PERCENT). SHOULD CONSUMPTION NOT
REACH THIS LEVEL AND INSTEAD REMAIN STAGNANT AT ABOUT 245,000
M.T., OUR PROJECTION WOULD IMPLY HEALTHY AND MUCH NEEDED INCREASE
IN STOCKS TO ABOUT 27,578 M.T. STOCK LEVEL IN TABLE 2 UNREALISTI-
CALLY LOW AND GOB AUTHORITIES UNDOUBTEDLY PLANNING TON HIGHER
LEVEL.
5. OUR COMMERCIAL IMPORT ESTIMATES FOR FY 1975 INCLUDE 20,000 M.T.
OF FLOUR ALREADY PURCHASED FROM U.S., 30,000 M.T. OF WHEAT WHICH
PROBABLY WILL ALL COME FROM U.S. UNDER ALREADY AUTHORIZED CALL FOR
BIDS AND 90,000 M.T. OF FLOUR FROM ARGENTINA UNDER AN AGREEMENT






 01 OF 02 142301Z


ALREADY REACHED WITH GOA.
6. GOB AUTHORITIES HAVE LITTLE CONFIDENCE, HOWEVER, THAT 90,000
M.T. FLOUR AGREEMENT WILL BE CARRIED OUT. GOA FAILED TO DELIVER
ABOUT 34,000 M.T. OF FLOUR AT US$ 165 PER M.T. UNDER 1973 AGREE-
MENT. ACCORDING TO SUBSECRETARY LANDIVAR GOB HAD OPENED L/C'S
AND MADE DOWN PAYMENT IN 1973 ON REMAINING 34,000 M.T. AND IS
NOW REFUSING PROCEED WITH PURCHASES UNDER 90,000 M.T. AGREEMENT
UNTIL 1973 COMMITMENT FULFILLED OR DOWN PAYMENT RETURNED. GOB




                    

                    

ALSO HAD AGREEMENT WITH GOA TO PURCHASE 30,000 M.T. OF WHEAT IN
ADDITION TO 90,000 M.T. OF FLOUR, BUT THIS AGREEMENT WAS CAN-
CELLED (PRESUMABLY BEFORE L/C'S OPENED) WHEN GOB DISCOVERED
THAT WORLD MARKET WHEAT PRICES, ESPECIALLY U.S. PRICES, HAD
FALLEN FAR BELOW GOA QUOTE. UNCERTAINTIES ABOUT ARGENTINE
DELIVERIES MAY GROW INTO MAJOR PROBLEM, CAUSING GOB TO SHIFT
SOME OF THESE FLOUR PURCHASES TO OTHER SUPPLIERS IN LATE CY 1974.
7. BOLIVIA HAS GREATLY IMPROVED EXPORT EARNINGS PROSPECTS AND B/P
SURPLUS FOG CY 1974. BELIEVE, HOWEVER, ATTENTION SHOULD BE GIVEN
TO FORTUITOUS AND LIKELY HIGHLY TRANSIENT NATURE THIS IMPROVEMENT.
FIRST, IT SHOULD BE BORNE IN MIND THAT IN CY 1973, BOLIVIA'S
FOREIGN EXCHANGE COST FOR 93,800 M.T. OF IMPORTED FLOUR WAS ABOUT
US$16.9 MILLION AND FOR ABOUT 71,400 M.T. OF IMPORTED WHEAT (ALL
PL-480 TITLE I) WAS ABOUT US$ 4.2 MILLION INCLUDING CUP,
5 PERCENT DOWN PAYMENT, INTEREST, FREIGHT AND INSURANCE. AT
CURRENT PRICES OF ABOUT US$ 290 PER M.T. (CIF LA PAZ) FOR IMPORTED
FLOUR AND US$ 200 PER M.T. (CIF LA PAZ) FOR IMPORTED WHEAT, SAME
TONNAGES WOULD COST US$ 27.2 MILLION AND US$ 14.3 MILLION RES-
PECTIVELY WITHOUT PL-480 CREDIT. THIS WOULD MEAN SUDDEN US$ 20.4
MILLION IMPORT COST. ON BASIS OUR CURRENT ESTIMATES FOR FLOUR AND
WHEAT US$ 15.2 MILLION (USING ABOVE UNIT COSTS) FOR US$ 28.5
MILLION INCREASE OVER 1973 PAYMENTS. THIS INCREASE PLUS ALMOST US$ 20
MILLION INCREASE IN GULF COMPENSATION PAYMENTS OVER 1973 AND
OTHER DEBT SERVICE INCREASES WILL CUT DEEPLY INTO BOLIVIA'S
EXCHANGE RECEIPT GAINS DESPITE RISING PRICES FOR METALS AND HIGH,
BUT DECLINING, PRICES FOR CRUDE OIL.
8. WHILE BOLIVIA'S 1974 BALANCE OF PAYMENTS SURPLUS NOW MAY
TURN OUT TO BE CLOSER TO US$ 50 MILLION THAN TO LOW END OF RANGE
SENT REFAIR, THIS DUE IN LARGE PART TO LARGE COMMERCIAL BANK
LOANS WHICH DO NOT INDICATE STRENGTHENING OF BASIC BALANCE.
WHILE BASIC BALANCE PROBABLY WILL IMPROVE IN 1974, MUCH BASED ON
FRAGILE PRICE INCREASES OF METALS (CONCENTRATES) EXPORTS. NO ONE
SURE WHEN SPECULATIVE BUYING MAY END AND SEND PRICES DOWN.






 01 OF 02 142301Z


9. B/P SURPLUS FOR BOLIVIA LIKELY TO BE SHORT-LIVED AS IMPORT
PRICES, FREIGHT AND INSURANCE COSTS CATCH UP WITH EXPORT PRICE
INCREASES. IMF HAS PROJECTED B/P SURPLUS MAY ALMOST DISAPPEAR
AND MAY WELL BE IN DEFICIT IN 1975 AND THAT CURRENT ACCOUNT BALANCE
WILL AGAIN BE DECIDEDLY NEGATIVE ON ALL REASONABLE ASSUMPTIONS.
ADDITIONAL B/P ANALYSIS BEING SENT SEPTEL UNDER PREPARATION WITH
SUBJECT TITLE "IMPLICATIONS FOR BOLIVIAN ECONOMIC AND DEVEL-
OPMENT PROSPECTS OF ITS 1974 EXPORT PRICES".
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03128

- **Date:** May 14, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** WHEAT, DATA, PL 480 TITLE 1, BALANCE OF PAYMENTS DEFICITS, CREDIT AGREEMENTS, FOREIGN ASSISTANCE PROGRAMS,
