---
title: "Establishment Of Narcotics Advisor Position In Usaid/Bolivia"
author: "Stedman"
date: "March 25, 1974"
editor: visual
cable-date: "March 25, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2630"
cable-info: "Oct-01 Iso-00 Mms-03 Deae-00 Snm-02 Aid-20 Per-05 Ss-20 Abf-01 Spc-03 Ciae-00 Dode-00 Juse-00 Trse-00 Rsc-01 Drc-01 /077 W --------------------- 081841 R 251348z Mar 74"
cable-subject: "Establishment Of Narcotics Advisor Position In Usaid/Bolivia"
cable-tags: "SNAR BL"
cable-ref: "STATE 055765"
cable-doc-number: "1974LAPAZ01807"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "DRUG CONTROL, FOREIGN ASSISTANCE PROGRAMS, PERSONNEL ASSIGNMENTS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Embassy appreciates opportunity to give more detailed assessment of its need for a new narcotics advisor position. Annex B of Survey Report of Narcotics Law Enforcement Study Team No. 4 (April-May 1972) gives a good picture of problems faced by GOB in coming to grips with the narcotics problem in Bolivia and proposes a strategy and plan of action for USG assistance which this Embassy through its Narcotics Control Action Plans has been trying to implement since that time.
2. While considerable progress has been made, e.g., the passage of a comprehensive narcotics law, the assignment of a DEA unit to the US Embassy, fairly extensive training to Bolivian enforcement officers both in the US and in-country, and the provision of equipment and operating funds to the narcotics unit in the police force, we are still in Phase I of the two-phase approach recommended in the Survey Report.
3. In the advisory category, the narcotics advisor would help the GOB in the difficult initial task of developing rationally the various segments of a comprehensive program of narcotics control, to be implemented by new units authorized under Bolivia's recently enacted Narcotics Control Law, (especially the high level entity with many added functions beyond enforcement). Certain of these activities probably will be formalized into various project agreements involving reasonable US financial and appropriate technical assistance.
4. In the institution building phase, the narcotics advisor would assist the GOB in working out a system of coordination and control of the various groups in Bolivia that have an interest or role in narcotics control efforts, e.g., various units in the police force, National Customs, Agricultural Customs, provincial authorities and the four Ministries members of the National Narcotics Control Board. The new overall narcotics entity authorized in the recent law should come into official being in the next few months, but needs our technical help. During its formative stage, when the institutional battles are being fought which will determine to a considerable degree what practical authority and influence this entity will have, it would be in our interest to provide support in the form of close, full-time liaison as well as some financial and appropriate technical assistance.
5. With regard to paragraph 2, reftel, we do indeed wish to retain the services of David S. Arroyo, USAID Public Safety Officer, for the new position. We do not suggest that Public Safety experience per se would be utilized in basic research to develop statistics on coca production, distribution and consumption. Basically the need is to bird-dog the Bolivians to do this job and it would be but one of several insignificant tasks of the narcotics advisor. We wish to keep Arroyo because he already has a deep knowledge of Bolivia and Bolivians, a demonstrated capacity to be effective, and the personal qualities of persuasiveness, tact, and charm that will assure this Mission of maximum effectiveness in the pursuit of our interests in the narcotics field during this complicated, ground-breaking period. Arroyo is bilingual. Arroyo already is preparing the groundwork for the relationships envisioned above, and the Ambassador has received personal requests from both the new Minister of Interior and the Sub-Secretary of Justice (at present the highest authorities in narcotics matters) that Arroyo be assigned to the new narcotics entity as a full-time advisor.
6. Regarding comment in paragraph 3 reftel, we believe that DEA representatives here will continue to be effective in their enforcement role if they are the primary contacts with the Bolivian Narcotics Enforcement Unit, which we conceive of being an arm of the overall narcotics unit. Due to his previous experience with the Bolivian Narcotics Enforcement Unit and his pioneering work in getting that unit established and operating, Arroyo will be of great service in providing counsel to DEA. However, we do not wish to encourage any confusion in the minds of the leaders of that police enforcement unit as to whom they must do business with in the US Mission, and we have therefore given DEA that responsibility. Furthermore, we believe that substituting DEA for OPS in the performance of duties in narcotics support work formerly done by OPS should remove any doubts that may remain in Washington that the establishment of a narcotics advisor position is merely a way of retaining the old OPS relationship here. Of major importance, however, is our belief that once confirmed in his new role as described above, Arroyo would be able to devote only a very small percentage of his time to the needs of the enforcement unit, whereas DEA can do this on a day-to-day basis. Finally, the Ambassador feels strongly that the retention of Mr. Arroyo here and his assignment to this position would make a meaningful contribution to the US Government's efforts on the narcotics front in Bolivia.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01807

- **Date:** March 25, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** DRUG CONTROL, FOREIGN ASSISTANCE PROGRAMS, PERSONNEL ASSIGNMENTS