---
title: "Bolivia Four Shortages"
author: "Stedman"
date: "January 16, 1974"
editor: visual
cable-date: "January 16, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 1946"
cable-info: "Oct-01 Iso-00 Aid-20 Iga-02 Agr-20 Eb-11 Come-00 Trse-00 Omb-01 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-10 Pa-04 Rsc-01 Prs-01 Spc-03 Ss-20 Usia-15 Drc-01 /153 W --------------------- 116898 R 161330z Jan 74"
cable-subject: "Bolivia Four Shortages"
cable-tags: "EAID, BL"
cable-ref: "LA PAZ 0246, AND LA PAZ 244 SUMMARY: BOLIVIA CURRENTLY EXPERIENCING SERIOUS FLOUR SHORTAGE WITH SERIOUS POLITICAL IMPLICATIONS FOR GOVERNMENT. ALTHOUGH PRECISE REASONS FOR CURRENT PROBLEM DIFFICULT TO UNTANGLE, BASIC CAUSE APPEARS TO BE FAILURE OF ARGENTINA TO FULFILL COMMITMENTS FOR FLOUR DELIVERIES. THIS HAS BEEN COUPLED IN RECENT WEEKS WITH GREATER THAN USUAL TRANSPORTATION DIFFICULTIES FROM PORTS, ESPECIALLY PERUVIAN RAIL STRIKE WHICH SLOWED MOVEMENT OF PL-480 WHEAT FROM MATARANI. SITUATION MAY IMPROVE THIS WEEK AS RAILROADS NOW MOVING WHEAT AT NORMAL PACE AND SMALL QUANTITY OF FOUR DUE TO ARRIVE FROM ARGENTINA, BUT SHORTAGES LIKELY TO REAPPEAR SINCE STOCKS WILL CONTINUE LOW AND SCARCITIES HAVE INDUCED SPECULATION AND CREATION BLACK MARKET. END SUMMARY."
cable-doc-number: "1974LAPAZ00292"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "FOOD SHORTAGE, AGREEMENTS, PUBLIC DEMONSTRATIONS, FLOUR, FOREIGN COMMITMENTS, BLACK MARKETS,"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. According to Millers' Association on January 10, mills had only 1,525 M.T. of wheat stocks. Two of three La Paz mills and one of two mills in Oruro were out and closed January 11. Mills reopened January 14 using wheat that arrived over weekend. Oruro and La Paz are supplied from Matarani. Mills in Cochabamba, supplied from Antofagasta, have improved position in first week of year but mills in other interior towns also showed decline in stocks. Authorities estimate that daily wheat consumption is 632 M.T. in country, of which 138 M.T. consumed in La Paz.

2. Under normal circumstances 2,000 M.T. of wheat can be moved from Matarani per week and 1,680 M.T. from Antofagasta. In fact, in December only 10,250 M.T. of PL-480 reached Bolivia from ports. On January 10, 6,000 M.T. of PL-480 wheat from October arrivals still in Antofagasta and 5,935 M.T. in Matarani from arrivals in November and before.

3. As reported earlier, GOB contracted last year for 86,000 M.T. flour from Argentina. When agreement failed to function it renegotiated in October for delivery 30,000 M.T. flour in following three months. At minimum Bolivia thus expected to receive 15,000 M.T. before end of year. Only 5,000 M.T. arrived. Sub-Secretary of MININD/COM traveled to Buenos Aires last week and government has announced that 1,500 M.T. Argentine flour due to arrive at border this week.

4. Scarcity of foodstuffs, including sugar, meat and cooking oil, has become principal Bolivian conversation topic. Week January 7, long waiting lines evident throughout city, especially in working barrios. Small demonstration of workers in Quillacollo near Cochabamba protesting shortages and prices broken up by police January 11. Nasty charges of hoarding and profitmaking have been aimed at millers and bakers. Government has made highly publicized "raids" on warehouses and La Paz authorities are now supervising distribution of certain products. Problem becoming political issue. Element of FSB called for end of wheat subsidy and another dissident FSB element published PL-480 arrival information and implied that quantities being misdirected. (Comment: We have no evidence of this. Problem seems to be shortfall arrivals).

5. On TV broadcast January 15, MININD/COM stated that contraband routes into Peru and Chile had been closely checked in recent weeks and that only very small amounts of flour had been found. Said this suggested that flour being hoarded and black marketed. After review steps being taken to speed deliveries Argentine flour to La Paz, said situation should ease in seven to ten days. (Comment: Situation not likely to improve much or for long unless flour and wheat stocks can be built up).

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00292

- **Date:** January 16, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** FOOD SHORTAGE, AGREEMENTS, PUBLIC DEMONSTRATIONS, FLOUR, FOREIGN COMMITMENTS, BLACK MARKETS,
