---
title: "Institute Of Geologic, Mining, And Metallurgic Investigations (Geomin) Created By Bolivian Government"
author: "Stedman"
date: "July 08, 1974"
editor: visual
cable-date: "July 08, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3592"
cable-info: "Oct-01 Iso-00 Aec-11 Aid-20 Cea-02 Ciae-00 Ciep-02 Come-00 Dode-00 Eb-11 Fpc-01 H-03 Inr-10 Int-08 L-03 Nsae-00 Nsc-07 Omb-01 Pm-07 Rsc-01 Sam-01 Sci-06 Sp-03 Ss-20 Str-08 Trse-00 Fea-02 Pa-04 Prs-01 Usia-15 Io-14 Drc-01 /183 W --------------------- 045915 R 082042z Jul 74"
cable-subject: "Institute Of Geologic, Mining, And Metallurgic Investigations (Geomin) Created By Bolivian Government"
cable-tags: "EMIN, ENRG TECH, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ04391"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "MINING, TECHNICAL ASSISTANCE, ECONOMIC ASSISTANCE, GEOLOGIC SURVEYS, INVESTIGATIONS, METALLURGY,"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. INSTITUTO DE INVESTIGACIONES GEOLOGICO-MINERO-METALURGICO
(GEOMIN) CREATED BY SUPREME DECREE REPORTEDLY ON JULY 7.
GEOMIN IS RESULT OF INTEGRATION OF SERVICIO GEOLOGICO DE
BOLIVIA (GEOBOL), INSTITUTO DE INVESTIGACIONES MINERO-
METALURGICAS (IIMM), AND DEPARTAMENTO DE MATERIAS PRIMAS
(DEPARTMENT RAW MATERIALS) OF COMISION BOLIVIANA DE
ENERGIA NUCLEAR (COBOEN).


2. GEOMIN DEPENDS ON MINISTRY OF MINING AND METALLURGY
AND ITS ACTIVITIES ANR GEOLOGIC EXPLORATION, MINING AND
METALLURGICAL INVESTIGATIONS. IT ALSO WILL ACT AS ADVISER
AND GIVE TECHNICAL ASSISTANCE TO MINING INDUSTRY. IT
IS MANAGED BY ADMINISTRATIVE COUNCIL PRESIDED BY MIN MINING
AND MADE UP BY REPRESENTATIVES OF MIN MINING, MIN FIN,
COMIBOL, ENAF, BANCO MINERO, AND PRIVATE MINING INDUSTRY.


3. EXECUTIVE DIRECTOR OF GEOMIN TO BE NAMED BY MIN MINING






 082145Z


WITH APPROVAL OF PRESIDENT OF REPUBLIC. ALL FINANCING FROM




                        

                 

NATIONAL TREASURY WHICH PREVIOUSLY GIVEN GEOBOL, IIMM,
AND COBOEM'S DEPARTMENT RAW MATERIALS WILL GO T GEOMIN.
ALSO, ALL CONTRIBUTIONS BY STATE AND NATIONAL PRIVATE
ENTITIES, PRIVATE FOREIGN ENTITIES, AND INTERNATIONAL
ORGANIZATIONS PREVIOUSLY GIVEN SEPARATELY TO THREE
COMPONENT ORGANIZATIONS WILL GO TO GEOMIN.


4. COMMENT: CREATION OF GEOMIN APPEARS ADVANTAGEOUS
BECAUSE IT CENTRALIZES THREE GOVERNMENT AGENCIES, REDUCING
POSSIBILITY OF REPETITIVE WORK AND BECAUSE FACT GATHERING
ON MINERALS INDUSTRY BY POTENTIAL INVESTORS COULD BE MADE
EASIER.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04391

- **Date:** July 08, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** MINING, TECHNICAL ASSISTANCE, ECONOMIC ASSISTANCE, GEOLOGIC SURVEYS, INVESTIGATIONS, METALLURGY,
