---
title: "[subject not available]"
author: "Morton"
date: "August 12, 1974"
editor: visual
cable-date: "August 12, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "Usinfo WashDC"
cable-info: "Oct-01 Iso-00 Pa-01 Inr-01 /005 W --------------------- 046107 R 121930z Aug 74"
cable-subject: "[subject not available]"
cable-tags: "PFOR, US, BL, (FORD, GERALD R), (NIXON, RICHARD M)"
cable-ref: ""
cable-doc-number: "1974LAPAZ05124"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PRESS COMMENTS, AMITY, FOREIGN RELATIONS, PRESIDENTIAL SUCCESSION, DIPLOMATIC COMMUNICATIONS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


Message Text




 122050Z


70
ACTION ARA-02


INFO OCT-01 ISO-00 PA-01 INR-01 /005 W
           --------------------- 046107
R 121930Z AUG 74
FM AMEMBASSY LA PAZ
TO USINFO WASHDC
INFO SECSTATE WASHDC 3877


UNCLAS LA PAZ 5124


FOR: IPS/IBS


LA PAZ." TODOS LOS PERIODICOS LOCALES, ESTE ULTIMO FIN DE SEMANA,
DEDICARSON SUS PRIMERAS PLANAS Y GRAN PARTE DE SUS SECCIONES DE
NOTICIAS INTERNACIONALES AL DESENLACE DEL LLAMADO "ESCANDELO
"WATERGATE" Y LA ASENSION DEL PRESIDENT FORD.
EL PRESIDENTE DE BOLIVIA, GENERAL HUGO BANZER SUAREZ, ENVIO
UN MENSAJE A GERALD FORD EXPRESANDOLE "SU MAS VIVA FELICITACION
POR HABER ASUMIDO LA PRIMERA MAGISTRATURA DE LA GRAN NACION
AMERICANA", MIENTRAS QUE EL CANCILLER ALBERTO GUZMAN ENVIO OTRO
MENSAJE AL SECRETARIO DE ESTADO, HENRY KISSINGER, FELICITANDOLO POR
SU RATIFICACION QUE, SEGUEN DICE, "PERMITIRA A MI PATRIA SEGUIR
CONTANDO CON UN LEAL AMIGO Y PROSEGUIDOR CON LA TRADICIONAL
POLITICA DE COOPERACION MUTUA QUE ANIMA A NUESTROS PUEBLOS Y
GOBIERNOS". POR SU PARTE, EL EMBAJADOR DE LOS ESTADOS UNIDOS,
WILLIAM P STEDMAN, REQUERIDO POR LA PRENSA DECLARO QUE LA
RENUNCIA DE NIXON RESULTABA UNA OCASION TRISTE "PERO
SERVIA PARA DEMOSTRAR DE FUERZA DE LAS INSTITUCIONES NORTEAMERICANAS"
.
ANDADIO EL SENOR STEDMAN QUE LA PRESENCIA DEL SENIOR HENRY
KISSINGER EN EL GOBIERNO "GARANTIZA LA
CONTINUIDAD DE LA POLITICA EXTERIOR DE LOS ESTADOS UNIDOS".
ASIMISMO, LA OPINION EDITORIAL DE LA PRENSA BOLIVIANA SE
SINTETIZA EL LOS SIGUIENTES CONCEPTOS".
EL MATUTINO "PRESENCIA" DICE QUE FRENTE A LA CARA NEGATIVE DEL
CITADO ESCANDELO, SURGE LA OTRA CARA QUE CONTIENE ASPECTOS
POSITIVOS, QUE SON MUCHOS Y MUY PODEROSOS. "POR EJEMPLO - DICE
- SE HA MOSTRADO UNA ENORME OBJETIVIDAD EN LAS COMISIONES
CONGRESALES QUE REALIZARON LAS INVESTIGACIONES Y QUE BUSCABAN






 122050Z


SALVAR, POR SOBRE TODO, LA INSTITUCIONALIDAD DE SU PAIS.




                     

                   

LA CORTE SUPREMA HA DADO UN EJEMPLO DE INDEPENDENCIA AL
IMPONER LA LEY FRENTE AL PRIMER MANDATARIO. LOS MEDIOS DE INFORMACION
,
COMO SIEMPRE, HAN COMPROBADO QUE EJERCEN, SIN PREJUICIOS
NI CORTAPISAS, EL DERECHO A LA LIBRE INFORMACION. LOS PROPIOS
FUNCIONARIOS DEL PODER EJECUTIVO - COMO LOS FISCALES QUE
INTERVINIERON EN EL CASO - DEMOSTRARON QUE SIRVEN A LAS
INSTITUCIONES Y A LA NACION Y NOS AL GOBIERNO"... "SI SOPRESAMOS,
POR UN LADO, EL ESCANDALO Y EL DESPRESTIGIO CONSIGUIENTE
Y, POR OTRO, LA IMPRESION MUNIDIAL QUE HA CAUSADO LA SOLIDEZ
DE LAS INSTITUCIONES DEMONCRATICAS, ES EVIDENTE QUE EL BALANCE
ES FAVORABLE Y QUE ESTADOS UNIDOS HA DEMOSTRADO SU CAPACIDAD
PARA GARANTIZAR EL REINO DE LA LIBERTAD Y DE LA JUSTICIA,
EN EL ORDEN INTERNO".
"EL DIARIO" DECANO DE LA PRENSA BOLIVIANA-AFIRMA QUE "SE
EQUIVOCAN QUIENES CREEN QUE WATERGATE HA DEBILITADO AL SISTEMA
DEMOCRATICO-REPRESENTATIVO DE LOS ESTAODS UNIDOS QUE, POR EL
CONTRARIO, SALE FORTALECIDO DE ESTA PRUEBA DE FUEGO". MAS ADELANTE
AIRMA QUE: "POR DURA QUE PAREZCA LA PRUEBE DE WATERGATE, ES MAS
ETICA Y BENIGNA QUE LOS DERROCAMIENTOS DE GOBERNANTES,
MENUDO BRUTALES Y SANGRIENTOS QUE CARACTERIZAN A LAS PSUEDO
DEMOCRACIAS, PARA NO HABLAR DE LOS REGIMENES TOTALITARIOS
EN LOS QUE EL PODER ABSOLUTO DE LOS QUE GOBIERNAN SE NUTRE
IMPLACABLEMENTE DE LA LIBERTAD, LOS DERECHOS Y LA VIDA MISMA
DE LOS GOBERNADOS. WATERGATE ENCIERRA ENSENANZAS QUE TODOS LOS
GOBERNANTES DEBERIAN RECOGER".
EL TABIOIDE "HOY" EN SU EDITORIAL DEL SABADO 10, AL REFERIRSE A LA
REUNCIA DEL PRESDIDENTE NIXON, DICE: "LA PIEDAD, SIGNO
CONTRARIO A LA CRUEIDAD, ES SENTIMIENTO QUE ENNOBLECE AL QUE
LO ABRIGA. SERA EL QUE CONVENGA INSPIRAR LOS JUCIOS QUE
SE HAGAN SOBRE EL PRESIDENTE REUNCIANTE"..."LAS PALABRAS DE
SU DISCURSO DE DESPEDIDA DE LA CASA BLANCA SON PRUEBA DE LO
QUE LE GUIO POR SOBRE TODO EL BIEN DE SU NCION. LASTIMA
QUE NO HAYA PENSADO ASI CUANDO TOMO PARTE EN LOS ENTREVEROS
DE WATERGATE. SE PERDIO UN PERSONAJE, PERO SE SALVO LA
DEMOCRACIA". EN OTRO EDITORIAL PUBLICADO EL DOMINGO ULTIMO,
"HOY" DICE QUE "HABRA QUE TENER CONFIANZA EN QUE LA POLITICA (DE ESTA
DOS
UNIDOS) CON LA AMERICA LATINA HA DE SEGUIR EL MISMO
RITMO DE BUEN ENTENDIMIENTO Y COOPERACION. MAS CONCRETAMENTE,






 122050Z


PREGUNTADO EL SECRETARIO KISSINGER POR LOS PERIODISTAS,
CONTESTO QUE "NADA HA CAMDIADO DESDE WASHINGTON, MEXICO Y
ATLANTA" REFIRIENDOSE SIN DUBA A LOS COLOQUIOS HABIDOS CON
PAISES LATINOAMERICANOS EN ESOS TRES LUGARES.
SE REFIRIO TAMBIEN A SU POSIBLE VISITA A ALGUNO DE ELLOS.
LO QUE QUIERE DECIR QUE PROSEQUIRA EL DIALOGO EN LOS MISMOS
TERMINOS ESTABLECIDOS, QUE HAN SIDO LOS DE BUENA AMISTAD Y LEAL
AYUDA POR PARTE DE LA NACION DEL NORTE".




                   

               

MORTON








NNN




               

                     


                                                       Message Attributes
Automatic Decaptioning: X
Capture Date: 01 JAN 1994
Channel Indicators: n/a
Current Classification: 
Concepts: PRESS COMMENTS, AMITY, FOREIGN RELATIONS, PRESIDENTIAL SUCCESSION, DIPLOMATIC COMMUNICATIONS
Control Number: n/a
Copy: SINGLE
Draft Date: 12 AUG 1974
Decaption Date: 01 JAN 1960
Decaption Note:
Disposition Action: n/a
Disposition Approved on Date:
Disposition Authority: n/a
Disposition Case Number: n/a
Disposition Comment:
Disposition Date: 01 JAN 1960
Disposition Event:
Disposition History: n/a
Disposition Reason:
Disposition Remarks:
Document Number: 1974LAPAZ05124
Document Source: CORE
Document Unique ID: 00
Drafter: n/a
Enclosure: n/a
Executive Order: N/A
Errors: N/A
Film Number: D740220-1167
From: LA PAZ
Handling Restrictions: n/a
Image Path:
ISecure: 1
Legacy Key: link1974/newtext/t19740856/aaaabvpu.tel
Line Count: 116
Locator: TEXT ON-LINE, ON MICROFILM
Office: ACTION ARA
Original Classification: 
Original Handling Restrictions: n/a
Original Previous Classification: n/a
Original Previous Handling Restrictions: n/a
Page Count: 3
Previous Channel Indicators:
Previous Classification: n/a
Previous Handling Restrictions: n/a
Reference: n/a
Review Action: RELEASED, APPROVED
Review Authority: golinofr
Review Comment: n/a
Review Content Flags:
Review Date: 26 JUN 2002
Review Event:
Review Exemptions: n/a
Review History: RELEASED <26 JUN 2002 by reddocgw>; APPROVED <27 JUN 2002 by golinofr>
Review Markings:


US Department of State

30 JUN 2005


Review Media Identifier:
Review Referrals: n/a
Review Release Date: n/a
Review Release Event: n/a
Review Transfer Date:
Review Withdrawn Fields: n/a
Secure: OPEN
Status: NATIVE
Subject: n/a
TAGS: PFOR, US, BL, (FORD, GERALD R), (NIXON, RICHARD M)
To: n/a
Type: TE
Markings:

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05124

- **Date:** August 12, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PRESS COMMENTS, AMITY, FOREIGN RELATIONS, PRESIDENTIAL SUCCESSION, DIPLOMATIC COMMUNICATIONS
