---
title: "Faa Section 32--Political Prisoners"
author: "Stedman"
date: "July 19, 1974"
editor: visual
cable-date: "July 19, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3709"
cable-info: "Oct-01 Iso-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-11 L-03 Nsae-00 Nsc-07 Pa-04 Rsc-01 Prs-01 Sp-03 Ss-20 Usia-15 Aid-20 Iga-02 Trse-00 /118 W --------------------- 054676 R 192117z Jul 74"
cable-subject: "Faa Section 32--Political Prisoners"
cable-tags: "PINS BL"
cable-ref: "STATE 150955"
cable-doc-number: "1974LAPAZ04690"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "MILITARY ASSISTANCE, HUMAN RIGHTS, LAW, FOREIGN ASSISTANCE, POLITICAL PRISONERS, FOREIGN POLICY POSITION"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. IN ACCORDANCE WITH REFTEL, I CALLED ON BOLIVIAN FOREIGN
MINISTER GUZMAN ON JULY 19 TO PROVIDE HIM AND THE GOB WITH
TEXT OF SECTION 32 OF FAA. I EXPLAINED THAT WHILE SENSE OF
CONGRESSIONAL PROVISION IS NOT MANDATORY REQUIREMENT UPON THE
PRESIDENT, IT DOES EXPRESS CONTINUING CONGRESSIONAL CONCERN
WITH POLITICAL PRISONERS AND HUMAN RIGHTS. I NOTED THAT SECTION
WAS IN FOREIGN ASSISTANCE ACT AND THAT APPROPRIATION OF FUNDS
FOR ASSISTANCE PROGRAMS NOW BEING CONSIDERED. I NOTED THAT
BOLIVIA WAS NOT BEING SINGLED OUT BUT THAT ALL AID RECIPIENT
GOVERNMENTS WERE BEING INFORMED OF THIS PROVISION.
I INDICATED THAT SECTION 32 DESERVES SERIOUS CONSIDERATION
BY THE GOB.


2. FOREIGN MINISTER GUZMAN READ SPANISH TEXT I PROVIDED HIM OF
SECTION 32 AND INDICATED HIS GENERAL APPROVAL OF THE
CONGRESSIONAL SENTIMENT. HE NOTED DIFFERENCE BETWEEN
GOVERNMENT TAKING ACTION AGAINST CITIZENS FOR POLITICAL
PURPOSES AND CITIZENS ENGAGING IN ILLEGAL ACTS AGAINST
GOVERNMENT REQUIREING PROTECTIVE MEASURES BY AUTHORITIES.
HE NOTED THAT NEWLY INSTALLED MILITARY CABINET SHOULD IMPROVE






 192224Z


POLITICAL STABILITY IN BOLIVIA AND THAT EPISODES SUCH AS




                      

                 

THE RECENT ABORTIVE PLOT OF JUNE 4/5 SHOULD NOT RECUR.
THEREFORE, GOB NEED NOT RESORT TO REPRESSIVE MEASURES BECAUSE
POLITICAL TRAQUILITY SHOULD BE INSURED NOW. FOREIGN MINISTER
SAID FOREGOING REMARKS SHOULD BE TREATTED AS HIS IMMEDIATE
PERSONAL REACTION TO READING TEXT OF SECTION 32 OF FAA.
HE SAID HE WOULD HAVE EARLY OPPORTUNITY TO MEET WITH PRESIDENT
AND WOULD REVIEW WITH HIM THE CONGRESSIONAL CONCERNS SO AS
TO GIVE ME AN OFFICIAL GOB POSITION.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04690

- **Date:** July 19, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** MILITARY ASSISTANCE, HUMAN RIGHTS, LAW, FOREIGN ASSISTANCE, POLITICAL PRISONERS, FOREIGN POLICY POSITION