---
title: "Opic Insurance Application: Charles E. Stokes"
author: "Parker"
date: "August 26, 1974"
editor: visual
cable-date: "August 26, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 4027"
cable-info: "Oct-01 Ara-16 Iso-00 Eb-11 Come-00 Aid-20 L-03 Ciae-00 Inr-11 Nsae-00 /074 W --------------------- 062693 R 261730z Aug 74"
cable-subject: "Opic Insurance Application: Charles E. Stokes"
cable-tags: "EINV, BL"
cable-ref: "(A) LA PAZ 2766; (B) STATE 185136"
cable-doc-number: "1974LAPAZ05513"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "INSURANCE, NATIONALIZATION, INVESTORS, LAND REFORMS, REAL PROPERTY ACQUISITION"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. EMBASSY STRONGLY OPPOSES ANY OPIC INSURANCE FOR STOKES OR
ANY OTHER U.S. CITIZEN PURCHASING FARMLAND IN BOLIVIA IN
WHATEVER REGION OF COUNTRY (FOR REASONS MADE CLEAR IN REF (A)
UNTIL SUCH INVESTOR ALREADY HAS DECREE ESTABLISHING
"INAFFECTABILITY" FOR PURPOSES OF EXPROPRIATION UNDER AGRARIAN
LAND REFORM.


2. OPIC HAS NOT RESOLVED OTHER ISSUES RAISED REF A, ESPECIALLY
PARA. 7.


3. WE SURPRISED STATEMENT PARA 1(D) OF REF B THAT OPIC WISHES
ISSUE INSURANCE INEARLY SEPTEMBER AS EMBASSY HAS NOT APPROVED
OPIC INSURANCE FOR THIS INVESTMENT IN SENSITIVE AREA.
PARKER

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05513

- **Date:** August 26, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** INSURANCE, NATIONALIZATION, INVESTORS, LAND REFORMS, REAL PROPERTY ACQUISITION
