---
title: "Idb Annual Meeting Refs: (A) State 34868: (B) La Paz 1587"
author: "Stedman"
date: "March 21, 1974"
editor: visual
cable-date: "March 21, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 2606"
cable-info: "Oct-01 Ara-16 Iso-00 Aid-20 Io-14 Trse-00 Oic-04 Ss-20 Spc-03 Str-08 Come-00 Frb-02 Omb-01 Xmb-07 Sam-01 Ciae-00 Inr-10 Nsae-00 Rsc-01 Drc-01 /120 W --------------------- 044412 P 212122z Mar 74"
cable-subject: "Idb Annual Meeting Refs: (A) State 34868: (B) La Paz 1587"
cable-tags: "EFIN, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ01754"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "CENTRAL BANK, BIOGRAPHIC INFORMATION, DEVELOPMENT BANKS, COMMITTEE MEETINGS, ANNUAL REPORTS, FLOODS,"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. GOB delegation to IDB Annual Meeting reportedly will consist of Lic. Manuel Mercado, President, Central Bank, Luis Viscarra, General Manager, Central Bank, Guiddo Valle, ex-IDB Director for Bolivia, Paraguay and Uruguay, Hector Ormachea, ex-Minister of Industry and Commerce and Director Designate of still to be established Institute of External Financing.

2. MINFIN, who is IDB Governor, will not attend. He had promised Embassy coordinated response points (A) and (B) of para 2 ref A, but did say that flood damage reconstruction financing would be major topic for Bolivia at meeting and that specific IDB loan problems such as loans for YPFB refineries and Oruro-Quillacollo Highway probably would be dealt with in meetings with IDB missions already in Bolivia or soon to arrive.

3. MINFIN subsequently asked Ormachea to call ECONOFF to discuss points (A) and (B). According to Ormachea, GOB del will wish discuss with U.S. del possible second loan for the Central Bank Agricultural Rediscount Fund (FRA), further PL-480 Title I Sales Agreement and flood reconstruction financing. GOB position on matters to be formally raised in plenary has not yet been established. Mercado and Ormachea agreed to meet with ECONOFF on March 25 to provide further info on points (A) and (B).

4. Re point (C) para 2 ref (A), believe Treasury officials of U.S. del should explore with Mercado and Viscarra Bolivia's balance of payments estimates (which are being carefully reviewed by annual Art. VIII IMF mission at present time) and with Ormachea YPFB's prospects, plans and creditworthiness for possible Eximbank financing for major projects such as gas pipeline from Santa Rosa-Yapacani fields to Brazilian border at Corumba and Mutun iron/manganese deposit, fertilizer, pesticide and herbicide plants. YPFB also requires some US$ 30 million additional financing over US$ 46.5 million thus far offered by IDB for refineries program and has been negotiating with commercial banks to cover this requirement.

5. Ref B provides Mission's current views on IDB program for Bolivia. We reiterate our concern that all agencies, bilateral and multilateral continue urge upon GOB desirability preparation agricultural production plan and coordination of its financing.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01754

- **Date:** March 21, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** CENTRAL BANK, BIOGRAPHIC INFORMATION, DEVELOPMENT BANKS, COMMITTEE MEETINGS, ANNUAL REPORTS, FLOODS,
