---
title: "House Subcommittee Decisions"
author: "Stedman"
date: "May 08, 1974"
editor: visual
cable-date: "May 08, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3023"
cable-info: "Oct-01 Ara-16 Iso-00 Agr-20 Come-00 Trse-00 Omb-01 Swf-02 Tar-02 Str-08 Cea-02 Ss-20 Nsc-07 Ciae-00 Inr-10 Nsae-00 Rsc-01 Drc-01 L-03 H-03 Sp-03 ( Iso ) W --------------------- 080701 R 081544z May 74"
cable-subject: "House Subcommittee Decisions"
cable-tags: "ETRD, EAGR"
cable-ref: ""
cable-doc-number: "1974LAPAZ02935"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "ECONOMIC GROWTH, DATA, MARKETS, US CONGRESSIONAL HEARINGS, COMMITTEES"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


Message Text




 081610Z


50
ACTION EB-11


INFO OCT-01 ARA-16 ISO-00 AGR-20 COME-00 TRSE-00 OMB-01


  SWF-02 TAR-02 STR-08 CEA-02 SS-20 NSC-07 CIAE-00


   INR-10 NSAE-00 RSC-01 DRC-01 L-03 H-03 SP-03 ( ISO ) W
           --------------------- 080701
R 081544Z MAY 74
FM AMEMBASSY LA PAZ
TO SECSTATE WASHDC 3023



 LA PAZ 2935


E. O. 11652: N/A
TAGS: ETRD, EAGR
SUBJ: HOUSE SUBCOMMITTEE DECISIONS


REF: STATE 92672


WOULD APPRECIATE WHATEVER INFO DEPARTMENT CAN SUPPLY US ON
SUBCOMMITTEE'S
RATIONALE FOR INCLUDING BOLIVIA AMONG COUNTRIES THAT WOULD NOT BE
ELIGIBLE TO PARTICIPATE IN DEFICIT REALLOCATIONS OR MARKET GROWTH.
WE PLAN TO GIVE GOB AUTHORITIES INFO CONTAINED REFTEL AS SOON AS WE
HAVE DEPARTMENT'S REPLY.
STEDMAN








NNN




                    

                     


                                                       Message Attributes
Automatic Decaptioning: X
Capture Date: 01 JAN 1994
Channel Indicators: n/a
Current Classification: 
Concepts: ECONOMIC GROWTH, DATA, MARKETS, US CONGRESSIONAL HEARINGS, COMMITTEES
Control Number: n/a
Copy: SINGLE
Draft Date: 08 MAY 1974
Decaption Date: 01 JAN 1960
Decaption Note:
Disposition Action: RELEASED
Disposition Approved on Date:
Disposition Authority: GarlanWA
Disposition Case Number: n/a
Disposition Comment: 25 YEAR REVIEW
Disposition Date: 28 MAY 2004
Disposition Event:
Disposition History: n/a
Disposition Reason:
Disposition Remarks:
Document Number: 1974LAPAZ02935
Document Source: CORE
Document Unique ID: 00
Drafter: n/a
Enclosure: n/a
Executive Order: N/A
Errors: N/A
Film Number: D740112-0066
From: LA PAZ
Handling Restrictions: n/a
Image Path:
ISecure: 1
Legacy Key: link1974/newtext/t19740565/aaaacgcj.tel
Line Count: 42
Locator: TEXT ON-LINE, ON MICROFILM
Office: ACTION EB
Original Classification: 
Original Handling Restrictions: n/a
Original Previous Classification: n/a
Original Previous Handling Restrictions: n/a
Page Count: 1
Previous Channel Indicators: n/a
Previous Classification: 
Previous Handling Restrictions: n/a
Reference: STATE 92672
Review Action: RELEASED, APPROVED
Review Authority: GarlanWA
Review Comment: n/a
Review Content Flags:
Review Date: 09 SEP 2002
Review Event:
Review Exemptions: n/a
Review History: RELEASED <09 SEP 2002 by cunninfx>; APPROVED <06 FEB 2003 by GarlanWA>
Review Markings:


US Department of State

30 JUN 2005


Review Media Identifier:
Review Referrals: n/a
Review Release Date: n/a
Review Release Event: n/a
Review Transfer Date:
Review Withdrawn Fields: n/a
Secure: OPEN
Status: NATIVE
Subject: HOUSE SUBCOMMITTEE DECISIONS
TAGS: ETRD, EAGR, BL
To: STATE
Type: TE
Markings:

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02935

- **Date:** May 08, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** ECONOMIC GROWTH, DATA, MARKETS, US CONGRESSIONAL HEARINGS, COMMITTEES
