---
title: "Major Project: Lead/Silver Metallurgical Project"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "July 06, 1979"
editor: visual
cable-date: "July 06, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 7128"
cable-info: "Oct-01 Ara-15 Ads-00 Eb-08 /028 W ------------------087075 062046z /62 P 061951z Jul 79"
cable-subject: "Major Project: Lead/Silver Metallurgical Project"
cable-tags: "BENC, BL"
cable-ref: "(A) STATE 167233, (B) LA PAZ 5090"
cable-doc-number: "1979LAPAZ05806"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "n/a"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1.  Embassy agrees with Hensey-Schmidt assessment that companies following project during the last two years do have a better chance to be successful bidder.

2.  Bid deadline has been extended to August 10, 1979 at 6:30 P.M. La Paz time. Specifications can be obtained directly through ENAF, Av. Villazon 1966, La Paz, Bolivia at a cost of US$ 500 (five hundred dollars). Embassy is unable to obtain a free copy of the specifications.

3.  To repeat info in prior cable: Telex numbers for Sociedad Complejo Metalurgico de Karachipampa are as follows: All America 35690 ENAFBOL and ENTEL 2300 ENAFBV.

4.  Design and construction of the project will be done by Klockner. Bid request is for an entity to serve ENAF as a consulting firm to follow project as well as supervision.
    Boeker

***

#### Message Attributes

- **Document Number:** 1979LAPAZ05806

- **Date:** July 06, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** n/a
