---
title: "Gob Interest In Purchasing Tanks"
author: ""
date: "May 28, 1974"
editor: visual
cable-date: "May 28, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState Washd Priority 3217"
cable-info: "Oct-01 Iso-00 /031 W --------------------- 077132 P 282118z May 74"
cable-subject: "Gob Interest In Purchasing Tanks"
cable-tags: "MASS, BL"
cable-ref: "STATE 110568 AND PREVIOUS"
cable-doc-number: "1974LAPAZ03430"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "28 MAY 2004"
cable-concepts: "PROCUREMENT, MILITARY ASSISTANCE, MILITARY EQUIPMENT, DATA, TANKS (COMBAT VEHICLES), MILITARY SALES"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. CHARGE AND ACTING COMMANDER MILGP CALLED ON COMMANDING
GENERAL BOLIVIAN ARMY CARLOS ALCOREZA MAY 28 PURSUANT TO
REFTEL. ALCOREZA WAS INFORMED THAT (1) M-41 LIGHT TANK NOT
AVAILABLE FROM US SOURCES BUT THAT POSSIBLE THIRD
COUNTRY SOURCES OF THIS VEHICLE WILL BE INVESTIGATED;
(2) THAT M-551 ARMORED AIRBORNE RECONNAISSANCE VEHICLE UN-
AVAILABLE AT THIS TIME; AND (3) THAT THE US WAS PREPARED TO
OFFER AS AN ALTERNATIVE TO (1) AND (2) THE M-48.


2. ALCOREZA REPLIED THAT THE M-48 TANK SEEMED TO HIM TOO
HEAVY A TANK AND TOO HEAVILY ARMORED FOR BOLIVIA'S NEEDS.
HE ELABORATED ON THESE NEEDS AS BEING ESSESTIALLY OF AN IN-
TERNAL SECURITY NATURE AND BY NO MEANS DESIGNED TO PARTI-
CIPATE IN ANY WAR AGAINST ANY OF BOLIVIA'S NEIGHBORS, E.G.
CHILE AND PERU. NONETHELESS, HE WAS PREPARED TO RECONSIDER
AND ACCEPTED OUR OFFER TO PROVIDE PRICE AND AVAILABILITY
INFORMATION. HE WENT ON TO SAY THAT THE BOLIVIAN ARMY WITH-
IN A VERY SHORT TIME WOULD BEGIN A DEFINITIVE STAFF STUDY OF
  SECRET


  SECRET


 072347Z


TANKS AND ARMORED VEHICLES WHICH WOULD BE SUITED TO THE NEEDS




                             

                  

OF THE BOLIVIAN ARMY.


3. COMMENT: GIVEN THE CHARACTERISTICS OF THE M-48, IT
WOULD NOT APPEAR THAT THIS TANK CAN REALISTICALLY BE
CONSIDERED AS A VIABLE ALTERNATIVE TO THE SOVIET T-55
TANK, AT LEAST AS VIEWED BY GEN ALCOREZA ATTHIS TIME.
FOR THIS REASON, THE EMBASSY HOPES THAT THE DEPT CAN
PROVIDE US AT AN EARLY DATE INFORMATION AS TO NON-US
SOURCES FOR THE M-41 LIGHT TANK. IN ANY EVENT, WE MADE IT
CLEAR TO GEN ALCOREZA THAT WE WERE OFFERING THE M-48 AS A
FIRM ALTERNATIVE TO THE M-41 AND THE M-551.


4. ACTION REQUESTED: THAT THE DEPT SUPPLY THE EMBASSY
WITH PRICE AND AVAILABILITY INFORMATION FOR THE M-48 TANK.



 SECRET

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03430

- **Date:** May 28, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 28 MAY 2004

- **Concepts:** PROCUREMENT, MILITARY ASSISTANCE, MILITARY EQUIPMENT, DATA, TANKS (COMBAT VEHICLES), MILITARY SALES