---
title: "Welfare & Whereabouts - Congressional Interest"
author: "Stedman"
date: "May 08, 1974"
editor: visual
cable-date: "May 08, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 3030"
cable-info: "Oct-01 Iso-00 H-03 Sso-00 /004 W --------------------- 081544 O 082059z May 74"
cable-subject: "Welfare & Whereabouts - Congressional Interest"
cable-tags: "CASC"
cable-ref: ""
cable-doc-number: "1974LAPAZ02954"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. INFORM SENATOR ROBERT TAFT, JR THAT EMBASSY RECEIVED
HIS CABLE REQUEST FOR W/W REPORT RE MR. AND MRS.
MARSHALL KNOFF OF SANTA CRUZ, BOLIVIA. EMBASSY NOT
YET IN CONTACT WITH KNOFF AS THE ADDRESS GIVEN IN
SANTA CRUZ STATES THAT KNOFF DEPARTED SANTA CRUZ.
EMBASSY IS INFORMED BY BRANIFF THAT MR. KNOFF, WIFE,
AND A CHILD HAVE RESERVATIONS ON BRANIFF 984 WHICH
SCHEDULED ARRIVE MAIMI 0800 HOURS MAY 10. BRANIFF
UNDERSTANDS MR. KNOFF WILL BE TRAVELLING IN BODY CAST.


2. EMBASSY CONTINUING EFFORT TO CONTACT MR. OR MRS. KNOFF
DIRECTLY AND WILL REPORT WHEN SUCCESSFUL. EMBASSY WILL,
OF COURSE, BE HAPPY TRANSMIT ANY MESSAGE TO THE FAMILY.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02954

- **Date:** May 08, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a
