---
title: "Discussion With President Banzer"
author: "Stedman"
date: "January 10, 1974"
editor: visual
cable-date: "January 10, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 1910"
cable-info: "Oct-01 Iso-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-10 Pa-04 Rsc-01 Prs-01 Spc-03 Ss-20 Usia-15 Oic-04 Aid-20 Come-00 Eb-11 Frb-02 Trse-00 Xmb-07 Opic-12 Ciep-02 Lab-06 Sil-01 Omb-01 Eur-25 Nic-01 Snm-02 Agr-20 Scem-02 Sci-06 Drc-01 /221 W --------------------- 067687 R 102147z Jan 74"
cable-subject: "Discussion With President Banzer"
cable-tags: "OREP, PFOR, PINS, EAID, BL"
cable-ref: "LA PAZ 0179 SUMMARY: DURING COURTESY CALL BY CONGRESSMAN CHARLES WHALEN, JR., (R-OHIO) JANUARY 10, PRESIDENT BANZER EXPLAINED EXPULSION OF VICTOR PAZ AND DISUCSSED BOLIVIA'S ECONOMIC PROSPECTS, NARCOTICS AND U.S. ASSISTANCE PROGRAM. END SUMMARY."
cable-doc-number: "1974LAPAZ00206"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. President had clear idea of topics he wished to cover and did most of talking in one-half hour interview. He began by explaining that the days of Congressman's visit were unusual because Bolivia experiencing serious food shortages and political scene was agitated. He related shortages and long lines seen in city to world-wide food crisis. He gave lengthy explanation of political problem stating that after several years of instability Bolivians generally agreed on need for national unity. For that reason Government, including military and two major parties, formed in 1971 and he recently seeking to broaden political base even further by including smaller groups. While most of MNR agreed with this concept, unfortunately Victor Paz did not and sought merely to strengthen his party for 1975 elections. He and small group of associates thus had to be expelled.

2. President asserted that Bolivia's economic prospects are good. It has excellent resources in energy, minerals and agriculture and must take advantage of favorable world price situation, which he expects to continue for some years. President said he is confident that with help of contracts with U.S. oil companies, large hydro-carbon deposits will be found. He gave special emphasis to Bolivia's hydroelectric possibilities which he thought may allow it even to export electricity in future years. He reiterated that economic development requires stability and national unity.

3. President gave high praise to U.S. economic assistance rendered during his time in office. Both PADES and Emergency Plan have had beneficial social effects. He made special mention of community development assistance which has "changed mentality of campesinos." As example, he said that in contrast to past, campesinos now arrive with one-half funds in hand and only ask Government grant for other half. In future, Government considering loaning its half on very long terms to encourage this mentality.

4. Regarding U.S. military assistance, President recalled that he had been encouraged when Ambassador Siracusa had told him that program would be raised from approximate average annual level of US$ one million to US$ four million. U.S. and Bolivian personnel had then drawn up plan for expenditures. President said he is disappointed that plan is not repeat not progressing better. Lack of progress had caused Government to make costly expenditures on its own. New equipment, he explained, is necessary for military morale and for internal "persuasive force" that Bolivia is building up to discourage extremists. "When Communists see that the military force is strong," he said, "they remain outside country." Congressman Whalen replied indicating that some in U.S. Congress reluctant to appropriate funds for use for internal security forces, but he wished to study problem raised by President.

5. As final item, President called attention Bolivia's new narcotics law, a GOB's determination to fight problem. President said he does not like to see children of friend being hurt by product produced in Bolivia. He said that Bolivia would need assistance and asked Congressman's support. Speaking for himself, Mr. Whalen opined that Congress would not hesitate to help worthwhile efforts to stop drug traffic.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00206

- **Date:** January 10, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a