---
title: "Trade Opportunity: Agricultural Commodites"
author: "Stedman"
date: "March 08, 1974"
editor: visual
cable-date: "March 08, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "US Dept Of Agriculture WashDC Priority"
cable-info: "Oct-01 Ara-16 Iso-00 Drc-01 Rsc-01 /030 W --------------------- 037193"
cable-subject: "Trade Opportunity: Agricultural Commodites"
cable-tags: "BEXP, EAGR, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ01425"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "WHEAT, AGRICULTURAL COMMODITIES, TRADE OPPORTUNITY REPORTS, FLOUR"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Following discussion between Ambassador and Min Ind/Com in which Minister asked for Embassy help. Official of Min Ind/Com called on Econ Off to request help in obtaining price quotes and offers from U.S. suppliers on following items: 70,000 M.T. flour in sacks (FOB Gulf Port price), 15,000 M.T. wheat in bulk (FOB Gulf Port) 3.5 million liters refined edible vegetable oil in cans, barrels or drums, 1.5 million liters unrefined edible vegetable oil in barrels or drums, 1,000 M.T. of lard (preferably pork fat) in 20 kilo cans or nearest equivalent.
2. Min Ind/Com wants U.S. firms to telex or write Director De Abastecimientos, Ministerio De Industria y Comercio, La Paz, Bolivia. Telex number is 5434 MINDUFBX. Firms undoubtedly will also wish contact their refrs in Bolivia if any.
3. GOB has freed imports and prices of these products (except wheat and flour) for 90 day period which expected to be increased soon. GOB policy is clearly one of trying to assure increased supply of these products in shortest time possible.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01425

- **Date:** March 08, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** WHEAT, AGRICULTURAL COMMODITIES, TRADE OPPORTUNITY REPORTS, FLOUR