---
title: "(C) Economic Stabilization Measures By Gob Unlikely, But A Financial Crisis Should Be Avoidable"
author: ""
date: "February 17, 1979"
editor: visual
cable-date: "February 17, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 4842"
cable-info: "Oct-01 Iso-00 Sp-02 Ica-11 Aid-05 Eb-08 Nsc-05 Trse-00 Ss-15 Str-08 Omb-01 Cea-01 Ciae-00 Frb-03 Inr-10 Nsae-00 Xmb-02 Opic-03 Lab-04 Sil-01 Com-02 Agr-20 Io-14 Pa-01 Doe-15 Soe-02 /149 W ------------------092956 182358z /61 R 171233z Feb 79"
cable-subject: "(C) Economic Stabilization Measures By Gob Unlikely, But A Financial Crisis Should Be Avoidable"
cable-tags: "EGEN, EFIN, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ01469"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "FINANCIAL CRISIS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. (C Entire text).

2. **Summary:** The return of Planning Minister Gary Prado from the United States has not been followed by economic initiatives, and it seems virtually certain that the Padilla government will not take the economic measures that would result in a stand-by agreement with the IMF.

3. Finance Minister Alba has announced a so-called austerity budget for the central government (excluding the public enterprises, which account for the major part of the consolidated public sector budget, but whose budgets have not been negotiated yet). The new budget, following approval of the first supplemental appropriations in a Cabinet meeting of February 9, provides for a deficit 41 percent greater than that planned for 1978, and 87 percent greater than the actual 1978 deficit. Although Alba is taking a hard line on salary increases, it does not appear that there is political support for other measures demanded by the IMF, particularly fuel prices increases.

4. Lacking credits from the IMF, the Bolivian government must obtain loans from other sources to cover its balance of payments deficit. In addition, it will presumably attempt to renegotiate a portion of the debt that falls due during 1979. While financing may be expensive, we believe that sufficient credits can be obtained to avoid a financial crisis before August. End summary.

5. Planning Minister Gary Prado's visit to the United States does not appear to have generated additional support within the Padilla government for economic measures. It is highly unlikely that stabilization measures which would facilitate an agreement with the International Monetary Fund will be introduced before the July elections. Although the Minister of Finance has announced an austerity budget, information we have obtained from government sources indicates that the budget may not be quite so tough as its publicity suggests. We do not have a breakdown of the budget, which does not include the public corporations, but the following table summarizes 1978 projected and actual results, and compares them with projections for 1979 adjusted to reflect supplementary expenditures approved by the Cabinet February 9.

         BUDGETED        ACTUAL      BUDGETED
         1978       1978      1979
INCOME        9,288      8,454.7   10,549.4
EXPENSES       11,656.1     10,248.1        13,896.1
SURPLUS
(DEFICIT)    (2,368.1)    (1,793.4)    (3,346.7)

Notes:
1. All figures in millions of Bolivians pesos. Exchange rate is 20 pesos to US$ 1.
2. Following the approval of 700 million pesos in additional expenditures at the Cabinet meeting of February 9, the internal GOB document from which we obtained these figures contains a comment to the effect that it will be impossible in 1979 to reduce the consolidated public sector deficit below 12 percent of Gross Domestic Product. This statement indicates that another large balance of payments deficit should be expected in 1979 (a preliminary Ministry of Finance estimate puts the 1979 balance of payments deficit at $184 million), and that large amounts of financing and refinancing will be necessary this year.

6. Financial officials have recently been jolted by the withdrawal of $21 million credit offer received from a German bank in late 1978 (believed to be the Westdeutsche Landisches Bank). GOB authorities had signed a promissory note for the loan, but had not formalized an agreement. On the basis of the note, a bridge credit was obtained, with the understanding that a formal loan agreement would be signed early in 1979. The German bank has now retracted its offer, apparently because of concern about the Bolivian economic situation, and the GOB must now repay or roll over the $21 million short-term bridge credit.

7. Despite the failure of this particular transaction, the Padilla government should be able to obtain the funds that it requires to keep the economy afloat until August 1979. We have learned from usually reliable sources that COMIBOL is currently considering a series of major general purpose loan offers, including one of $100 million for short-term (180 day) working capital, and three others of $90, $60 and $80 million at longer (5-8 year) terms. American Express and Librabank, in which Chase Manhattan has a financial interest, are known to be among the banks offering these credits. It is doubtful that all of these transactions could be realized, but in view of the fact that COMIBOL credit requirements are thought to be less than $140 million, a combination might be worked out that would allow some of the funds to be used for balance of payments support. We have also learned that the Central Bank has received an offer of $70 million from Wells Fargo Bank.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ01469

- **Date:** February 17, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** FINANCIAL CRISIS
