---
title: "1979 Bolivia Human Rights Report"
author: ""
date: "December 26, 1979"
editor: visual
cable-date: "December 26, 1979"
cable-from: "SecState WashDC"
cable-to: "AmEmbassy La Paz"
cable-info: "Oct-00 Ads-00 Ha-05 /020 R"
cable-subject: "1979 Bolivia Human Rights Report"
cable-tags: "SHUM, BL"
cable-ref: ""
cable-doc-number: "1979STATE331361"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "HUMAN RIGHTS, REPORTS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

Bolivia's past political instability has been an impediment to economic and social progress and, therefore, at least partially responsible for the country's uneven record in terms of human rights observance. In 1977 then President Banzer initiated a liberalization of virtually all major restrictions on human rights, releasing all reported political prisoners, allowing exiles to return, and scheduling elections for July 1978. This positive human rights momentum was not checked by the Pereda coup (August 1978) or the Padilla takeover (November 1978). While the first represented a brief interruption in the democratization process and the second was designed to put it back on track, both governments contributed to the improving human rights situation: General Pereda by abrogating the feared State Security Law, and General Padilla by overseeing in July 1979, possibly the most democratic elections in Bolivia's history.

As none of the eight presidential hopefuls achieved the needed [majority] of the popular vote in the July 1979 elections, the issue went before the Congress where, similarly, none of the three leading candidates succeeded in obtaining [majority]. Finally, the Congress selected Senate President Walter Guevara Arze to serve as interim president with new elections scheduled for May 1980.

Guevara's interim government came to an abrupt end November 1, 1979, when a group of military officers and civilians under the leadership of Army Colonel Alberto Natusch Busch seized the government. The Natusch government responded to strong popular reaction against the coup and its interruption of the democratic process with the implementation of press censorship, a state of siege, and martial law. Protesting but unarmed civilians were confronted by undisciplined soldiers resulting in the death of approximately 200 persons, the wounding of some 200 others, and the unaccounted for disappearance of about 125 citizens, many of whom are now presumed dead. Popular discontent, a seven-day strike by the Confederation of Bolivian Workers (COB), and Natusch's repressive measures hastened the demise of his regime.

After Natusch's resignation on November 16, an agreement was reached between the Congress, the COB, and the armed forces appointing Chamber of Deputies President Lidia Gueiler as interim president. President Guevara, who had become a resistance symbol in hiding during the Natusch regime, returned to his former Senate position. Ms. Gueiler is to be Bolivia's interim president until the inauguration on August 6, 1980 of the winner of the 1980 elections, which will probably be held in June.

1.  **Respect for the Integrity of the Person, Including Freedom From:**

    A. **Torture**

    The Bolivian constitution prohibits torture and other forms of cruel, inhuman, or degrading treatment. The Padilla and Guevara administrations apparently respected this constitutional guarantee; there were no reports of torture during their brief governments -- nor during the first weeks of President Gueiler's administration. Allegations of torture during the short-lived Natusch regime remain unsubstantiated, but are currently being investigated by the Permanent Assembly on Human Rights (PAHR), Bolivia's principal non-governmental organization promoting respect for human rights.

    The Bolivian Congress also requested the PAHR on November 19 to document all cases of persons killed, wounded, or missing as a result of Natusch's repressive measures. The findings are expected to be made public.

    B. **Cruel, Inhuman or Degrading Treatment or Punishment**

    No reports of cruel, inhuman, or degrading treatment were received during the Padilla or Guevara governments nor during the first weeks of the Gueiler government. There are unsubstantiated allegations of beatings of political and labor leaders detained during the Natusch regime.

    Although the Bolivian constitution prohibits cruel, inhuman or degrading treatment or punishment in all circumstances, PAHR representatives indicate that infractions occur. According to the PAHR, policemen sometimes beat persons accused of common crimes during interrogation to force confessions. Most such detainees do not file complaints, however, presumably either because they are unaware of their civil rights or because they fear reprisals. The PAHR believes that only a few police officials engage in such practices, and it is attempting to document cases of mistreatment so that offending policemen can be punished.

    Most prisons in Bolivia are old and overcrowded. Sanitary conditions are poor, and prisoners' diet is inadequate. These conditions result in part from Bolivia's low level of economic development and associated poverty. Many prisoners, however, receive supplementary money, food, clothing and medicines from relatives or friends. Others manufacture smalls for outside contractors in exchange for money or food to supplement prison fare. Prisoners have no opportunity to become rehabilitated through learning job skills or improving their education while in prison. Prison officials recognize the problems in the present system, but indicate that lack of adequate funding precludes early improvement.

    C. **Arbitrary Arrest or Imprisonment**

    The Padilla, Guevara, and Gueiler governments have not imprisoned persons for their political beliefs or activity. During the Natusch coup before press censorship was imposed, newspapers and the radio reported the arrest of several labor leaders and politicians in various parts of the country. These people were held only briefly. Additional reports of similar short-term detentions appeared in the press after censorship was lifted. There have also been reports that as many as 125 people disappeared during this two-week period, the majority of whom are unaccounted for. There were no known political prisoners in Bolivia at the end of November, 1979.

    Persons are frequently arrested and held for brief periods without charge in Bolivia. Occasionally, especially in serious criminal cases, a suspect is held longer than the 24 hours stipulated in the constitution before being brought before a judge. This is probably due more to procedural delays than any attempt by the police to deny justice. Habeas corpus exists and is respected in practice.

    D. **Denial of Fair Public Trial**

    Persons arrested in Bolivia are entitled by law to a fair public trial. However, the judicial process moves slowly, with some criminal cases taking years to complete because of inherent faults in the judicial system -- antiquated procedures, shortage of qualified personnel, etc. Defendants may hire their own counsel, and may confer with them in private. Civil courts are independent of the military and civilians are not tried in military courts.

    E. **Invasion of the Home**

    The sanctity of the home is constitutionally protected. There were no reports of invasions of the home during either the Padilla or Guevara governments nor were there during the first weeks of the Gueiler government. During the Natusch coup, however, illegal searches were made of the houses of some persons opposed to his takeover -- mainly labor leaders and politicians -- for weapons and for members of the Guevara "government in hiding".

2.  **Governmental Policies Relating to the Fulfillment of Such Vital Needs as Food, Shelter, Health Care and Education:**

    Bolivia remains an underdeveloped country. Nevertheless, despite recurring serious macroeconomic problems, the government of Bolivia has succeeded in significantly improving the quality of life for the majority of its citizens. Since 1975, successive governments implemented a five-year Economic and Social Development Plan emphasizing a rapid growth, export-oriented strategy. The Plan's original goals included improving national income distribution (an OAS study indicates that 5 percent of the Bolivian population controls 31 percent of the national income), incorporating the rural (mostly Indian) population into the modern life of the country, and improving overall welfare through education, health, and agricultural programs. While Bolivia's worsening economic situation prevented the fulfillment of major elements of the plan, World Bank figures showed that by 1979 per capita GNP had reached $630 in 1977 dollars, up from $352 in 1960. The Gueiler government in its first weeks implemented an economic stabilization program, which, if well carried out, can provide the basis for resuming soundly-based long-term economic growth.

    Average life expectancy is 52 years. The nationwide annual death rate is estimated at 18.5 per thousand and the infant mortality rate for children under one year of age in rural areas is 235 per thousand. These figures are partially the results of communicable, respiratory, and gastrointestinal diseases and malnutrition among the population. The health problems persist largely because of inadequate financing and direction to improve the quality and distribution of health services. Of the rural population, 11.2 percent lives in areas which have adequate sewage disposal; 12 percent have access to potable water.

    An estimated 40 percent of the Bolivian population over the age of 15 is illiterate. In an effort to overcome this problem the government provides a free public education system through the university level. Unfortunately, rural poverty forces many children to neglect their studies in favor of working to help support their families. Also, school sessions are often interrupted by labor strife or political activity.

    The lack of adequate housing is a serious problem. The majority of housing units in the major cities are substandard. Rural families typically live in adobe dwellings without basic sanitary facilities. The poor environmental conditions accompanying such housing exacerbate problems of sanitation, nutrition and other impediments to health.

    Government programs to fulfill basic human needs are hampered primarily by the lack of financial, human, and material resources. Although there have been occasional reports of corruption in the administration of some of these programs, it does not appear that corruption has been a major factor impeding their effective implementation.

3.  **Respect for Civil and Political Liberties, Including:**

    A. **Freedom of Speech, Press, Religion and Assembly**

    Under the Padilla and Guevara governments, there were no reports of violations of any of these freedoms which are constitutionally guaranteed. Soon after assuming power, Colonel Natusch, however, imposed press censorship, a state of siege, curfew, and martial law. After a crippling seven-day general strike called by the COB, Natusch agreed to lift these measures in exchange for an end to the strike. The National Press Association (ANP), and the Vice President of the Bolivian Ecumenical Conference, among others, protested the press censorship and the silencing of several radio stations during the two-week military takeover. Before the Natusch coup, the press in Bolivia exercised a degree of "self-censorship", ostensibly to avoid political controversy that could jeopardize the democratization process.

    Freedom of speech, the press, and assembly were restored by the Gueiler government. There are no restrictions on religious freedom.

    B. **Freedom of Movement Within the Country, Foreign Travel and Emigration**

    Freedom of movement, travel, and emigration is constitutionally protected although as a vestige of the MNR days of the 1950s Bolivians outside the country must apply at a Bolivian consulate for a visa to enter their own country. Only under the two-week Natusch regime were there any new restrictions on travel and these were eliminated when President Gueiler took office.

    C. **Freedom to Participate in the Political Process**

    Political parties and labor unions have been able to operate freely since early 1978. In July 1979, eight political parties or coalitions participated in the general elections; none was the official party. Despite some allegations of electoral fraud by the contending parties and coalitions, it is generally accepted that the Electoral Court did its job well and that actual fraud in these elections was minor. All citizens 21 years of age and older may vote.

    Traditionally, women have not enjoyed equal opportunity in Bolivia. However, this is changing. For example, before becoming interim president, Lidia Gueiler had been elected President of the Chamber of Deputies and awarded the Order of the Condor, Bolivia's highest decoration, for her political activities. Two women presently serve in the Congress, and two in the cabinet. Indian women in both rural and urban areas continue to play a major role in the commercial sector and contribute substantially to family incomes.

    Labor unions exercise considerable power in Bolivian society, as evidenced by the general strike in early November, 1979 which contributed to the demise of the Natusch regime. Trade unions profess to maintain neutrality among political parties. Individual union members, however, often actively participate in partisan political activities.

4.  **Government Attitude and Record Regarding International and Non-Governmental Investigation of Alleged Violations of Human Rights:**

    The Permanent Assembly on Human Rights (PAHR) is Bolivia's principal non-governmental organization promoting respect for human rights. It maintains close contact with other international human rights organizations, whose members often travel to Bolivia for consultations on the state of human rights. The PAHR is working for the ratification of UN human rights agreements to which Bolivia is not yet a party.

    Bolivia is the only Latin American country whose parliament has a human rights committee in each house. As part of its effort to improve human rights observance, Bolivia became a party to the American Convention on Human Rights in 1979.

***

#### Message Attributes

- **Document Number:** 1979STATE331361

- **Date:** December 26, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** HUMAN RIGHTS, REPORTS