---
title: "Guevara Bids To Extend His Term, Amid An Atmosphere Of Military-Civilian Confrontation"
author: ""
date: "October 05, 1979"
editor: visual
cable-date: "October 05, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 8493"
cable-info: "Oct-01 Ads-00 Sso-00 /026 W ------------------028467 052238z /73"
cable-subject: "Guevara Bids To Extend His Term, Amid An Atmosphere Of Military-Civilian Confrontation"
cable-tags: "PINT, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ08491"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "20 Mar 2014"
cable-concepts: "PRESIDENT, POLICIES, POLITICAL STABILITY, POLITICAL MILITARY RELATIONS, PRESIDENTIAL SUCCESSION, ELECTIONS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


2. **Summary:** President Guevara told me October 4 that he had on the previous evening asked Hernan Siles and Victor Paz to support the extension of Guevara's term in office to mid-1981, when general elections would be held. Guevara told them that in his view Paz' and Siles' choice was elections in '81 or a return to military government, since a call for May 1980 elections would maintain the current political climate at a confrontational pitch which would provoke a military coup before elections. Guevara claimed that with Paz' and Siles' support for a two-year term, special economic powers and reduction of the charges against Banzer, Guevara could assuage the military, stabilize the economy and hand over a working civilian democracy to someone else in 1981. Without this support, he feared the worse. Neither Paz nor Siles has given Guevara a response. The fat is now in the fire and Guevara's government, and maybe civilian rule, are headed for a showdown by early November on a complex set of questions – the two-year Guevara term, economic stabilization and changes in the military high command. End Summary.

3. In an October 4 meeting with me, President Guevara said he was deeply worried by the deterioration of the political climate that he found on his return from Panama. The military – with good reason – felt threatened by the looming indictment of General Banzer and associates. The Congress was handling this badly and everything else not at all. The military, Congress and labor were exchanging charges and threats at a pitch which Bolivia's fragile democracy could not long survive. General Padilla was losing his authority within the military and hotter heads now sensed an opportunity to hatch their own political plans, including some to close down the Congress. In the course of our 90-minute meeting, Guevara elaborated on each of these points of concern.

4. Both the military and the Congress, Guevara said, were at fault in the current confrontation over the likely indictment of Hugo Banzer. The military had a shabby record of corrupt administration and should have anticipated that no representative government could protect them from an airing of this record. Also, the military had to recognize that the General Staff's views on what was desirable for Bolivia were now not the last word but one of several voices in a complex process of accommodation. The Congress, on the other hand, was a "mediocre lot" which had let Marcelo Quiroga Santa Cruz and his tiny party dominate the agenda and the tone of the Congress and to use this position to goad the military in a way which would weaken the moderate elements as well as imperil civilian government. The two major coalitions, the MNR Alliance and the UDP, should never have allowed consideration of an indictment of the undefined group of "Banzer and his associates" since a large group of officers could see themselves as potential associates in seven years of military government. Guevara said Paz and Siles in their meeting with him on October 3 had agreed to seek an indictment resolution (to emerge from committee at the end of October) which would charge only Banzer and a few named associates with specific offenses, particularly corruption, but the damage of arousing the whole officer corps had already been done.

5. Guevara was distressed that the exchange of threats between the Congress and the military over the Banzer indictment had now been augmented by an exchange of accusing communiques between the military and the Labor Union Federation (COB) over the military budget. Before Guevara left for Panama, Padilla had promised that no more communiques would be issued by the military without coordination with Guevara.

6. To Guevara, the fact that Padilla felt compelled to issue the attack on the COB was one of several indications that Padilla was losing his grip on the military. In his recent consultations with unit commanders, Padilla was apparently playing with the idea of military intervention to keep himself at the front of the pack. Guevara feared that if Padilla could not control the military some hothead would try a coup against the Congress, Guevara or both. The COB would respond with a general strike and civilians and the military would be in a confrontation without a peaceful solution.

7. Guevara believed that several groups within the military were cooking political plots and if anyone could bring them together on one strategy, there could be a coup. He felt that Army Chief of Staff Julio Herrera was the one hothead who had the will and position to bring the malcontents together. Therefore, he had to move to replace Herrera. Guevara said he had to change his cabinet soon in any event, to replace at least ineffective ministers of mines and health. He wanted to use this occasion to kick Herrera upstairs to the Minister of Defense position and to replace him with General Jorge Terrazas, commander of the Seventh Division in Cochabamba. (Terrazas would then move up to Army Commander position when General Azero retires in December.) Guevara said he also planned to replace the commander of the Military Police Battalion, Captain Luis Montero, who insists on being Guevara's watchdog. Guevara said he would present these changes to Padilla this weekend.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ08491

- **Date:** October 05, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 20 Mar 2014

- **Concepts:** PRESIDENT, POLICIES, POLITICAL STABILITY, POLITICAL MILITARY RELATIONS, PRESIDENTIAL SUCCESSION, ELECTIONS
