---
title: "Short Range Development Plans And Gas Reserves"
author: "Brewin"
date: "May 31, 1974"
editor: visual
cable-date: "May 31, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3268"
cable-info: "Oct-01 Iso-00 Aec-11 Aid-20 Cea-02 Ciae-00 Ciep-02 Come-00 Dode-00 Eb-11 Fea-02 Fpc-01 H-03 Inr-10 Int-08 L-03 Nsae-00 Nsc-07 Omb-01 Pm-07 Rsc-01 Sam-01 Sci-06 Sp-03 Ss-20 Str-08 Trse-00 Drc-01 /149 W --------------------- 108464 R 312107z May 74"
cable-subject: "Short Range Development Plans And Gas Reserves"
cable-tags: "ENRG, BL"
cable-ref: "A-110 OF MAY 31, 1974"
cable-doc-number: "1974LAPAZ03545"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "GAS RESERVES, PROPOSALS (BID), CONTRACTS, EXPLORATORY DRILLING, OIL FIELDS, PETROLEUM CONCESSIONS,"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. CARLOS MIRANDA, DIRECTOR DIRECCION NACIONAL DE PETROLEOS,
MINISTRY ENERGY AND HYDROCARBONS, DURING LUNCHEON ON MAY 31, TOLD
EMBOFFS YPFB EXPECTING TO CONTRACT TECHNICAL PETROLEUM-GAS FIRM TO
VERIFY NATURAL GAS RESERVES. INDICATED FIRM TO BE FROM THIRD
COUNTRY AND POSSIBLY AMERICAN. SAID YPFB ALSO EXPECTED TO RECEIVE
BIDS FOR SERVICE CONTRACT TO DRILL EXPLORATION WELLS IN YPFB'S
TERRITORIAL CONCESSIONS, BUT THAT PETROBRAS NOT INCLUDED IN GROUP
OF POSSIBLE CONTRACTORS WHO WOULD OBTAIN CONTRACTS. STATED IN
U.S. EXPLORATION DRILLING HAS INCREASED TREMENDOUSLY CAUSING SEVERE
SHORTAGE OF DRILLING RIGS. HE CONFIDENT YPFB MAY OBTAIN SERVICE
CONTRACT SOON INSPITE OF SHORTAGE WITH HELP OF COMPANIES NOW IN
BOLIVIA.


2. ADDED FERTILIZER PLANT MAY BE LOCATED IN CITY OF SANTA CRUZ
TO SUPPLY NOT ONLY BRAZILIAN MARKET BUT ALSO ARGENTINE MARKET IF






 312147Z


REQUIRED. (COMMENT: IF LATTER IS CASE, THEN FERTILIZER PLANT




                     

                  

COULD BE PLANNED AND BUILT EVEN BEFORE GAS PIPELINE TO BRAZIL.
BRAZIL NOT LIKELY TO BUY FERTILIZER UNTIL IT RECEIVES BOLIVIAN
NATURAL GAS, BUT ARGENTINE MARKET POSSIBLY COULD BE AVAILABLE
BEFORE THEN, DEPENDING ON ARGENTINE POLICY.)
BREWIN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03545

- **Date:** May 31, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** GAS RESERVES, PROPOSALS (BID), CONTRACTS, EXPLORATORY DRILLING, OIL FIELDS, PETROLEUM CONCESSIONS,