---
title: "(U) Bolivia Commemorates Centennial Of War Of The Pacific"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "March 28, 1979"
editor: visual
cable-date: "March 28, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 5432"
cable-info: "Oct-01 Iso-00 Ciae-00 Dode-00 Pm-05 H-01 Inr-10 L-03 Nsae-00 Nsc-05 Pa-01 Sp-02 Ss-15 Ica-11 /069 W ------------------128362 300006z /75 R 281342z Mar 79"
cable-subject: "(U) Bolivia Commemorates Centennial Of War Of The Pacific"
cable-tags: "POINT, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ02637"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "WAR, COMMEMORATIVE CELEBRATIONS, ACCESS TO PORTS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. On March 23, 1979, Bolivia celebrated "Sea Day", the 100th anniversary of the Battle of Topater, in which Bolivia's national hero, Eduardo Avaroa, lost his life, with parades and speeches in all the major cities throughout the country.

2. The theme of the day was that Bolivia would never abandon its right and determination to regain its Pacific seacoast, lost in the War of the Pacific 100 years ago. In La Paz the parade, described by the press as Bolivia's longest and largest parade ever, lasted ten hours. Marchers carried Bolivian flags with a blue banner symbolic of Bolivia's lost seacoast.

3. In his speech President Padilla castigated Chile for a "spirit of conquest" which still exists and accused Bolivia's neighbor of "bad faith, arrogance, incomprehension, and intransigence" in recent negotiations. Consequently, he said Bolivia broke relations with Chile and "only when the very difficult conditions which they have tried to impose on us have disappeared, when the unchanging Chilean intransigence had gone, can we renew the dialogue." Padilla lauded the heroes of Topater and called on Bolivians never to renounce their right to access to the sea. He described the sea outlet question as the greatest threat to the peace in the Americas. Nevertheless, "the Bolivian people are not animated by any feeling of hatred or resignation. Therefore, its love of peace should not be confused with fear or blind acceptance of injustice."

4. Padilla reiterated the commitment of the armed forces to return Bolivia to constitutional government and called for all Bolivians to be united and to fulfill their responsibilities.

5. An Argentine military delegation led by Vice Admiral Vanek participated in the ceremonies and a group of Argentine Air Force Canberra aircraft overflew La Paz to demonstrate support for Bolivia's sea outlet claim.

6. **Comment:** Bolivia's commemoration of the centennial of the Battle of Topater came off smoothly and without incident and provided another opportunity for the country to underscore its determination to negotiate a solution to the sea outlet problem. The tone of Padilla's speech and the themes of the placards carried in the parades were all consistent with Bolivia's oft-repeated statement that while it is determined to regain access to the Pacific it is also determined to do this via peaceful negotiations. The massive participation of the La Paz population in the March 23 commemoration was an impressive demonstration that (a) no cause incites and unites Bolivians like the sea-access issue and (b) this cause will not recede in Bolivian diplomacy, regardless of passage of time.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ02637

- **Date:** March 28, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** WAR, COMMEMORATIVE CELEBRATIONS, ACCESS TO PORTS
