---
title: "Inaugural: Mrs. Carter's Visit"
author: ""
date: "August 02, 1979"
editor: visual
cable-date: "August 02, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 7573"
cable-info: "Oct-01 Ara-15 Ads-00 Opr-02 Ss-15 Sso-00 Sy-05 Sye-00 Usss-00 Oc-06 Cco-00 Cpr-02 Pa-02 Nsce-00 /050 W ------------------079000 022210z /62 O 022113z Aug 79"
cable-subject: "Inaugural: Mrs. Carter's Visit"
cable-tags: "PDIP, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ06634"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "INAUGURATION, VISITS, PRESS RELEASES"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


Following is press movements only to be coordinated with staff schedule.

Press note: Bolivian time is the same as EDT.

**Saturday, August 4, 1979**

5:30 P.M. Mrs. Carter arrives.

6:10 P.M. Press proceed to press vehicles and depart en route Sheraton-La Paz Hotel.

6:30 P.M. Press arrive Sheraton-La Paz Hotel.
Press note 1:
1.  Filing center located in Salon Versailles: Five LDS, four Telex, TV monitors.
2.  Keys available in filing center.

**Sunday, August 5, 1979**

3:10 P.M. Pool no. 1 assembles in filing center, board press vehicle, and depart en route Government Palace.

3:20 P.M. Pool no. 1 arrives Government Palace and proceeds inside for coverage of presentation of credentials.

Press note: Press must remain for presentation of credentials by all delegations.

4:00 P.M. Press board press vehicles and depart Sheraton en route Ambassador's Residence.

4:10 P.M. Press arrive Ambassador's Residence and proceed side to press area.

4:15 P.M. Mrs. Carter presents credentials.
Pool no. 1 coverage.

4:25 P.M. Mrs. Carter departs Government Palace en route Ambassador's Residence.
Press pool no. 1 follows.

4:35 P.M. Mrs. Carter arrives residence to greet embassy personnel.
Open press coverage.
Facilities: One MULT.

5:00 P.M. Mrs. Carter departs garden to private room in residence.

5:10 P.M. Press depart Ambassador's Residence en route La Paz filing center.

5:20 P.M. Press arrive Sheraton-La Paz filing center.

**Monday, August 6, 1979**

8:30 A.M. Press board vehicles and depart Sheraton en route Legislative Palace.
Press note: The inauguration ceremony lasts three hours. It is televised in the filing center.

8:40 P.M. Press arrive Legislative Palace. Photographers escorted to floor boxes (one pool TV camera); writers escorted to third floor balcony reviewing area.
Press note: No MULT hook-up. No translation available in Legislative Palace.

9:40 A.M. Mrs. Carter arrives; proceeds to presidential box.

10:00 A.M. Inauguration ceremonies begin.

1:00 P.M. Inauguration ceremonies conclude.
Mrs. Carter departs Legislative Palace en route Sheraton.

1:20 P.M. Press departs Legislative Palace en route Sheraton.

1:30 P.M. Press arrive.

5:15 P.M. Pool no. 2 departs Sheraton en route Government Palace.

5:25 P.M. Pool no. 2 arrives; proceeds to room for coverage of greetings to new president.
Press note: Press must remain for all delegations' greeting to new Bolivian president.

6:45 P.M. Mrs. Carter greets new Bolivian president and presents members of US delegation.
Pool no. 2 coverage.

6:55 P.M. Mrs. Carter departs Government Palace.

7:30 P.M. Press pool no. 2 departs Government Palace en route Sheraton filing center.

7:40 P.M. Pool no. 2 arrives Sheraton filing center.

8:30 P.M. Press pool no. 3 departs Sheraton en route Government Palace for coverage of reception.

8:40 P.M. Pool no. 3 arrives Palace; proceeds to press area.

9:40 P.M. Mrs. Carter arrives Government Palace for inaugural reception.
Note: The newly elected president will arrive at 10:00 P.M.

10:20 P.M. Pool no. 3 departs Government Palace en route Sheraton filing center.

10:30 P.M. Pool no. 3 arrives.

11:25 P.M. Mrs. Carter departs Government Palace en route Sheraton.

**Tuesday, August 7, 1979**

Baggage call: All bags must be placed outside your rooms in an unlocked condition no later than 7:00 A.M.

8:30 A.M. Press vehicles depart La Paz Sheraton en route El Alto Airport.

8:55 A.M. Press arrive airport; proceed to press area.

9:45 A.M. Mrs. Carter arrives El Alto International Airport and proceeds to board aircraft.

9:55 A.M. Mrs. Carter departs La Paz, Bolivia.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ06634

- **Date:** August 02, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** INAUGURATION, VISITS, PRESS RELEASES
