---
title: "Visit Of Bolivian Businessman"
author: "Stedman"
date: "March 06, 1974"
editor: visual
cable-date: "March 06, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "Usdoc WashDC"
cable-info: "Oct-01 Iso-00 Eb-05 Drc-01 Rsc-01 /018 W --------------------- 007819 R 061401z Mar 74"
cable-subject: "Visit Of Bolivian Businessman"
cable-tags: "BTRA, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ01353"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. Mr. Jorge Lonsdale, President, National Distillers, La Paz, Bolivia, is interested in acquiring technical know-how and production equipment for the manufacture of "baby food".
2. Will visit New York City from 17 to 24 March and is interested in contacting firms producing "baby food".
3. Subject was not knowledgeable in the business services of the USDOC. Thus, upon his return from New York City, a request will be submitted for publication in Commerce Today.
4. **Action Requested:** Subject has been invited to visit the New York City District Office of USDOC to obtain appointments with interested U.S. firms. Please notify the District Office of this request.
Stedman

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01353

- **Date:** March 06, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a
