---
title: "Availability Of Fy 1975 Fms Credit Funds"
author: "Stedman"
date: "July 23, 1974"
editor: visual
cable-date: "July 23, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3729"
cable-info: "Oct-01 Iso-00 H-03 Iga-02 Pm-07 Nsc-07 Sp-03 Ss-20 Rsc-01 Ciae-00 Inr-11 Nsae-00 L-03 Mc-02 Eb-11 Trse-00 Omb-01 Aid-20 Drc-01 /113 W --------------------- 095883 R 232025z Jul 74"
cable-subject: "Availability Of Fy 1975 Fms Credit Funds"
cable-tags: "MASS BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ04746"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "MILITARY ASSISTANCE, FOREIGN RELATIONS, MILITARY SALES, MILITARY CREDIT"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. I WOULD APPRECIATE IT IF A SMALL FMS CREDIT IN THE RANGE
OF 2-1/2 TO 4 MILLION DOLLARS COULD BE APPROVED NOW UNDER THE
CONTINUING RESOLUTION AUTHORITY FOR BOLIVIA. I UNDERSTAND
THE IMPORTANCE OF OUR MULTI-YEAR COMMITMENTS FOR LARGER
PROGRAMS INCLUDING SOPHISTICATED EQUIPMENT, BUT WOULD LIKE
TO UNDERLINE CERTAIN SIGNIFICANT US INTERESTS HERE THAT
CAN BE SERVED WELL BY THE EARLY APPROVAL OF A SMALL FY 1975
FMS CREDIT.


2. BOLIVIA'S INTEREST IN TANKS HAS RESULTED IN OFFERS FROM
UNDESIRABLE SUPPLYING COUNTRIES WHICH WE MAY BE ABLE TO
PRE-EMPT BY SUPPLYING PROMPTLY
INFORMATION ON A SUTIABLE ALTERNATIVE SUCH AS THE V-150
CADILLAC-GAGE ASSAULT CAR AND ALSO AN OFFER OF FMS CREDIT
FOR THE BOLIVIAN ARMY. I UNDERSTAND THAT A REPRESENTATIVE
OF CADILLAC-GAGE MAY VISIT LA PAZ IN LATE AUGUST AND WOULD
OBVIOUSLY WISH TO DISCUSS THE V-150 ASSAULT CAR WITH THE
BOLIVIAN MILITARY. IT WOULD BE AN EFFECTIVE STEP IF WE






 232214Z


WERE ABLE TO SUPPORT ANY INTEREST AROUSED WITH AN FMS CREDIT.




                        

                  


3. WE ARE NOW SUCCESSFULLY PURSUING A LONG-RANGE STRATEGY
OF PROGRAMMING A PHASE-DOWN IN MAP GRANTS FOR MATERIEL
WITH THE EXPECTATION OF A COMPENSATORY INCREASE IN FMS CREDITS.
TO CONTINUE THIS SUCCESSFUL STRATEGY, WE SHOULD HAVE
AT HAND FMS CREDITS FOR FY 75. THE $4 MILLION FY 74 FMS
CREDIT MADE AVAILABLE TOWARD THE END OT THE FISCAL YEAR
HAS BEEN ALLOCATED BY THE GOB TO THE BOLIVIAN AIR FORCE.
THE FAB (BAF) IS MAKING ACTIVE EFFORTS TO USE ITS CREDITS
IMMEDIATELY. THE BOLIVIAN AUTHORITIES HAVE TOLD ME AND
THE MILGP THAT SUBSEQUENT FMS CREDITS ARE TO BE ALLOCATED
TO THE BOLIVIAN ARMY. THUS A MODEST CREDIT FOR FY 75
FROM 2-1/2 TO 4 MILLION DOLLARS WOULD SUSTAIN THE PRESENT
STRATEGY FOR MILITARY ASSISTANCE IN BOLIVIA.


4. I FEAR THAT AN ASSOCIATED PRESS WIRE SERVICE STORY FROM
LIMA CARRIED IN THE BOLIVIAN PRESS CONCERNING A US OFFER
OF $20 MILLION MILITARY CREDIT TO PERU DURING THE VISIT
TO LIMA OF ARMY SECRETARY CALLOWAY WILL NOT HAVE ESCAPED
THE ATTENTION OF THE BOLIVIAN MILITARY. I CAN WELL UNDERSTAND
THAT THE ANNOUNCEMENT MAY NOT BE TRUE, BUT IT WILL COMPLICATE
ANY EFFORT TO CONVINCE THE BOLIVIANS THAT THEIR NEIGHBORS
HAVE NOT RECEIVED FY 75 FMS CREDIT OFFERS.


5. IN VIEW OF THE FOREGOING, I EARNESTLY REQUEST A SMALL
FMS CREDIT ALLOCATION UNDER CRA TO BE USED NOW IN BOLIVIA.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04746

- **Date:** July 23, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** MILITARY ASSISTANCE, FOREIGN RELATIONS, MILITARY SALES, MILITARY CREDIT
