---
title: ""Fsi: Commercial Locals Us Training Program" Highly Recommend: Name: Jaime M. Bilbao Born: La Paz, Bolivia, January 23, 1945 Fluency In English: Mr Bilbao Is Completely Bilingual Service: Joined Embassy October 1970 Education: 1. Business Administration Certificate, Centro Superior De Ensenanza Length Of Course: Two Years 2. Architecture, University Of San Andres Length Of Course: Three Years 3. Correspondence Course For Commercial Specialists, Usdoc. Length Of Course: One Year 4. Correspondence Course, Part I & Part Ii, Writing For Government & Business, Us Department Of Agriculture Length Of Course: Two Years 5. International Trade Seminar, Organization Of American States. Length Of Course: Two Weeks Experience:"
author: "Parker"
date: "August 29, 1974"
editor: visual
cable-date: "August 29, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 4069"
cable-info: "Oct-01 Ara-16 Iso-00 Eb-11 Come-00 Per-05 /034 W --------------------- 099792 R 291830z Aug 74"
cable-subject: ""Fsi: Commercial Locals Us Training Program" Highly Recommend: Name: Jaime M. Bilbao Born: La Paz, Bolivia, January 23, 1945 Fluency In English: Mr Bilbao Is Completely Bilingual Service: Joined Embassy October 1970 Education: 1. Business Administration Certificate, Centro Superior De Ensenanza Length Of Course: Two Years 2. Architecture, University Of San Andres Length Of Course: Three Years 3. Correspondence Course For Commercial Specialists, Usdoc. Length Of Course: One Year 4. Correspondence Course, Part I & Part Ii, Writing For Government & Business, Us Department Of Agriculture Length Of Course: Two Years 5. International Trade Seminar, Organization Of American States. Length Of Course: Two Weeks Experience:"
cable-tags: "APER, BL, (BILBAO, JAIME M)"
cable-ref: "STATE 187748 TAGS ACOM, BEXP SUBJ: "FSI: COMMERCIAL LOCALS US TRAINING PROGRAM" HIGHLY RECOMMEND: NAME: JAIME M. BILBAO BORN: LA PAZ, BOLIVIA, JANUARY 23, 1945 FLUENCY IN ENGLISH: MR BILBAO IS COMPLETELY BILINGUAL SERVICE: JOINED EMBASSY OCTOBER 1970 EDUCATION: 1. BUSINESS ADMINISTRATION CERTIFICATE, CENTRO SUPERIOR DE ENSENANZA LENGTH OF COURSE: TWO YEARS 2. ARCHITECTURE, UNIVERSITY OF SAN ANDRES LENGTH OF COURSE: THREE YEARS 3. CORRESPONDENCE COURSE FOR COMMERCIAL SPECIALISTS, USDOC. LENGTH OF COURSE: ONE YEAR 4. CORRESPONDENCE COURSE, PART I & PART II, WRITING FOR GOVERNMENT & BUSINESS, US DEPARTMENT OF AGRICULTURE LENGTH OF COURSE: TWO YEARS 5. INTERNATIONAL TRADE SEMINAR, ORGANIZATION OF AMERICAN STATES. LENGTH OF COURSE: TWO WEEKS EXPERIENCE:"
cable-doc-number: "1974LAPAZ05622"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. RESPONSIBLE FOR ALL WDTR'S AND ADS
2. SEEKS TRADE OPPORTUNITIES
3. CONDUCTS MARKET RESEARCH STUDIES. TO REVIEW PART OF
MR. BILBAO'S TRADE OPPORTUNITIES AND MARKET RESEARCH EFFORTS,
REFER TO AIRGRAM A124 OF JUNE 21, 1974 "TEXTILE MACHINERY
OPPORTUNITIES/US TRADE MISSION" AND AIRGRAM A-163 OF AUGUST
21, 1974, "HOSPITAL CONSTRUCTION AND EQUIPMENT REQUIREMENTS".






 291957Z


THOUGH AIRGRAM A124 WAS WRITTEN BY THE COMMERCIAL ATTACHE,




                     

                 

ALL INFORMATION AND OPPORTUNITIES WERE OBTAINED BY MR.
BILBAO.
4. RESPONSIBLE FOR INVESTMENT OPPORTUNITIES REPORTING.
SEE AIRGRAMS A-94 OF MAY 17, 1974.
5. MR. BILBAO WILL BE PROMOTING US AGRICULTURAL PRODUCTS
AT THE SANTA CRUZ FAIR. EMBASSY HAS CONTRACTED FOR TWO STANDS.
PRODUCT INTEREST:
1. BIO-MEDICAL EQUIPMENT
2. AGRICULTURAL EQUIPMENT
3. CONSTRUCTION EQUIPMENT
4. CHEMICAL INDUSTRY
5. AIRCRAFT INDUSTRY
MR. BILBAO HAS DEMONSTRATED OUTSTANDING INTEREST IN ALL
OF THE COMMERCIAL ACTIVITIES. HE HAS THE AMBITION,
BACKGROUND AND CAPACITY TO FURTHER DEVELOP HIS ABILITIES
IN THE EXPORT PROMOTION FIELD.
MR. BILBAO IS HIGHLY MOTIVATED. AS A VERY ACTIVE INDIVIDUAL,
HIS VISITS TO INDUSTRY AND GOVERNMENT ARE VERY PRODUCTIVE
AS DEMONSTRATED IN THE REFERENCED AIRGRAMS. IT IS
IMPORTANT TO INCREASE THE EXPORT PROMOTION CAPABILITY OF
THIS EMBASSY AS THE ECONOMY IS IN AN ECONOMIC BOOM AND
THE EMBASSY'S STAFF IS SMALL. BY BROADENING MR. BILBAO'S
KNOWLEDGE, WE WILL BE IN A BETTER POSITION TO ASSIT US
COMPANIES IN PENETRATING THIS MARKET.
OUR COMMERCIAL ATTACHE HAS SERVED NOT ONLY IN THE LOS
ANGELES DISTRICT OFFICE, USDOC, BUT ALSO IN THE MEXICO CITY
TRADE CENTER. BASED ON HIS EXPERIENCE IT IS RECOMMENDED
THAT MR. BILBAO ADD TO HIS SCHEDULE AND ON HIS RETURN TO
BOLIVIA, A VISIT TO THE ABOVE TRADE CENTER. THIS WILL
PERMIT HIM TO DISCUSS MARKET RESEARCH TECHNIQUES WITH MEXICAN
LOCALS, WITNESS OLD-TO-MARKET AND NEW-TO-MARKET US BUSINESS-
MEN CONDUCTING ON-THE SPOT BUSINESS TRANSACTIONS AND
REVIEW ACTIVE TRADE CENTER PROMOTIONAL ACTIVITIES.
PARKER

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05622

- **Date:** August 29, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a