---
title: "Standardization Of Color Tv Project--Andean Area"
author: "Parker"
date: "August 30, 1974"
editor: visual
cable-date: "August 30, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 4086"
cable-info: "Oct-01 Ara-16 Iso-00 Eb-11 Usia-15 Drc-01 Rsc-01 /045 W --------------------- 116013"
cable-subject: "Standardization Of Color Tv Project--Andean Area"
cable-tags: "BEXP, CO, VE, PE, EC, CI"
cable-ref: "STATE 164164"
cable-doc-number: "1974LAPAZ05671"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. TASK FORCE ESTABLISHED:
   (A) EDGAR L. ROJAS, COMATT, CHAIRMAN.
   (B) ROBERT MINUTILLO, USIS INFORMATION OFFICER
   (C) PHILLIP MCLEAN, ECONOMIC/COMMERCAIL OFFICER


2. GOB DECISION MEMBERS ARE:
   (A) CAPT. DE NAV., WALTER NUNEZ RIVERO, MINISTER DE
TRANSPORTE Y COMUNICACIONES, EDIFICIO LA URBANA, AVENIDA
CAMACHO, LA PAZ, BOLIVIA; TELEPHONE 26509.
   (B) MR. ALFONSO GUZMAN, SUB-SECRETARY DE COMUNICACIONES,
EDIFICIO LA URBANA, AVENIDA CAMACHO, LA PAZ, BOLIVIA,
   TELEPHONE 26511.
   (C) MAJOR VICTOR AGUILAR DORADO, GENERAL MANAGER,
TELEVISION
   BOLIVIANA, CASILLO 900, LA PAZ, BOLIVIA, TELEPHONE 50481.


3. THE PRIME DECISION MAKER WILL BE MAJOR VICTOR AGUILAR
DORADO. THE ZENITH LOCAL REPRESENTATIVE, MR. OSCAR HANDAL,






 302255Z


AGENCIAS INTERNACIONALES LTDA., ADVISED OF A CONVERSATION




                    

                   

HE HAD RECENTLY WITH MAJOR AGUILAR IN WHICH THE MAJOR TOLD
MR. HANDAL THAT THE U.S. COLOR SYSTEM IS PREFERRED.
THE REASON GIVEN WAS THE COST OF PROGRAMMING, WHICH IS LESS FOR
U.S. SYSTEM.


4. MR. HANDAL HAS SOLD 30,000 BLACK AND WHITE ZENITH TV
SETS SINCE THE ESTABLISHMENT OF TV STATION IN 1969. THE
TOTAL NUMBER OF ALL SETS SOLD IS ESTIMATED AT 70,000. HE
ESTIMATES A MARKET OF 200,000 BLACK AND WHITE SETS.


5. THE U.S. TV BROADCASTING EQUIPMENT COMPANY, TELEMATION
OF SALT LAKE CITY, UTAH, RECENTLY SOLD TELEVISION
BOLIVIANA A NEW BROADCASTING SYSTEM. IT CAN BE USED FOR
EITHER BLACK AND WHITE OR COLOR AND IS EQUIPPED WITH A
CONVERTER TO USE EITHER THE EUROPEAN OR U.S. COLOR SYSTEM.
THIS EQUIPMENT WILL SERVE THE LA PAZ AREA. WITH THE EXCEPTION
OF A PORTABLE REPEATER SYSTEM IN AND AROUND MINING CENTERS
NEAR ORURO, TV IS NOT AVAILABLE ELSEWHERE.


6. TELEMATION IS PRESENTLY CONDUCTING A STUDY FOR TELEVISION
BOLIVIANA. TELEMATION IS REQUIRED, INTER ALIA, TO RECOMMEND
EITHER THE EUROPEAN OR AMERICAN TV STANDARD FOR THE ESTABLISH-
MENT OF TV BROADCASTING IN THE CITIES OF COCHABAMBA AND
SANTA CRUZ. IF THE U.S. STANDARD IS ACCEPTED FOR THESE TWO
CITIES, IT IS ALMOST CERTAIN THAT BOLIVIA WILL RECOMMEND THE
NTSC COLOR SYSTEM.


7. AS LA PAZ IS NOW ON THE EUROPEAN STANDARD OF 625 LINES,
50 CYCLES, ACCEPTANCE OF THE AMERICAN STANDARD WILL CAUSE
TV VIEWING PROBLEMS TO THOSE VIEWERS NOT EQUIPPED WITH
TRANSISTORIZED SETS. AS TV BROADCASTING IS ONLY FIVE YEARS
OLD, THERE ARE FEW TUBE SETS AND AS THE MARKET FOR BLACK
AND WHITE SETS IS NOWHERE NEAR SATURATED, THE RATIO OF
TRANSISTOR TO TUBE SETS WILL GROW FAR GREATER. (PERHAPS
PROGRAMS WOULD HAVE TO BE INTRODUCED TO SATISFY LA PAZ TV
VIEWERS EQUIPPED WITH TUBE SETS BY INSTALLING SUB-CARRIERS.) MAJOR
AGUILAR RECOGNIZES THAT U.S. COLOR PROGRAMS ARE AVAILABLE
IN GREATER QUANTITY, BETTER QUALITY AND AT LOWER COST THAN
PAL PROGRAMS. THEREFORE, WE HOPE THAT ESPECIALLY THE LOWER COST
OF PROCURING NTSC COLOR PROGRAMS, WILL CAUSE THE CHOOSING






 302255Z


OF THE AMERICAN TV STANDARD FOR COCHABAMBA AND SANTA CRUZ.


8. TELEVISION BOLIVIANA IS FAMILIAR WITH THE NTSC SYSTEM AND
ITS ADVANTAGES. AT PRESENT, TWO OF THEIR ENGINEERS,
INCLUDING THEIR OPERATIONS ENGINEER, ARE UNDERGOING A COURSE
AT TELEMATION. IN ADDITION, TELEVISION BOLIVIANA HAS CONTRACTED
WITH TELEMATION FOR THE COCHABAMBA, SANTA CRUZ STUDY.
NATURALLY, THIS U.S. COMPANY IS PROMOTING THE U.S. STANDARD




                   

                  

AND COLOR SYSTEM. WE SEE NO REASON AT THE PRESENT TIME TO USE
THE LEADER GRANT PROGRAM.


9. GOB INTEGRATION OFFICIALS STATE THAT GOB IS ACTIVELY
CONSIDERING POSITION IT WILL TAKE ON COLOR TELEVISION QUESTION
IN ANDEAN CONTEXT AND DECISION EXPECTED IN NEXT FEW WEEKS.
PARKER

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05671

- **Date:** August 30, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a
