---
title: "Bolivian Air Force Decision Use Fms Credit For Convair 580 Transport Aircraft"
author: "Page 02 La Paz 05026 022139z"
date: "August 02, 1974"
editor: visual
cable-date: "August 02, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 3825"
cable-info: "Oct-01 Ara-16 Iso-00 L-03 Ciae-00 Inr-11 Nsae-00 Rsc-01 Mc-02 Aid-20 Iga-02 Come-00 Trse-00 Eb-11 Drc-01 /075 W --------------------- 083974"
cable-subject: "Bolivian Air Force Decision Use Fms Credit For Convair 580 Transport Aircraft"
cable-tags: "PFOR MARR MASS BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ05026"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "MILITARY PROCUREMENT, MILITARY CREDIT, TRANSPORT AIRCRAFT"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. GENERAL ADRIAZOLA, COMMANDER BOLIVIAN AIR FORCE, HAS TOLD ME
THAT IN VIEW OF LONG LEAD TIME AND HIGH PRICE NEW C-130 AIRCRAFT,
BOLIVIA NOW WISHES USE $4 MISSION FMS CREDIT TO PURCHASE CONVAIR
TURBO-PROP 580 TRANSPORT AIRCRAFT. ADRIAZOLA TOLD ME HE WILL
ARRANGE TO HAVE BOLIVIA "GET IN LINE" FOR NEW C-130 AIRCRAFT
BUT WILL NOT USE PRESENT FMS CREDIT FOR THIS PURCHASE


2. USE OF FMS CREDIT FOR TRANSPORT AIRCRAFT (RATHER THAN FIGHER
AIRCRAFT) IS VERY MUCH IN OUR INTEREST. WHILE BOLIVIAN INTEREST
IN C-130 REMAINS HIGH, IT IS MY RECOMMENDATION THAT WE SUPPORT
THE USE OF THE EXISTING $4 MILLION FMS CREDIT FOR THE PURCHASE OF
CONVAIR 580 TRANSPORT AIRCRAFT. I UNDERSTAND CONVAIR TRANSPORT
AIRCRAFT ARE AVAILABLE IN US AND THAT BOLIVIANS MAY HAVE IDENTIFIED
SUITABLE UNITS. I WOULD GREATLY APPRECIATE FAVORABLE ACTION ON
THE USE OF THE FMS CREDIT.
PERSONAL REPRESENTATIVE FROM PRESIDENT BANZER HAS BEEN
IN TOUCH WITH US TO EXPEDITE TRANSACTION.
STEDMAN






 022139Z

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05026

- **Date:** August 02, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** MILITARY PROCUREMENT, MILITARY CREDIT, TRANSPORT AIRCRAFT