---
title: "Projected 1979 Bolivian Tin Production"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "October 11, 1979"
editor: visual
cable-date: "October 11, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 8568"
cable-info: "Oct-01 Ara-11 Ads-00 Com-02 Trse-00 Omb-01 Xmb-02 Opic-07 Aid-05 Gsa-02 Int-05 Frb-03 Ciae-00 Inr-10 Nsae-00 Doe-17 Ss-15 Sp-02 /091 W ------------------082014 131425z /43 R 111901z Oct 79"
cable-subject: "Projected 1979 Bolivian Tin Production"
cable-tags: "EMIN, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ08621"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "INDUSTRIAL PRODUCTION, TIN, ECONOMIC ESTIMATES"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. Based on current production trends, Post predicts that Bolivia's tin production this year will total 28,176 metric tons. Although in physical terms this is 5.1 percent less than the 29,696 tons produced in 1978, record tin prices will enable this year's earnings substantially to exceed last year's. (We currently project Bolivia's total 1979 tin receipts at approximately $US 580 million versus the $US 515 million earned in 1978.)
2. While there's little chance 1979 production will exceed our estimate by a significant amount, there is always the possibility that serious labor unrest could reduce the year-end total substantially below the current projection.
3. Decontrol on receipt. Boeker

***

#### Message Attributes

- **Document Number:** 1979LAPAZ08621

- **Date:** October 11, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** INDUSTRIAL PRODUCTION, TIN, ECONOMIC ESTIMATES
