---
title: "Exploration Projects In National Reserve Areas"
author: "Stedman"
date: "July 01, 1974"
editor: visual
cable-date: "July 01, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3544"
cable-info: "Oct-01 Iso-00 Aid-20 Int-08 Eb-11 Eur-25 Sci-06 Come-00 Io-14 Ciae-00 Dode-00 Inr-10 Nsae-00 Pa-04 Rsc-01 Usia-15 Prs-01 Sp-03 Drc-01 /140 W --------------------- 099778 R 011912z Jul 74"
cable-subject: "Exploration Projects In National Reserve Areas"
cable-tags: "EMIN, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ04264"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "EXPLORATION, ECONOMIC ASSISTANCE, MAPS, MINERAL RESERVES, PROGRAMS (PROJECTS)"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. SERVICIO GEOLOGICO DE BOLIVIA (GEOBOL) AND COMIBOL WILL START
IN JULY MINERAL EXPLORATION OF NATIONAL RESERVE AREAS IN NORTH
AND SOUTH LIPEZ DEPARTMENT OF POTOSI (SOUTHWESTERN BOLIVIA AND
OTHERS, NORTHERN AREA OF DEPARTMENT OF LA PAZ, SIERRA MOSETENES
NORTHWESTERN AREA DEPARTMENT OF COCHABAMBA.
FINANCING FOR EXPLORATION PROJECTS
US$ 350,000 FROM U.N. AND US$ 500,000 FROM COMIBOL AND GEOBOL.


2. TECHNICAL GEOLOGICAL HELP REPORTEDLY WILL BE RECEIVED FROM
ROYAL SCHOOL OF MINES, LONDON: QUEENS UNIVERSITY, CANADA,
TUBINGEN UNIVERSITY, GERMANY: AND UNIVERSITY OF OREGON.


3. BRITISH GEOLOGIC INSTITUTE AND GEOBOL ALSO SCHEDULED TO MAKE
GEOLOGIC MAP OF 12,000 SQUARE KILOMETER AREA ROUGHLY WHERE DEPART-
MENTS SANTA CRUZ, COCHABAMBA AND CHUQUISACA MEET.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04264

- **Date:** July 01, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** EXPLORATION, ECONOMIC ASSISTANCE, MAPS, MINERAL RESERVES, PROGRAMS (PROJECTS)