---
title: "Private Trade Opportunity"
author: "Stedman"
date: "July 30, 1974"
editor: visual
cable-date: "July 30, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3779"
cable-info: "Oct-01 Ara-10 Iso-00 Eb-05 Drc-01 Rsc-01 /018 W --------------------- 052554 R 302057z Jul 74"
cable-subject: "Private Trade Opportunity"
cable-tags: "BPRO, BEXP, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ04908"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. 335/01/P0049
2. 072574
3. E. ROJAS
4. 335 BOLIVIA
5. Y. PUBLIC WORKS COMMITTEE
6A. --
6B. --
6C. -- COMITE DE OBRAS PUBLICAS DE SANTA CRUZ
    CONVOCATORIA NO. 47/74
    CASILLA 218
    SANTA CRUZ, BOLIVIA
7. CABLE--
8. --
9. 104
9A. BID REQUEST BY PUBLIC WORKS COMMITTEE OF SANTA CRUZ DEPT.
10. DESCRIPTION:
0000 - 114,000 METERS OF ASBESTOS CEMENT WATER PIPING AND
ACCESSORIES AS STATED IN THE SPECIFICATIONS. ONE COPY OF
SPECIFICATIONS BEING POUCHED TO THE DEPARTMENT OF COMMERCE.
THE BID DEADLINE IS AUGUST 13, 1974 AT 5:00 P.M. COMPLETE
SPECIFICATIONS CAN BE PURCHASED FOR $B 200 OR US$ 10 FROM COMITE
DE OBRAS PUBLICAS DE SANTA CRUZ, CASILLA 218, SANTA CRUZ, BOLIVIA.
NOTE: PLEASE PUBLISH IN COMMERCE TODAY. WTDR OF OCTOBER, 1973.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04908

- **Date:** July 30, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a