---
title: "Message To The Nation Delivered By President Banzer On June 5, 1974. Quote:"
author: "Brewin"
date: "June 06, 1974"
editor: visual
cable-date: "June 06, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 3332"
cable-info: "Oct-01 Iso-00 Ss-20 Nsc-07 Ciae-00 Dode-00 Inr-10 Nsae-00 Pa-04 Rsc-01 Usia-15 Prs-01 Sp-03 Drc-01 /083 W --------------------- 057173"
cable-subject: "Message To The Nation Delivered By President Banzer On June 5, 1974. Quote:"
cable-tags: "PINT, PGOV, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ03687"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PRESIDENT, GOVERNMENT REFORM, POLITICAL STABILITY, ARMED FORCES, SPEECHES, PUBLIC ADMINISTRATION,"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. TO THE COMRADES OF THE ARMED FORCES OF THE NATION WHO DURING MY
ABSENCE AND WITH EXEMPLARY POLITICAL MATURITY DEMONSTRATED BEFORE
HISTORY, THE FIRM PURPOSE OF THE (MILITARY) INSTITUTION TO MAINTAIN,
ABOVE ALL PERSONAL AMBITIONS AND SECTARIAN INTERESTS, THE CONTINUITY
OF THE NATIONAL REVOLUTION, AS THE SOLE ALTERNATIVE TO ATTAIN SUCCESS
IN OVERCOMING BACKWARDNESS AND DEPENDENCY.


2. TO EACH OF THE MEMBERS OF THE NATIONALIST POPULAR FRONT, WHO IN A
FEW MINUTES DEMONSTRATED, TOGETHER WITH THE ARMED FORCES OF THE NATION
THEIR CAPACITY OR STRUGGLE.



3. TO THE SECURITY UNITS OF THE STATE, THAT WITH DISCIPLINE EFFECTIVELY


FOLLOWED THE INSTRUCTIONS GIVEN BY THE MINISTRY OF INTERIOR






 062121Z


RENEWING THUS THEIR FULL IDENTIFICATION WITH MY GOVERNMENT.




                     

                   


4. TO THE FARMERS AND WORKERS, DEVOTED MEN WHO FULLY REALIZE WHO
ARE THOSE WHO WORK AND FIGHT FOR THEIR GOALS AND WHO ARE THOSE WHO
ATTEMPT TO ENGAGE IN SMALL ADVENTURES AGAINST THE NATION, CONTRARY
TO REASON AND HISTORY.


5. TO THE CITIZENS WHO, FACING THE CHOICE BETWEEN A COUNTRY WITH
DIGNITY AND DEVELOPMENT, OR A REGRESSIVE AND DESTRUCTIVE CHAOS,
ADOPTED THE GREAT DECISION TO FIGHT THE BATTLE AGAINST THOSE WHO
ATTEMPTED TO MAINTAIN POVERTY.


6. TO THE PERSONAL FRIENDS WHO, AT THE TIME OF TRIAL, SUPPORTED THE
IDEALS OF THE GOVERNMENT AND SUPPORTED ME.


7. I ADDRESS ALL OF YOU, WITH THE REWARDING FEELING OF A DEFINITE AND
CLEAN VICTORY, BUT AT THE SAME TIME WITH THE BITTERNESS CAUSED BY THE
INCONSISTENCY AND MEANNESS OF SMALL GROUPS WHO TRY NOT TO UNDERSTAND
THAT THE HEROIC DESTINY OF OUR COUNTRY DEMANDS GREATNESS OF SPIRIT,
AND THE HUMAN QUALITY WHICH CHARACTERIZES THE BOLIVIANS WHO LEAD THE
GREAT CHANGES THAT THE COUNTRY REQUIRES.


8. BOLIVIA IS GOING THROUGH A DIFFICULT TIME IN ITS DEVELOPMENT. FOR
THIS, WE ARE USING OUR SACRIFICE, DISCIPLINE AND WORK IN ORDER TO EST
ABLISH
THE BASES WHICH WILL MAKE POSSIBLE A SUSTAINED RHYTHM OF SHARED
PROGRESS AND WELFARE.


9. THE BASIC OBJECTIVE OF MY GOVERNMENT IS THAT OF DEVELOPMENT. THE
PEOPLE OF THIS WORTHY LAND ARE ENTITLED TO WORK, THINK, AND BELIEVE
WITH
NO OTHER LIMITATION THAN THAT OF THEIR OWN POSSIBLITIES. WITH A
THIRELESS EFFORT, WE ARE WORKING DAY AND NIGHT, SO THAT OUR BELOVED
COUNTRY WILL TAKE ADVANTAGE OF THE OPPORTUNITIES AND MEANS OFFERED
US BY CONTEMPORARY SOCIETY: AND VERY SOON IT WILL BE POSSIBLE THAT
BOLIVIA WILL ACT JOINTLY WITH THE OTHER COUNTRIES OF THE WORLD IN
EQUAL CONDIDTIONS AND WITHIN A FRAMEWORK OF MUTUAL BENEFIT AND
RESPECT.


10. DURING THE CONSULTATION MEETING HELD IN COCHABAMBA, CONVINCED OF
THE NECESSITY TO MOBILIZE ALL RESOURCES OF THE COUNTRY IN ORDER TO






 062121Z


FACE
THE CHALLENGE OF POVERTY, I ASKED THE BOLIVIAN PEOPLE FOR THEIR UNITY
AROUND THE ARMED FORCES OF THE NATION. SUPPORTED BY THE STRENGTH OF
MY DEEPEST CONVICTION, I ALSO RAISED THE ISSUE OF NATIONAL PARTICIPA-
TION SO THAT EACH TASK COULD BE ACCOMPLISHED WITH THE HELP OF THE
DECISION AND CAPABILITY OF EACH BOLIVIAN. THE ANSWER RECEIVED FROM THE


ANTI-NATIONAL GROUPS, WHO ARE MOTIVATED BY ANGER AND UNILIMITED




                   

                   

AMBITION. HAS BEEN A TOTAL LACK OF UNDERSTANDING, ISOLATED
VIOLENCE, GROUNDLESS CRITICISM, AND OPPOSITION FOR THE SAKE OF
OPPOSITION.


11. AS A PART OF OUR INTERNATIONAL STRATEGY IN THE CONTEXT OF
THE STRUGGLE FOR CONTRO OF THE WORLD, BOLIVIA, BECAUSE OF ITS
GEOGRAPHIC POSITION AND BECAUSE OF THE DEFICIENCES OF OUR HERITAGE,
HAS BEEN CHOSEN AS THE CENTER OF EXTREMIST ACTIVITIES OF THOSE
WHO HAD INTENDED TO SPEAD THEIR VIOLENT ACTIVITIES INTO OTHER
COUNTRIES OF THE HEMISPHERE.


12. UNFORTUNATELY, AMBITIOUS POLITICIANS, SUCH AS HUMBOLT AND
VALVERDE, WITHOUT INTELLIGENCE ENOUGH TO UNDERSTAND INTERNATIONAL
EVENTS, ALLOWED THEMSELVES TO BE USED IN SUCH PLANS WITHOUT
RELAIZING THE HUGE DAMAGE CAUSED TO THE NATION.


13. BUT THE MOST SERIOUS FACT ABOUT THE PERSONS WHO ASSUMED THIS
ATTUDE IS THAT IN THEIR EFFORT TO GAIN FOLLOWERS, THEY TURNED TO
THE MILITARY HEADQUARTERS, TOOK ADVANTAGE OF INGENUOUS OFFICERS AND
DAMAGED THE IMAGE AND UNITY OF THE ARMED FORCES OF THE NATION.


14. THE AUTHORS OF EVENTS OF THIS KIND WILL BE DISCIPLINED WITH THE
SEVERITY PRESCRIBED BY THE LAW, BECAUSE ULTIMATELY THE UNITY OF THE
ARMED FORCES OF THE NATION IS THE UNITY OF THE COUNTRY.


15. I ACCOMPLISH WITH HONOR THE MISSION TO DISMISS THE CHARGES
AGAINST THE AIR (FORCE) BASE AND THE MILITARY ACADEMY MADE BY
CERTAIN NEWSPAPERS, MAKING CLEAR THAT THESE UNITS MAINTAINED FULL
AND CONSISTENT LOYALTY TOWARD THE CONSITUTED ORDER.


16 IT IS ALSO MY DUTY TO EMPHASIZE THE LOYAL AND DISCIPLINED
CONDUCT OF ALL THE GARRISONS OF THE INTERIOR OF THE COUNTRY, TO WHOM
I EXPRESS MY APPRECIATION.






 062121Z



17. ONCE MORE, I TAKE THIS OPPORTUNTY TO MENTION THAT THE EFFORT I
MAKE, TOGETHER WITH THE ARMED FORCES OF THE NATION AND WITH ALL
Y CO-WORKERS, I S NOT TO ATTAIN AN OBJECTIVE OF A PERSONAL NATURE.
I AM LEADING THE GOVERNEMENT BECAUSE I BELIEVE IN BOLIVIA AND
ITS CAPACITY TO BE A GREAT (COUNTRY) VERY SOON: WITHIN THE
FRAMEWORK OF THIS CONCEPT, WHEN FACING THE CHOICE BETWEEN BOLIVIA
AND ITS GRETNESS OR ACTIVITIES WHICH DISTURB PEACE AND DEVELOPMENT,
I WARN THAT I SHALL UNHESTATINGLY CHOOSE BOLIVIA OVER THE
ENEMIES OF ITS GREATNESS.


18. THE VICTORY WHICH HAS BEEN ATTAINED DURING MY ABSENCE BY THE
PEOPLE SHOWS THE HISTORIC STRENGTH OF MY GOVERNMENT. I SHALL NOT
WASTE SUCH MORAL AND MATERIAL STRENGTH OVER SMALL OBSTACLES. MY EFFORT




                   

                  

WITH THE PEOPLE AND WITH THE COUNTRY'S PRINCIPAL INSTITUTIONS IS
DECISIVE.


WE SHALL WIN THE BATTLE AGAINST MISERY SO THAT IN THE FUTURE
THERE WILL BE NO TEARS FOR LACK OF BREAD, NOR BITTERNESS OVER
TREASONOUS ACTS.


19. BOLIVIANS: I HAVE RECEIVED AGAIN
THE LIVING LOYALTY OF MY PEOPLE, OF THE ARMED FORCES OF THE
NATIONA, THE NATIONALIST POPULAR FRONT, THE FARMERS, WORKERS
AND ALL HONEST AND NOBLE MEN OF BOLIVIA. THIS BEAUTIFUL
AND MAGNIFICENT DEMONSTRATION DEFINITELY COMMITS ME TO
CONTINUE STRUGGLING TOGETHER WITH THE BOLIVIAN PEOPLE FOR THE
GREAT NATIONAL DESTINY.
THANK YOU. UNQUOTE.
BREWIN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03687

- **Date:** June 06, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PRESIDENT, GOVERNMENT REFORM, POLITICAL STABILITY, ARMED FORCES, SPEECHES, PUBLIC ADMINISTRATION,
