---
title: "American Indian Convention"
author: "Brewin"
date: "May 22, 1974"
editor: visual
cable-date: "May 22, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3161"
cable-info: "Oct-01 Iso-00 Ss-20 Nsc-07 L-03 Sy-04 Int-08 Ciae-00 Inr-10 Nsae-00 Rsc-01 Fbie-00 /074 W --------------------- 125854 R 221429z May 74"
cable-subject: "American Indian Convention"
cable-tags: "BL"
cable-ref: "STATE 101850"
cable-doc-number: "1974LAPAZ03292"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "MINORITIES, MEETINGS, MEETING DELEGATIONS, FOREIGN POLICY POSITION"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. EMBASSY INFORMED DIRECTOR OF NORTH AMERICAN AFFAIRS AT
FOREIGN MINISTRY MAY 17 OF PROPOSED INDIAN TREATY CONVENTION.
FOREIGN MINISTRY IS CHECKING WITH OTHER GOVERNMENT AGENCIES TO
LEARN IF ANY INVITATIONS TO THIS EVENT WERE RECEIVED BY GOB.
MEANWHILE, WEEKLY  NEWSLETTER ABC REPORTED MAY 20
THAT SEVERAL INVITATPONS TO CONVENTION HAVE BEEN RECEIVED IN
BOLIVIA, WITHOUT IDENTIFYING RECIPIENTS OF SAME.


2. USIS PAO REPORTS VISIT RECENTLY BY NOTED BOLIVIAN EXPERT ON
INDIAN AFFAIRS FAUSTO REINAGA, WHO HAS RECEIVED AND ACCEPTED IN-
VITATION TO JUNE 8-16 CONVENTION. HOWEVER, REINAGA STATED HE
LACKS MONEY TO PAY TRAVEL, HOTEL EXPENSES AND EXPRESSED HOPE
THAT USIS COULD PROVIDE LEADER GRANT FUNDS FOR THIS PURPOSE.
TURNED DOWN ON THIS SCORE, REINAGA THEN STATED THAT HIS SON
WOULD ATTEND CONVENTION IN HIS PLACE AS "REPRESENTATIVE
OF BOLIVIA." REINAGA'S SON IS ATTEMPTING TO HAVE HIS BOOK,
WHICH IS STRONGLY ANTI-U.S., PUBLISHED IN NEW YORK WHERE
HE LIVES. SON ALSO IS USING EXPIRED VISA, ACCORDING TO
REINAGA, WHO ASKED U.S. MISSION TO HELP HIM RESOLVE THIS
PROBLEM AS WELL. REINAGA WAS REFERRED TO U.S. CONSUL IN
LA PAZ.






 221538Z




                    

                  

3. EMBASSY WILL CONTINUE LOW-KEY EFFORT TO LEARN IDENTITIES
OF OTHER RECIPIENTS OF THESE INVITATIONS, AND WILL IN-
FORM DEPARTMENT WHEN FOREIGN MINISTRY RESPONDS TO OUR INITIAL
INQUIRY ON THIS SUBJECT.
BREWIN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03292

- **Date:** May 22, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** MINORITIES, MEETINGS, MEETING DELEGATIONS, FOREIGN POLICY POSITION