---
title: "Dea Six-Week International Drug Enforcement Officiers School No. 5"
author: "Stedman"
date: "February 14, 1974"
editor: visual
cable-date: "February 14, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "Dea Hqs WashDC"
cable-info: "Oct-01 Iso-00 Aid-20 Snm-02 Rsc-01 Drc-01 /045 W --------------------- 034878 R 141711z Feb 74"
cable-subject: "Dea Six-Week International Drug Enforcement Officiers School No. 5"
cable-tags: "SNAR, BL"
cable-ref: "DEA 468"
cable-doc-number: "1974LAPAZ00992"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PERSONNEL TRAINING, DRUG CONTROL"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Bolivian candidates for subject school are Lt Oscar Bernal Vasquez and Det Edgar Garcia Munoz. These candidates are endorsed and recommended by DEA.

2. Although no bilateral agreement exists, it has been policy to pay for international travel of Bolivian police participants for U.S. training. Therefore, PIO/P should provide for international travel.

3. If additional space available this school, DEA, Bolivia would like to have at least two additional spaces, for a total of four.

4. Bio data:
A. Lt Oscar Bernal Vasquez - Office of Narcotics and Dangerous Drugs, National Police, seven years police experience, two months narcotics experience, apparent good physical condition.
B. Detective Edgar Garcia Munoz - Office of Narcotics and Dangerous Drug, National Police, four years police experience, two years narcotic experience, apparent good physical condition.

5. Completed bio data and medical forms to be pouched.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00992

- **Date:** February 14, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PERSONNEL TRAINING, DRUG CONTROL