---
title: "Congressman Whalen's Conversation With Bolivian Foreign Minister Guzman"
author: "Stedman"
date: "January 10, 1974"
editor: visual
cable-date: "January 10, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 1897"
cable-info: "Oct-01 Iso-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-10 Pa-04 Rsc-01 Prs-01 Spc-03 Ss-20 Usia-15 Oic-04 Aid-20 Come-00 Eb-11 Frb-02 Trse-00 Xmb-07 Opic-12 Ciep-02 Lab-06 Sil-01 Omb-01 Eur-25 Nic-01 Drc-01 /191 W --------------------- 064630 R 101327z Jan 74"
cable-subject: "Congressman Whalen's Conversation With Bolivian Foreign Minister Guzman"
cable-tags: "OREP PFOR PINS EAID BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ00179"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "WHEAT, CODELS, MEETINGS, MEETING REPORTS, FOREIGN POLICY POSITION, FOREIGN MINISTERS MEETINGS, FOREIGN"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1.  **During courtesy call on the Bolivian Foreign Minister General Guzman January 9, Congressman Charles Whalen (R.-Ohio) asked whether Bolivia had any special points it intended to raise during the forthcoming meeting of Foreign Ministers with SecState Kissinger. The Foreign Minister indicated that the staff of the Foreign Ministry is working on some positions but basically Bolivia has no particular points; rather wishes to participate with the other Foreign Ministers in the preparatory session in Mexico to work out a constructive agenda. He expressed interest in special tariff preference legislation and hoped that the Congressman would assist in bringing about a final and helpful bill inasmuch as Bolivia considers opportunities in relations with the U.S. as more potentially beneficial than benefits to be derived from Latin American integration which is going so slowly. Foreign Minister indicated his appreciation for U.S. assistance and hoped for a continuation of such cooperation, without which, he said, Bolivia cannot break out of its low level of development. He repeated the GOB's interest in PL-480 wheat imports from the U.S. because of the acute shortage of flour and wheat which could create political problems. Mr. Whalen said that there was a high demand for wheat and a consequent short supply in the world. He did say though that he understood that Bolivian and U.S. authorities were discussing the Bolivian request, and he knew that the USG would do whatever it could, although the situation with regard to wheat is bleak.**
2.  **Congressman Whalen inquired about Bolivia's attitude toward the OAS and Cuba. Foreign Minister expressed support for an effective OAS and felt that efforts should go forward to reconstruct it for the benefit of all members. Foreign Minister said that Bolivian Ambassador Valencia, who occupies double capacity of Ambassador to the U.S. and to the OAS, would join him in Mexico as his advisor on key discussions of OAS aspects during the Foreign Ministers' meeting. As to Cuba, he said the position of the GOB is constant and firm in viewing Cuba as a menace which has harmed Bolivia seriously. Foreign Minister said that Bolivia does not wish to have any variation in the present OAS policy toward Cuba.**
3.  **Congressman Whalen asked if the Foreign Minister would give him any official explanation for the expulsion of Dr. Victor Paz on January 8. The Minister said that the departure of Dr. Paz was a surprise to him and that the instructions to deport him were directed by President Banzer himself.**

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00179

- **Date:** January 10, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** WHEAT, CODELS, MEETINGS, MEETING REPORTS, FOREIGN POLICY POSITION, FOREIGN MINISTERS MEETINGS, FOREIGN
