---
title: "Action Against Egypt In Fao Conference November 10-30, 1979"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "November 01, 1979"
editor: visual
cable-date: "November 01, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 8988"
cable-info: "Oct-01 Ara-11 Nea-06 Ads-00 Agr-01 Aid-05 Eb-08 Ica-11 Com-02 Trse-00 Ciae-00 Dode-00 Pm-06 H-01 Inr-10 L-03 Nsae-00 Nsc-05 Pa-01 Sp-02 Ss-15 Ses-01 Sph-01 Ssn-02 Ha-05 /112 W ------------------114565 040741z /15 R 012315z Nov 79"
cable-subject: "Action Against Egypt In Fao Conference November 10-30, 1979"
cable-tags: "PORG, FAO"
cable-ref: "STATE 282993"
cable-doc-number: "1979LAPAZ09361"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "DEMARCHE, RELOCATION, AGRICULTURE, TRANSFER OF OFFICES, REPRISALS, SPECIALIZED AGENCIES (UN)"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

2. Embassy officer made points outlined reftel to MFA under secretary for exterior political affairs Moise Fuentes. Fuentes was not aware of the issue, but did note that Bolivia followed a line supportive of the Camp David Accords and one that eschewed introduction of divisive political issues in UN technical agencies. Hence his off-the-cuff reaction was that Bolivia would be helpful. Nevertheless, he requested an aide memoire to follow-up, since Bolivia will probably be represented at the conference by a technical functionary from the Agriculture Ministry, who would otherwise be unacquainted with some of the political issues.
3. We are preparing the memoire, and will provide name of Bolivian delegate when appointed, since follow-up in Rome might be useful. Fuentes also noted he had not been approached by Egyptian Embassy on the matter. A check with Egyptian Embassy reveals they have similar instructions, but had not planned their demarche before November 5.
4. Foregoing was prepared before attempted overthrow of Guevara regime, which is still in process. Hence follow-up will probably not be possible for an undetermined period.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ09361

- **Date:** November 01, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** DEMARCHE, RELOCATION, AGRICULTURE, TRANSFER OF OFFICES, REPRISALS, SPECIALIZED AGENCIES (UN)