---
title: "Product Lists For Gsp"
author: "Stedman"
date: "August 15, 1974"
editor: visual
cable-date: "August 15, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3924"
cable-info: "Oct-01 Ara-16 Iso-00 Fea-02 Agr-20 Cea-02 Ciae-00 Come-00 Dode-00 Frb-03 H-03 Inr-11 Int-08 L-03 Lab-06 Nsae-00 Nsc-07 Pa-04 Rsc-01 Aid-20 Ciep-03 Ss-20 Str-08 Tar-02 Trse-00 Usia-15 Prs-01 Sp-03 Omb-01 Swf-02 Drc-01 /174 W --------------------- 084280 R 152000z Aug 74"
cable-subject: "Product Lists For Gsp"
cable-tags: "ETRD, XM, BL"
cable-ref: "STATE 166536"
cable-doc-number: "1974LAPAZ05259"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "INTERGOVERNMENTAL COOPERATION, GENERALIZED PREFERENCES (TARIFFS), GSP LIST"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. AFTER RECEIPT REFTEL, EMBASSY CONSULTED WITH FONOFF,
ECONOMIC DIVISION, RE BOLIVIAN PRODUCT LIST. WE NOW TOLD
THAT AS CONSEQUENCE OF OUR APPROACH, FONOFF CONSULTING WITH
MINISTRY IND/COM AND FOREIGN TRADE PROMOTION OFFICE (FOMEX)
OF CENTRAL BANK.


2. EMBASSY HAS BEEN UNABLE TO DETERMINE FROM FILES AND
FONOFF UNABLE TO CONFIRM WHETHER BOLIVIA EVER SUBMITTED
PRODUCT LIST. WE WOULD APPRECIATE DEPARTMENT'S ASSISTANCE
DETERMINING WHETHER LIST PREVIOUSLY SUBMITTED AND SENDING
EMBASSY COPY OF LIST IF LOCATED.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05259

- **Date:** August 15, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** INTERGOVERNMENTAL COOPERATION, GENERALIZED PREFERENCES (TARIFFS), GSP LIST
