---
title: "List Of Potential Invitees To World Energy Conference (Wec)"
author: "Brewin"
date: "May 20, 1974"
editor: visual
cable-date: "May 20, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3141"
cable-info: "Oct-01 Ara-16 Iso-00 Eb-11 Fea-02 Come-00 Sca-01 Ss-20 Int-08 Ciae-00 Inr-10 Nsae-00 Rsc-01 Ciep-02 Trse-00 Fpc-01 Drc-01 /080 W --------------------- 095550 R 202035z May 74"
cable-subject: "List Of Potential Invitees To World Energy Conference (Wec)"
cable-tags: "TECH, ENRG, BL"
cable-ref: "STATE A-3772 OF MAY 8, 1974"
cable-doc-number: "1974LAPAZ03250"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "ENRGY, MEETINGS, INVITATIONS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. FROM NATIONAL PETROLEUM COMPANY YACIMIENTOS
PETROLIFEROS FISCALES BOLIVIANOS (YPFB)
ING. ROLANDO PRADA M GENERAL MANAGER
ING. WILLIAM MCKENNEY, PRODUCTION MANAGER
ING. JAIME OBLITAS G., EXPLORATION MANAGER
ING. DELFIN POZO J., INDUSTRIAL MANAGER
ING. LUIS SALINAS E., PLANNING DIRECTOR
ING. CARLOS DELIUS E., MANAGER SANTA CRUZ DIVISION
ING. ADRIAN BUSTILLO C., COMMERCIAL MANAGER
ING. CARLOS URIA C., YABOG MANAGER
LIC. JAIME LARRAZABAL, FINANCIAL MANAGER
LIC. JOSE CANDIA M., MANAGEMENT COORDINATOR
ADDRESS FOR ABOVE LIST-YACIMIENTOS PETROLIFEROS
FISCALES BOLIVIANOS, CALLE BUENOS S/N, LA PAZ BOLIVIA


2. FROM MINISTERIO DE ENGERIA E HIDROCARBUROS:
COL GUILLERMO JIMENEZ G., MINISTER
ING. JORGE ZAMORA, SUBSECRETARY
ING. RENAN ARCE, NATIONAL DIRECTOR OF ELECTRICITY






 202216Z


ING. CARLOS MIRANDA, NATIONAL DIRECTOR OF




                       

                  

HYDROCARBONS
ADDRESS FOR ABOVE LIST, MINISTERIO DE ENERGIA E
HICROCARBUROS, 1322 AV MARISCAL SANTA CRUZ,
LA PAZ BOLIVIA


3. PRIVATE SECTOR REPRESENTATIVES IN BOLIVIA MOSTLY
REPRESENT WELL KNOWN US PETROLEUM COMPANIES
WHICH VERY LIKELY KNOW OF WEC THROUGH HOME OFFICES
THREE BOLIVIAN COMPANY REPRESENTATIVES ARE JOSE
MENDIETA, MANAGER LIQUID CARBONIC DE BOLIVIA S.A.,
CASILLA 571, LA PAZ, BOLIVIA: GONZALO GARCIA, CASILLA
958, LA PAZ, BOLIVIA: EDUARDO LOPEZ, MANAGER GASONA
LTDA., CASILLA 1851, COCHABAMBA, BOLIVIA.


4. FROM COMISSION BOLIVIANA DE ENERGIA NUCLEAR
(COBOEN) TTE. DE NAVIO ALBERTO SAENZ K., EXECUTIVE
DIRECTOR: ING. JORGE DORIA M, TECHNICAL MANAGER.
COBOEN'S ADDRESS, AV 6 DE AGOSTO 2905, LA PAZ,
BOLIVIA


5. FROM MINISTERIO DE MINERIA Y METALURGIA:
DR RAUL LEMA P., MINISTER: ADDRESS 1322
AV MARISCAL SANTA CRUZ, LA PAZ, BOLIVIA.
BREWIN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03250

- **Date:** May 20, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** ENRGY, MEETINGS, INVITATIONS