---
title: "Text Of \"Declaration Of Cochabamba\""
author: "Stedman"
date: "April 09, 1974"
editor: visual
cable-date: "April 09, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2786"
cable-info: "Oct-01 Iso-00 Coa-02 Dlos-06 Eb-11 Aid-20 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-07 Pa-04 Rsc-01 Prs-01 Sp-03 Ss-20 Usia-15 Drc-01 /135 W --------------------- 015904 R 091336z Apr 74"
cable-subject: "Text Of \"Declaration Of Cochabamba\""
cable-tags: "PINT, PFOR, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ02209"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "LANDLOCKED COUNTRIES, ACCESS TO PORTS"
---


# DEPARTMENT OF STATE TELEGRAM

**UNCLASSIFIED**

::: {.cable-meta}
:::


1.  Embassy transmits with this telegram full text of "Declaration of Cochabamba", issued on April 5 by the National Consultative Meeting called together by President Banzer in that city:

The institutions and persons invited by the President of the Republic to attend the "National Consultation (Assembly)", which took place on April 5, 1974 in the city of Cochabamba and who have hereunto affixed their signatures:

Considering that "returning to the sea" is a national, non-partisan desire which requires that all Bolivians take joint action (for its achievement).

Taking fully into account the message of Gen. Hugo Banzer Suarez, President of the Republic; the position of the Armed Forces of the Nation; the addresses and suggestions made by the institutions and persons who participated in the National Assembly; the expectations and hopes of the country; the demands of our youth and our duty as men and as Bolivians.

Convinced that the development of the country will be attained only by harmonious development, of a deeply social nature, which will permit us to solve our international problems and face the future in relationship with the general desires of the Bolivian people.

Being prepared to overcome social and political dispersion, to make compatible the interests of the various social sectors with the objectives of the country and to loyally carry out a national political alliance for the execution of concrete tasks related to our prompt return to the sea.

Declare:

1.  **First**- That the return to the sea is the most important national objective, in which all Bolivians are involved equally.
2.  **Second** - That in order to attain the national objective of returning to the sea, a general process of development is necessary, which would provide the national state with the capacity to solve its internal problems and face the foreign situation with greater strength.
3.  **Third** - To commit themselves in maintaining and respecting a political truce and a social peace which will make possible a stable and homogenous historical period.
4.  **Fourth** - To accept the wider political participation proposed by Gen. Hugo Banzer Suarez, President of the Republic, whereby a National Council of Consultation and a Specialized Commission will be established, which will be in charge of studying the problem of Bolivia's land-locked situation.
5.  **Fifth** - To agree not to exercise any pressures thereby enabling Gen. Hugo Banzer Suarez, President of the Republic, to organize the Executive Power by taking into account the abilities of his co-workers in relation to the great goal of returning to the sea.

By the will of the nationalist institutions and persons who affix their signatures, given in the city of Cochabamba, on the fifth day of April in the year nineteen seventy-four.

------------------------------------------------------------------------

#### Message Attributes

-   **Document Number:** 1974LAPAZ02209

-   **Date:** April 09, 1974

-   **Classification:** UNCLASSIFIED

-   **Declassified:** 01 JAN 1960

-   **Concepts:** LANDLOCKED COUNTRIES, ACCESS TO PORTS
