---
title: "Two Week Training School In La Paz, Bolivia"
author: "Stedman"
date: "May 16, 1974"
editor: visual
cable-date: "May 16, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "Dea Hqs WashDC"
cable-info: "Oct-01 Iso-00 Aid-20 Snm-02 Trse-00 Rsc-01 Drc-01 /045 W --------------------- 049387 R 162037z May 74"
cable-subject: "Two Week Training School In La Paz, Bolivia"
cable-tags: "SNAR, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ03188"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "DRUG CONTROL, PERSONNEL TRAINING"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. ON MAY 15 AND 16, 1974, S/A MARTIN CONDUCTED
MEETINGS WITH LUIS CARRASCO GUTIERREZ, HEAD OF THE DIRECCION
NACIONAL DE EL CONTROL DE SUSTANCIAS PELEGROSAS REGARDING
THE PROPOSED TWO-WEEK SCHOOL IN LA PAZ, BOLIVIA. DURING
THOSE MEETINGS, THE FOLLOWING LOGISTICAL DETAILS WERE
DISCUSSED AND FINALIZED:
A. THE SCHOOL WILL BE CONDUCTED FROM TUESDAY,
JUNE 25, 1974, THROUGH FRIDAY, JULY 5, 1974. SCHOOL HOURS
WILL BE FROM 8:30 AM TO 3:30PM, WITH SATURDAY, JUNE 29 BEING
IMPLEMENTED AS A WORKING DAY.
B. THE CLASSROOM, LOCATED IN THE BIBLIOTECA
MUNICIPAL, HAS BEEN OSBERVED AND IS EXCELLENT BOTH AS A
TRAINING FACILITY AND FOR SECURITY OF EQUIPMENT.
C. THERE WILL BE 40 STUDENTS PARTICIPATING.
COURSE CONTENT WILL BE STRUCTURED TO FACILITATE THE TRAINING
OF THE ABOVE-MENTIONED STUDENTS WHO WILL FORM A NEWLY-
CREATED NARCOTIC UNIT IN BOLIVIA. AS REQUESTED BY BOLIVIAN
OFFICIALS, TIME HAS BEEN ALLOTTED FOR A PRESENTATION ON
HOST COUNTRY LAW. A PRACTICAL EXERCISE TAILORED TO THE






 162206Z


NEEDS OF BOLIVIA, HAS BEEN ARRANGED AND WILL BE CONDUCTED




                       

                     

ON JULY 3 AND 4, 1974.


2. DISCUSSIONS CONDUCTED IN BOLIVIA PROVED BOTH
CORDIAL AND FRUITFUL. THE OFFICIALS OF THE DIRECCION
NACIONAL WERE EXTREMELY RECEPTIVE AND EAGER TOWARD IDEAS
PRESENTED, AND WERE LOOKING FORWARD TO THE SCHOOL WITH
GREAT ANTICIPATION.
BEDOLLA, SAIC.
DECONTROL ON RECEIPT BY DEA ONLY.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03188

- **Date:** May 16, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** DRUG CONTROL, PERSONNEL TRAINING
