---
title: "Us/Gob Narcotics Program: Proposed Demarche By President Carter's Representative To Bolivian Inaugural"
author: ""
date: "July 21, 1979"
editor: visual
cable-date: "July 21, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 7352"
cable-info: "Oct-01 Ara-11 Ads-00 Deae-00 Ciae-00 Inr-10 Io-14 Jus-01 Nsae-00 Ctme-00 Sp-02 Trse-00 Ica-11 Nsc-05 Oes-09 Omb-01 Ss-15 Hew-04 Dode-00 Agr-01 Aid-05 /095 W ------------------113256 211257z /43 P 211200z Jul 79"
cable-subject: "Us/Gob Narcotics Program: Proposed Demarche By President Carter's Representative To Bolivian Inaugural"
cable-tags: "SNAR, OVIP, PDIP, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ06238"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "NARCOTICS, DEMARCHE, PRESIDENT"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. I recommend that the US delegation to the Bolivian August 6 inauguration, headed by Mrs. Carter, take this opportunity for a strong demarche to the President-elect on US desire for more effective GOB cooperation on our US/GOB narcotics program. This newly elected president will be beholden to us for our support of democratization in Bolivia. He will also have significant requests for further economic and political support from us. Therefore, it is the right time for us to raise our desiderata. Since late 1977 there has been a lack of strong commitment and drive from the top of the GOB, partly resulting from the electoral campaigns of 1978 and 1979. The US must seize the opportunity of the inauguration to impress upon the President-elect our major concern with illicit cocaine trafficking and production. The main point to impress upon him is that sterner, more disciplined GOB policies and enforcement action from the cabinet on down should be adopted. To help finance this increased Bolivian effort and to make it politically tolerable for the new president, the US will need to offer new financial support for narcotics programs in Bolivia. We should offer in return for Bolivian commitments $15 million (over five years) for measures to control the coca leaf market and, in addition to presently planned USAID projects for Bolivia in FY80, $19 million for an agricultural development program which will provide small farmers the incentives to cease or restrict their production of coca. Our ideas on the general content of a memorandum for the White House proposing such a demarche follow.

A. **Problem**
1. Since November 1977, when then President Banzer announced that elections were to be held in July 1978, progress in achieving our goal of reducing the illicit flow of cocaine to the US has been disappointing. While substantial progress has been made in laying structural and institutional foundations for future efforts and drug seizures in 1979 have increased somewhat, the Bolivian Government has not shown the will to live up to its commitments. Primarily for political reasons related to election campaigns, the GOB has been weak and ineffective in the narcotics area, as indeed in others.
2. The GOB needs a sharp kick to awake it to its responsibility to:
    *   Move against major traffickers;
    *   Curtail or destroy new, illegal coca plantings;
    *   Support vigorously an effective program of replacement income for farmers in coca areas;
    *   Reduce corruption in the judicial system and keep traffickers in jail.
3. Bearing in mind the weakness of Bolivian political institutions and the US goal of encouraging free, democratic elections in Bolivia, we have not recently sought to force these issues. We should now, however, seek the new President's commitment on these four points and, if we get it, offer our cooperation to implement a comprehensive strategy.
4. If the new government is found unwilling to cooperate with the USG in this respect, we should review again our narcotics strategy vis-a-vis Bolivia. A modest enforcement support program and a DEA presence in Bolivia will always be worthwhile for the US. However, without effective GOB action on enforcement, penal and judiciary reforms and destruction of new coca plantings, it is doubtful that major expansions of enforcement programs, large-scale agricultural development and coca income substitution plans or the establishment of a coca crop marketing monopoly would ever be successful in reducing production to the level demanded by the legal (chewing and leaf exports) market.

B. **Talking Points**
1. For over three years the US has been engaged in an intensified cooperative campaign with the GOB to suppress the production and illicit traffic in cocaine. The US has contributed about $8.5 million to this effort since 1975 and has plans for greatly increased contributions and expanded efforts during the forthcoming years.
2. Nevertheless, the flow of cocaine continues unabated. As much as 48 metric tons of cocaine hydrochloride and base valued at about $170 million may continue to be exported from Bolivia.
3. The actual and potential danger which this represents to Bolivian youth continues and the corruptive and distorting effects on Bolivia's young democracy of the flows of black money resulting from the traffic are on the increase.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ06238

- **Date:** July 21, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** NARCOTICS, DEMARCHE, PRESIDENT
