---
title: "Guest List For Dinner In Honor Of First Lady"
author: "He Speaks Excellent English."
date: "August 02, 1979"
editor: visual
cable-date: "August 02, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 7571"
cable-info: "Oct-01 Ara-11 Ads-00 Ss-15 Sso-00 Cpr-02 Opr-02 Sy-05 Usss-00 /038 W ------------------078622 022110z /62 O 021950z Aug 79"
cable-subject: "Guest List For Dinner In Honor Of First Lady"
cable-tags: "OVIP, PDIP, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ06628"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "VISITS, SOCIAL RECEPTIONS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Mrs. Carter's program includes buffet dinner at residence on Sunday, August 5, at 1900. We are planning to invite approximately ten Bolivian couples, though we cannot do so until the new president has been named.

2. Depending on outcome, we would invite Bolivian guests from following list, which capsules individuals' personal history and language ability. We would appreciate comment before selecting and sending invitations.

3. Jaime Paz Zamora. The UDP's vice presidential candidate, Paz, 40, is one of the three kingpins of the left-leaning MIR, which is often characterized as Bolivia's "party of the future." Paz is bright, articulate and personable--but he does not speak English.

4. Luis Ossio Sanjines. The MNR's vice presidential candidate, Ossio, 47, is a leader of the small but influential Christian Democratic Party. A lawyer with close ties to Bolivia's private mining sector, he is frank and easily approached. He does not speak English.

5. Carlos Iturralde Ballivian. Formerly ambassador to Malaysia and to the United States (1978), Iturralde, 39, is a wealthy mine-owner with close ties to the rightist Hugo Banzer sector. He holds degrees in economics and business administration from the University of North Dakota and New York University. Excellent English.

6. Mario Rolon Anaya. Until recently Bolivia's permanent representative to the United Nations, Rolon, 52, was vice presidential candidate on Hugo Banzer's right-wing ADN ticket. Although a lawyer, writer and educator of broad experience, he is not believed to speak English.

7. Walter Guevara Arze: Founder and guiding light of the small, relatively conservative PRA party, Guevara, 67, was elected Senator from Cochabamba on Victor Paz Estenssoro's MNR ticket. He has served in previous governments as Minister of Foreign Affairs, Ambassador to Israel and France and permanent representative to the United Nations. English is good.

8. Guillermo Bedregal Gutierrez. A veteran MNR politician, Bedregal, 52, was elected as a deputy from La Paz on the Paz Estenssoro slate. A lawyer and prolific author on political subjects, he could be appointed Minister of Planning. He does not speak English.

9. Carlos Antonio Carrasco. A former Minister of Education, Carrasco, 43, is a model technocrat who until recently was employed by the United Nations in Caracas. Elected to a deputy position from Cochabamba on Hernan Siles' UDP ticket, he speaks excellent English.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ06628

- **Date:** August 02, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** VISITS, SOCIAL RECEPTIONS