---
title: "[subject not available]"
author: "Stedman"
date: "August 23, 1974"
editor: visual
cable-date: "August 23, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 4008"
cable-info: "Oct-01 Iso-00 /002 W --------------------- 036438 R 231300z Aug 74"
cable-subject: "[subject not available]"
cable-tags: "ATRN, ASUP"
cable-ref: ""
cable-doc-number: "1974LAPAZ05466"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

Message Text




 231426Z


44
ACTION ST-01


INFO OCT-01 ISO-00 /002 W
           --------------------- 036438
R 231300Z AUG 74
FM AMEMBASSY LA PAZ
TO SECSTATE WASHDC 4008
PARKER HARLAND CHIEF OP AND C. BR. FSS GSA
FORT WORTH, TEXAS


UNCLAS LA PAZ 5466


E.OM 11652: N/A
TAGS: ATRN, ASUP
RE: ORDER 5104-450091 RQN 19G203-4071


SHIP WASHERS AND DRYERS VIA SURFACE FROM NEAREST PORT OF
DELIVERY IN LIEU CHARLESTON AFB.
MARK AMERICAN EMBASSY
5104-450091
LA PAZ, BOLIVIA
VIA MATARANI, PERU
STEDMAN








NNN




                     

                     


                                                       Message Attributes
Automatic Decaptioning: X
Capture Date: 01 JAN 1994
Channel Indicators: n/a
Current Classification: 
Concepts: n/a
Control Number: n/a
Copy: SINGLE
Draft Date: 23 AUG 1974
Decaption Date: 01 JAN 1960
Decaption Note:
Disposition Action: n/a
Disposition Approved on Date:
Disposition Authority: n/a
Disposition Case Number: n/a
Disposition Comment:
Disposition Date: 01 JAN 1960
Disposition Event:
Disposition History: n/a
Disposition Reason:
Disposition Remarks:
Document Number: 1974LAPAZ05466
Document Source: CORE
Document Unique ID: 00
Drafter: n/a
Enclosure: n/a
Executive Order: N/A
Errors: N/A
Film Number: D740233-0734
From: LA PAZ
Handling Restrictions: n/a
Image Path:
ISecure: 1
Legacy Key: link1974/newtext/t19740823/aaaaatkd.tel
Line Count: 37
Locator: TEXT ON-LINE, ON MICROFILM
Office: ACTION ST
Original Classification: 
Original Handling Restrictions: n/a
Original Previous Classification: n/a
Original Previous Handling Restrictions: n/a
Page Count: 1
Previous Channel Indicators:
Previous Classification: n/a
Previous Handling Restrictions: n/a
Reference: n/a
Review Action: RELEASED, APPROVED
Review Authority: elyme
Review Comment: n/a
Review Content Flags:
Review Date: 20 MAR 2002
Review Event:
Review Exemptions: n/a
Review History: RELEASED <20 MAR 2002 by reddocgw>; APPROVED <17 JAN 2003 by elyme>
Review Markings:


US Department of State

30 JUN 2005


Review Media Identifier:
Review Referrals: n/a
Review Release Date: n/a
Review Release Event: n/a
Review Transfer Date:
Review Withdrawn Fields: n/a
Secure: OPEN
Status: NATIVE
Subject: n/a
TAGS: ATRN, ASUP, BL
To: STATE
Type: TE
Markings:

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05466

- **Date:** August 23, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a