---
title: "Bolivian Aviation Gasoline Shortage Pass Usdoc Washdc Summary. Bolivia's Aviation Gasoline Requirments Now Exceed Quantity Esso, Bolkvia's Traditional Supplier, Willing Supply. Minfon Has Approached Ambassador To Seek Help In Convincing Esso It Should Meet Bolivia's Requirements. Ypfb Appears To Believe Contract It Has With Esso Entitles It To More Than It Now Receiving. Adequate Gas Supply Extremely Important For Bolivia's Economic And Political Stability. Action Requested: Department Communicate With Esso Head Office In Coral Gables To Suggest It Review Decision Against Increasing Supply To Bolivia Or, At Least, Cooperate By Helping Arrange Purchase And Delivery Additional Supply From Non Esso Source. End Summary."
author: "Stedman"
date: "June 28, 1974"
editor: visual
cable-date: "June 28, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 3533"
cable-info: "Oct-01 Iso-00 Aec-11 Aid-20 Cea-02 Ciae-00 Ciep-02 Come-00 Dode-00 Eb-11 Fpc-01 H-03 Inr-10 Int-08 L-03 Nsae-00 Nsc-07 Omb-01 Pm-07 Rsc-01 Sam-01 Sci-06 Sp-03 Ss-20 Str-08 Trse-00 Fea-02 Drc-01 /149 W --------------------- 086786"
cable-subject: "Bolivian Aviation Gasoline Shortage Pass Usdoc Washdc Summary. Bolivia's Aviation Gasoline Requirments Now Exceed Quantity Esso, Bolkvia's Traditional Supplier, Willing Supply. Minfon Has Approached Ambassador To Seek Help In Convincing Esso It Should Meet Bolivia's Requirements. Ypfb Appears To Believe Contract It Has With Esso Entitles It To More Than It Now Receiving. Adequate Gas Supply Extremely Important For Bolivia's Economic And Political Stability. Action Requested: Department Communicate With Esso Head Office In Coral Gables To Suggest It Review Decision Against Increasing Supply To Bolivia Or, At Least, Cooperate By Helping Arrange Purchase And Delivery Additional Supply From Non Esso Source. End Summary."
cable-tags: "ENRG, BL, BEXP"
cable-ref: ""
cable-doc-number: "1974LAPAZ04239"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "CIVIL AVIATION, ECONOMIC STABILITY, POLITICAL STABILITY, SUPPLIES, AGREEMENTS, TREATY SIGNATURE, JET FUEL,"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. MINISTER OF EXTERNAL RELATIONS GUZMAN RECENTLY TOLD AMBASSADOR
BOLIVIA RUNNING SHORT OF AVIATION GASOLINE BECAUSE ESSO REFUSED TO
DELIVER CONTRACT AMOUNTS. SAID SHORTFALL FROM REQUIREMENTS WOULD






 291410Z


BE DISASTROUS FOR MAINTENANCE OF INTERNAL SECURITY AND ECONOMY WHICH




                    

                   

DEPENDENT ON PISTON AIRCRAFT FOR PROVISION OF MEAT TO LA PAZ AND WIDE
VARIETY OF SUPPLIES TO MOST TOWNS IN BOLIVIA'S NORTH WHICH NOT
CONNECTED BY ROAD OR RAIL TRANSPORTATION TO "OUTSIDE". WE ALSO
KNOW GOB ALREADY HAS PLACED RESTRICTIONS ON AVGAS USERS, INCLUDING
MILITARY.


2. YPFB HAS SUPPLIED US WITH CONTRACT, DECREE, LETTERS, TELEXES
AND OTHER DOCUMENTS WHICH ESTABLISH SITUATION AS DESCRIBED BELOW.


3. CONTRACT BETWEEN ESSO AND YPFB SIGNED JAN 1, 1973, VALID FOR
THREE YEARS BEGINNING NOV 1, 1972, STATES YPFB WILL BUY 3,300,000
U.S. GALLONS OF 100/130 OCTANE AVIATION GASOLINE PER YEAR PLUS OR
MINUS 10 PERCENT ACCORDING TO YPFB'S NEEDS. CONTRACT ALSO STATES
THAT IF YPFB NEEDS TO BUY AVGAS FROM CAMPANA, ARGENTINA(AN ESSO
SUBSIDIARY).."ALL THE TERMS OF THE SELLERS OFFER EXPRESSED IN THE
LETTER OF AUGUST 24, 1972 (ANNEX 3) WOULD APPLY TO THIS PURCHASE.."
LETTER OF AUGUST 24, 1972 CONTAINS DELIVERY SCHEDULES THAT WORK OUT
TO 2,060,520 GALLONS PER YEAR THROUGH ARICA, SAME AMOUNT THROUGH
ANTOFAGASTA AND 951,012 THROUGH CAMPANA, ARGENTINA FOR 5,072,052
TOTAL. AS YPFB PURCHASED ALMOST ONE MILLION BARRELS FROM CAMPANA
IN JULY TO DECEMBER PERIOD OF 1973, IT APPEARS TO BELIEVE ALL PRO-
VISIONS OF AUGUST 24, 1972 LETTER IN FORCE INCLUDING TOTAL QUANTITY
INDICATED IN LETTER OF MORE THAN FIVE MILLION BARRELS PER YEAR.


4. YPFB HAS ASKED EMBASSY, AS FIRST PREFERENCE, TO SEEK REDRESS
AND BETTER UNDERSTANDING SITUATION BY APPEALING TO ESSO HEAD OFFICE.
RECOMMEND DEPARTMENT RAISE MATTER WITH ESSO 1) ON BASIS YPFB REDING
OF CONTRACT TERMS AND IMPORTANCE AVGAS HAS FOR ECONOMIC AND
POLITICAL STABILITY OF BOLIVIA AND/OR 2) BASIS PRESENTED BY RENE
URQUIDI, ESSO REP IN LA PAZ, THAT ESSO HAS ENJOYED 22 YEARS OF
VERY GOOD BUSINESS AS SINGLE SELLER OF AVGAS TO BOLIVIA AND SHOULD
DO EVERYTHING IN ITS POWER TO MEET BOLIVIA'S REQUIREMENTS TO MAIN-
TAIN THIS GOOD RELATIONSHIP.


5. ESSO CURRENTLY DELIVERY AT 4.7 MILLION GALLON RATE, ACCORDING
TO YPFB DATA, BUT ACCORDING URQUIDI THIS HIGH LEVEL WAS DUE TO
CONTROL ERROR ESSO ARGENTINA AND ESSO NOW INSISTING IT WILL NOT
DELIVER MORE THAN 3.3 MILLION GALLONS SPECIFIED IN CONTRACT PLUS
TEN PERCENT.








 291410Z


6. YPFB OFFICIAL SAID URGENT EXCHANGE OF PAST TWO DAYS HAD RESULTED
IN ESSO AGREEMENT TO DELIVER IMMEDIATELY EXTRA 10PERCENT (OR
330,000 GALLONS) ALLOWED UNDER TERMS OF CONTRACT WHICH WILL STAVE OFF
SERIOUS SHORTAGE UNTIL SEPTEMBER, 1974.


7. YPFB TELEXED JOSE VARELA, ESSO ARGENTINA IN BUENOS AIRES ON
JANUARY 21, 1974. REQUESTING 430,000 GALLONS PER MONTH (5,160,000
ANNUAL RATE) BEGINNING IN FEBRUARY FOR DELIVERY IN ANTOFAGASTA AND




                   

                   

ARICA. TELEX CITES SUSPENSION F DELIVERIES FROM ARGENTINA DUE TO
RAIL TRANSPORT DIFFICULTIES. VARELA REPLIED BY LETTER DATED MARCH
25 THAT FOLLOWING A CHECK WITH CORAL PETROLEUM CO.(ESSO REFINING
SUBSIDIARY IN ARUBA) THAT NOT POSSIBLE ACCEDE TO YPFB REQUEST AS
WORLD SUPPLY SITUATION PREVENTS IT. YPFB REPLIED IN APRIL 8
LETTER TO VARELA, REFERRING TO CLAUSE THAT BRINGS INTO FORCE
LETTER OF AUGUST 24, 1972, AGAIN CITING TRANSPORT DIFFICULTIES
FROMARGENTINA AND STATING THAT YPFB HAD BEEN RECEIVING 395,000
GALLONS PER MONTH (4,740,000 GAL. ANNUAL RATE) AND ONLY ASKING FOR
35,000 GALLONS PER MONTH(420,000 GAL. ANNUAL RATE) MORE.


8. ON OTHER HAND, CONTRACT AND LETTER OF AUGUST 24, 1972 CONTAIN
FORCE MAJEURE CLAUSES THAT WE THINK WOULD ALLOW ESSO TO ESCAPE
FROM ITS CONTRACT OBLIGATIONS IN VIEW OF WORLD SUPPLY SITUATION
AND ACTIONS TAKEN BY GOVERNMENTS OF OIL EXPORTING COUNTRIES.


9. URQUIDI NOTES THAT WHEN BOLIVIA RAISED PRICE ON ITS CRUDE TO
US$ 16 PER BARREL IN JANUARY, ARGENTINA RAISED PRICE ON AVGAS
SUPPLIED BY CAMPANA IN ROUGHLY PROPORTIONAL AMOUNT. URGUIDI
BELIEVES, ON OTHER HAND, THAT ESSO ARGENTINA SO OCCUPIED WITH
PROBLEMS RELATING TO ARGENTINA, URUGUAY AND PARAGUAY IT UNABLE TO
GIVE ADEQUATE CONSIDERATION TO BOLIVIAN PROBLEM.


10 DURING CONVERSATON WITH YPFB OFFICIAL, HE OPENED DOOR TO
POSSIBILITY OF SUPPLYING ESSO WITH BOLIVIAN CRUDE IN EXCHANGE FOR
ADDITIONAL AVGAS AND ALL AVGAS DELIVERIES TO ARICA AND ANTOFAGASTA.


11. YPFB SECOND PREFERENCE IS THAT SOME OTHER U.S FIRM SUPPLY
ADDITIONAL QUANTITY REQUIRED.AT DEPARTMENT'S DISCRETION, USDOC
SHOULD BE ASKED TO INFORM U.S. AVGAS SUPPLIERS TO CONTACT ING.
BELMONTE, YPFB, TELEX BX-5267. NOTE, HOWEVER, THAT ESSO'S FULL
COOPERATION WILL BE REQUIRED IN EFFICIENT SUPPLY OF AVGAS TO BOLIVIA
FROM ANY SOURCE OTHER THAN ESSO BECAUSE ESSO CONTROLS ESSENTIAL






 291410Z


SHIPPING AND TANK FARMS AT ARICA AND ANTOFAGASTA. ESSO PROBABLY
WILL HAVE TO MERGE OTHER SUPPLIES INTO ITS SHIPPING AND TANK
STORAGE CAPACITY. URQUIDI BELIEVES ESSO WILLING GIVE ITS FULL
COOPERATION.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04239

- **Date:** June 28, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** CIVIL AVIATION, ECONOMIC STABILITY, POLITICAL STABILITY, SUPPLIES, AGREEMENTS, TREATY SIGNATURE, JET FUEL,
