---
title: "Military Assistance For Bolivia: Fy 1976-1980 A. Jcs Msg 221205 Aug 74 B. Radio Call Between J5 & Cpt Garcia"
author: "Parker"
date: "August 26, 1974"
editor: visual
cable-date: "August 26, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 4026"
cable-info: "Oct-01 Ara-16 Iso-00 Sp-03 Ss-20 L-03 Inr-11 Sso-00 Inre-00 Mc-02 Rsc-01 Drc-01 /065 W --------------------- 063137 O 261730z Aug 74"
cable-subject: "Military Assistance For Bolivia: Fy 1976-1980 A. Jcs Msg 221205 Aug 74 B. Radio Call Between J5 & Cpt Garcia"
cable-tags: "MARR, MASS, MMOL, MORG, MPOL, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ05497"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "28 MAY 2004"
cable-concepts: "MILITARY EQUIPMENT, DATA, MILITARY ASSISTANCE PROGRAMS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. THE FOLLOWING INFORMATION AS ADDITIONAL JUSTIFICATION
FOR MILITARY ASSISTANCE IN FY 1976 - 1980 FOR BOLIVIA
IS PROVIDED PER A ABOVE. THIS INFORMATION IS INTENDED TO
REINFORCE AND SUPPLEMENT THAT PROVIDED IN THE SECURITY
ASSISTANCE POM, FY76-80 (U)
A. (S) MATERIEL, ARMY.
(1) ALTHOUGH THE FIVE "TIPO" REGIMENTS ARE FULLY FUNDED
IN 76, FOLLOW-ON-SUPPORT FOR THIS EQUIPMENT IS REQUIRED
FOR THE PERIOD THRU FY80.
(2) DELAYS IN DEVELOPMENT OF THE SIGNAL UNIT TOE'S
HAS DELAYED PROGRAMMING OF REQUIRED COMMUNICATIONS
EQUIPMENT. IT IS ANTICIPATED THAT THIS WILL BE PROGRAMMED
1977-1980.
(3) THE ENGINEER EQUIPMENT THAT HAS BEEN PROGRAMMED FOR
FY77-78-79 IS REQUIRED FOR THE CONTINUED DEVELOPMENT AND
IMPROVEMENT OF THE COUNTRY'S ROAD NETWORK.
(4) A COLONIZATION PROJECT IS SANTA CRUZ DEPARTMENT BY
THE BOLIVIAN ARMY WILL ENTER THE PLANNING STAGE FY76-76
AND THE EXECUTION STATE DURING FY 76-77. THE BOLIVIAN
  SECRET


  SECRET


 262014Z


ARMY HAS REQUESTED SUPPORT IN THIS DEVELOPMENT PROJECT




                               

                   

PRIMARILY WITH EQUIPMENT AND TRAINING. THE ARMY IS DEVELOPING
A MOBILE MEDICAL BDE. TO SUPPORT THIS PROJECT AND ANOTHER
FOR SUPPORTING THE BENI REGION UNDER THE JOINT CIVIC ACTION
PROGRAM. THESE 2 BDES WILL NEED EQUIPMENT.
(5) WITH THE PLANNED PHASE DOWN OF EXPENSIVE DOLLAR EQUIPMENT
ITEMS FROM GRANT AID SERIOUS ATTENTION MUST BE GIVEN TO
PROVIDING FUNDS FOR TRAINING AIDS AND SUPPORT MATERIAL
TO DEVELOP A TRAINING BASE IN BOLIVIA.
(6) THE LACK OF FUNDS HAS DELAYED THE DEVELOPMENT OF THE
SANTA CRUZ AND CAMIRI MAINTENANCE CENTERS. WITHOUT THESE
CENTERS THE BOLIVIAN ARMY WILL NOT BE ABLE TO SUPPORT THE
THE EQUIPMENT CURRENTLY BEING RECEIVED OR THAT PROGRAMMED.
ADDITIONALLY THE DEVELOPMENT OF THE PROPOSED ENGINEER
MAINTENANCE CENTER FOR LA PAZ WILL NEED INCREASED MAP
SUPPORT IN VIEW OF THE PROGRAMMED AND PROJECTED FMS
ACQUISITIONS TO BE MADE BY THE BOLIVIAN ARMY.
B. MATERIEL AIR FORCE PROGRAM. IN ADDITION TO THE JUSTIFICATION
GIVEN IN THE POM, THE FOLLOWING IS SUBMITTED. IT IS IMPORTANT
THAT THERE BE FINANCING FOR THE ABOVE PROGRAM YEARS
FOR THE BOLIVIAN AIR FORCE (BAF). THE PROGRAM INCLUDES
SUPPORT ITEMS ESSENTIAL FOR BAF SELF-SUFFICIENY. TO
ELIMINATE OR REDUCE ASSISTANCE FOR THIS PROGRAM WOULD
DESTROY THE PROGRESS WHICH HAS BEEN ATTAINED DURING THE
PAST FEW YEARS. THIS PROGRAM INCLUDES ONLY 7 AIRFRAMES
(6 EA A-37B AND 1 EA UH-1H) WHICH HAVE BEEN CONSIDERED
ESSENTIAL TO THE INTERNAL SECURITY OF THE COUNTRY. AS
STATED IN THE POM, THE BAF IS PROCEEDING WITH THE ESTABLISHMENT
OF AN AIRCRAFT MAINTENANCE CENTER INNCOCHABAMBA BOLIVIA.
AFTER BUDGETING FOR HANGERS, LIGHTING EQUIPMENT, RUNWAYS,
PARKING RAMPS ETC. BAF HAS NOTHING LEFT FOR EQUIPMENT FOR
THE MAINTENANCE SHOPS. ALTHOUGH NO COMMITMENTS HAVE BEEN
MADE AT THIS LEVEL, SHOP EQUIPMENT HAS BEEN PROGRAMMED
RHOUGH GRANT AID DURING THIS TIME FRAME. WE BELIEVE THAT
THE ONLY WAY FOR THE BAF TO PROJECT ITSELF OUT OF ANTIQUITY IS
BY ESTABLISHING A SOUND MAINTENANCE/SUPPLY/LOGISTICS
SYSTEM CAPABLE OF SELF-SUFFICIENCY.
C. MATERIEL, NAVY. DURING TIME-FRAME FY76-80 MODERNICATION
OF NAVAL UNITS THROUGH THE PROVISION OF LIMITED INTERNAL
DEFENSE WEAPONS AND EQUIPMENT IS PROGRAMMED. FAILURE TO
PROVIDE THIS MATERIAL WILL SERIOUSLY LIMIT THE CAPABILITY
  SECRET


 SECRET


 262014Z


OF NAVAL UNITS IN THE BENI REGION TO ASSIST IN REGIONAL
DEVELOPMENT PROJECTS DISCUSSED IN THE POM. IT SHOULD BE
NOTED, HOWEVER, THAT TERMINATION OF MAP GRANT AID IS
ANTICIPATED IN GRADUATED BU LARGE INCREMENTS BEGINNING
IN FY78 AND PHASING OUR COMPLETELY IN FY80.
2. THE AMBASSADOR CONCURS IN VALIDITY OF CONTINUED MILITARY
ASSISTANCE FOR REASONABLE PROJECTS IN FY 7/-80 PERIOD AND
NOTES THAT IF THE BOLIVIAN FINANCIAL SITUATION WERE TO




                   

                 

CONTINUE TO IMPROVE, FRANT ASSISTANCE COULD BE REDUCED
PROVIDED THAT AN ADEQUATE LEVEL OF FMS CREDITS IS
SUBSTITUTED.
PARKER



 SECRET

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05497

- **Date:** August 26, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 28 MAY 2004

- **Concepts:** MILITARY EQUIPMENT, DATA, MILITARY ASSISTANCE PROGRAMS
