---
title: "Status Of Bolivian Zoological Suppliers"
author: "Stedman"
date: "August 21, 1974"
editor: visual
cable-date: "August 21, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3983"
cable-info: "Oct-01 Ara-16 Iso-00 Sci-06 Smi-01 L-03 Coa-02 Drc-01 Rsc-01 /039 W --------------------- 008390 R 211410z Aug 74"
cable-subject: "Status Of Bolivian Zoological Suppliers"
cable-tags: "ETRD, SENV, BL, US"
cable-ref: "STATE 171823"
cable-doc-number: "1974LAPAZ05392"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "ANIMALS, EXPORTS, TRADE LAW, SPECIES PROTECTION, ZOOLOGY, BUSINESS FIRMS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. LOCAL REPRESENTATIVE BOLIVIAN ZOOLOGICAL SUPPLIERS, LTDA.
TOLD EMBASSY THAT COMPANY EXPORTS ANIMALS FROM BOLIVIA AND
INTERESTED IN EFFECTING EXCHANGES OF ANIMALS BETWEEN U.S.
AND BOLIVIA. HE DENIED THAT FIRM HAS ANY CONNECTION WITH BOLIVIAN
GOVERNMENT.


2. OFFICIAL OF BOLIVIAN AGRICULTURAL MINISTRY STATED THAT HE
KNOWS OF SUBJECT COMPANY AND SEVERAL SIMILAR ENTERPRISES.
HE AVOIDED CHARACTERIZING BOLIVIAN ZOOLOGICAL SUPPLIERS
EXCEPT TO EMPHASIZE IT HAS NO RPT NO "OFFICIAL STATUS." HE
ADDED THAT INCREASING PRESSURE FROM LOCAL COMPANIES TO EXPORT
LIVE ANIMALS HAS CAUSED GOB TO ACCELERATE EFFORTS TO ESTABLISH
LAWS CONTROLLING THIS ACTIVITY. HE SAID NEW LAW AND REGULATIONS
WOULD BE PUBLISHED IN NEXT SEVERAL MONTHS.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05392

- **Date:** August 21, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** ANIMALS, EXPORTS, TRADE LAW, SPECIES PROTECTION, ZOOLOGY, BUSINESS FIRMS
