---
title: "Rector And Vice-Rector Of Umsa Resign"
author: "Stedman"
date: "June 19, 1974"
editor: visual
cable-date: "June 19, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3436"
cable-info: "Oct-01 Iso-00 Pm-07 Nsc-07 Sp-03 Ss-20 Rsc-01 Ciae-00 Dode-00 Inr-10 Nsae-00 Pa-04 Usia-15 Prs-01 Drc-01 Aid-20 Acda-19 Cu-04 /133 W --------------------- 078073 R 191302z Jun 74"
cable-subject: "Rector And Vice-Rector Of Umsa Resign"
cable-tags: "PINT BL"
cable-ref: "LA PAZ 3504"
cable-doc-number: "1974LAPAZ03970"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "UNIVERSITIES, STUDENT DEMONSTRATIONS, PERSONNEL RESIGNATIONS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. SURPRISE RESIGNATIONS OF RECTOR AND VICE-RECTOR OF
SAN ANDRES UNIVERSITY (UMSA) IN LA PAZ DURING EARLY MORNING
HOURS OF JUNE 18 MAY OPEN WAY TO INTERIM RESOLUTION OF
UNIVERSITY POLITICAL PROBLEM. IN PAST TEN DAYS, PRESS AND RADIO
ASSOCIATION OF BOLIVIA HAS BEEN ACTING AS INTERMEDIARY BETWEEN
EDUCATION OFFICIALS AND UNIVERSITY STUDENTS IN EFFORT TO
SEEK COMMON GROUNDS FOR AGREEMENT. THIS MEDIATION EFFOR,
HOWEVER, WAS OPPOSED BY UMSA AUTHORITIES IN PERSONS OF
FALANGE RECTOR MARIO AGUILAR AND MNR VICE-RECTOR GONZALO
SANCHEZ DE LORIA. STUDENT-LED INTER-FACULTY COMMITTEE ALSO
HAD INDICATED THAT UNIVERSITY STUDENT STRIKE BEGUN ON MAY 21
WOULD NOT END UNTIL RECTOR AGUILAR RESIGNED HIS POST. AT
PRESENT, UNIVERSITY STUDENTS CONTINUE ON STRIKE AT UMSA AND IN
SUCRE, COCHABAMBA AND POTOSI.


2. NOW THAT CONTROVERSIAL UMSA RECTOR HAS BEEN REMOVED FROM
SCENE, POSSIBLE BASIS FOR A TRUCE MAY BE PROVIDED BY FIVE-
POINT AGREEMENT REACHED BY STUDENTS AND NATIONAL COUNCIL ON
HIGHER EDUCATION (CNES) JUNE 16. BOTH PARTIES AGREED TO NEED
FOR MODIFICATION OF 1972 FUNDAMENTAL LAW OF BOLIVIAN UNIVERSITY






 191441Z


BY A NEW SUPREME DECREE, FOLLOWING WHICH A UNIVERSITY ASSEMBLY




                        

                 

(CLAUSTRO UNIVERSITARIO) COULD MEET TO SELECT NEW ACEDEMIC
AUTHORITIES. AGREEMENT ALSO WAS REACHED TO HOLD PUBLIC EX-
AMINATIONS OF COMPETENCE FOR CURRENT TEACHING PERSONNEL IN
BOLIVIAN UNIVERSITIES, MANY OF WHOM OBTAINED THEIR POSTS
THROUGH POLITICAL CONNECTIONS. STUDENTS AND EDUCATION
AUTHORITIES ALSO DETERMINED THAT ELECTIONS FOR STUDENT
REPRESENTATIVES SHOULD BE HELD IN NEAR FUTURE, AND IN MEANTIME
ANNOUNCED CLOSURE OF CUB AND FUL OFFICES SINCE LEADERS OF
THESE BODIES WERE NOT ELECTED TO THEIR POSTS AND THUS LACK
OFFICIAL UNIVERSITY RECOGNITION.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03970

- **Date:** June 19, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** UNIVERSITIES, STUDENT DEMONSTRATIONS, PERSONNEL RESIGNATIONS