---
title: "Secretary's Initiative On Double Taxation Treaties State 162751"
author: "Stedman"
date: "July 31, 1974"
editor: visual
cable-date: "July 31, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3791"
cable-info: "Oct-01 Ara-16 Iso-00 Sp-03 Aid-20 Nsc-07 Rsc-01 Ciep-03 Trse-00 Ss-20 Str-08 Omb-01 Cea-02 L-03 H-03 Come-00 Opic-12 Ciae-00 Inr-11 Nsae-00 Drc-01 /123 W --------------------- 055683 R 311837z Jul 74"
cable-subject: "Secretary's Initiative On Double Taxation Treaties State 162751"
cable-tags: "EFIN, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ04927"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "TAX AGREEMENTS, DOUBLE TAXATION, NEGOTIATIONS, FOREIGN INVESTMENTS, TAX INCENTIVES"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. NEW MINFIN CASTILLO AND DIRECTOR INDEF (EXTERNAL FINANCE
INSTITUTE) ORMACHEA EXPRESSED INTEREST IN NEGOTIATING DOUBLE
TAXATION TREATY ON GROUNDS THAT IT WOULD HELP STIMULATE US
INVESTMENT. ADCM SAID USG UNABLE NEGOTIATE TAX-SHARING CREDIT
PROVISIONS OR OTHER TYPES INVESTMENT INCENTIVES, BUT MINFIN AND
ORMACHEA STILL BELIEVED DOUBLE TAXATION TREATY WOULD OPERATE AS
INVESTMENT INCENTIVE.


2. COMMENT: WOULD APPRECIATE JUDGEMENT USG TAX EXPERTS ON
WHETHER STANDARD DOUBLE TAXATION TREATY SHOULD BE REGARDED
BY GOB AS INCENTIVE TO INVEST IN BOLIVIA. US INVESTMENT IN
BOLIVIA NOW RISING FOLLOWING PERIOD OF DECLINE.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04927

- **Date:** July 31, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** TAX AGREEMENTS, DOUBLE TAXATION, NEGOTIATIONS, FOREIGN INVESTMENTS, TAX INCENTIVES
