---
title: "Spanish Version Of A Speec On The Andes Pact"
author: "Morton"
date: "March 28, 1974"
editor: visual
cable-date: "March 28, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "Usinfo WashDC"
cable-info: "Oct-01 Iso-00 Pa-01 Inr-01 /005 W --------------------- 127913 R 281823z Mar 74"
cable-subject: "Spanish Version Of A Speec On The Andes Pact"
cable-tags: "SCUL, XM, ANDES PACT"
cable-ref: ""
cable-doc-number: "1974LAPAZ01919"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "COMMUNITY RELATIONS, ECONOMIC COOPERATION, SPEECHES, LANGUAGE SERVICES"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


La Paz.- Con el propósito de acelerar la integración educativa, cultural y científica en el área que comprende el Pacto Andino, ayer (miércoles 27) fueron inauguradas las labores de la Quinta Reunión de Ministros de Educación de la Subregión Andina y en la que también participan representantes especiales de la OEA, UNESCO, BID y otras entidades internacionales.

En la ceremonia de inauguración, el Ministro de Educación de Bolivia, Doctor Mario Serrate Ruiz, afirmó que el Convenio "Andrés Bello", como elemento complementario de los organismos de integración del Pacto Andino, "está obligado a coadyuvar en la solución de los problemas de recursos humanos del área, incorporando a la inmensa mayoría de marginados al proceso de desarrollo, por los beneficios de la educación."

Luego, el Ministro de Educación del Perú, General Alfredo Carpio Becerra, en representación de las misiones participantes, hizo resaltar la necesidad de "emplear todos nuestros recursos para realizar un pleno desarrollo económico, social y cultural". "Por eso - agregó - el Gobierno Revolucionario del Perú considera que no debe distraerse o malgastarse el dinero del pueblo en una carrera armamentista en la que solo pueden estar interesados y salir gananciosos los mercaderes de la guerra".

Finalmente, el Presidente de Bolivia, General Hugo Banzer Suárez, abogó por la urgencia de modificar los sistemas de educación "a fin de preparar mejor y más rápidamente a los jóvenes que pugnan por aportar sus energías y su capacidad creadora a la tarea común de acelerar el progreso de nuestros pueblos".

Después de la ceremonia de inauguración, los Ministros de Colombia, Chile, Ecuador, Perú, Venezuela y Bolivia y sus delegaciones iniciaron sus deliberaciones sobre un amplio temario, las mismas que se prolongarán hasta mañana viernes.

Morton

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01919

- **Date:** March 28, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** COMMUNITY RELATIONS, ECONOMIC COOPERATION, SPEECHES, LANGUAGE SERVICES
