---
title: "Text Of Bolivian Access To Sea (Spanish)"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "October 31, 1979"
editor: visual
cable-date: "October 31, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 8952"
cable-info: "Oct-01 Ads-00 Ss-15 Sso-00 Nsce-00 Ciae-00 Inr-10 Nsae-00 Inre-00 L-03 Sph-01 Spta-02 Io-15 /062 W ------------------086414 311454z /43 O 311441z Oct 79"
cable-subject: "Text Of Bolivian Access To Sea (Spanish)"
cable-tags: "OAS"
cable-ref: ""
cable-doc-number: "1979LAPAZ09290"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "TEXT, LANDLOCKED COUNTRIES, ACCESS TO PORTS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Following is Spanish text of Bolivia access to the sea as approved by the General Committee.

"Acceso de Bolivia al Oceano Pacifico

(Proyecto de resolución aprobado por la Comisión General en su segunda sesión celebrada el 26 de octubre de 1979 y revisado por la Comisión de Estilo)

La Asamblea General,

Declara:

1. Que es de interés hemisférico permanente encontrar una solución equitativa mediante la cual Bolivia obtenga acceso soberano y útil al Oceano Pacifico, y

2. Que para lograr el objetivo señalado en el punto anterior y consolidar una paz estable que estimule el progreso económico y social en el área de América directamente afectada por las consecuencias del enclaustramiento de Bolivia, el noveno periodo ordinario de sesiones de la Asamblea General de la Organización de los Estados Americanos, con espíritu de fraternidad e integración americana,

Resuelve:

1. Recomendar a los estados a los que este problema concierne más inmediatamente, que inicien negociaciones encaminadas a dar a Bolivia una conexión territorial libre y soberana con el Oceano Pacifico. Tales negociaciones deberán tomar en cuenta los derechos e intereses de las partes involucradas y podrían considerar, entre otros elementos, la inclusión de una zona portuaria de desarrollo multinacional integrado, y así mismo tener en cuenta el planteamiento boliviano de no incluir compensaciones territoriales."

***

#### Message Attributes

- **Document Number:** 1979LAPAZ09290

- **Date:** October 31, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** TEXT, LANDLOCKED COUNTRIES, ACCESS TO PORTS