---
title: "Minister Mining Signs Mineral Exploration Agreement With French Company"
author: "Stedman"
date: "June 26, 1974"
editor: visual
cable-date: "June 26, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3502"
cable-info: "Oct-01 Iso-00 Eb-11 Int-08 Come-00 Trse-00 L-03 Eur-25 Sci-06 Omb-01 Aid-20 Ciae-00 Inr-10 Nsae-00 Rsc-01 Drc-01 /107 W --------------------- 053126 R 261421z Jun 74"
cable-subject: "Minister Mining Signs Mineral Exploration Agreement With French Company"
cable-tags: "EMIN, BL, BGEN"
cable-ref: ""
cable-doc-number: "1974LAPAZ04139"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "EXPLORATION, AGREEMENTS, TREATY SIGNATURE, TECHNICAL ASSISTANCE, BUSINESS FIRMS, MINING INDUSTRY,"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. ON JUNE 25 MINMINING JACQUES BOULANGER, REPRESENTATIVE OF
BUREAU DE RESERCHES GEOLOGIQUES ET MINIERES, BRGM AND FRANCOIS
CHENEVIER REPRESENTATIVE FRENCH MINISTRY OF MINES SIGNED GENERAL
MINERAL EXPLORATION AGREEMENT (LETTER OF INTENT) IN NATIONAL
RESERVE AREAS WHICH SCHEDULED TO BE RATIFIED WITHIN 60 DAYS
FROM JUNE 25.


2. MINERAL EXPLORATION AREA NOT SPECIFIED BUT LIKELY TO BE
NORTH OR SOUTH LIPEZ AREA, DEPARTMENT POTOSI, SOUTHWESTERN
BOLIVIA WHICH CONTAINS COPPER, ANTIMONY, LEAD, SILVER, TIN,
AND BISMUTH MINERALIZATION.


3. AFTER FIXED EXPLORATION PERIOD, AT NO COST TO BOLIVIA
AND UNDER CONDITIONS YET TO BE FIXED BY SUBSEQUENT CONTRACTS
BRGM WILL CONTRIBUTE ITS TECHNICAL COOPEATION IN EXPLORATION,
EXPLOITATION, AND SALES OF MINERALS MINED THROUGH MIXED COMPANY
WHICH WILL BE OWNED OVER 50 PERCENT BY BOLIVIAN GOVERNMENT.
COMIBOL LIKELY TO BE BOLIVIAN ASSOCIATE IN MIXED COMPANY.


4. COMMENT: ALTHOUGH GENERAL AGREEMENT DOES NOT MENTION IT, IT
IS FELT IN MINISTRY MINING CIRCLES THAT EXPENSES INCURRED IN




 271448Z


ADVANCED EXPLORATION AND DEVELOPMENT WILL BE DEDUCTIBLE FROM
SUBSEQUENT MINING OPERATIONS. TRANSLATION OF GENERAL AGREEMENT




                        

                  

WILL BE SENT BY AIRGRAM.


5. EMBASSY WILL FOLLOW EVENTS CLOSELY WITH PURPOSE OF FINDING NEW
INVESTMENT OPPORTUNITIES TO AMERICAN COMPANIES INTERESTED IN MINERAL
INDUSTRY. AT PRESENT NO SUBSTANTIVE NEGOTIATIONS HAVE BEEN SIGNED
SUCH AS MINIMUM REQUIRED INVESTMENT AND TOTAL TIME OF EXPLORATION,
DEVELOPMENT, PRODUCTION, OR DURATION OF CONTRACT.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04139

- **Date:** June 26, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** EXPLORATION, AGREEMENTS, TREATY SIGNATURE, TECHNICAL ASSISTANCE, BUSINESS FIRMS, MINING INDUSTRY,
