---
title: "Pl 480, Title I: Cup Payment"
author: "Brewin"
date: "June 07, 1974"
editor: visual
cable-date: "June 07, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3352"
cable-info: "Oct-01 Ara-16 Iso-00 Fse-00 Abf-01 Agr-20 Aid-20 Eb-11 Rsc-01 Drc-01 /071 W --------------------- 075752 R 072109z Jun 74"
cable-subject: "Pl 480, Title I: Cup Payment"
cable-tags: "EAID, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ03729"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "AGREEMENTS, PL 480 TITLE 1, FOREIGN EXCHANGE TRANSACTIONS, DEBT REPAYMENTS, CHECKS (MONEY)"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


Message Text




 072201Z


13
ACTION TRSE-00


INFO OCT-01 ARA-16 ISO-00 FSE-00 ABF-01 AGR-20 AID-20 EB-11


   RSC-01 DRC-01 /071 W
            --------------------- 075752
R 072109Z JUN 74
FM AMEMBASSY LA PAZ
TO SECSTATE WASHDC 3352


UNCLS LA PAZ 3729


E.O. 11652: N/A
TAGS: EAID, BL
SUBJ: PL 480, TITLE I: CUP PAYMENT


REF: STATE 97359


ONE JUNE 7 EMBASSY RECEIVED FROM TREASURER OF BOLIVIA CHECK
NO. 814636 IN THE AMOUNT OF $B5,629,719.66 EQUIVALENT TO
$JS 275,966.65 UNDER CUP PROVISION OF DECEMBER 20, 1972,
PL 480 AGREEMENT.
BREWIN








NNN




                        

                     


                                                       Message Attributes
Automatic Decaptioning: X
Capture Date: 01 JAN 1994
Channel Indicators: n/a
Current Classification: 
Concepts: AGREEMENTS, PL 480 TITLE 1, FOREIGN EXCHANGE TRANSACTIONS, DEBT REPAYMENTS, CHECKS (MONEY)
Control Number: n/a
Copy: SINGLE
Draft Date: 07 JUN 1974
Decaption Date: 01 JAN 1960
Decaption Note:
Disposition Action: n/a
Disposition Approved on Date:
Disposition Authority: n/a
Disposition Case Number: n/a
Disposition Comment:
Disposition Date: 01 JAN 1960
Disposition Event:
Disposition History: n/a
Disposition Reason:
Disposition Remarks:
Document Number: 1974LAPAZ03729
Document Source: CORE
Document Unique ID: 00
Drafter: n/a
Enclosure: n/a
Executive Order: N/A
Errors: N/A
Film Number: D740147-0106
From: LA PAZ
Handling Restrictions: n/a
Image Path:
ISecure: 1
Legacy Key: link1974/newtext/t19740665/aaaacehs.tel
Line Count: 37
Locator: TEXT ON-LINE, ON MICROFILM
Office: ACTION TRSE
Original Classification: 
Original Handling Restrictions: n/a
Original Previous Classification: n/a
Original Previous Handling Restrictions: n/a
Page Count: 1
Previous Channel Indicators: n/a
Previous Classification: n/a
Previous Handling Restrictions: n/a
Reference: STATE 97359
Review Action: RELEASED, APPROVED
Review Authority: martinjw
Review Comment: n/a
Review Content Flags:
Review Date: 26 AUG 2002
Review Event:
Review Exemptions: n/a
Review History: RELEASED <26 AUG 2002 by PhilliR0>; APPROVED <08 JAN 2003 by martinjw>
Review Markings:


US Department of State

30 JUN 2005


Review Media Identifier:
Review Referrals: n/a
Review Release Date: n/a
Review Release Event: n/a
Review Transfer Date:
Review Withdrawn Fields: n/a
Secure: OPEN
Status: NATIVE
Subject: PL 480, TITLE I: CUP PAYMENT
TAGS: EAID, BL
To: STATE
Type: TE
Markings:

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03729

- **Date:** June 07, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** AGREEMENTS, PL 480 TITLE 1, FOREIGN EXCHANGE TRANSACTIONS, DEBT REPAYMENTS, CHECKS (MONEY)
