---
title: "\"Early Warning\": Construction Of Zinc Smelter"
author: "Stedman"
date: "February 04, 1974"
editor: visual
cable-date: "February 04, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2154"
cable-info: "Oct-01 Iso-00 Eb-05 Rsc-01 Drc-01 Eur-06 Ea-07 /031 W --------------------- 059451 R 042014z Feb 74"
cable-subject: "\"Early Warning\": Construction Of Zinc Smelter"
cable-tags: "BEXP, ETRD, EMIN, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ00742"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "ZINC, CONSTRUCTION, MINING INDUSTRY"
---


# DEPARTMENT OF STATE TELEGRAM

**UNCLASSIFIED**

::: {.cable-meta}
:::


1.  On January 30, local representative of Engelhard Minerals and Chemicals Corporation stated that he was recommending to his firm to make an offer to GOB to construct smelter under mixed enterprise arrangement with ENAF. Russian, German, Japanese, Brazilian, French, Polish and Czechoslovak offers reportedly also likely to be made.
2.  **Comment:** According to Singmaster and Bryer (consultants to U.S. Steel and COMIBOL) report of 1969, there is no technical reason why an electrolytic zinc plant could not be installed and operated successfully in Bolivia despite problems of high altitude. However, report also stated that economic success of the zinc refinery depended on electric power costs, sufficient reserves for guaranteed delivery of zinc concentrates for 20 years, and guaranteed market for sulphuric acid produced, which due to high transportation costs, would have to be marketed internally. For zinc refinery with annual output of 33,600 metric tons of zinc, 265,440 pounds of cadmium, and 360 tons of copper residues, 61,000 metric tons of sulphuric acid would be produced. Embassy believes that whether present economics of smelter are justifiable or not, smelter will be built in any event.
3.  **Action requested:** USDOC is requested to encourage potentially interested U.S. firms to communicate directly with Minister of Mining and Metallurgy, Raul Lema Patino, Ministero de Mineria y Metalurgia, 1769 Avenida 16 de Julio, La Paz, Bolivia and copy to Empresa Nacional de Fundiciones (ENAF), Casilla 4298 La Paz Bolivia. ENAF's cable address is "ENAFBOL", La Paz: its telex numbers are BX5271 and ITT 3560090.
4.  The tender will be reported to USDOC when issued.

------------------------------------------------------------------------

#### Message Attributes

-   **Document Number:** 1974LAPAZ00742

-   **Date:** February 04, 1974

-   **Classification:** UNCLASSIFIED

-   **Declassified:** 01 JAN 1960

-   **Concepts:** ZINC, CONSTRUCTION, MINING INDUSTRY
