---
title: "Bolivian Tariff Schedule Refs: (A) State 060395; (B) State 092708"
author: "Stedman"
date: "May 08, 1974"
editor: visual
cable-date: "May 08, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3025"
cable-info: "Oct-01 Ara-16 Iso-00 Eb-11 Ciae-00 Inr-10 Nsae-00 Pa-04 Rsc-01 Usia-15 Prs-01 Sp-03 Tar-02 Trse-00 Agr-20 Drc-01 /085 W --------------------- 081076 R 082011z May 74"
cable-subject: "Bolivian Tariff Schedule Refs: (A) State 060395; (B) State 092708"
cable-tags: "ETRD, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ02047"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "COMMITTEES, ELECTION CANDIDATES, INTERNATIONAL ORGANIZATIONS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1.  **Press report cited reftel a not rpt not correct.** Gob "Arancel Aduanero de Importaciones 1972" still in effect and addendum of February 28, 1973 has expired.

2.  **Two temporary exceptions to 1972 Arancel have been put in effect in 1974.** First, Supreme Decree No. 11345 of February 13, 1974 created sliding percentage reductions of normal customs rates for raw materials and parts needed by Bolivian industries. Each exemption must be approved separately. Second, Supreme Decree 11358 of February 22, 1974 suspended duties (but not all fees) on importation certain basic food commodities including powdered milk, rice, vegetable oil, lard, wheat flour, tuna fish, salmon and sardines. Original decree was for 90 days which was subsequently extended another 180 days, that is to November 18, 1974.

3.  **Three to five percent sales tax on imports still in effect but also suspended for these basic food items.** Consular fees do not appear in tariff columns. Embassy pouching above decrees and consular fee schedule.

4.  **Bolivia's tariff regime will be described in greater detail in post's answer to Department's A-3164 of April 19 which now being prepared.**

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02047

- **Date:** May 08, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** COMMITTEES, ELECTION CANDIDATES, INTERNATIONAL ORGANIZATIONS