---
title: "Commercial Action Program Fy 74"
author: "Stedman"
date: "April 04, 1974"
editor: visual
cable-date: "April 04, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2732"
cable-info: "Oct-01 Iso-00 Eb-11 Per-05 Mms-03 Come-00 Ss-20 Sp-03 Abf-01 Drc-01 Rsc-01 /066 W --------------------- 088721 R 041943z Apr 74"
cable-subject: "Commercial Action Program Fy 74"
cable-tags: "BEXP, AFSP"
cable-ref: "STATE 235324 OF 11/30/73 STATE 240150 OF 12/8/73 LA PAZ 7565 OF 12/17/73"
cable-doc-number: "1974LAPAZ02080"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. Recent commercial programs instituted for ARA posts make it imperative that additional FSL clerk-typist position be authorized La Paz commercial section. Present FSL economic/commercial staff of four serves four officers including COMATT. Of these four only one qualified as typist and workload for other econ officers is such that she cannot RPT not handle COMATT typing.

2. Major areas of activity for first three months of 1973 and 1974 reflect following increase:

              1973   1974
  A. Outgoing WTDRs       21     79
  B. US Visitors     31     75
  C. Local Visitors     214    254
  D. ADS           3   13
  E. Private Trade Opportunities 14       62
  F. GOB Tenders       3     13

3. Trade promotion requires active participation of members of commercial section. Prior to arrival of new COMATT, local members seldom left office to promote US commercial services. From March 1-27 visits to private and public firms totaled 72. It is impossible to keep staff busy on outside with promotional work when there is insufficient clerical help to take care of resulting paperwork. Cannot RPT not stress too strongly need for this additional FSL position. Feel great US commercial gains can be made in Bolivia and full intent of CAP realized with adequate help. Would appreciate telegraphic authorization this essential FSL position.

4. Post has reviewed its program positions in an attempt to free some other position for commercial assistance. However, reduction of two program positions this post by Department in January has already reduced staffing to absolute bare minimum.
Stedman

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02080

- **Date:** April 04, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a
