---
title: "Gob Increases Wages And Selected Food Prices. Summary: Gob Announced Monday Morning January 21, 1974 Increases In Prices Of Rice, Sugar, Wheat Flour, Bread, Coffee, Noodles, Amounting To Approximately 100 Percent Over Previous Officially Quoted Prices. However, In Terms Of Effective Market Prices Increases Were Only About 20 Percent Higher, Except For Bread Which Was Subsidized By Gob. Effective Increase For Bread, Including Further Pan De Batalla Weight Decrease, Was Approximately 100 Percent. Wages And Salaries Increased By Up To 47 Percent For Both Private And Public Employees By Monthly Bonus Of 400 Pesos. End Summary."
author: "Stedman"
date: "January 21, 1974"
editor: visual
cable-date: "January 21, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2005"
cable-info: "Oct-01 Iso-00 Spc-03 Aid-20 Eb-11 Nsc-10 Rsc-01 Ciep-02 Trse-00 Ss-20 Str-08 Omb-01 Cea-02 Ciae-00 Come-00 Frb-02 Inr-10 Nsae-00 Xmb-07 Opic-12 Lab-06 Sil-01 Dode-00 Pm-07 H-03 L-03 Pa-04 Prs-01 Usia-15 Fea-02 Sci-06 Agr-20 Int-08 Drc-01 /207 W --------------------- 039761 R 212015z Jan 74"
cable-subject: "Gob Increases Wages And Selected Food Prices. Summary: Gob Announced Monday Morning January 21, 1974 Increases In Prices Of Rice, Sugar, Wheat Flour, Bread, Coffee, Noodles, Amounting To Approximately 100 Percent Over Previous Officially Quoted Prices. However, In Terms Of Effective Market Prices Increases Were Only About 20 Percent Higher, Except For Bread Which Was Subsidized By Gob. Effective Increase For Bread, Including Further Pan De Batalla Weight Decrease, Was Approximately 100 Percent. Wages And Salaries Increased By Up To 47 Percent For Both Private And Public Employees By Monthly Bonus Of 400 Pesos. End Summary."
cable-tags: "ECON BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ00430"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "FOOD SHORTAGE, WHEAT, INFLATION, IMPORTS, ECONOMIC PROGRAMS, SUBSIDIES, PRICE TRENDS, RETAIL PRICES, WAGE"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. Product scarcities for above items were extreme in last month, although Bolivia was frequently plagued by problem throughout 1973. These scarcities were basically result of low domestic prices relative to external market and in the case of wheat flour absolute shortages caused by world-wide scarcities, failure of Argentina to supply flour under its agreements with Bolivia and possibly contraband movement of wheat flour to neighboring countries. Official price announced per pound for sugar is $B3.05 which 118 percent over previous official price of $B1.40 and 20 percent over effective market price of $B2.54 per pound. Common bread (pan de batalla) price was 30 centavos per unit of about 66 grams. Price increase to 50 centavos and reduction in weight to 53 grams results in increase of about 100 percent. New wheat flour price was increased approximately 52 percent over earlier official price and 10 percent over "black market" price. Price increased 145 percent over official price and about 20 percent market price.

2. Wage and salary increase of 400 perso per month represents 47 percent increase for lower income group, 27 percent for medium/low income group. On basis MINFIN salary survey, above groups represent approximately 84 percent of work force.

3. **Comment:** Price increases for the above products may be considered adequate in light of effective market prices. However, the maintenance of GOB presence in the pricing decisions implies that continued speculation could take place if prices inadequate relative to prices in neighboring countries. In case of flour world-wide availability, but especially availability from Argentina, will determine whether scarcity can be overcome at new price. It is unclear whether GOB will have to continue flour subsidy which depends on price in world market. For present GOB has not included subsidy in budget. Wage and salary increase for public sector which implies $B214 million in additional expenditures not fully included in budget. Concentration of increase in low income category means immediate translation into consumption expenditures adding further pressure on prices and imports. Appears that inflationary process will be difficult to slow in 1974--placing heavy burden on GOB incomes and monetary policies for remainder of year.
Stedman

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00430

- **Date:** January 21, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** FOOD SHORTAGE, WHEAT, INFLATION, IMPORTS, ECONOMIC PROGRAMS, SUBSIDIES, PRICE TRENDS, RETAIL PRICES, WAGE
