---
title: "Farmabol Case"
author: "Stedman"
date: "March 18, 1974"
editor: visual
cable-date: "March 18, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2564"
cable-info: "Oct-01 Iso-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-07 Pa-04 Rsc-01 Prs-01 Spc-03 Ss-20 Usia-15 Drc-01 Aid-20 Come-00 Eb-11 Frb-02 Trse-00 Xmb-07 Opic-12 Ciep-02 Lab-06 Sil-01 Omb-01 /158 W --------------------- 003564 R 182134z Mar 74"
cable-subject: "Farmabol Case"
cable-tags: "EIND, BDIS, EFIN, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ01649"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "INDUSTRY, MONEY, NEGOTIATIONS, COURTS, FINANCIAL AGREEMENTS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. **Captain Augusto Sanchez**, manager of FANAQUINA and GOB's negotiator on FARMABOL case, called on EMBOFF March 15. He urged that FARMABOL rep Hathorn respond to Sanchez's last letter of December 20, 1973 and if possible come to La Paz to pursue negotiations.

2. **Sanchez** claims to be under considerable pressure from his superiors to settle FARMABOL matter in Bolivian courts. He said FANAQUINA's lawyer advises that with evidence available, especially inventory comparisons, legal action would almost certainly result in deposit by FANAQUINA of approximately US$ 5,000 with court as settlement. Owners of FARMABOL would then have to seek funds from court in separate action since Sanchez claims FARMABOL never established legal status in Bolivia. EMBOFF observed that lawyer's suggestion would unnecessarily complicate case at this point and advised delay until negotiations with Hathorn could be resumed. Sanchez agreed.

3. **Sanchez** admitted that he has not yet written directly to Hathorn inviting him to return to La Paz but promised to do so immediately. As Department aware, Hathorn's fiduciary deposit scheme was turned down by GOB financial advisors but Sanchez believes Hathorn can either convince GOB of value of scheme or offer some other proposal. Sanchez himself seems to prefer amicable negotiated settlement rather than legal action in part because he sees possibility of further capitalizations FANAQUINA and other COFADENA projects.

4. **Action requested:** Department may wish to inform Hathorn of Sanchez' expressed desire for continued negotiations, possibility of court action and Sanchez' invitation.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01649

- **Date:** March 18, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** INDUSTRY, MONEY, NEGOTIATIONS, COURTS, FINANCIAL AGREEMENTS
