---
title: "Geometric Bid For Uranium Air Survey Contract"
author: "Stedman"
date: "August 13, 1974"
editor: visual
cable-date: "August 13, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 3890"
cable-info: "Oct-01 Iso-00 Eb-11 Come-00 Rsc-01 Drc-01 Sso-00 /034 W --------------------- 058273 O 131945z Aug 74"
cable-subject: "Geometric Bid For Uranium Air Survey Contract"
cable-tags: "ETRN,SBE/P, BL"
cable-ref: "LA PAZ 5091 FOR: ARA/BC/B - ATTN: MIKE CO TER"
cable-doc-number: "1974LAPAZ05158"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. PLEASE INFORM BOB FOWLER, GEOMETRIC, INC. OF FOLLOWING
FURTHER INFORMATION PICKED UP FROM GOB NUCLEAR ENERGY
COUNCIL, COBOEN.


2. AIRCRAFT ENTERING COUNTRY UNDER AGIP CONTRACT HAS TO REGISTER
WITH BOLIVIA CIVIL AVIATION DIRECTOR BUT THIS IS PRO FORMA
STEP ANTICIPATED IN CONTRACT. OWNERS WILL HAVE TO PAY
TWO PERCENT CUSTOMS "SERVICE" TAX ON PLANE AND EQUIPMENT,
BUT ALL OTHER DUTIES ARE WAIVED.


3. SUBCONTRACTORS DO NOT HAVE TO PAY PROFITS TAX BUT INDIVIDUAL
WORKERS MUST PAY INCOME TAX AS EXPLAINED REFTEL, WHICH
IS COLLECTED BY PRIME CONTRACTOR.


4. IAGS COL. FURRER IS REPLYING TODAY TO YOUR QUESTION RE MAPS.
GENERALLY, 1:50,008 MAPS AVAILABLE FOR ALL SITES EXCEPT
SAN JOSE.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05158

- **Date:** August 13, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a