---
title: "[subject not available]"
author: "Stedman"
date: "August 09, 1974"
editor: visual
cable-date: "August 09, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 3868"
cable-info: "Oct-01 Ara-16 Iso-00 Med-03 Sci-06 Io-14 Aid-20 Pa-04 Usia-15 Ciae-00 Inr-11 Nsae-00 Rsc-01 Sca-01 Dode-00 Sp-03 Prs-01 Opr-02 M-02 A-01 Drc-01 /110 W --------------------- 026147"
cable-subject: "[subject not available]"
cable-tags: "PBOR, SWEL, BL, PAHO, WHO, (GAMARRA)"
cable-ref: ""
cable-doc-number: "1974LAPAZ05093"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "HEALTH, DISEASE CONTROL, BORDER CONTROLS, MENINGITIS, COMMUNICABLE DISEASES, VACCINES, EPIDEMICS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. DEPARTMENT OF PUBLIC RELATIONS OF MINISTRY OF PUBLIC
HEALTH ANNOUNCED AUG 8 THAT BORDER WITH BRAZIL HAD BEEN CLOSED
AUG 2 TO PREVENT SPREAD OF MENINGITIS FROM THAT COUNTRY TO
BOLIVIA. ADDED, HOWEVER, THAT PERSONS WITH MEDICAL CERTIFICATE
ATTESTING TO THEIR GOOD HEALTH ON BASIS OF "LABORATORY DIAGNOSIS"
MIGHT BE ADMITTED AFTER EXAMINATION BY BORDER AUTHORITIES.
ACCORDING TO DR. GAMARRA OF NATIONAL INSTITUTE OF TRANSMISSIBLE
DISEASES, PERSONS ARRIVING BY AIR OR GROUND FROM OTHER
NEIGHBORING COUNTRIES WILL BE CLOSELY CHECKED FOR MENINGITIS
SYMPTOMS.


2. ACCORDING TO THE MINISTRY, NO CASES OF MENINGITIS HAVE BEEN
REPORTED IN BOLIVIA AS YET. DOCTORS HAVE BEEN INSTRUCTED TO
REPORT ANY SUSPICIOUS CASES TO PUBLIC HEALTH EPIDEMIOLOGISTS.


3. DR. GAMARRA TOLD MISSION OFFICER THAT TYPE C VACCINE HAD
BEEN REQUESTED FROM PAHO IN ANY QUANTITY IT CAN PROVIDE.
PUBLIC RELATIONS DEPARTMENT STATED SAME REQUEST HAD BEEN MADE
OF WHO.


4. REGIONAL MEDICAL OFFICER NOTES THAT QUALIFIED MEDICAL
PERSONNEL ARE NOT GENERALLY AVAILABLE AT MOST FRONTIER TRANSIT






 092213Z


POINTS AND THAT CONTROL MAY NOT BE VERY EFFECTIVE.




                     

                  


5. RMO BELIEVES MENINGITIS OUTBREAK IN BRAZIL DOES NOT
PRESENT SIGNIFICANT DANGER TO MISSION PERSONNEL.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05093

- **Date:** August 09, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** HEALTH, DISEASE CONTROL, BORDER CONTROLS, MENINGITIS, COMMUNICABLE DISEASES, VACCINES, EPIDEMICS