---
title: "Inm Authorization To Purchase Household Furniture And Applicances, University Of Florida Contract, Agricultural Development In Coca Zones"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "September 04, 1979"
editor: visual
cable-date: "September 04, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 8005"
cable-info: "Oct-01 Ara-15 Ads-00 Std-01 Ste-00 /022 W ------------------056317 051348z /44 R 041634z Sep 79"
cable-subject: "Inm Authorization To Purchase Household Furniture And Applicances, University Of Florida Contract, Agricultural Development In Coca Zones"
cable-tags: "SNAR"
cable-ref: ""
cable-doc-number: "1979LAPAZ07486"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

With reference to OINM authorization per reference telecon, here is the amendment of the University of Florida/Department of State contract for the purpose of procuring a total of seven complete sets of household furniture and appliances in support of the Florida technicians and their families in residence. Amendment 8, University of Florida Contract 511-107-U. The University of Florida is authorized to expend up to $125,000 to purchase five complete sets of household furniture and appliances from United States suppliers, including the cost of shipment to La Paz, Bolivia. The University of Florida is also authorized to expend up to $30,000 to reimburse the Consortium for International Development for two partial sets of household furniture and appliances made available to the University of Florida in La Paz, Bolivia, to replace certain broken items in the sets, and to purchase appliances needed to complete the two sets of household effects. Grant funds are available for this purpose in PROW/AG 104-0-02-02-90002 under line item 1., Basic Agronomic and Economic Research, UFLA, $450,000.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ07486

- **Date:** September 04, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** n/a