---
title: "Law Of War (Low) Conference: Prg Invitation Refs: A. State 27026: B. State 27778: C. State 34265"
author: "Stedman"
date: "February 21, 1974"
editor: visual
cable-date: "February 21, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 2329"
cable-info: "Oct-01 Ara-16 Io-14 Iso-00 Acda-19 Inre-00 Sso-00 Nsce-00 Usie-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 Nsae-00 Nsc-10 Pa-04 Rsc-01 Prs-01 Spc-03 Ss-20 Sam-01 Oic-04 Ea-11 Drc-01 /129 W --------------------- 121476 O 211450z Feb 74"
cable-subject: "Law Of War (Low) Conference: Prg Invitation Refs: A. State 27026: B. State 27778: C. State 34265"
cable-tags: "PARM ICRC VN"
cable-ref: ""
cable-doc-number: "1974LAPAZ01114"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "LAW, WAR, GENEVA CONVENTIONS, FOREIGN POLICY POSITION, MEETINGS, MEETING DELEGATIONS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. EMBOFF discussed subject with Acting Chief (Carrasco) International Organizations Department of FONOFF February 15. She said Bolivia represented by its Ambassador to Switzerland and one other official also of ambassadorial rank and that while not specifically instructed, they would be familiar with Bolivian position on this subject and that we could count on Bolivian support. Suggest USDEL contact both Bolivians and try again citing very clear position taken here by FONOFF against invitation to PRG in particular and to national liberation movements in general.
2. Carrasco told same EMBOFF today that she would now send instructions, which hopefully will arrive in time.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01114

- **Date:** February 21, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** LAW, WAR, GENEVA CONVENTIONS, FOREIGN POLICY POSITION, MEETINGS, MEETING DELEGATIONS
