---
title: "Opic Insurance Applications: John Lamar Lessor And Charles E. Stokes State Pass Opic Summary. Gob Has Sent Note Indicating Min Ag's Approval Subject Opic Investment. Telegram Discusses Form Of Note And Comments On Land Investments In Bolivia. End Summary."
author: "Stedman"
date: "April 30, 1974"
editor: visual
cable-date: "April 30, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2968"
cable-info: "Oct-01 Ara-16 Iso-00 Sp-03 Aid-20 Eb-11 Nsc-07 Ciep-02 Trse-00 Ss-20 Str-08 Omb-01 Cea-02 Agr-20 Swf-02 L-03 Come-00 Xmb-07 /135 W --------------------- 118101 R 302019z Apr 74"
cable-subject: "Opic Insurance Applications: John Lamar Lessor And Charles E. Stokes State Pass Opic Summary. Gob Has Sent Note Indicating Min Ag's Approval Subject Opic Investment. Telegram Discusses Form Of Note And Comments On Land Investments In Bolivia. End Summary."
cable-tags: "EFIN, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ02766"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "INSURANCE, CATTLE, NATIONALIZATION, INVESTORS, FOREIGN INVESTMENTS, CONTRACTS, LAND REFORMS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1.  **Embassy has received note from Foreign Office asking U.S. to inform OPIC that Bolivian Ministry of Agriculture has approved proposed investment in cattle ranches by subject U.S. citizens.**
2.  **Ministry official told EMBOFF that note intended to constitute Bolivian Government approval of OPIC insurance for projects.** Nonetheless, OPIC will wish to inspect text of note carefully (Embassy translating and pouching) to see if language adequately constitutes foreign government approval since language of note only implies that Min Ag's approval constitutes GOB approval. In fact, note goes on to further inform OPIC that details of investments must still be approved by GOB's Institute of National Investment (INI).
3.  **This is first GOB action approving new OPIC coverage in several years.** Foreign Ministry Economic Office aware of OPIC needs and INI has just established Office of Foreign Private Investment which Embassy is attempting to educate in OPIC matters. If OPIC has suggestion for change in approval format, we will discuss with these offices.
4.  **While recognizing potential advantage to Bolivian economy of investment by experienced U.S. cattlemen, Embassy concerned re Bolivia's history of land tenure disputes and therefore advises that any OPIC insurance contract covering U.S. agricultural investment should carefully define conditions of land tenure being insured and insurance should only be extended to investment in land whose title has been fully cleared by procedure provided by Bolivian law.** Insurance should also carefully define character and purposes of investment. This important caveat applies to Lessor and Stokes investments plus pending applications of Clair Peterson and Verne Hutchinson. (Latter's local contact, Warren Young, told EMBOFF that Hutchinson has decided not, repeat not, to go ahead with investment here.)
5.  **Long-term dispute over Applegate-Youngquist land expropriation illustrates potential difficulties which can arise out of Agrarian Reform Law of Bolivia's 1952 Revolution.** Law has frequently resulted, according to practices of past governments, in lengthy legal disputes over titles and outright land expropriations. Law provides for compensation of expropriations in 25-year, 2 percent bonds, but we are told that no, repeat no, such compensation has ever been given. Land titles can be confirmed (given "inafectabilidad") by several step legal process ending in decree signed by Bolivian President. Law also limits size of private land holdings according to character of investment and land's location and use. As we read law "large-scale", "modern enterprises" investing in livestock production in the tropical Beni area must be no larger than 50,000 hectares and have at least one head of cattle for each five hectares. In contrast large enterprise investing in agricultural production in same area would be limited to 2,000 hectares.
6.  **Lessor and Stokes' local attorney states that each investor intends to buy approximately 10,000 hectares in Beni and he foresees each having more than 2,000 head necessary to meet one to five hectares requirement.** He correctly notes that Agrarian Reform has resulted in few expropriations in lightly populated Beni and that present GOB has shown no, repeat no, penchant for further land expropriations and has improved administration of law somewhat. On other hand, attorney states that, as with many land parcels in country, those being considered for purchase by Lessor and Stokes have not yet received confirmation by presidential decree. He mentioned that investors contemplating eventually expanding from meat production to processing and canning.
7.  **Embassy notes that even in Beni Agrarian Reform has resulted in many title disputes, if not expropriations, and this likely to continue as population and economic activity now increasing.** Moreover, present agrarian policies may last only as long as present government. Thus, Embassy sees need to take all possible steps to secure title and decree establishing "inafectabilidad" before issuing OPIC insurance. Insurance contract should also guard against a change in character of investment or use of land that might open it up for challenge under Agrarian Reform Law.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02766

- **Date:** April 30, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** INSURANCE, CATTLE, NATIONALIZATION, INVESTORS, FOREIGN INVESTMENTS, CONTRACTS, LAND REFORMS