---
title: "Civair Andean Airline Association"
author: "Stedman"
date: "July 30, 1974"
editor: visual
cable-date: "July 30, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3777"
cable-info: "Oct-01 Ara-16 Iso-00 Cab-09 Ciae-00 Come-00 Dode-00 Dote-00 Inr-11 Nsae-00 Rsc-01 Faa-00 L-03 Nsc-07 Ss-20 Io-14 Drc-01 /094 W --------------------- 053480 R 302057z Jul 74"
cable-subject: "Civair Andean Airline Association"
cable-tags: "ETRN, LAFTA, BL"
cable-ref: "STATE 159662; SANTIAGO 4423"
cable-doc-number: "1974LAPAZ04903"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "CIVIL AVIATION, AIRCRAFT, PROCUREMENT, AIRLINES, BUSINESS ASSOCIATIONS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. LLOYD AEREO BOLIVIANA (LAB) PRESIDENT BILBAO TOLD EMBOFF JULY
29 THAT SUBJECT ASSOCIATION FORMED, FIRST, TO INCREASE ANDEAN
AIRLINES' SHARE OF AIR PASSENGER TRAFFIC IN AND OUT OF REGION
AND, SECOND, TO ENCOURAGE COST SAVING COMPLEMENTATION AMONG ANDEAN
CARRIERS.


2. BILBAO REPORTED THAT FIRST PROBLEM WILL BE ADDRESSED BY
JOINT PROMOTIONS AND SCHEDULING TIE-INS AND SECOND BY ESTABLISH-
MENT OF REGIONAL SPARE PARTS CENTER, PURCHASE 727 TRAINING MOCK-UP
FOR JOINT USE AND STANDARDIZATION OF AIRCRAFT PURCHASES. HE SAID
STUDY WILL BE MADE TO DETERMINE BEST WIDE-BODY AIRCRAFT FOR
ANDEAN AIRLINES, ALTHOUGH HE NOTED THAT VIASA HAS ALREADY SETTLED
ON DC-10. LAB OF COURSE NOT RPT NOT IN MARKET FOR WIDE-BODY
AIRCRAFT BUT IN ITS CURRENT EFFORT TO RESCHEDULE SERVICES AND
EXTEND ROUTES, IT WISHES CONNECT WITH WIDE-BODY STOPS.






 311653Z




                        

                  

3. BILBAO STATED EMPHATICALLY THAT ASSOCIATION NOT RPT NOT FIRST
STEP IN FORMING ANDEAN AIRLINE. HE SAID NATIONAL AIRLINE EXECU-
TIVES ALSO GENERALLY OPPOSED TO CAF PROPOSAL FOR LEASING AIRCRAFT.


4. BILBAO CONFIRMED THAT LAB WILL PROBABLY SOON RE-ESTABLISH LA
PAZ - ARICA SERVICE. ONE DAY A WEEK 727 WILL FLY LA PAZ - ARICA -
SANTIAGO - SANTA CRUZ, BOLIVIA AND ON ANOTHER DAY WILL MAKE TRIP
IN REVERSE. BILBAO FEARS THAT ROUTE WILL NOT BE PROFITABLE AND
HAS HIGHER HOPES FOR NEWLY ESTABLISHED STOP IN ASUNCION ON LA PAZ-
BUENOS AIRES ROUTES AND PLAN FOR INCREASED FREQUENCY TO SAO PAULO.


5. COMMENT: WE ALSO DOUBT THAT SANTIAGO-SANTA CRUZ LEG WOULD BE
PROFITABLE.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04903

- **Date:** July 30, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** CIVIL AVIATION, AIRCRAFT, PROCUREMENT, AIRLINES, BUSINESS ASSOCIATIONS
