---
title: "Ex-President Padilla's Visit To Us For Medical Treatment"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "October 11, 1979"
editor: visual
cable-date: "October 11, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 8571"
cable-info: "Oct-01 Ads-00 Cpr-02 Nsc-05 Pa-02 Pm-06 Ss-15 Sy-05 Sye-00 Icae-00 Usss-00 Sso-00 /051 W ------------------067113 112033z /64 O 112015z Oct 79 Zff4"
cable-subject: "Ex-President Padilla's Visit To Us For Medical Treatment"
cable-tags: "OVIP, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ08626"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "MEDICAL CARE, POLITICAL LEADERS, VISITS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. GENERAL DAVID PADILLA ARANCIBIA, PRESIDENT OF
BOLIVIAN UNTIL AUGUST 8, 1979, PLANS TO VISIT THE US
OCTOBER 13 TO 17 FOR MEDICAL TREATMENT. GENERAL
PADILLA WILL BE ACCOMPANIED BY MRS. PADILLA, WHO WILL
ALSO HAVE A MEDICAL CHECK-UP, HIS BROTHER DR. ALFREDO
PADILLA, A PHYSICIAN, AND HIS WIFE.


2. GENERAL PADILLA'S ITINERARY IS AS FOLLOWS:
OCTOBER 12 9:25 PM LV LA PAZ ON BN 974
OCTOBER 13 6:20 AM ARRIVE MIAMI
OCTOBER 14 3:50 PM LEAVE MIAMI ON NATIONAL 39
OCTOBER 14 5:12 PM ARRIVE HOUSTON


3. DR. CARLOS H. FERNANDEZ IS COORDINATING ARRANGEMENTS
FOR GENERAL PADILLA IN HOUSTON WHERE HE PLANS TO BE
EXAMINED AT MEMORIAL HOSPITAL AND WILL LIKELY ENTER
THE HOSPITAL FOR SOME TREATMENT.


4. REQUEST RECEPTION CENTER IN MIAMI MEET
GENERAL PADILLA AND LEND APPROPRIATE ASSISTANCE IN






 112030Z


MIAMI.


5. REQUEST DEPARTMENT CONTACT DR. CARLOS H. FERNANDEZ
AND/OR MEMORIAL HOSPITAL IN HOUSTON TO INFORM THEM OF
GENERAL PADILLA'S STATUS AND TO ASSURE GENERAL PADILLA
IS RECEIVED IN HOUSTON.




          Sheryl P. Walter 

         Sheryl P. Walter 

6. GENERAL PADILLA HAS OVERSEEN BOLIVIA'S TRANSITION TO
CIVILIAN, CONSTITUTIONAL RULE AND HAS BEEN A GOOD FRIEND
OF THE US. THIS IS HIS FIRST VISIT TO THE US.
BOEKER

***

#### Message Attributes

- **Document Number:** 1979LAPAZ08626

- **Date:** October 11, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** MEDICAL CARE, POLITICAL LEADERS, VISITS
