---
title: "Bolivian Postal Debt"
author: "Stedman"
date: "August 21, 1974"
editor: visual
cable-date: "August 21, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3991"
cable-info: "Oct-01 Iso-00 Eb-11 Usps-02 Drc-01 Rsc-01 /036 W --------------------- 011040 R 212000z Aug 74"
cable-subject: "Bolivian Postal Debt"
cable-tags: "ETEL, BL"
cable-ref: "(A) STATE 082399 (B) STATE A-6510"
cable-doc-number: "1974LAPAZ05418"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "POSTAL SERVICE, DEBT REPAYMENTS, CHECKS (MONEY), BALANCE OF PAYMENTS, DIPLOMATIC COMMUNICATIONS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. EMBASSY HAS JUST RECEIVED FURTHER LETTER FROM BOLIVIAN
GENERAL DIRECTOR OF POST OFFICE PRUDENCIO DETAILING
UNSUCCESSFUL EFFORTS TO OBTAIN PHOTOCOPIES OF CANCELLED
CHECKS. EMBASSY THEREFORE INFORMED DIRECTOR AUGUST 20
THAT USPS WILL ACCEPT BOLIVIAN CLAIM AND ACCOUNTING ENTRIES
WILL REFLECT CREDIT TO BOLIVIAN POSTAL ADMINISTRATION.


2. PRUDENCIO AGREES THAT BALANCE OF POSTAL ACCOUNT CURRENTLY
FAVORS BOLIVIA.


3. COPIES OF ABOVE CORRESPONDENCE WILL BE SENT TO DEPT.
BY AIRGRAM.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05418

- **Date:** August 21, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** POSTAL SERVICE, DEBT REPAYMENTS, CHECKS (MONEY), BALANCE OF PAYMENTS, DIPLOMATIC COMMUNICATIONS
