---
title: "Bolivian Foreign Minister Plannig To Deliver Letter From President Banzer To President Nixon"
author: "Stedman"
date: "April 15, 1974"
editor: visual
cable-date: "April 15, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2826"
cable-info: "Oct-01 Iso-00 Sso-00 /031 W --------------------- 074228 R 151710z Apr 74"
cable-subject: "Bolivian Foreign Minister Plannig To Deliver Letter From President Banzer To President Nixon"
cable-tags: "PBOR PFOR BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ02306"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "28 MAY 2004"
cable-concepts: "LANDLOCKED COUNTRIES, PRESS COMMENTS, DIPLOMATIC COMMUNICATIONS, ACCESS TO PORTS, FOREIGN POLICY"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. Bolivian Foreign Minister Guzman intends to deliver to Secretary Kissinger a letter from President Banzer to President Nixon. According to the Foreign Minister, the letter requests comprehension of the USG of Bolivia's hopes for an outlet to the sea. The letter will also express Banzer's regret at not having been able to visit the US in fall 1973 and will note Banzer's interest in making the visit at sometime in the future.
2. Sub-Secretary Foreign Ministry told me that the letter to President Nixon is not drafted as a request for any action on our part but rather is a review of what Bolivia considers to be an unjust situation and is designed to elicit from the US favorable understanding. The Sub-Secretary indicated that Bolivia may discuss its land-locked position with other Foreign Ministers but for the moment has put aside the idea of a circular memorandum to other Foreign Ministers.
3. Foreign Ministry has come under domestic political pressure to show some forward motion on behalf of Bolivia regarding an outlet to the sea. Leading La Paz newspaper Diario has criticized the Foreign Minister for ineptness in previous meetings and has joined others in calling on the Foreign Minister to express more clearly in meetings in Washington/Atlanta Bolivia's deep-seated desires for an opening to the sea.
4. If the letter is indeed drafted as I have been told, it should not be difficult to answer. However, in the current emotional state here on return to sea, the reply should be written bearing in mind that it very likely will be published in the Bolivian press. With regard to a repeat invitation to President Banzer to visit the US, I would hope for a bland acknowledgment, again suggesting that it would be possible but at a mutually convenient time for both Presidents.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02306

- **Date:** April 15, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 28 MAY 2004

- **Concepts:** LANDLOCKED COUNTRIES, PRESS COMMENTS, DIPLOMATIC COMMUNICATIONS, ACCESS TO PORTS, FOREIGN POLICY
