---
title: "Energy: Oil Trade Data From Bolivia For Year 1973"
author: "Stedman"
date: "January 24, 1974"
editor: visual
cable-date: "January 24, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 2039"
cable-info: "Oct-01 Ara-16 Iso-00 Fea-02 Int-08 Spc-03 Aid-20 Nsc-10 Rsc-01 Ciep-02 Trse-00 Ss-20 Str-08 Omb-01 Cea-02 Ciae-00 Come-00 Frb-02 Inr-10 Nsae-00 Xmb-07 Opic-12 Lab-06 Sil-01 Nea-11 Drc-01 /155 W --------------------- 079282 P 242039z Jan 74"
cable-subject: "Energy: Oil Trade Data From Bolivia For Year 1973"
cable-tags: "ENRG, ECRP, BL"
cable-ref: "STATE 251108: A-62 OF APRIL 6, 1973"
cable-doc-number: "1974LAPAZ00521"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PETROLEUM PRODUCTS, TRADE DATA, EXPORT DATA, IMPORT DATA"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1.  **Following data supplied by Bolivian National Oil Company Yacimientos Petroliferos Fiscales Bolivianos (Y.P.F.B.), the only petroleum gas producing and exporting entity in Bolivia:**
    A. Crude oil production - 17,265,582 US barrels.
    B. Crude oil exports in US barrels to Argentina, 5,029,106; Brazil, 2,426,785; Peru, 1,563,423; Chile, 1,374,457; U.S.A., 1,201,072; Paraguay, 249,383. Total crude oil exports 11,844,136 U.S. barrels. No refined petroleum exports other than reported slight contraband of gasoline.
    C. No imports of crude oil. Imports of products from Chile: 4,482,000 U.S. gallons aviation gasoline 100/130 octane and 138,000 U.S. gallons aviation oil; from U.S.A.: 393,000 U.S. gallons oil blend stocks and 1,040 metric tons asphalt.
    D. Source of refineries crude input totally Bolivian. All refinery products destined for local consumption. Total refinery input 5,533,309 U.S. barrels of crude. Output in U.S. barrels: Gasoline, 2,266,322; Fuel oil, 1,041,300; Kerosine, 990,290; Diesel oil, 848,819; Jet fuel, 148,176; L.P.G., 93,894; Natural gasoline, 76,239; Ether, 1,338; Solvent, 239; Losses, 66,682.

2.  **As additional information, Bolivian natural gas exports were totally to Argentina and amounted to 55,449,989 thousands cubic feet valued at border US$ 18,101,160. Total petroleum exports to countries listed (B) valued at US$ 48,860,816. Additional L.P.G. recovered from gas plant, 48,462 U.S. barrels.**

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00521

- **Date:** January 24, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PETROLEUM PRODUCTS, TRADE DATA, EXPORT DATA, IMPORT DATA
