---
title: "Possible Appointment Of New Bolivian Ambassador To The United States. Reference: La Paz 4436"
author: "Stedman"
date: "August 20, 1974"
editor: visual
cable-date: "August 20, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3973"
cable-info: "Oct-01 Iso-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-11 L-03 Nsae-00 Nsc-07 Pa-04 Rsc-01 Prs-01 Sp-03 Ss-20 Usia-15 Drc-01 /097 W --------------------- 000777 R 201800z Aug 74"
cable-subject: "Possible Appointment Of New Bolivian Ambassador To The United States. Reference: La Paz 4436"
cable-tags: "PFOR, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ05369"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "DIPLOMATIC ACCREDITATION, PRESS COMMENTS, AMBASSADORS, PERSONNEL APPOINTMENTS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. REFTEL REPORTED THAT PRESS ITEM JULY 9 ANNOUNCED
APPOINTMENT OF REOBERTO CAPRILES AS AMBASSADOR TO THE
UNITED STATES. CAPRILES TOLD EMBOFF AUGUST 19 THAT HE
HAD DECIDED NOT TO ACCEPT OFFER AS HE HAD ALREADY SPENT
MUCH TIME IN PUBLIC SERVICE AND NEEDED TO ATTEND TO HIS
BUSINESS AFFAIRS. PRESIDENTIAL ADVISOR ALFREDO ARCE WHO
WAS PRESENT DURING CONVERSATION NOTED THAT AT THIS CRITICAL
STAGE IN BOLIVIA'S POLITICAL AND ECONOMIC DEVELOPMENT,
PRESIDENT BANZER COULD NOT AFFORD TO SEND HIS CLOSEST
COLLABORATORS TO ASSIGNMENTS ABOARD.


2. ARCE AND CAPRILES ALSO NOTED THAT APPROPRIATE CANDIDATE
FOR WASHINGTON ASSIGNMENT NOT IN SIGHT. THEY AGREED THAT
BOLIVIAN AMBASSADOR TO U.S. SHOULD HAVE CREDENTIALS SIMILAR
TO THOSE POSSESSED BY CAPRILES, BUT THAT FOR THE
MOMENT THEY COULD IDENTIFY NO ONE WHO FIT THE BILL.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05369

- **Date:** August 20, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** DIPLOMATIC ACCREDITATION, PRESS COMMENTS, AMBASSADORS, PERSONNEL APPOINTMENTS
