---
title: "National Economic-Planning Council (Coneplan) Signs Cooperation And Technical Assistance Project (Ctap) With Japanese Overseas Technical Cooperation Agency (Otca)"
author: "Stedman"
date: "June 27, 1974"
editor: visual
cable-date: "June 27, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3514"
cable-info: "Oct-01 Iso-00 Ea-11 Ciae-00 Dode-00 Inr-10 Nsae-00 Pa-04 Rsc-01 Usia-15 Prs-01 Sp-03 Drc-01 /067 W --------------------- 054780 R 271523z Jun 74"
cable-subject: "National Economic-Planning Council (Coneplan) Signs Cooperation And Technical Assistance Project (Ctap) With Japanese Overseas Technical Cooperation Agency (Otca)"
cable-tags: "IAGS, TGEN, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ04167"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "TECHNICAL ASSISTANCE, AGREEMENTS, TREATY SIGNATURE, INTERGOVERNMENTAL COOPERATION, PROGRAMS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. SUBSECRETARY OF CONEPLAN, EDUARDO DAVALOS, DR. YOSHMICHI
HARADA, CHIEF JAPANESE MISSION, COL. JORGE QUINTANA OF
INSTITUTO GEOGRAFICO MILITAR (IGS), AND BOLIVIA AIR FORCE
AMJOR RENE OCAMPO, ON JUNE 24 SIGNED AGREEMENT OF TECHNICAL
COOPERATION WITH JAPANESE MISSION INVOLVING MAPPING
(SCALE 1:50,000) BY AERIAL PHOTOGRAPHY OF 20,000 TO 25,000
SQUARE KILOMETERS OF CHAPARE AREA, DEPARTMENT OF COCHABAMBA.


2. OTCA WILL PROVIDE ALL EQUIPMENT AND MATERIAL FOR EXECUTION
OF PROJECT. BOLIVIAN GOVERNMENT TO PROVIDE LABOR,
INTERPRETERS, AND BOLIVIAN COUNTERPART TECHNICIANS AS
WELL AS OFFICE, GARAGES, MEDICAL CENTERS, AND OTHER
GENERAL SERVICES. TIME TO FINISH PROJECT STARTING 1974
ESTIMATED FROM 2 TO 4 YEARS.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04167

- **Date:** June 27, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** TECHNICAL ASSISTANCE, AGREEMENTS, TREATY SIGNATURE, INTERGOVERNMENTAL COOPERATION, PROGRAMS