---
title: "Banzer And Campesinos In Cochabamba Summary: President Banzer Sought During Appearance March 8 In Cochabamba To Reconcile His Government With Campesinos Of Area. Banzer Spoke At Military Airport During Ceremony Marking Government's Free Gift Of 1,000 Metal Plows And 24 Tractors To Cochabamba's Farmers And Cooperatives. Estimated 5,000 Campesinos Present. End Summary."
author: "Stedman"
date: "March 12, 1974"
editor: visual
cable-date: "March 12, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2504"
cable-info: "Oct-01 Iso-00 Aid-20 Pc-04 Omb-01 Agr-20 Eb-11 Come-00 Trse-00 Snm-02 Deae-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-07 Pa-04 Rsc-01 Prs-01 Spc-03 Ss-20 Usia-15 Nic-01 Drc-01 /155 W --------------------- 069702 R 121254z Mar 74"
cable-subject: "Banzer And Campesinos In Cochabamba Summary: President Banzer Sought During Appearance March 8 In Cochabamba To Reconcile His Government With Campesinos Of Area. Banzer Spoke At Military Airport During Ceremony Marking Government's Free Gift Of 1,000 Metal Plows And 24 Tractors To Cochabamba's Farmers And Cooperatives. Estimated 5,000 Campesinos Present. End Summary."
cable-tags: "PINT, BGEN, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ01488"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PRESIDENT, FARM EQUIPMENT, PUBLIC RELATIONS, SPEECHES, AGRICULTURAL WORKERS, LAND REFORMS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. Theme of gathering pronounced by Minister of Campesino Affairs and Agriculture, Col. Natusch Busch, who declared "Military-Campesino Pact" in full force. Natusch identified himself with Banzer and extolled president as campesino's friend. He said Banzer had told him that he hoped campesino would be president of Bolivia in near future.

2. Banzer's long and measured speech sought to explain economic measures as means of increasing income to campesinos, the producers of basic products. He said former low level of legal prices allowed profits to be made by speculators. He urged farmers to raise more now. Bolivia, he said, ironically, is fortunate in contrast to rest of world because it has shown itself capable of producing many things for domestic consumption, legal export and contraband. Banzer told the campesinos that Bolivia exports coca worth US $280 million which is destroying the youth of world and urged them to switch to other crops.

3. Banzer pictured himself as deeply concerned for campesino welfare, a duty he claimed that came to him, in a sense, as posthumous charge from President Barrientos. He regretted that he could not speak Quechua so that he could speak of his love of them more expressively. He recognized poor state of Cochabamba economy but ticked off list of government measures that will improve future including distribution of free land in newly opened Chapare region and industrialization of Cochabamba itself. He said gift of tractors and plows is first step in making agrarian reform more meaningful by helping increase production.

4. **Comment:** Right at beginning of speech Banzer said that gift of tractors and plows was not (rpt not) response to recent "tragic events" in valley but circumstances argue otherwise. Banzer's sincerity evident in speech, including reference to coca which helpful to US but not necessarily good politics for him. Nonetheless, both president and MINAG spoke in paternalistic tones. Crowd was large but only very small clack responded to speeches. Large numbers streamed toward exit when president began speaking until guards closed gate of base.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01488

- **Date:** March 12, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PRESIDENT, FARM EQUIPMENT, PUBLIC RELATIONS, SPEECHES, AGRICULTURAL WORKERS, LAND REFORMS
