---
title: "Gob Announces Economic Measures"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "November 30, 1979"
editor: visual
cable-date: "November 30, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 9551"
cable-info: "Oct-01 Ads-00 Aid-05 Ciae-00 Com-02 Eb-08 Frb-03 Inr-10 Nsae-00 Trse-00 Xmb-02 Opic-07 Sp-02 Lab-04 H-01 Sil-01 Omb-01 Ss-15 Str-08 Cea-01 Sso-00 Nsce-00 Icae-00 Inre-00 Doe-17 /103 W ------------------041274 302226z /64"
cable-subject: "Gob Announces Economic Measures"
cable-tags: "ECON, BL"
cable-ref: "LA PAZ 9970 (NOTAL)"
cable-doc-number: "1979LAPAZ10309"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "ECONOMIC CONTROLS, DEVALUATIONS, CURRENCIES"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. This morning, November 30, at 0345 hours, the GOB announced a package of economic measures much along the lines of reftel. The program includes the following:
    (A) A devaluation of 25 percent to 24.51 pesos (buying) 25 pesos (selling) to the dollar.
    (B) A graduated wage bonus for private and public sector employees earning less than 9,000 pesos per month.
    (C) Increases in hydrocarbon prices and the cost of public transportation.
    (D) A 1980 consolidated public sector budget equivalent to the 1979 levels plus the cost of the wage increase. Some small increases would be permitted for the ministries of Defense, Health, Education, and the Interior.
    (E) Creation of a Council of Monetary Stabilization (Consejo Nacional de Politica Monetaria) to monitor the program.
    (F) Monetary measures include increases in time and demand deposit interest rates, changes in the legal reserve requirements, a prior import deposit of 100 percent replacing the previous 500 percent deposit, and a new tax on commercial bank credit for both peso and dollar loans. Bankers have been in meetings with the Central Bank most of the day finding out what the new measures mean to them. For this reason, commercial banks are not carrying out foreign exchange transactions today. Money exchange houses are open and are buying dollars at the official rate and selling them at near 25 pesos to the dollar but, according to one exchange house manager, there are no dollars to sell.
    (G) Price controls on flour, some pasta products, rice, sugar, bread, and rent controls on all housing.

2. We anticipate some popular reaction, since the Bolivian Labor Federation, which caused the measures to be postponed, apparently was not included in the government's decision to go ahead with the measures. Nevertheless, we anticipate that after some show of protest, Juan Lechin and his COB will go along.

3. According to local IMF representative Jorge Sol Perez, the GOB's economic measures include the basic program outlined in reftel. The Central Bank is authorized to make daily exchange rate adjustments and plans to do so until the rate reaches an equilibrium. The price hike for petroleum products will average 136 percent. Sol Perez said that an IMF mission will arrive over the coming weekend; he expects a letter of intent to be prepared and ready for signature by late next week.

4. After the early morning announcement of the economic measures, Bolivia's major cities remain calm and business is normal. This morning a student demonstration rumored to be against the measures turned out to be students gathering at one of La Paz' main plazas for the final leg of an early morning marathon. Minister of Finance Augusto Cuadros Sanchez told the ambassador that so far public reaction to the measures had been calm and philosophical, that in a sense the measures turned out less severe than the public had anticipated. Cuadros was sanguine the stabilization program would now go forward without the threat of a major strike by the labor sector.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ10309

- **Date:** November 30, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** ECONOMIC CONTROLS, DEVALUATIONS, CURRENCIES