---
title: "Ia-Ecosoc Annual Meeting"
author: "Stedman"
date: "March 07, 1974"
editor: visual
cable-date: "March 07, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2459"
cable-info: "Oct-01 Iso-00 Io-14 Aid-20 Ciae-00 Come-00 Eb-11 Frb-02 Inr-10 Nsae-00 Rsc-01 Trse-00 Xmb-07 Opic-12 Spc-03 Ciep-02 Lab-06 Sil-01 Omb-01 L-03 Str-08 Iga-02 Oic-04 Drc-01 /129 W --------------------- 023146 R 071102z Mar 74"
cable-subject: "Ia-Ecosoc Annual Meeting"
cable-tags: "EGEN, IA-ECOSOC, BL"
cable-ref: "(A) STATE 039787; (B) LA PAZ 1329"
cable-doc-number: "1974LAPAZ01394"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "MEETING AGENDA, COMMITTEE MEETINGS, NEGOTIATIONS, MEETING DELEGATIONS, MEETINGS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. In a meeting March 6, Fonoff official added little to earlier discussion of IA-ECOSOC agenda. He stated the Fonmin was pleased that the U.S. saw the meeting as a continuation of discussion begun at Mexico City. Bolivians will be interested in picking up themes from the last annual meeting, including trade preference and soft loan financing. The official said that the minister was interested in establishing special preferences for the least developed. It was clear that this position did not (repeat not) include the views of the Planning Council and its Minister-Secretary, who will lead the Bolivian delegation.
2. The official said that Bolivia has not (repeat not) come to a firm decision on CIAP leadership but noted a general sentiment that Interim Chairman Rodriguez be confirmed.
3. In addition to those listed reftel, Gonzalo Acha of Minind/Com and Agustin Ugalde of Fomex will be in the Bolivian delegation. Stedman

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01394

- **Date:** March 07, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** MEETING AGENDA, COMMITTEE MEETINGS, NEGOTIATIONS, MEETING DELEGATIONS, MEETINGS