---
title: "Foreign Ministers' Meeting Mexico"
author: "Stedman"
date: "February 08, 1974"
editor: visual
cable-date: "February 08, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2218"
cable-info: "Oct-01 Iso-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-10 Pa-04 Rsc-01 Prs-01 Spc-03 Ss-20 Usia-15 Sam-01 Drc-01 /100 W --------------------- 115284 R 082006z Feb 74"
cable-subject: "Foreign Ministers' Meeting Mexico"
cable-tags: "PFOR OCON XM MX BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ00878"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PRESS COMMENTS, MEETING AGENDA, FOREIGN RELATIONS, LESS DEVELOPED COUNTRIES, FOREIGN MINISTERS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. Bolivian interest increasing in Foreign Ministers' meeting with Secretary Kissinger. News stories and commentaries appearing in La Paz press almost daily. Meeting and its importance being noted to mission personnel by leading Bolivians. Foreign Ministry officials state they working hard on positions for each agenda item and hope to have constructive and active Bolivian participation in sessions. Embassy believes Bolivian delegation will be helpful in conciliatory role and in drafting committees where felicitous choice of phraseology is important.

2. Major recurring theme, virtually a consensus, is belief that meeting with Secretary Kissinger is major opportunity to strengthen US-Latin relations. Most Bolivians express open admiration for Secretary's accomplishments and for his boldness in tackling and solving seemingly impossible international problems.

3. While we are gratified by rising attention to Foreign Ministers' meeting, there is risk that Bolivians may be expecting something dramatic to occur in our relations immediately and thus may be disappointed if results of meeting do not match their aspirations. Other difficulty in local interest about meeting with Secretary is generalized assumption that he will "solve" Cuban problem. Although official GOB policy remains anti-Cuba, which most Bolivians share, there is often stated view that Cuban problem is ready-made for Secretary's style of diplomacy.

4. We sense the following general views of the GOB:
    A. Poorer nations deserve greater share of lending agencies resources at long-term low interest rates;
    B. Less developed countries should have preference in markets of industrialized nations;
    C. Countries producing basic commodities should have guaranteed protection against sudden and sharp drops in prices or compensation mechanism to offset balance of payments losses;
    D. Arrangements should be made to continue to supply food to those countries having chronic deficit in domestic production of such commodities as wheat;
    E. Industrialized countries should establish means of holding down prices of machinery exports so that terms of trade will be more favorable to LDCs.
    F. Some compensation should be awarded Bolivia by other nations from their exploitation of resources from the sea, since Bolivia has been deprived of her seacoast.
    G. Hemispheric support for Bolivia's claim to an outlet to the Pacific should be forthcoming in the same way that Panama obtained hemispheric support for its claim against USG.

5. If Bolivian Foreign Minister were to have bilateral meeting with Secretary Kissinger, he could be expected to make following points:
    A. Bolivia is friend of U.S.;
    B. Bolivia is target for international communist agitation to establish new base of intrigue and conspiracy on continent;
    C. GOB wishes to have another program loan to finance economic and social development projects managed by the Presidency;
    D. GOB is unhappy at slow deliveries of military equipment in our military assistance programs;
    E. GOB would like US support of Bolivia's aspirations to regain a passage to the sea and to have her own seaport;
    F. Inter-American system should not be dominated by large Latin American countries;
    G. US should take more active role in hemisphere affairs, stepping up its cultural, military, political, and economic programs, especially in the less developed countries;
    H. While admitting price of tin currently high, still Bolivia needs such prices. If tin price drops, GSA sales is partly to blame, so US should consider compensation.

Comment: Really key issues for Bolivia are under paragraph 4C and G. No blast on GSA sales from stockpiles anticipated.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00878

- **Date:** February 08, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PRESS COMMENTS, MEETING AGENDA, FOREIGN RELATIONS, LESS DEVELOPED COUNTRIES, FOREIGN MINISTERS
