---
title: "Padilla Passes The Baton To Guevara Who Promises Government Of National Conciliation"
author: "And The Future."
date: "August 08, 1979"
editor: visual
cable-date: "August 08, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Niact Immediate 7642"
cable-info: "Oct-01 Ads-00 Ciae-00 Pm-05 H-01 Inr-10 L-03 Nsae-00 Pa-01 Sp-02 Ss-15 Ha-05 Aid-05 Trse-00 Eb-08 Omb-01 Sph-01 Io-14 Nsce-00 Sso-00 Icae-00 Inre-00 /087 W ------------------123774 082206z /73"
cable-subject: "Padilla Passes The Baton To Guevara Who Promises Government Of National Conciliation"
cable-tags: "PINT, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ06747"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "INAUGURATION, INTERIM GOVERNMENT, SPEECHES"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1.  **Summary:** In a simple, moving ceremony Walter Guevara Arze took the oath of office as interim president of Bolivia at 1pm on August 8, and was promptly given a bear hug by outgoing President General David Padilla -- the emotional centerpiece of the ceremony. Padilla's receding speech stressed that he and the armed forces had now done exactly what they promised to do -- restore Bolivia to constitutional rule. Guevara promised a government of national conciliation, but regretted that apparently not all groups would participate in his yet-to-be formed cabinet. His major tasks, Guevara said, will be confronting Bolivia's economic crisis and reforming the electoral laws to provide for a second round popular vote in the May 1980 elections. This modest inauguration and its indications of the pragmatic evolution of Bolivia's young democracy are most encouraging for U.S. interests. End summary.

2.  (U) Interim president Guevara's inauguration address was short and conciliatory. He noted that his government emerged from exceptional circumstances, a deadlocked indirect election, and commended the flexibility and maturity of the major party leaders in resolving an impasse that in other eras of Bolivian history would have ended in violence.

3.  (U) His political task, Guevara said, was to avoid confrontations and violent solutions. His government should therefore be a symbol of national consensus, and his central task would be to consolidate the constitutional process already in train and to resolve some of the political and administrative problems that have been postponed. In that regard he enlisted the support of all sectors -- the parties, the armed forces and the unions -- and emphasized their right to speak out and propose their own ideas in participating in the resolution of Bolivia's problems. He proposed to reform the electoral system to create an independent electoral authority, to install a modern system to tabulate promptly the results of the popular vote and to provide a second round popular vote if necessary to assure that a candidate gets a majority of the popular vote.

4.  (U) Guevara called for unity and strength within the armed forces to reinforce the constitutionalization process. He paid special tribute to Padilla, noting that the latter's place in Bolivian history had been firmly established, a reference which invoked a strong round of applause.

5.  (U) Of foreign policy, Guevara stated that an effort would be made to resolve the sea outlet problem. Formulas would be developed and submitted to a national consensus. At the same time, Bolivia would maintain a policy of openness in its external relations, emphasizing states and not ideologies. He reaffirmed his country's primary objective of maintaining good relations with its immediate neighbors.

6.  (U) Guevara said his government would examine and attack the causes of Bolivia's economic crisis rather than symptoms. He alluded to the tremendous size of the country's external debt, and lowered production of petroleum and minerals, as well as the crisis in the modern agricultural sector. But he noted that a transitory government could not resolve all the problems. He would propose medium and long term programs to resolve the problems, but emphasized that it was not up to the government alone to tackle them, but everyone's task. He exhorted the Congress, political alliances and fronts, and leaders of all sectors to bring their influence to bear on helping make the right decisions to resolve these problems.

7.  (U) Guevara did imply some specific actions in discussing the great deficit in the country's balance of payments. He said "almost immediate action" was needed to reduce this deficit. He also implied that he would seek renegotiation of Bolivia's external debt, which he termed unsupportable. Guevara also said petroleum product prices have to reflect costs.

8.  (U) In concluding, Guevara said his purposes must be to get Bolivia moving again and build a bridge between the past and the future.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ06747

- **Date:** August 08, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** INAUGURATION, INTERIM GOVERNMENT, SPEECHES