---
title: "Bolivian Power Company"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "May 16, 1979"
editor: visual
cable-date: "May 16, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 6265"
cable-info: "Oct-01 Ara-11 Ads-00 Eb-08 L-03 Aid-05 /035 W ------------------072875 181221z /50 R 161302z May 79"
cable-subject: "Bolivian Power Company"
cable-tags: "EINV, BL"
cable-ref: "STATE 120454"
cable-doc-number: "1979LAPAZ04250"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "INSURANCE, LOAN GUARANTEES, FOREIGN INVESTMENTS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. WE BELIEVE THAT IT WOULD BE WELL TO DELAY UNTIL
AFTER THE BOLIVIAN ELECTIONS CONSIDERATION OF AN OPIC
GUARANTEE FOR THE LOAN DESCRIBED IN REFTEL. IT IS
IMPOSSIBLE TO PREDICT THE ATTITUDE OF A NEW GOVERN-
MENT TOWARD EITHER OPIC LOAN GUARANTEES OR TOWARD
THE STATUS OF BOLIVIAN POWER AS A PRIVATE UTILITY.
SO FAR AS WE ARE AWARE, THE CURRENT GOVERNMENT HAS
NO INTEREST IN BUYING THE COMPANY. ALTHOUGH WE BELIEVE
BOLIVIAN POWER COMPANY OFFICIALS MAY HAVE ATTEMPTED
ABOUT TWO YEARS AGO TO INTEREST THE GOVERNMENT OF
BOLIVIA IN THE PURCHASE OF THE FIRM, THE GOB DID
NOT ELECT TO BUY.


2. THE PADILLA GOVERNMENT, IN ITS CLOSING DAYS IN
OFFICE, IS NOT LIKELY TO BREAK NEW GROUND ON THE
QUESTION OF THE COMPATIBILITY OF OPIC LOAN
GUARANTEES WITH BOLIVIA'S ANDEAN PACT OBLIGATIONS.
IN THE UNLIKELY EVENT THAT THE GUARANTEE WAS
APPROVED BEFORE AUGUST 6, IT WOULD PRESUMABLY
BE SUBJECT TO AT LEAST A DE FACTO REVIEW BY THE
ELECTED GOVERNMENT. WE THEREFORE BELIEVE IT






 171643Z


WOULD BE IN THE INTEREST OF OPIC TO MAKE A DECISION
ON THE GUARANTEE REQUEST LATER IN 1979, FOLLOWING
THE ELECTIONS, AND IN THE BROADER CONTEXT OF A
DISCUSSION WITH THE NEW GOVERNMENT OF OPIC PROGRAMS.
BOEKER




            Sheryl P. Walter 

         Sheryl P. Walter

***

#### Message Attributes

- **Document Number:** 1979LAPAZ04250

- **Date:** May 16, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** INSURANCE, LOAN GUARANTEES, FOREIGN INVESTMENTS
