---
title: "[subject not available]"
author: ""
date: "July 09, 1974"
editor: visual
cable-date: "July 09, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 3593"
cable-info: "Oct-01 Iso-00 Sso-00 Nsce-00 Usie-00 Inre-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-07 Pa-04 Rsc-01 Prs-01 Sp-03 Ss-20 Aid-20 Pc-10 Omb-01 Ciep-02 Ssc-01 Drc-01 /115 W --------------------- 053347"
cable-subject: "[subject not available]"
cable-tags: "P*"
cable-ref: ""
cable-doc-number: "1974LAPAZ04394"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "BIOGRAPHIC INFORMATION, CONSTITUTION, PERSONNEL APPOINTMENTS, ELECTIONS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

Message Text


 091252Z


44
ACTION ARA-20


INFO OCT-01 ISO-00 SSO-00 NSCE-00 USIE-00 INRE-00 CIAE-00


   DODE-00 PM-07 H-03 INR-10 L-03 NSAE-00 NSC-07 PA-04


   RSC-01 PRS-01 SP-03 SS-20 AID-20 PC-10 OMB-01 CIEP-02


   SSC-01 DRC-01 /115 W
            --------------------- 053347
O R 091233Z JUL 74
FM AMEMBASSY LA PAZ
TO SECSTATE WASHDC IMMEDIATE 3593
INFO USCINCSO


 LA PAZ 4394


TAGS: P*
                     *******************************CALLY, WELL
DISPOSED TO U.S., AND NOT INCLINED TO GO OFF HALF-COCKED ON
SOLUTIONS TO DOMESTIC PROBLEMS. ADDITIONAL BIOGRAPHIC
INFORMATION WILL BE SENT ASAP.


3. PRESIDENT ALSO ANNOUNCED THAT COUNTRY WOULD BE CONSTITUTIONALIZED
IN 1975. ORDINARILY, THIS WOULD MEAN GENERAL ELECTIONS FOLLOWING SOME
DEGREE OF POLITICAL AMNESTY. HOWEVER, GIVEN EXPECTED FORMATION OF
CONSULTATIVE COUNCIL REFERED TO IN PREVIOUS REPORTING, RULES OF
POLITICAL GAME IN BOLIVIA, INCLUDING THE CONSTITUTION, WILL CHANGE.
THEREFORE, EXACT MEANING OF CONSTITUTIONALIZATION CANNOT BE
DETERMINED
YET, ALTHOUGH IT APPEARS DEFINITE THAT BANZER WILL BE REPLACED
LEGALLY
AT THAT TIME (PRESUMABLY AUGUST 1975).
STEDMAN






<< END OF DOCUMENT >>




                     

                     


                                                       Message Attributes
Automatic Decaptioning: X
Capture Date: 27 JUL 1999
Channel Indicators: n/a
Current Classification: 
Concepts: BIOGRAPHIC INFORMATION, CONSTITUTION, PERSONNEL APPOINTMENTS, ELECTIONS
Control Number: n/a
Copy: SINGLE
Draft Date: 09 JUL 1974
Decaption Date: 01 JAN 1960
Decaption Note:
Disposition Action: RELEASED
Disposition Approved on Date:
Disposition Authority: martinml
Disposition Case Number: n/a
Disposition Comment: 25 YEAR REVIEW
Disposition Date: 28 MAY 2004
Disposition Event:
Disposition History: n/a
Disposition Reason:
Disposition Remarks:
Document Number: 1974LAPAZ04394
Document Source: ADS
Document Unique ID: 00
Drafter: n/a
Enclosure: n/a
Executive Order: N/A
Errors: n/a
Film Number: D740182-0002
From: LA PAZ
Handling Restrictions: n/a
Image Path:
ISecure: 1
Legacy Key: link1974/newtext/t19740789/abbrzaxq.tel
Line Count: 42
Locator: TEXT ON-LINE, TEXT ON MICROFILM
Office: ACTION ARA
Original Classification: 
Original Handling Restrictions: n/a
Original Previous Classification: n/a
Original Previous Handling Restrictions: n/a
Page Count: 1
Previous Channel Indicators:
Previous Classification: 
Previous Handling Restrictions: n/a
Reference: n/a
Review Action: RELEASED, APPROVED
Review Authority: martinml
Review Comment: n/a
Review Content Flags:
Review Date: 09 SEP 2002
Review Event:
Review Exemptions: n/a
Review History: RELEASED <09 SEP 2002 by kelleyw0>; APPROVED <19 FEB 2003 by martinml>
Review Markings:


US Department of State

30 JUN 2005


Review Media Identifier:
Review Referrals: n/a
Review Release Date: n/a
Review Release Event: n/a
Review Transfer Date:
Review Withdrawn Fields: n/a
Secure: OPEN
Status: NATIVE
Subject: n/a
TAGS: PGOV, BL
To: STATE INFO USCINCSO
Type: TE
Markings:

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04394

- **Date:** July 09, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** BIOGRAPHIC INFORMATION, CONSTITUTION, PERSONNEL APPOINTMENTS, ELECTIONS