---
title: "Interim President Lidia Gueiler"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "November 19, 1979"
editor: visual
cable-date: "November 19, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 9370"
cable-info: "Oct-01 Ads-00 Ciae-00 Pm-06 H-01 Inr-10 L-03 Nsae-00 Nsc-05 Pa-01 Sp-02 Ss-15 Ica-11 Trse-00 Omb-01 /071 W ------------------091830 192328z /75"
cable-subject: "Interim President Lidia Gueiler"
cable-tags: "PINT, PINS, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ09990"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "PRESIDENT, INTERIM GOVERNMENT, BIOGRAPHIC INFORMATION"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


2. Lidia Gueiler Tejada, chosen by the Congress to serve as Bolivia's interim president until Aug 6, 1980, is, by her own account, "not a great intellectual," but rather a "revolutionary woman" guided by the experience of "30 years of struggle." Although she previously served as president of the Chamber of Deputies (and as acting chairperson of the bicameral Congress), Ms. Gueiler is not a very well known politician. Her roots are in the Nationalist Revolutionary Movement (MNR), which she joined when it began to gather force in 1946. Regarded for many years as "leftist" and labor-oriented, she split from the mainstream MNR before the 1960 general elections to help Juan Lechin form the Revolutionary Party of the National Left (PRIN). In early 1978, she veered away from Lechin to found her own PRIN faction. In 1979, she and her small band of followers became affiliated with Victor Paz Estenssoro's MNR alliance. Her subsequent emergence as president of the lower house--a circumstance that led to her being selected Chief of State on Nov 16--was more attributable to Paz' machinations than to any of her own.

3. A secretary and accountant by training, Gueiler early achieved recognition through her willingness to adopt and defend labor and far left political positions. At the same time, however, she is not widely regarded as an ideologue or dogmatist--particularly since assuming the chairmanship of the Congress. Perhaps of interest in this regard, she recently told an EMBOFF that she had come to realize that contentious social and economic issues take on more complex dimensions when one is in a position of responsibility. Her leadership in Congress has been steady, at times courageous, but never brilliant. Some of her critics maintain that she is "controlled" by Victor Paz; others that she is guided by Beijing-line Communist leader Oscar Zamora, with whom, in a non-doctrinaire fashion, she has been politically associated in the past. Given the heavy influx of MNR Alliance figures into her cabinet, the Embassy's assumption at this juncture is that Paz' influence will be greatest. But Ms. Gueiler is a strong-willed woman, and, insofar as she feels within her depth, she will probably try to plot her own course.

4. More checkered is Ms. Gueiler's personal history, which, inevitably, has been distorted by rumor and deliberate slander. In the early 1960's, for example, while serving as Bolivia's Charge d'Affaires in Bonn, she reportedly was declared non grata, perhaps for trying to propagate her political views or for engaging in contraband. Twice divorced, she married her first husband, a Paraguayan surnamed Perez, when he was being held prisoner in Cochabamba during the Chaco War. Her second husband, Edwin Moeller, currently heads up a rival PRIN faction which was affiliated with Hernan Siles' UDP in the last elections. Prior, between and after her marriages, Ms. Gueiler is widely rumored to have engaged in liaisons with a number of prominent political figures. While these stories may not be true, they have conferred on her a "racy" reputation which her appearance would otherwise belie. According to biographic data now circulating in La Paz, she was born on Aug 28, 1926. We estimate that this date is about ten years off. She has at least one daughter, Maria Teresa Perez Gueiler, about 45, and a grandson studying at a university in Florida.

5. In addition to some of the above information, Ms. Gueiler's curriculum vitae lists these accomplishments:
--Primary and commercial studies in Cochabamba at the Instituto Americano (degree in accounting).
--Languages: Quechua, German (fair) and English (fair).
--Joined MNR in 1946.
--Subsecretary of Ministry of Peasant Affairs.
--Twice Lower House deputy.
--Charge d'Affaires in Bonn.
--Chief of departmental "command" (Cochabamba) of MNR.
--Chief of national command of MNR.
--Author of book entitled "Women and Revolution."
--Candidate for Vice President of the Republic.
--Vice President of the Leftist Revolutionary Front (FRI).
--Invited to visit Albania and the People's Republic of China as representative of the Bolivian Woman's Union.
--President of the Chamber of Deputies.
--President of the Congress.
--Interim President of Bolivia.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ09990

- **Date:** November 19, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** PRESIDENT, INTERIM GOVERNMENT, BIOGRAPHIC INFORMATION
