---
title: "Sidersa Seeks Embassy Help To Hire Consultants"
author: "Stedman"
date: "September 06, 1974"
editor: visual
cable-date: "September 06, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 4150"
cable-info: "Oct-01 Ara-16 Iso-00 Drc-01 Rsc-01 /030 W --------------------- 054101 R 061930z Sep 74"
cable-subject: "Sidersa Seeks Embassy Help To Hire Consultants"
cable-tags: "EMIN, BEXP, BL"
cable-ref: "CAP, LA PAZ A-150"
cable-doc-number: "1974LAPAZ05801"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "IRON, DATA, MINING, STEELS, INDUSTRIAL PLANTS, MANAGERS, CONSULTANTS, METALLURGY, PROGRAMS (PROJECTS)"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. EMB OFF RECEIVED WRITEEN REQUEST FROM JAVIER SALINAS R.,
TECHNICAL MANAGER SIDERSA, TO HELP FIND THREE AMERICAN EXPERTS,
ONE EACH FOR FOLLOWING FIELDS: (1) IRON-STEEL METALLURGY, (2)
OPEN CUT MINING ON MUTUN HEMATITE DEPOSIT, AND (3) EVALUATOR OF
IRON-STEEL METALLURGICAL FPROJECT WITH EXPERIENCE IN MARKETING
IRON-STEEL PRODUCTS. CONTRACTS TO START NOVEMBER, 1974 SCHEDULED
FOR THREE MONTHS BUT COULD BE EXTENDED TO FIVE MONTHS. NO SALARIES
OR FEES MENTIONED. USDOC ACTION REQUEST: ADVERTISE SIDERSA'S
REQUEST IN COMMERCE TODAY AND IN ANY OTHER APPROPRIATE MANNER.


2. REPLIES BY INTERESTED EXPERTS SHOULD BE ADDRESSED TO ING.
JAVIER SALINAS R., GERENTE TECNICO, EMPRESA SIDERURGICA BOLIVIANA
S.A., AVENIDA 16 DE JULIO 1769, LA PAZ, BOLIVIA: TELEGRAPH
ADDRESS-SIDERSA, CASILLA 7082, LA PAZ, BOLIVIA.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05801

- **Date:** September 06, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** IRON, DATA, MINING, STEELS, INDUSTRIAL PLANTS, MANAGERS, CONSULTANTS, METALLURGY, PROGRAMS (PROJECTS)