---
title: "Export Competition: Large Tractors"
author: "Stedman"
date: "May 07, 1974"
editor: visual
cable-date: "May 07, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3008"
cable-info: "Oct-01 Ara-16 Iso-00 Aid-20 Ciae-00 Come-00 Frb-02 Inr-10 Nsae-00 Rsc-01 Trse-00 Xmb-07 Opic-12 Sp-03 Ciep-02 Lab-06 Sil-01 Omb-01 Str-08 Drc-01 Agr-20 /122 W --------------------- 061662 R 071236z May 74"
cable-subject: "Export Competition: Large Tractors"
cable-tags: "BEXP, BL"
cable-ref: "LA PAZ A87"
cable-doc-number: "1974LAPAZ02898"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. EMBASSY JUST COMPLETED BUSINESS AND ECONOMIC SURVEY OF
36 BOLIVIAN FIRMS WHICH REVEALED THAT ONE OF MAIN OBSTACLES
TO U.S. EXPORTS TO BOLIVIA IS GROWING DELIVERY DELAY.


2. TRADE SOURCE RECENTLY POINTED UP THIS PRBOLEM BY SUGGESTING
THAT RECENT ARRANGEMENT BY LOCAL REP AT FIAT OF ITALY MAY RESULT
IN LOSS TO U.S. OF LARGE PART OF GROWING BOLIVIAN MARKET FOR
EARTH-MOVING TRACTORS OF D-6 AND D-7 SIZE. MAIN ELEMENT OF
ARRANGEMENT IS GOB DECREE AUTHORIZING BANCO AGRICOLA GUARANTEE
75 PERCENT OF FINANCING COST OF IMPORTING 50 FIAT AD-20
TRACTORS FROM ITALY. GUARANTEED AMOUNT PUT AT NEARLY US$2
MILLION.


3. LOCAL TRADE SOURCE SEES DECREE AS DEVICE TO ASSURE FIAT
OF LARGE SALE IF DELIVERY MADE WITHIN 90 DAYS AS SPECIFIED
IN DECREE. NOTES U.S. SUPPLIERS INDICATING DELIVERY TIME OF ABOUT
18 MONTHS AND CONCLUDES U.S. MAY LOSE MARKET DUE LONGER DELIVERY






 071508Z


TIME.




                       

                  

STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02898

- **Date:** May 07, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a