---
title: "Bolivia's Petroleum Production - Exports & Gas Exports For First Four Months Of 1974"
author: "Page 02 La Paz 03851 131450z"
date: "June 12, 1974"
editor: visual
cable-date: "June 12, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3396"
cable-info: "Oct-01 Ara-16 Iso-00 Nea-14 Ciae-00 Inr-10 Nsae-00 Rsc-01 Come-00 Feae-00 Omb-01 Trse-00 Str-08 Int-08 Drc-01 /071 W --------------------- 012274 R 122117z Jun 74"
cable-subject: "Bolivia's Petroleum Production - Exports & Gas Exports For First Four Months Of 1974"
cable-tags: "ENRG, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ03851"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PETROLEUM PRODUCTION, PETROLEUM, EXPORT DATA, PRICE TRENDS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. FOLLOWING STATISTICS OBTAINED FROM Y.P.F.B. ARE ONLY FOR
FIRST FOUR MONTHS OF 1974 COMPARED TO SAME PERIOD IN 1973.
PETROLEUM PRODUCTION FOR PERIOD IN 1974 DECLINED TO 5,229,035
BARRELS COMPARED TO 5,752,980 IN 1973. PETROLEUM EXPORTS
ALSO DECLINED 1,010,934 BARRELS FROM 4,876,175 IN 1973
TO 3,8YTNWRQ IN 1974. HOWEVER, VALUE OF PETROLEUM EXPORTS
INCREASED IN PERIOD FROM US$ 11,63 MILLION IN 1973 TO
US$59.98 MILLION IN 1974.


2. GAS EXPORTS TO ARGENTINA DURING THIS TIME INCREASED
SLIGHTLY FROM 16,783,715 THOUSAND CUBIC FEET (TCF) IN 1973
TO 16,791,667 TCF IN 1974. VALUE OF GAS EXPORTED IN SAME
PERIOD IN 1974 IS US$ 7,023,958 COMPARED TO US$ 4,671,961
IN 1973.


3. COMMENT: WHILE CURDE PRODUCTION ABOUT 9.1 PERCENT LESS IN
FIRST FOUR MONTHS, EXPORTS ABOUT 20.7 PERCENT LESS. WE
WILL ATTEMPT OBTAIN MORE INFORMATION TO ESTABLISH
TO WHAT EXTENT CONSUMPTION AND STOCKS MAY HAVE INCREASED.
BREWIN






 131450Z

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03851

- **Date:** June 12, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PETROLEUM PRODUCTION, PETROLEUM, EXPORT DATA, PRICE TRENDS