---
title: "President Banzer Comments To Ambassador On Soviet Offers Of Military Equipment"
author: "Stedman"
date: "June 21, 1974"
editor: visual
cable-date: "June 21, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3470"
cable-info: "Oct-01 Iso-00 /031 W --------------------- 111235 R 211247z Jun 74"
cable-subject: "President Banzer Comments To Ambassador On Soviet Offers Of Military Equipment"
cable-tags: "PFOR MASS BL UR"
cable-ref: ""
cable-doc-number: "1974LAPAZ04041"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "28 MAY 2004"
cable-concepts: "PRESIDENT, MILITARY EQUIPMENT, MILITARY PROCUREMENT, TECHNICAL ASSISTANCE, ECONOMIC ASSISTANCE, MEETINGS,"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. DURING CALL I MADE JUNE 20 ON PRESIDENT BANZER FOR ANOTHER
PURPOSE, I INDICATED THAT I HAD HEARD THAT BOLIVIAN MILITARY
OFFICERS WERE EXPLORING POSSIBLE EQUIPMENT PURCHASES FROM
EUROPEAN COUNTRIES AND THAT ONE OFFICER HAD RECEIVED OFFERS OF
COMMUNICATIONS EQUIPMENT AND TANKS FROM THE SOVIET UNION. I
INDICATED THAT I DID NOT KNOW VERY MUCH ABOUT THIS MATTER BUT
HAD HEARD THAT THE BOLIVIAN ARMY WAS INTERESTED IN TANKS SINCE
THEY HAD BEEN IN TOUCH WITH US RECENTLY. PRESIDENT BANZER PICKED
UP MY REMARKS AND SAID THAT COL. RIVERA HAD MADE A TRIP FOR
OTHER PURPOSES TO EUROPE AND HAD MADE A VISIT TO THE SOVIET
UNION WHERE HE HAD RECEIVED OFFERS OF SOME MILITARY EQUIPMENT.
PRESIDENT NOTED THAT SOVIET AMBASSADOR TO BOLIVIA HAD BEEN ACTIVE
IN RECENT MONTHS TRYING TO PRESS MILITARY EQUIPMENT ON BOLIVIA
AND ALSO HAD BEEN ACTIVE IN OFFERING SOVIET FINANCIAL AND
TECHNICAL COOPERATION FOR THE CONSTRUCTION OF THE BALA DAM.
PRESIDENT ALSO INFORMED ME THAT HE WAS PLANNING TO NAME A NEW
AMBASSADOR TO THE SOVIET UNION AND PROBABLY WOULD SEND DR.
RICHARDO ANAYA OF COCHABAMBA. IN THE LATTER CONNECTION, HE SAID
THE SUBJECT HAD COME UP AS TO WHETHER OR NOT BOLIVIA SHOULD
ACCEPT EXCHANGE OF PERSONS PROGRAMS, INCREASED CULTURAL PRESENTA-
TIONS, AND HOW TO DEAL WITH MILITARY EQUIPMENT OFFERS. PRESIDENT
BANZER SAID THAT THERE HAD BEEN NO FORMAL OFFER MADE TO THE GOB
AND THAT THE GOVERNMENT HAD NOT MADE ANY DECISION TO ACCEPT






 211825Z


SOVIET EQUIPMENT. PRESIDENT SAID, ON HIS OWN VOLITION, THAT THE




                        

                  

GREAT DIFFICULTY WITH SOVIET EQUIPMENT, EVEN IF IT IS A GIFT, IS
THAT IT GENERALLY COMES ACCOMPANIED BY TECHNICIANS WITH OTHER
INTERESTS. HE SAID HIS OWN EXPERIENCE WITH THE SOVIETS HERE IN
BOLIVIA WAS THAT HE HAD TO KICK OUT SEVERAL MEMBERS OF THE SOVIET
MISSION FOR INTELLIGENCE ACTIVITIES. BUT, SAID PRESIDENT BANZER,
THE PROBLEM IS THAT THE MORALE OF THE BOLIVIAN ARMY IS DEPENDENT
UPON YOUNGER OFFICERS HAVING RELATIVELY NEW EQUIPMENT TO WORK
WITH. GOB HAS NO INTENTION OF USING MILITARY EQUIPMENT, BUT
THERE IS A NEED TO BOOST MORALE IN THE TROOPS. HE SAID THE
BEST WAY TO COUNTER THE SOVIET PRESSURE FOR BOLIVIA TO ACCEPT
THEIR MILITARY EQUIPMENT IS FOR THE PROMPT DELIVERY BY FRIENDLY
COUNTRIES OF ITEMS APPROPRIATE FOR THE BOLIVIAN MILITARY.


2. PRESIDENT BANZER SAID THAT HE KNEW QUITE A BIT ABOUT THE
TANK SITUATION AS THAT WAS HIS BASIC MILITARY SPECIALTY, HAVING
BEEN TRAINED IN THIS IN THE U.S. HE SAID HE KNEW THE M-48 BUT
CONSIDERED IT TOO HEAVY FOR BOLIVIA. HE VOLUNTEERED THAT HE KNEW
THAT THE M-41 WAS NO LONGER AVAILABLE. IN SUM, HE SAID THAT HE
WAS WELL AWARE THAT THE U.S. NO LONGER PRODUCES A MEDIUM SIZE
TANK APPROPRIATE FOR BOLIVIA. ACCORDINGLY HE SAID THAT IT WOULD
BE AN APPROPRIATE ALTERNATIVE IF WE WERE TO PROVIDE FOR BOLIVIAN
PURCHASE OF "CARROS DE ASALTO." HE SAID THAT HE HAD PERSONALLY
PURCHASED SOME EQUIPMENT FROM CADILLAC-GAGE AND FELT THAT LATE
MODELS OF ASSAULT CARS WOULD SATISFY THE MORALE NEEDS OF THE
BOLIVIAN ARMY. I ASKED HIM DIRECTLY WHETHER HE FELT TAHT US SALE
OF ASSAULT VEHICLES OF THIS SORT WOULD ELIMINATE ANY INTEREST IN
TANKS OFFERED BY OTHER COUNTRIES. HIS REPLY, WHILE SOMEWHAT
ELLIPTICAL, WAS BASED ON THE FINANCIAL ASPECT OF OTHER COUNTRIES'
OFFERS. HE NOTED IT WOULD BE MOST DIFFICULT FOR BOLIVIA TO PASS
UP WHAT MIGHT AMOUNT TO A GIFT. HE SAID THAT HE WOULD HAVE
DIFFICULTIES WITH YOUNGER MEMBERS OF THE ARMED FORCES WERE HE TO
REFUSE TO ACCEPT EQUIPMENT FROM OTHER SUPPLIERS AT LITTLE OR NO
COST, ALTHOUGH HE HIMSELF DID NOT WISH TO HAVE OTHER COUNTRIES'
TECHNICIANS PHYSICALLY PRESENT IN THIS COUNTRY. THE WAY HE LEFT
THE SUBJECT WAS THAT PROMPT DELIVERIES OF PROGRAMMED AND
SUITABLE MILITARY EQUIPMENT FROM OTHERS WOULD REDUCE SOVIET
PRESSURES TO GIVE EQUIPMENT AND ANY JUNIOR MILITARY OFFICERS
DESIRES TO HAVE SUCH EQUIPMENT.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04041

- **Date:** June 21, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 28 MAY 2004

- **Concepts:** PRESIDENT, MILITARY EQUIPMENT, MILITARY PROCUREMENT, TECHNICAL ASSISTANCE, ECONOMIC ASSISTANCE, MEETINGS,
