---
title: "Iv Program"
author: "Stedman"
date: "March 08, 1974"
editor: visual
cable-date: "March 08, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2478"
cable-info: "Oct-01 Ara-10 Iso-00 /015 W --------------------- 037000 R 081446z Mar 74"
cable-subject: "Iv Program"
cable-tags: "EOXC"
cable-ref: ""
cable-doc-number: "1974LAPAZ01433"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. POST REQUESTS ASSISTANCE EITHER THROUGH PARTIAL
LEADER GRANT OR VOLUNTARY VISITORS'S BUREAU AND USIS
LA PAZ FUNDS FOR ARTURO CANDARILLAS GALZARZA, HIGHLY-
RESPECTED REPORTED FOR LA PAZ NEWSPAPER HOY TO PERMIT HIM TO
VISIT NEWSPAPERS AND OTHER INSTITUTIONS US EAST COAST
FOR PERIOD UP TO TWO WEEKS FOLLOWING HIS PARTICIPATION
APPLIED COMMUNICATION SEMINAR SPONSORED BY AIRLIE
FOUNDATION MARCH 17 TO 21.


2. CANDARILLAS, BORN ORURO NOVEMBER 30, 1937, DOES
SPECIAL FEATURES FOR HOY. HAS NEVER BEEN OUT OF
BOLIVIA AND SPEAKS NO ENGLISH. POST BELIEVES EXPOSURE
TO US INSTITUTIONS AND COLTURE WOULD BE BENEFICIAL
COUNTRY OBJECTIVES. HE IS ESPECIALLY INTERESTED
PROBLEM OF CUBAN EXILES IN MIAMI AREA. SHOULD ALSO
VISIT USIA


3. AIRLIE FOUNDATION PAYING TRAVEL EXPENSES. PROGRAM
ASSISTANCE WOULD REQUIRE ONLY PER DIEM AND INTERPRETER
ADVISE SOONEST IF POSSIBLE ARRANGE PROGRAM FOR HIM FOLLOWING
SEINAR AT AIRLIE HOUSE.






 081528Z


CLEARANCE PENDING.




                       

               

STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01433

- **Date:** March 08, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a