---
title: "Banzer Goes On Trial Before Congress"
author: ""
date: "August 31, 1979"
editor: visual
cable-date: "August 31, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 7997"
cable-info: "Oct-01 Ads-00 Ha-05 Sy-05 Sye-00 Ciae-00 Nsae-00 Nsce-00 Sso-00 Icae-00 Inre-00 Acda-12 Io-14 Anae-00 Aid-05 Pm-05 H-01 Inr-10 L-03 Pa-01 Inc-01 Sp-02 Ss-15 /095 W ------------------033175 011257z /41"
cable-subject: "Banzer Goes On Trial Before Congress"
cable-tags: "POINT, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ07472"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "TREASON TRIALS, CENTRAL LEGISLATURE, POLITICAL LEADERS, COURT PROCEEDINGS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1.  **Summary:** On August 30 former President Hugo Banzer went on trial before the Congress. This is the sixth such trial in Bolivian history since 1857, and none so far has resulted in convictions. On the eve of the hearing several political parties expressed solidarity with the proceedings. That same day, Banzer went on television to defend his regime and pledge he would go along with the verdict of the people and history. On the first day of the trial, PS-1 Deputy Marcelo Quiroga presented the lengthiest and most detailed of the two accusations made in the time span allowed. While no one can predict at this time how these proceedings will end, the possibility exists that the process—particularly if the Armed Forces become involved as an institution—could jeopardize the consummation of Bolivia's transition to democracy.

2.  **Introduction:** If any informed observer of Bolivia had predicted in the summer of 1977—at the very height of the Hugo Banzer dictatorship—that in only two years a constitutionally-elected Congress would have President Banzer on trial for high treason, misuse of funds, and violation of human rights, the observer would have been regarded as something of a doomsday freak. We are not aware that anyone made such a prediction, but the event, highly unlikely in 1977, is now taking place, for the much heralded trial in the Congress began August 30, 1979. It is the sixth time since 1857 that trials of high government officials have taken place. No convictions have ever occurred.

3.  **Background:**
    A. In 1857, General Cordova's entire cabinet was charged with violating the Constitution and the civil rights of the people. The Congress dismissed the charges. In 1893, similar accusations against President Mariano Baptista—one of Cordova's accusers—were also dismissed by the Congress. That same year, General Daza was accused of treason during the war with Chile, graft, and violation of the Constitution. He was never tried. Returning from Europe to defend himself, Daza was assassinated in 1894. José Manuel Pando and his cabinet was charged in 1913 with the same crimes as Cordova and Baptista, and like them was never tried. Finally, in 1917, the trial of President Ismael Montes led to a riot that kept his accusers away from the Congress. He too escaped prosecution.

    B. Presently, charges against public officials can be brought under the 1967 Political Constitution, and the Law of Responsibilities (passed October 23, 1944, modifying a similar law enacted October 31, 1884). The process calls for:
    - Accusations against a President or other high government officials "for crimes committed in the exercise of their functions" must be presented in open session to the Congress;
    - Afterwards, the matter is to be promptly referred to a special commission to study the evidence, and within 15 days, present Congress a recommendation to either dismiss or sustain charges;
    - The accused may defend themselves in person or through deposition. Once their defense is heard, Congress must decide, by a two-thirds vote, whether to dismiss charges or refer the matter to the Supreme Court. (Note: The Congress is not bound by the commission's recommendation.)
    - The Supreme Court, acting on evidence and testimony previously presented, issues a decision and imposes a sentence.

    C. In preparation for the trial of the former President, the Congress petitioned the GOB to provide detailed information on persons detained, persecuted, and exiled during the Banzer years. When given advance notice of this request, the press reports the Interior Minister asked for 90 days to prepare a reply. Oscar Zamora, MNR Senator from Tarija and PCML leader, reportedly refused to grant the Minister's request and trenchantly suggested the information be expeditiously obtained from Armed Forces J-2 files, which he qualified as the most complete source of political information.

    D. On the eve of the trial, August 29, many political parties appeared in favor of it. Press reports quoted Casiano Amurrio, leader of the PCML and Deputy for Cochabamba, "The MNR alliance is not out for revenge, but only seeks justice be done and the law respected." Qualifying those remarks, Jose Harb, an MNR leader and Deputy for La Paz, cautiously told reporters he could not comment on the position the alliance would take at the hearings. Jaime Tapia Alipaz, ADN leader and Deputy for La Paz, told the press his party will seek to include under the present trial all governments since 1952, particularly the governments of Paz Estenssoro, Siles Zuazo and Ovando. He reasoned these governments repeatedly violated the rights of individuals, and hoped the present trial would prevent recurrence of past errors. Finally, Banzer in a televised statement August 29 defended his regime, asked the trial be conducted in an atmosphere of respect and proper decorum, and claimed he would

***

#### Message Attributes

- **Document Number:** 1979LAPAZ07472

- **Date:** August 31, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** TREASON TRIALS, CENTRAL LEGISLATURE, POLITICAL LEADERS, COURT PROCEEDINGS