---
title: "Recent Developments In Bolivia's Quest For An Access To The Sea. Panama For Uscincso"
author: "Stedman"
date: "April 02, 1974"
editor: visual
cable-date: "April 02, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2714"
cable-info: "Oct-01 Iso-00 Eb-11 Aid-20 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-07 Pa-04 Rsc-01 Prs-01 Sp-03 Ss-20 Usia-15 Io-14 Acda-19 Drc-01 /160 W --------------------- 054034 R 021525z Apr 74"
cable-subject: "Recent Developments In Bolivia's Quest For An Access To The Sea. Panama For Uscincso"
cable-tags: "PINT, PFOR, BL, CI, PE"
cable-ref: ""
cable-doc-number: "1974LAPAZ02024"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "LANDLOCKED COUNTRIES, CHIEFS OF STATE MEETINGS, FOREIGN POLICY POSITION, ACCESS TO PORTS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. **Summary:** President Banzer's mid-March interview with Chilean President Pinochet in Brasilia, where both men were attending the inauguration of Brazilian President Ernesto Geisel, set off a wave of speculative commentary in Bolivia on prospects for realizing the country's long-standing desire to regain an access to the sea. Banzer himself did much to stimulate this renewed upsurge of interest in the historic Bolivian obsession with "returning to the sea" by his optimistic appraisals of the outcome of his talks with Pinochet. Although the Banzer-Pinochet meeting coincided with the beginning of Bolivia's annual "Week of the Sea" celebrations, most Bolivian political observers displayed a new willingness, in the wake of the talks, to put aside patriotic rhetoric in favor of a pragmatic search for possible grounds of agreement with its Pacific coast neighbors. At the same time, however, politicians and government officials alike realized the enormous difficulties facing Bolivia in its efforts to convince Chile and/or Peru to grant it renewed direct access to the sea. The major point upon which both the majority of political observers and the government of Bolivia itself appeared to be in agreement was the necessity for Bolivia to abstain from self-defeating threats of violence, much less actual recourse to physical force, in favor of peaceful, diplomatic initiatives toward resolving the country's century-old landlocked status.

2. The principal theme of political discussion in Bolivia during March 1974 was the renewed prospect for movement on Bolivia's desire for an access to the sea, opened up by the Banzer-Pinochet meeting in Brasilia at mid-month. Even before the two presidents held their widely-publicized "secret" meeting, political observers in La Paz were engaging in intensive speculation about the possibility that such an encounter could produce an improvement in Bolivian-Chilean relations. President Banzer himself lent credence to such speculation upon his return March 19 from the inauguration of President Geisel. According to press accounts, Banzer's initial comments upon his interview with President Pinochet were as follows: Quote "President Pinochet has expressed to me his willingness to seek a solution to the fundamental problems (between Bolivia and Chile), considering that the fundamental problem of Bolivia is its maritime reintegration. He has demonstrated his good will, and let us hope that in a not too distant future we can take positive steps toward the solution of this problem." Quote. Subsequently, in the face of Pinochet's statement that the two presidents had agreed not to discuss Bolivia's desire for a sea outlet, Banzer retreated to the position that he and Pinochet had quote "discussed the fundamental problems that have interrupted our relations (since 1962)" quote but that no specific discussion of possible solutions to Bolivia's landlocked status had taken place.

3. Although the Banzer-Pinochet meeting coincided with the beginning of Bolivia's annual "Week of the Sea", commemorating the loss of its seacoast to Chile in 1879, the tone of the president's remarks appears to have influenced government officials and most political commentators to reduce traditional patriotic rhetoric in favor of a pragmatic search for possible grounds of agreement with Bolivia's Pacific coast neighbors. Thus Jaime Ponce Caballero, secretary-general of the government's Nationalist Popular Front, called upon public opinion to put aside "demagogic slogans" and support the president's quest for improved relations with Chile. A considerable majority of Bolivian journalistic and political opinion also appeared to approve of the initial Banzer-Pinochet conversation, and expressed the hope that working-level talks could soon be initiated between the two countries.

4. While discussion of the prospects for improved Bolivian-Chilean relations predominated in political circles, a number of observers also considered the problem of Bolivia's desire for an outlet to the sea in the larger context of Bolivian-Chilean-Peruvian trilateral relations. Here an atmosphere of pessimism tended to prevail, despite spirited attempts by some commentators to raise the possibility of a summit conference of the three presidents, at which an accord might be reached to grant Bolivia a "corridor" to the sea. More typical of Bolivian views on the attitudes of its western neighbors was the comment of one politician that "Peru is willing to give us an outlet to the sea, through Antofagasta, and Chile will gladly grant us access to the sea through Tacna."

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02024

- **Date:** April 02, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** LANDLOCKED COUNTRIES, CHIEFS OF STATE MEETINGS, FOREIGN POLICY POSITION, ACCESS TO PORTS
