---
title: "Gob Mission To Argentina"
author: "Stedman"
date: "August 09, 1974"
editor: visual
cable-date: "August 09, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3849"
cable-info: "Oct-01 Iso-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-11 L-03 Nsae-00 Nsc-07 Pa-04 Rsc-01 Prs-01 Sp-03 Ss-20 Usia-15 Eb-11 Ciep-03 Aid-20 Iga-02 Come-00 Trse-00 Omb-01 Cu-05 Hew-08 Fea-02 Int-08 Agr-20 Xmb-07 Drc-01 /184 W --------------------- 022213 R 091531z Aug 74"
cable-subject: "Gob Mission To Argentina"
cable-tags: "ENRG, EIND, EAID, BL, AR"
cable-ref: ""
cable-doc-number: "1974LAPAZ05069"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "AGREEMENTS, AMBASSADORS, VISITS, NEGOTIATIONS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. LA PAZ PRESS CARRIED REPORT ON AUG 3 THAT GOB AMBASSADOR
TO ARGENTINA, WALDO CERRUTO, STATED THAT GOB ECONOMIC, EDUCATION
AND CULTURAL MISSION WOULD GO TO BUENOS AIRES AT END OF AUGUST.
CERRUTO REPORTEDLY STATED AGREEMENTS WOULD BE CONCLUDED THAT WOULD
BE MORE IMPORTANT AND ADVANTAGEOUS THAN THOSE RECENTLY CONCLUDED
WITH BRAZIL. THEY WOULD COVER BOLIVIAN GAS, PETROLEUM AND IRON
SALES TO ARGENTINA AND ARGENTINE SALES OF WHEAT, FLOUR, FATS
AND OILS TO BOLIVIA. CERRUTO STATED THAT ARGENTINE ASSISTANCE
(COOPERACION) WOULD BE GREAT ENOUGH TO (A) PERMIT CREATION
OF ANOTHER DEVELOPMENT POLE IN SOUTHERN BOLIVIA, (B) PERMIT
CONSTRUCTION OF TARIJA-BERMEJO-POTOSI ROAD, AND (C) PERMIT
CONSTRUCTION OF FIRST PHASE OF SANTA CRUZ-RIO MAMORE RAILWAY.


2. MININD AYOROA CONFIRMED TO ADCM THAT GOB MISSION WOULD






 091734Z


GO TO BUENOS AIRES AS REPORTED, BUT DOUBTED THAT MUCH WOULD BE




                       

                  

NEGOTIATED IN TERMS OF INDUSTRIAL INVESTMENTS. MINISTER PLACED
GREATEST IMPORTANCE ON NEGOTIATION OF GAS AND PETROLEUM
AGREEMENTS AND ARGENTINE ASSISTANCE FOR ROAD CONSTRUCTION.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05069

- **Date:** August 09, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** AGREEMENTS, AMBASSADORS, VISITS, NEGOTIATIONS
