---
title: "Secretary's Meeting With Latin American Colleagues At Unga"
author: "Stedman"
date: "August 13, 1974"
editor: visual
cable-date: "August 13, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 3888"
cable-info: "Oct-01 Iso-00 Sso-00 Nsce-00 /031 W --------------------- 057039 O 131810z Aug 74r"
cable-subject: "Secretary's Meeting With Latin American Colleagues At Unga"
cable-tags: "PFOR"
cable-ref: "STATE 175342"
cable-doc-number: "1974LAPAZ05155"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "28 MAY 2004"
cable-concepts: "FOREIGN MINISTERS MEETINGS, MEETING DELEGATIONS, INTERNATIONAL ORGANIZATIONS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1.IN ABSENCE FOREIGN MINISTER FROM LA PAZ, SUB-SECRETARY
BOLIVIAN FOREIGN MINISTRI INFORMED ME AUGUST 13 THAT FOREIGN
MINISTER GUZMEK WILL DEFINIETELY ATTEND UNGA. SUBSECRETARY STATED
HIS BELIEF FOREIGN MINISTER WILL WISH TO SHCEDULE HIS TRIP
SO AS TO BE PRESENT FOR SECRETARY KISSINGER'S SOCIAL EVENT
IN NEW YORK. USUALLY FOREIGN MINISTER'S TRAVEL IS GEARED
TO COINCIDE WITH DATE HE SCHEDULED TO MAKE ADDRESS AT UN.
AT THIS TIME THIS DATE IS NOT KNOWN TO THE BOLIVIAN FOREIGN
MINISTRY.


2. SUB-SECRETARY SAID HE WOULD INFORM ME AS PROMPTLY
AS HE COULD OF SPECIFIC PLANS FOR FOREIGN MINISTER'S
TRAVEL AND REQUESTED IN TURN ANY INFORMATION WE MIGHT BE
ABLE TO FURNISH HIM WITH REGARD TO SECRETARY KISSINGER'S
DATE FOR SOCIAL EVENT AND BOLIVIA'S ADDRESS AT UN.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05155

- **Date:** August 13, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 28 MAY 2004

- **Concepts:** FOREIGN MINISTERS MEETINGS, MEETING DELEGATIONS, INTERNATIONAL ORGANIZATIONS
