---
title: "Argentine Overture To Bolvian Foreign Ministry On Cuba"
author: "Stedman"
date: "April 05, 1974"
editor: visual
cable-date: "April 05, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2753"
cable-info: "Oct-01 Iso-00 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-07 Pa-04 Rsc-01 Prs-01 Sp-03 Ss-20 Usia-15 Io-14 Nic-01 Aid-20 Drc-01 /131 W --------------------- 111639 R 051833z Apr 74"
cable-subject: "Argentine Overture To Bolvian Foreign Ministry On Cuba"
cable-tags: "PFOR BL CU AR"
cable-ref: ""
cable-doc-number: "1974LAPAZ02117"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "MEETING AGENDA, FOREIGN RELATIONS, DIPLOMATIC RELATIONS ESTABLISHMENT, FOREIGN MINISTERS MEETINGS,"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Sub-Secretary Bolivian Foreign Ministry told me April 4 that Argentina plans to raise Cuban issue during forthcoming foreign ministers meeting with Secretary of State Kissinger. Argentina intends to organize as much Latin American support as possible for this initiative during prior meeting of Latins at Argentine Embassy in Washington. According to Sub-Secretary, Argentine Ambassador in La Paz called on Foreign Minister on instructions from Buenos Aires and solicited Bolivian support for the initiative, which the GOB did not give.

2. Sub-Secretary said policy of Bolivian Government remains firm that existing OAS restrictions on Cuba should remain. He pointed out that Bolivia one of the countries in the Hemisphere which had suffered at hands of Cuba and that and that Government still convinced that Cuba an active menace in the Hemisphere.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02117

- **Date:** April 05, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** MEETING AGENDA, FOREIGN RELATIONS, DIPLOMATIC RELATIONS ESTABLISHMENT, FOREIGN MINISTERS MEETINGS,