---
title: "Private Voluntary Assistance For Disasters"
author: "Stedman"
date: "April 24, 1974"
editor: visual
cable-date: "April 24, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2907"
cable-info: "Oct-01 Iso-00 Aid-20 Sca-01 Hud-02 Drc-01 Rsc-01 ( Iso ) W --------------------- 056424 R 241324z Apr 74"
cable-subject: "Private Voluntary Assistance For Disasters"
cable-tags: "SGEN OTRA BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ02574"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "DISASTER RELIEF, VISITS, NATURAL DISASTERS, VOLUNTARY AGENCIES"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. PRIVATE WOMEN'S ORGANIZATION, WOMEN'S LEAGUE FOR PROTECTION
OF HUMAN RIGHTS, HAS INQUIRED ABOUT AGENCIES OF USG IN NEW YORK
OR WASHINGTON OR PRIVATE GROUPS WHICH THEIR SECRETARY MIGHT
VISIT IN JUNE TO LEARN HOW PRIVATE ORGANIZATIONS RENDER EFFECTIVE
ASSISTANCE DURING EMERGENCIES. SECRETARY, MRS BALLIVIAN, WILL
TRAVEL IN US ON HER OWN ACCOUNT AND IS CHARGED WITH OBTAINING
INFORMATION TO GUIDE HER ORGANIZATION IN LA PAZ. WOMEN ARE
CONCERNED THAT THEY ARE NOT AS HELPFUL AS THEY COULD BE WHEN
FLOODS AND SIMILAR PROBLEMS STRIKE IN BOLIVIA.


2. GROUP IS COMPOSED OF RESPONSIBLE CIVIC-MINDED BOLIVIAN
LADIES WHO ARE IN SEARCH OF IDEAS. IT OCCURES TO US THAT HUD'S
FEDERAL DISASTER ASSISTANCE ADMINISTRATION AND PERHAPS NATIONAL
CENTER FOR VOLUNTARY ACTION MIGHT BE PREPARED TO RECEIVE MRS
BALLIVIAN EITHERIN WASHINGTON OR NEW ORK TO ADVISE HER.


3. WOULD APPRECIATE ANY INFO YOU MAY BE ABLE TO PROVIDE.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02574

- **Date:** April 24, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** DISASTER RELIEF, VISITS, NATURAL DISASTERS, VOLUNTARY AGENCIES