---
title: "Export 79, Trade Fair Of The Americas, Coconut Grove Exhibition Center, Miami, Fla. July 21-28, 1979"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "March 20, 1979"
editor: visual
cable-date: "March 20, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 5322"
cable-info: "Oct-01 Ara-15 Iso-00 Eb-08 /024 W ------------------116772 202132z /65 P 202045z Mar 79"
cable-subject: "Export 79, Trade Fair Of The Americas, Coconut Grove Exhibition Center, Miami, Fla. July 21-28, 1979"
cable-tags: "BEXP, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ02423"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "n/a"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. Amembassy La Paz interested in promoting subject fair. Please submit 150 brochures in Spanish ASAP.

2. FOMEX (Gob Export Promotion Division) expressed high interest in repeating their successful participation experienced in the 1978 Miami "Trade Fair of the Americas".

3. FOMEX key officials are the following:
Hugo Duchen
Gerente de Operaciones
Banco Central de Bolivia - FOMEX
Casilla 5947
La Paz, Bolivia

Angel Guzman
Jefe de Division FOMEX
Banco Central de Bolivia - FOMEX
Casilla 5947
La Paz, Bolivia

Other officials are:
Cap. Frag. Oscar Pammo

Ministro de Industria, Comercio y Turismo
Ministerio de Industria, Comercio y Turismo
Calle Bueno Esq. Camacho
La Paz, Bolivia

Ing. Carlos Caceres
Sub-Secretario de Comercio

Sheryl P. Walter
Ministerio de Industria, Comercio y Turismo
Calle Bueno Esq. Camacho
La Paz, Bolivia

Sr. Orlando Donoso Torrez
Director de Comercio Exterior
Ministerio de Industria, Comercio y Turismo
Calle Bueno Esq. Camacho
La Paz, Bolivia

***

#### Message Attributes

- **Document Number:** 1979LAPAZ02423

- **Date:** March 20, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** n/a
