---
title: "Property Matter: Ford Pickup"
author: ""
date: "March 14, 1979"
editor: visual
cable-date: "March 14, 1979"
cable-from: "SecState WashDC"
cable-to: "AmEmbassy La Paz Priority"
cable-info: "Oct-01 Iso-00 H-02 /009 R"
cable-subject: "Property Matter: Ford Pickup"
cable-tags: "CPRS: (ILLOBRE, MARIO R.)"
cable-ref: ""
cable-doc-number: "1979STATE062940"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

Dept recently received inquiry from Congressman Bud Shuster's office regarding Embassy's delay in responding to their letter dated January 23 and directed to attention of Ambassador Boeker. Specifically, Congressman Shuster requested assistance on behalf of Mr. Donald L. Beaver in securing release from customs officials in Santa Cruz, a 1979 Ford pickup truck, serial no. F14BCDC1583, Pennsylvania registration. Olivet Baptist Church in Bellwood, Pennsylvania, of which Mr. Beaver is a member, purchased truck as a gift to Mr. Mario R. Illobre for his missionary work in Bolivia. Mr. Illobre presently residing at Casilla 1960, Santa Cruz de la Sierra.

Please endeavor to assist him to the greatest extent possible in this matter and provide Congressman Shuster's office with a report on your findings soonest. Vance

***

#### Message Attributes

- **Document Number:** 1979STATE062940

- **Date:** March 14, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** n/a