---
title: "Port Talks End Summary. Three-Day Meeting Of Port Commissions Of Bolivia And Chile Concluded In La Paz September 4. In Subsequent Days Bolivian Press Has Carried Debate Over Whether Talks Success Or Failure. In Attempt At Last Word Fon Off Issued Statement Published Sept. 6 That Chilean Delegations's Agreement To Consider Bolivian Social And Economic Needs When Setting Port Charges Is Clear Advance For Bolivian Interests. End Summary."
author: "Stedman"
date: "September 09, 1974"
editor: visual
cable-date: "September 09, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 4160"
cable-info: "Oct-01 Iso-00 Ciae-00 Come-00 Dode-00 Dote-00 Eb-11 Fmc-04 Inr-11 Nsae-00 Rsc-01 Cg-00 Coa-02 Dlos-07 Swf-02 Pa-04 Usia-15 Prs-01 Sp-03 L-03 Tar-02 Trse-00 Aid-20 Omb-01 Drc-01 /109 W --------------------- 074956 R 091545z Sep 74"
cable-subject: "Port Talks End Summary. Three-Day Meeting Of Port Commissions Of Bolivia And Chile Concluded In La Paz September 4. In Subsequent Days Bolivian Press Has Carried Debate Over Whether Talks Success Or Failure. In Attempt At Last Word Fon Off Issued Statement Published Sept. 6 That Chilean Delegations's Agreement To Consider Bolivian Social And Economic Needs When Setting Port Charges Is Clear Advance For Bolivian Interests. End Summary."
cable-tags: "ETRN, PFOR, BL, CI"
cable-ref: ""
cable-doc-number: "1974LAPAZ05823"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PRESS COMMENTS, PORT CHARGES, MEETINGS, MEETING REPORTS, PRICE TRENDS, RAIL TRANSPORTATION, MEETING"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. BOLIVIANS CALLED FOR MEETING AFTER CHILEAN AUTHORITIES
ONCE AGAIN RAISED PORT AND RAIL CHARGES LAST JUNE. CHILEAN
DELEGATION OF ELEVEN HEADED BY AMBASSADOR HENRIQUE BERNSTEIN MET
WITH BOLIVIAN DELEGATION OF TWENTY-SIX, INCLUDING REPRESENTATIVES
FROM PRIVATE SECTOR.


2. EARLY STATEMENTS STRESS CORDIAL ATMOSPHERE OF TALKS BUT
PRESS CARRIED STORIES DESCRIBING CARGO DELAYS AND MISHANDLING
IN CHILEAN PORTS AND CHARGE THAT RECENT FLOUR SHIPMENTS STORED






 091701Z


IN OPEN AIR HAVE BEEN DAMAGED BY LIGHT RAIN IN ARICA. FRONT-




                        

                  

PAGE STORIES CONCLUDED SEPT. 5 THAT TALKS WERE FAILURE BECAUSE
CHILEAN DELEGATION WAS NOT IN FACT EMPOWERED TO NEGOTIATE
AGREEMENT AND "ONLY PROMISED TO RECOMMEND" TO GOC THAT JUNE
INCREASE IN CHARGES BE TEMPORARILY SUSPENDED. FON OFF
RELEASE POINTED OUT THAT COMMISSIONS AGREED TO MEET AGAIN WITHIN
SIXTY DAYS TO MAKE TECHNICAL STUDY OF NOMENCLATURE AND TARIFF
STRUCTURE, TAKING INTO ACCOUNT FOR FIRST TIME BOLIVIA'S " NEEDS
FOR ECONOMIC AND SOCIAL DEVELOPMENT."


3. COMMENT: PORT CHARGES HAVE BEEN CONTINUAL PROBLEM DUE TO
CHILEAN INFLATION. CHILEAN DELEGATION PROPOSED AND BOLIVIANS RE-
JECTED SUGGESTION THAT CHARGES BE COLLECTED IN U.S. DOLLARS AS WAY


OF AVOIDING NEED FOR FREQUENT ADJUSTMENT. (BOLIVIAN CUSTOMARILY
OBTAIN BLACK MARKET ESCUDOS TO PAY PORT CHARGES.)
BOLIVIA IS SUFFERING ONE OF PERIODIC PORT CRISES WITH LARGE BACKLOGS
OF CARGO IN PERUVIAN PORT OF MATARANI (SEE A-169 OF SEPT 9)
AND APPARENTLY ALSO ARICA.


LATTER PORT HAS RECEIVED LARGE QUANTITY OF FLOUR DESTINED FOR BOLIVIA
AND THIS HAS SLOWED DOWN OTHER SHIPMENT. COMMISSIONS DID NOT DIS-
CUSS LONGER-RANGE SOLUTIONS TO PORT PROBLEMS. BOLIVIANS INSTEAD
TAKE OUT THEIR FRUSTRATIONS ARISING THEIR LACK OF CONTROL OF
OWN FACILITIES BY MAKING SHORT-TERM PRACTICAL SOLUTIONS MORE
DIFFICULT. NEGATIVE PUBLICITY DURING MEETING CAME FROM MINISTRY
OF INDUSTRY AND COMMERCE SOURCES.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05823

- **Date:** September 09, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PRESS COMMENTS, PORT CHARGES, MEETINGS, MEETING REPORTS, PRICE TRENDS, RAIL TRANSPORTATION, MEETING