---
title: "[subject not available]"
author: "Brewin"
date: "May 30, 1974"
editor: visual
cable-date: "May 30, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 3237"
cable-info: "Oct-01 Ara-10 Iso-00 L-03 H-01 Sy-04 Deae-00 Sso-00 /022 W --------------------- 086855 O 301410z May 74"
cable-subject: "[subject not available]"
cable-tags: "CASC, BL, (ROELLE, DANIEL)"
cable-ref: "STATE 111090 AND LA PAZ 2771"
cable-doc-number: "1974LAPAZ03478"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. ROELLE STATUS UNCHANGED SINCE EMBASSY'S REFTEL
ROELLE'S LAWYER VISITED JUDGE TWICE MAY 29 AND JUDGE
STATED THAT DECISION WOULD BE GIVEN MAY 30. CONSULAR
OFFICER IN DAILY CONTACT WITH ROELLE.


2. EMBASSY OBVIOUSLY UNABLE PRESSURE JUDGE FURTHER
EITHER DIRECTLY OR THROUGH OTHERS. THE QUESTION NOW
IS WHETHER JUDGE'S CONTINUING DILATORY TACTICS REFLECT
HIS DESIRE TO PROVE HIS INDEPENDENCE AND HIS PIQUE AT
EMBASSY INTERVENTION OR, AS ROELLE'S LAWYER ASSUMES,
JUDGE IS WAITING FOR AN OFFER OF MONEY FROM THE LAWYER.
IT WHOULD BE NOTED FOR THE RECORD THAT NO OTHER PERSON,
REGARDLESS OF NATIONALITY, OF THOSE ARRESTED HERE SINCE
INCEPTION OF THE NEW NARCOTICS LAW HAS YET BEEN FURTHER
ALONG THE BOLIVIAN JUDICIAL PROCESS THAN HAS ROELLE.
SLOW AND DRAWN-OUT PROCESS ROELLE CASE IS NOT TO BE
TAKEN AS UNUSUAL, ANTI-AMERICAN TREATMENT BUT RATHER
THE NATURE OF THE JUDICIAL PROCESS IN BOLIVIA.
BREWIN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03478

- **Date:** May 30, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a