---
title: "French Bureau Of Geologic And Mining Research Signs Agreement With Ministry Of Mining"
author: "Parker"
date: "August 29, 1974"
editor: visual
cable-date: "August 29, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 4067"
cable-info: "Oct-01 Iso-00 Eur-25 Int-08 Eb-11 Fea-02 Sci-06 Ciae-00 Dode-00 Inr-11 Nsae-00 Pa-04 Rsc-01 Usia-15 Prs-01 Sp-03 Omb-01 Trse-00 Come-00 Aid-20 Drc-01 /130 W --------------------- 098127 R 291600z Aug 74"
cable-subject: "French Bureau Of Geologic And Mining Research Signs Agreement With Ministry Of Mining"
cable-tags: "EMIN, BL"
cable-ref: "LA PAZ 4139"
cable-doc-number: "1974LAPAZ05618"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "EXPLORATION, AGREEMENTS, MINING INDUSTRY, MINERALS, GEOLOGIC SURVEYS"
---

::: cable-meta
:::

# DEPARTMENT OF STATE TELEGRAM

**UNCLASSIFIED**

1.  ON AUGUST 26, 1974 DR. JACQUES J. BOULANGER, DELEGATE OF BUREAU RECHERCHES GEOLOGIQUES ET MINIERES (BRGM) AND FRENCH AMBASSADOR TO BOLIVIA, SIGNED AGREEMENT WITH MIN MINING, COL. JOSE ANTONIO ZELAYA, ENABLING BRGM TO WORK IN BOLIVIA FOR NEXT FIVE YEARS IN CONNECTION WITH MINERAL EXPLORATION AND IN ADVISORY CAPACITIES TO BOLIVIAN ENTITIES IN MINERAL EXPLOITATION AND INVESTIGATIONS.

2.  AGREEMENT DIVIDED IN TWO CLAUSES. FIRST CLAUSE STATES (1.1) BRGM WILL CONTRIBUTE TECHNICAL ASSISTANCE AT REQUEST OF MIN MINING TO ACHIEVE FOLLOWING OBJECTIVES: (1.2) SUPPORT BOLIVIAN TECHNICAL SERVICES: (1.3) INVESTIGATION, DEVELOPMENT AND EVALUATION OF MINERAL RESOURCES IN AREAS CHOSEN BY MIN MINING; (1.4) TRANSFER AND CREATION OF TECHNOLOGY PRINCIPALLY THROUGH FORMATION OF PROFESSIONAL BOLIVIAN PERSONNEL. SECOND CLAUSE STATES (2.1) BRGM WILL CONTRIBUTE ITS ASSISTANCE AND COOPERATION ACCORDING TO

291725Z

FOLLOWING MANNERS; (2.2) THROUGH PROVIDING SERVICES

REQUIRED BY ANY MINING ENTITY WHICH WILL CONTRACT BASES AND CONDITIONS WITH BRGM; (2.3) PARTICIPATION BY BRGM IN INVESTIGATION PROGRAMS FOR BEST EXPLOITATION METHODS OF MINERAL DEPOSITS WITH ANY ENTITY LEGALLY ORGANIZED LEAVING BOTH PARTIES TO AGREEE ON BASES AND CONDITIONS OF CONTRACT.

3.  BRGM - MIN MINING AGREEMENT TO LAST FIVE YEARS AND MAY BE EXTENDED BY AGREEMENT OF BOTH PARTIES. PARKER

------------------------------------------------------------------------

#### Message Attributes

-   **Document Number:** 1974LAPAZ05618

-   **Date:** August 29, 1974

-   **Classification:** UNCLASSIFIED

-   **Declassified:** 01 JAN 1960

-   **Concepts:** EXPLORATION, AGREEMENTS, MINING INDUSTRY, MINERALS, GEOLOGIC SURVEYS
