---
title: "Visit To Washington--Dr. Marcos Lezama, Venezuelan Writer"
author: "Stedman"
date: "March 25, 1974"
editor: visual
cable-date: "March 25, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2639"
cable-info: "Oct-01 Iso-00 Prs-01 Pa-04 Usia-15 Cu-04 Ss-20 Nsc-07 Cpr-02 Io-14 Drc-01 Rsc-01 /090 W --------------------- 090019 R 252052z Mar 74"
cable-subject: "Visit To Washington--Dr. Marcos Lezama, Venezuelan Writer"
cable-tags: "OTRA VE BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ01828"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Dr. Marcos Lezama, a Venezuelan national who is president of the Fundacion Bolivariano, called at the Embassy on March 25 to indicate that he was planning to visit Washington on or about April 1. He indicated that he would participate in a ceremony in which a medal would be presented to AOS Secretary-General Galo Plaza. He indicated that he and the Ambassadors in Washington of the Bolivarian countries would be requesting an appointment with Secretary Kissinger.

2. Dr. Lezama has been in and out of La Paz frequently in recent months. He presided over a ceremony in which President Banzer was given the Good Citizenship Award of the Fundacion Bolivariano. Most recently he has been here as the head of a conference setting forth Bolivia's claim for a seaport on the Pacific Coast. In his conversation at the Embassy, he cited his great friendship for the US, his knowledge of many leading Americans, and his earnest desire to strengthen US/Latin American ties. He said that he is a writer and the owner of a radio station in Caracas, Venezuela.

3. Dr. Lezama confined his visit to the Embassy to matters of courtesy and provided information about his trip without requesting any assistance or favors.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01828

- **Date:** March 25, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a