---
title: "(S) The Padilla Government - A Balance Sheet Of Negatives"
author: ""
date: "March 08, 1979"
editor: visual
cable-date: "March 08, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 5135"
cable-info: "Oct-01 Iso-00 Ciae-00 Pm-05 H-01 Inr-10 L-03 Nsae-00 Nsc-05 Pa-01 Sp-02 Ss-15 Ica-11 Ha-05 Io-14 Eb-08 Trse-00 Com-02 Aid-05 Omb-01 /104 W ------------------105952 102259z /21 R 082005z Mar 79"
cable-subject: "(S) The Padilla Government - A Balance Sheet Of Negatives"
cable-tags: "POINT, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ02023"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "DEMOCRACY, FORM OF GOVERNMENT"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. **Summary:** The Padilla government and its cabinet of Young Turk generationalist military officers raised high hopes in many quarters with its announcement of elections, its continuation of the upbeat pattern of respect for human rights, and the pronouncements of individual ministers with regard to the return to democratic government, the withdrawal of the armed forces from the political direction of the country back to the barracks, the revamping of public corporations, and the general improvement in the quality of government in Bolivia. While human rights and the electoral process have thus far fared well, the Padilla regime has in the meantime mired itself down in a shabby display of infectious venality and incompetence that has tarnished its image and raised some doubts about its ability to carry forward its well-advertised objectives for Bolivia's democratization.

2. When B/Gen Padilla executed his overthrow of the Pereda regime almost four months ago, a certain euphoria permeated La Paz' notably rarefied air, emanating mainly from among some of the generationalist officers who constituted the underpinnings of the coup. The immediate tension reliever, of course, was the announcement of elections for July 1979 (instead of May 1980), a move which provided a kind of moral justification for the takeover as well as a mandate for constitutionalism which few could challenge. Utterances of reform, elimination of corruption, a restructuring of the government (and public sector corporations in particular) were heard in loose, uncoordinated statements to the press. The prisoners implicated in the previous months coup plotting were released, and the regime appeared off to a good start in both word and deed.

3. Exactly who was in charge was not clear. For a time it appeared that Padilla had ridden the tail of the tiger into power and would ultimately disappear from the scene at the pleasure of the younger officers who had used him as their key instrument. Or was Padilla — nobody's fool — really using these young and ambitious officers, several of whom had been arrested by him only a month previously for plotting, to propel him into the presidency? More than likely, both scenarios were accurate to a degree in that the plotting and execution of the coup as it unfolded revealed a strange coterie of collaborators — conservative Padilla on the one hand, his generationalist officers on the other — who had nothing really in common except the desire to overthrow the incumbent Pereda regime. Surely their reasons were quite different: Padilla wanted personal power, or in any case to avoid being victimized in an overthrow. The most zealous younger officers wanted power, ostensibly for purposes of reform. To determine which side prevailed is only to review what has transpired since last November; i.e., Padilla has accumulated power and encouraged corruption and incompetence in the process; the influence of his generationalist cabinet has waned; and there has been no reform on any front.

4. What can be said in Padilla's behalf is that the election schedule remains firm and that there has been no diminution in the respect for human rights in Bolivia. Indeed, the political process appears to be moving forward as a number of political parties have held conventions, named candidates, and as the government has implemented some significant changes in electoral procedures. One has the clear impression that the Padilla government is sincere in purpose and really means to step down come August 6. Human rights and a democratization process apparently well in train are the two positive entries on the ledger.

5. The negative side of the ledger, however, is bleak with shabby efforts to consolidate power, promote corruption, and burden the civil administration with the appointment of hacks and incompetents in key positions. The problem, of course, is whether ultimately Padilla may not have grabbed another tiger by the tail, i.e., the miring down of his regime in a system of patronage and payoffs involving Bolivia's Armed Forces to the extent that he loses control in the process so that other powerful and conservative forces — not so willing to give up the game and its rewards — see elections and a new government as a clear threat to their interests.

6. **Corruption**
    A. We have good information that the Bolivian Armed Forces have been engaged in rather extensive arms purchases, possibly amounting to some $103 million. A source close to the President informs us that Army Deputy G-4 Lt Col Javier Alcoreza is currently involved in some of the arms purchases arrangements. The source voiced his impression that Padilla stands to profit personally in a very substantial way.
    B. We also know that officers of the Armed Forces of Lt Col or equivalent grade have been accorded an exemption from customs duties for importation of two automobiles each, which in Bolivia could mean a windfall profit from the resale of $15-30,000. This exemption is in addition to the recent influx of illegal automobiles into Bolivia as well as the blatant sale of entry permits for automobiles coming in through Santa Cruz.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ02023

- **Date:** March 08, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** DEMOCRACY, FORM OF GOVERNMENT