---
title: "Ia-Ecosoc Annual Meeting"
author: "Stedman"
date: "March 05, 1974"
editor: visual
cable-date: "March 05, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2426"
cable-info: "Oct-01 Iso-00 L-03 Oic-04 Nsc-07 Ciae-00 Inr-10 Nsae-00 Pa-04 Rsc-01 Usia-15 Prs-01 Spc-03 Eb-11 Aid-20 Trse-00 Come-00 Drc-01 /101 W --------------------- 120164 R 051255z Mar 74"
cable-subject: "Ia-Ecosoc Annual Meeting"
cable-tags: "EGEN, IA-ECOSOC, BL"
cable-ref: "STATE 039787"
cable-doc-number: "1974LAPAZ01329"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "MEETING AGENDA, MEETINGS, MEETING DELEGATIONS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Acting Director Economic Affairs Bolivian Foreign Ministry Ortiz states that GOB still in midst planning for Ninth Annual ECOSOC meeting. He now certain that Sergio Otero, Minister-Secretary of Government Planning Office (CONEPLAN) will lead delegation accompanied by Armando Loayza, CONEPLAN, Eulalio Medina of Foreign Ministry and not yet named reps of MININD/COM and of FOMEX, Bolivian Export Promotion Office.
2. Ortiz promised to discuss GOB position again March 6. Embassy will cable results conversation. For moment he only wished to stress GOB interest in maintaining CIPE, which has given effective assistance to Bolivia. Stedman

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01329

- **Date:** March 05, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** MEETING AGENDA, MEETINGS, MEETING DELEGATIONS