---
title: "Election Day Impressions"
author: "Popular Vote. Boeker"
date: "July 02, 1979"
editor: visual
cable-date: "July 02, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Niact Immediate 0000"
cable-info: "Oct-01 Ads-00 Sso-00 Nsce-00 Inre-00 Icae-00 Ciae-00 Pm-05 H-01 Inr-10 L-03 Nsae-00 Pa-01 Sp-02 Ss-15 /053 W ------------------032945 020934z /10"
cable-subject: "Election Day Impressions"
cable-tags: "PINT, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ05655"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "ELECTION RESULTS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. By all accounts thus far, the July 1 elections have come off extremely smoothly with virtually no violence and few reports of fraud or irregularities. Turnout appears to have been heavy. These may well be the cleanest elections in Bolivia's history, as promised by the Padilla regime from its inception last November.

2. Conagents in Cochabamba and Santa Cruz confirm for their areas what we have heard officially from the Ministry of the Interior as being the situation throughout the country, that the whole process has been peaceful and orderly with only a few incidents of no political significance being reported.

3. According to unofficial results, as of 2300 hours local time July 1, some 578,000 votes had been counted (31 per cent) of the total registered vote. The breakdown is as follows:

    A. Hernan Siles Zuazo (UDP) - 199,000 (34 percent)
    B. Victor Paz Estenssoro (MNR) - 150,000 (26 per cent)
    C. Hugo Banzer Suarez (ADN) - 133,000 (23 per cent)
    D. Marcel Quiroga Santa Cruz (PS) - 52,000 (9 per cent)
    E. Rene Bernal Escalante (APIN) - 28,000 (5 per cent)

4. In the city of La Paz, Siles is leading with 43 per cent of the vote, to win handily in the department, but the big surprise is Banzer's lead over Paz in the city itself.

5. Elsewhere in the Altiplano (Highlands), early returns are as follows:

    A. Oruro - Paz has a narrow lead over Siles (29-28 pct) overall. Final results show that Paz captured the capital city with 30 pct, but most of the countryside vote has not yet come in and could well give the department ultimately to Siles. Bernal appears not to have been a factor in his home department.

    B. Cochabamba - With results thus far only from the city of Cochabamba, Banzer is leading Siles 17,304 to 16,268 with Quiroga Santa Cruz having won 14,506. Paz is fourth with 7,155. With about 20 pct of the countryside vote in, Siles is leading Paz 33 pct to 27 pct with Banzer in third place with 13 pct.

    C. Chuquisaca - Final results from the city of Sucre show Siles won 52 pct followed by Banzer with 14 pct and Paz with 11.5 pct. No results are in yet from the countryside.

    D. Potosi - Siles has a narrow edge over Paz, 41 pct to 39 pct with about 60 pct of the city vote in. Scattered returns from the countryside show both Paz and Siles doing well but with no pattern yet apparent. None of the other candidates appears to be a factor in this department.

6. In the eastern departments of Beni, Santa Cruz, Pando, and Tarija, Paz is, as expected, doing very well, and Banzer surprisingly is beating out Siles for second place. In the Pando, final results from the capital city Cobija show Paz winning 42 pct to Banzer's 33 pct and Siles' 20 pct. In Santa Cruz, Paz is leading in the capital city by 36 pct to 34 pct over Banzer, and apparently doing even better in the countryside. With returns from only three towns, Paz' majorities range from 53 pct to 67 pct. In Paz' home department of Tarija, he was leading in the capital city with 43 pct, and in the countryside with 65 pct of the vote. Finally, in the Beni, with an estimated 55 pct of the total vote in, Paz was leading Banzer 41 pct to 31 pct, with Siles in third place (17 pct).

7. According to officials of the Permanent Assembly on Human Rights (PAHR), there have been very few incidents of fraud or violence thus far reported. The only incident of violence reported involved the theft of three voting boxes Saturday night in the department of Beni. Allegations of fraud have also been few, and, according to the PAHR, minor. The only incident of any importance involved the nullification of the results at two voting stations in Beni because of "irregularities." All radio broadcasts thus far monitored support the impression the election day 1979 was remarkably tranquil throughout the country.

8. **Comment:** The major surprise thus far is Banzer's strength manifested by early returns. This may wane somewhat, however, as returns from the provinces of Potosi, Cochabamba, Oruro and Chuquisaca departments come in where Banzer is generally much less influential. The above overall percentages will therefore fluctuate (somewhat) until the final returns come in, but it would appear at this time that Siles will win his plurality, but not big, and certainly not the majority of the popular vote.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ05655

- **Date:** July 02, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** ELECTION RESULTS
