---
title: "First Lady's Bolivian Schedule"
author: ""
date: "August 02, 1979"
editor: visual
cable-date: "August 02, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 7560"
cable-info: "Oct-01 Ara-11 Ads-00 Opr-02 Ss-15 Sso-00 Sy-05 Sye-00 Usss-00 Oc-06 Cco-00 Cpr-02 Pa-01 /045 W ------------------077842 021848z /41 O 021630z Aug 79"
cable-subject: "First Lady's Bolivian Schedule"
cable-tags: "PDIP, OVIP, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ06614"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "ITINERARY, VISITS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


Subject: First Lady's Bolivian Schedule

Following is Mrs. Carter's La Paz schedule:

Mrs. Carter's visit to La Paz, Bolivia August 4-7, 1979

**Saturday, August 4, 1979**

*   5:30 P.M. U.S. Air Force aircraft arrives El Alto International Airport, La Paz, Bolivia.
    *   Open coverage.
    *   Closed arrival.
    *   Mrs. Carter will be met by Ambassador Ernesto Ruiz Rada, Director General of Ceremonies.
    *   Mrs. Carter, escorted by Ambassador Ruiz, proceeds down red carpet and is greeted by:
        *   Foreign Minister Jorge Escobari Cusicanqui
        *   Mrs. Laura Cardozo de Escobari
        *   Mrs. Marina Goytia de Padilla, wife of President
    *   Note: Mrs. Carter will be presented with a bouquet of flowers by either Mrs. Padilla or Mrs. Escobari.
    *   Mrs. Carter, escorted by Ambassador Ruiz, proceeds further down red carpet and greets:
        *   Ambassador Carlos Costa Du Rels, Director of Protocol
        *   Colonel Ricardo Sanchez, Mayor of La Paz
        *   Ambassador and Mrs. Paul Boeker (Margaret)
        *   Deputy Chief of Mission and Mrs. Williams Beal (Robbie)
    *   Guest and staff instructions: Proceed to motorcade for boarding. Assignments are as follows:
        *   Lead
        *   Spare: K. Le Grand
        *   Mrs. Carter's Vehicle: Mrs. Carter
        *   USSS Follow-up
        *   Control: H. Hoyt, M. Macbean, M. Fackelman
        *   Staff: S. Van Reigersberg, K. Dobelle, J. Fenderson
        *   Guest and Staff Bus: Amb. Vaky, R. Bonilla, R. Burris, W. Mixson, B. Pastor, D. Barnebey, K. Hays, J. Clark, G. Guerra, M. Crowell, L. Dewan, E. Bjerke, Dr. Falk
        *   Tail
*   5:35 P.M. Mrs. Carter, escorted by the Mayor, proceeds to speakers' platform and remains standing.
*   5:36 P.M. Welcoming remarks by either the Foreign Minister or Mrs. Padilla.
*   5:38 P.M. Remarks by Mayor, concluding in the introduction of Mrs. Carter.
*   5:40 P.M. Remarks by Mrs. Carter.
    *   Open press coverage.
*   5:45 P.M. Mrs. Carter proceeds to motorcade for boarding.

**Sunday, August 5, 1979**

*   5:50 P.M. Motorcade departs El Alto International Airport en route to La Paz Sheraton Hotel.
    *   (Driving time: 20 minutes)
*   6:10 P.M. Motorcade arrives La Paz Sheraton Hotel.
    *   Press pool coverage. Closed arrival.
    *   Mrs. Carter will be met by:
    *   Guest and staff instructions: Proceed to hotel rooms. Room list attached. Keys will be in your doors. Free evening.
*   6:12 P.M. Mrs. Carter proceeds to suite.
*   6:15 P.M. Mrs. Carter arrives suite.
    *   Free evening.
    *   RON.
*   3:40 P.M. Guest and staff instructions: Proceed to motorcade for boarding. Assignments are as follows:
    *   Lead
    *   Spare: K. Legrand
    *   Mrs. Carter's Vehicle: Mrs. Carter, Ambassador Vaky, Amb. Boeker
    *   Control: M. Hoyt, M. Macbeal, M. Fackelman
    *   Staff: R. Bonilla, R. Burris, W. Mixson
    *   Tail
*   3:45 P.M. Mrs. Carter departs suite en route motorcade for boarding.
*   3:50 P.M. Motorcade departs La Paz Sheraton Hotel en route Government Palace.
    *   (Driving time: 10 minutes)
*   4:00 P.M. Motorcade arrives Government Palace.
    *   Press pool coverage. Closed arrival.
    *   Mrs. Carter will be greeted by:
        *   Mr. Pablo Jimenez, Counselor for Protocol
        *   Mr. Antonio Salgado, Second Secretary for Protocol
    *   Guest and staff instructions: Official party follow Mrs. Carter.
    *   Mrs. Carter, escorted by Mr. Jimenez and Mr. Salgado, proceeds inside Government Palace en route Red Room.
    *   Mrs. Carter arrives Red Room and greets other delegations.
*   4:15 P.M. Mrs. Carter, escorted by Ambassador Costa Du Rels, departs Red Room en route Hall of Mirrors.
*   4:16 P.M. Mrs. Carter arrives Hall of Mirrors and is presented to President David Padilla Arancibia by Ambassador Costa Du Rels.
*   4:17 P.M. Mrs. Carter presents her credentials to President Padilla.
*   4:18 P.M. Mrs. Carter greets President Padilla and Foreign Minister Jorge Escobari.
*   4:19 P.M. Mrs. Carter presents members of U.S. delegation to President Padilla.
*   4:20 P.M. Mrs. Carter thanks President Padilla and, escorted by Mr. Jimenez and Mr. Salgado, departs Hall of Mirrors en route motorcade for boarding.
    *   Guest and staff instructions: Proceed to motorcade. Assignments as on arrival.
*   4:25 P.M. Motorcade departs Government Palace en route Ambassador Boeker's residence.
    *   (Driving time: 10 minutes)
*   4:35 P.M. Motorcade arrives Ambassador's residence.
    *   Mrs. Carter, escorted by Ambassador Boeker, proceeds inside residence en route garden area.
*   4:40 P.M. Mrs. Carter arrives garden and proceeds to podium to greet American Embassy personnel and members of the American community in La Paz.
*   4:41 P.M. Remarks by Mrs. Carter.
    *   Press pool coverage.
*   4:46 P.M. Remarks conclude.
*   4:47 P.M. Mrs. Carter proceeds inside garden and greets American guests.
*   5:00 P.M. Mrs. Carter thanks her hosts and proceeds inside residence en route holding room.
*   5:02 P.M. Mrs. Carter arrives holding room.
    *   Personal/staff time: 1 hour, 58 minutes.
*   6:40 P.M. Guest and staff instructions: Proceed to bus for buffet at Ambassador's residence.
    *   Participants: S. Reigersberg, K. Dobelle, J. Fenderson, B. Pastor, D. Barnebey, K. Hays, J. Clark, G. Guerra, M. Crowell, L. Dewan, E. Bjerke.
*   6:50 P.M. Bus departs La Paz Sheraton en route Ambassador's residence.
*   6:57 P.M. Bus arrives Ambassador's residence.
    *   Guest and staff instructions: Proceed inside for buffet.
*   7:00 P.M. Mrs. Carter departs holding room for informal buffet dinner followed by a musical presentation by two Bolivian folk groups.
*   8:55 P.M. Guest and staff instructions: Proceed to motorcade for boarding. Assignments as on arrival.
*   9:00 P.M. Mrs. Carter thanks her hosts and proceeds to motorcade for boarding.
*   9:05 P.M. Motorcade departs Ambassador's residence en route La Paz Sheraton Hotel.
    *   (Driving time: 7 minutes)

**Monday, August 6, 1979**

*   9:12 P.M. Motorcade arrives La Paz Sheraton Hotel.
    *   Closed arrival.
    *   Mrs. Carter proceeds to suite.
*   9:18 P.M. Mrs. Carter arrives suite.
    *   RON.
*   9:20 A.M. Guest and staff instructions: Proceed to motorcade for boarding. Assignments are as follows:
    *   Lead
    *   Spare: K. Legrand
    *   Mrs. Carter's Vehicle: Mrs. Carter, Amb. Boeker, Amb. Vaky
    *   USSS Follow-up
    *   Control: M. Hoyt, M. Macbean, M. Fackelman
    *   Staff: R. Bonilla, R. Burris, W. Mixson
*   9:25 A.M. Mrs. Carter departs suite en route motorcade for boarding.
*   9:30 A.M. Motorcade departs La Paz Sheraton Hotel en route to Legislative Palace.
    *   (Driving time: 10 minutes)
*   9:40 A.M. Motorcade arrives Legislative Palace.
    *   Press pool coverage. Closed arrival.
    *   Mrs. Carter will be greeted by:
        *   Mrs. Maritza de Carazas, Second Secretary for Protocol
        *   Gladys Costa Du Rels, Mrs. Carter's Bolivian escort
    *   Guest and staff instructions: Official party follow Mrs. Carter to box.
*   9:42 A.M. Mrs. Carter, escorted by Mrs. de Carazas and Mrs. Costa Du Rels, proceeds inside Legislative Palace en route Presidential Box of the Congressional Chamber.
*   9:45 A.M. Mrs. Carter arrives Presidential Box and takes her seat for inauguration ceremonies.
    *   Press pool coverage. Attendance:
*   10:00 A.M. Inauguration ceremonies begin.
*   1:00 P.M. Inauguration ceremonies conclude.
    *   Guest and staff instructions: Proceed to motorcade for boarding. Assignments as on arrival.
*   1:00 P.M. Mrs. Carter departs Presidential Box en route motorcade for boarding.
*   1:05 P.M. Motorcade departs Legislative Palace en route La Paz Sheraton Hotel.
    *   (Driving time: 10 minutes)
*   1:15 P.M. Motorcade arrives La Paz Sheraton Hotel.
    *   Mrs. Carter proceeds to suite.
*   1:20 P.M. Mrs. Carter arrives suite.
    *   (Personal/staff time: 4 hrs. 50 min.)
*   6:05 P.M. Guest and staff instructions: Proceed to motorcade for boarding. Assignments as in previous motorcade.
*   6:10 P.M. Mrs. Carter departs suite en route Government Palace.
    *   (Driving time: 10 minutes)
*   6:25 P.M. Motorcade arrives Government Palace.
    *   Mrs. Carter will be greeted by:
        *   Mr. Pablo Jimenez, Counselor for Protocol
        *   Mr. Antonio Salgado, Second Secretary for Protocol
    *   Official party instructions: Follow Mrs. Carter.
    *   Mrs. Carter, escorted by Mr. Jimenez and Mr. Salgado, proceeds inside Government Palace en route Red Room.
    *   Mrs. Carter arrives Red Room and greets other delegations.
*   6:45 P.M. Mrs. Carter, escorted by Ambassador Costa Du Rels, departs Red Room en route Hall of Mirrors.
*   6:46 P.M. Mrs. Carter arrives Hall of Mirrors and is presented to the newly elected President of Bolivia by Ambassador Costa Du Rels.
*   6:47 P.M. Mrs. Carter greets the new President.
*   6:48 P.M. Mrs. Carter presents members of U.S. delegation to the new President.
*   6:50 P.M. Mrs. Carter thanks the President and, escorted by Mr. Jimenez and Mr. Salgado, departs Hall of Mirrors en route motorcade for boarding.
    *   Guest and staff instructions: Proceed to motorcade. Assignments as on arrival.
*   6:55 P.M. Motorcade departs Government Palace en route La Paz Sheraton Hotel.
    *   (Driving time: 10 minutes)
*   7:05 P.M. Motorcade arrives La Paz Sheraton Hotel.
    *   Mrs. Carter proceeds to suite.
*   7:10 P.M. Mrs. Carter arrives suite.
    *   (Personal/staff time: 2 hrs. 15 min.)
*   9:30 P.M. Guest and staff instructions: Proceed to motorcade for boarding. Assignments as in previous motorcade.
*   9:25 P.M. Mrs. Carter departs suite en route motorcade for boarding.
*   9:30 P.M. Motorcade departs La Paz Sheraton en route to Government Palace.
    *   (Driving time: 10 minutes)
*   9:40 P.M. Motorcade arrives Government Palace.
    *   Press pool coverage. Closed arrival.
    *   Mrs. Carter will be met by:
        *   Ambassador Costa Du Rels
        *   Mrs. Carazas
    *   Official party instructions: Proceed inside Palace to reception area.
*   9:42 P.M. Mrs. Carter, escorted by Ambassador Costa Du Rels and Mrs. Carazas, proceeds inside Palace Hall and greets other delegations.
    *   Note: At 10:00 P.M. the newly elected President will arrive. The Bolivian National Anthem will be played and following that, the reception begins.
*   11:15 P.M. Official party instructions: Proceed to motorcade for boarding. Assignments are as on arrival.
*   11:20 P.M. Mrs. Carter thanks her hosts and proceeds to motorcade for boarding.
*   11:25 P.M. Motorcade departs Government Palace en route to Sheraton Hotel.
    *   (Driving time: 10 minutes)
*   11:35 P.M. Motorcade arrives La Paz Sheraton Hotel.
    *   Mrs. Carter proceeds to suite.
*   11:40 P.M. Mrs. Carter arrives suite.
    *   RON.

**Tuesday, August 7, 1979**

*   Baggage call: All bags must be placed outside your rooms in an unlocked condition no later than 7:00 A.M.
*   9:15 A.M. Guest and staff instructions: Proceed to motorcade for boarding. Assignments are as follows:
    *   Lead
    *   Spare: K. Legrand
    *   Mrs. Carter's Vehicle: Mrs. Carter
    *   USSS Follow-up
    *   Control: M. Hoyt, M. Macbean, M. Fackelman
    *   Staff: S. Van Reigersberg, K. Dobelle, J. Fenderson
    *   Guest and Staff Bus: Amb. Vaky, B. Pastor, D. Barnebey, K. Hays, J. Clark, G. Guerra, M. Crowell, L. Dewan, E. Bjerke
*   9:20 A.M. Mrs. Carter departs suite en route motorcade for boarding.
*   9:25 A.M. Motorcade departs La Paz Sheraton Hotel en route to El Alto International Airport.
    *   (Driving time: 20 minutes)
*   9:45 A.M. Motorcade arrives El Alto International Airport.
    *   Open press coverage. Closed departure.
    *   Mrs. Carter is greeted by:
        *   Colonel Ricardo Sanchez, Mayor of La Paz
    *   Guest and staff instructions: You will be escorted to viewing area.
*   9:47 A.M. Mrs. Carter, escorted by the Mayor, proceeds to speakers' platform.
*   9:47 A.M. Remarks by the Mayor.
*   9:50 A.M. Remarks conclude.
*   9:51 A.M. Remarks by Mrs. Carter.
*   9:55 A.M. Remarks conclude.
    *   Guest and staff instructions: Board aircraft. Manifest as on arrival, except delete:
        *   R. Bonilla
        *   R. Burris
        *   W. Mixson
        *   Dr. Falk
    *   Mrs. Carter, escorted by the Mayor, bids farewell to:
        *   Ambassador Ernesto Ruiz Rada, Director General of Ceremonies
        *   Foreign Minister Jorge Escobari Cusicanqui
        *   Mrs. Laura Cardozo de Escobari
        *   Mrs. Marina Goytia de Padilla
        *   Ambassador Carlos Costa Du Rels, Director of Protocol
        *   Colonel Ricardo Sanchez, Mayor of La Paz
        *   Ambassador and Mrs. Paul Boeker (Margaret)
        *   Deputy Chief of Mission and Mrs. Beal (Robbie)
*   9:58 A.M. Mrs. Carter boards aircraft.
*   10:00 A.M. U.S. Air Force aircraft departs La Paz, Bolivia, en route Cotopaxi Air Base, Ecuador.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ06614

- **Date:** August 02, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** ITINERARY, VISITS
