---
title: "Ecla Plenary Conference: Committee Ii (Institutional Issues/Program Of Work)"
author: "No Consensus By Committee."
date: "April 24, 1979"
editor: visual
cable-date: "April 24, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 5899"
cable-info: "Oct-01 Ara-15 Ads-00 Oes-09 Ss-15 L-03 Sp-02 Ciae-00 Come-00 Eb-08 Inr-10 Lab-04 Nsae-00 Sil-01 Labe-00 Trse-00 Omb-01 Aid-05 Ica-15 Nasa-02 Agre-00 Dote-00 Hud-02 Hew-06 Int-05 Ceq-01 Doe-15 Soe-02 Oic-02 /139 W ------------------062426 241837z /47"
cable-subject: "Ecla Plenary Conference: Committee Ii (Institutional Issues/Program Of Work)"
cable-tags: "OCON, ECLA, UN"
cable-ref: "LA PAZ 3493"
cable-doc-number: "1979LAPAZ03561"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "n/a"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. **Summary:** As of the evening of April 21, Committee II's work has been virtually completed, the committee having fully discussed the Secretariat's activities over the last two years, the Secretariat's projected work program for 1979-81, and having considered 25 out of 26 draft resolutions before it. The US delegation played an active role and was successful in promoting greater concern over the need for budgetary discipline and the need to stop the proliferating number of international meetings and subsidiary bodies of ECLA. A very good resolution on decentralization (restructuring) of UN activities was adopted which incorporates the concept of redeploying resources from New York to the regional commission to enable the latter to effectively assume their growing responsibilities (text to be sent septel). Only remaining business on Committee II agenda is consideration of Uruguayan draft resolution on energy which is still before Latin American Working Group and adoption of Committee II report which will be forwarded to Plenary. End summary.

2. Committee II, which was assigned to review the Secretariat's activities and work program, has completed virtually all items on its agenda and dealt with 25 draft resolutions. In addition to the resolutions noted in reftel, the following nine resolutions were also considered:

(A) COM II/19: Withdrawn

(B) COM II/21
SPONSOR: Venezuela
SUBJECT: Amends Resolution 13
US POSITION: Yes, with reservation
COMMENT: Objectionable language on graduation removed, US supported consensus

(C) COM II/22: Withdrawn

(D) COM II/23:
SPONSOR: Argentina, Costa Rica, Cuba, El Salvador, Guatemala, Honduras, Mexico, Nicaragua, Venezuela
SUBJECT: Economic and social projections
US POSITION: Yes

(E) COM II/24
SPONSOR: Uruguay
SUBJECT: Decentralization of UN activities
US POSITION: Yes
COMMENT: Approved with US amendments on transfer and redevelopment of resources.

(F) COM II/25
SPONSOR: Bolivia
SUBJECT: The needs of children and the shaping of the coming generations within the framework of the development process.
US POSITION: Yes

(G) COM II/26
SPONSOR: Uruguay
SUBJECT: Energy
US POSITION: To be decided
COMMENT: Remanded to working group

(H) COM II/27
SPONSOR: Cuba, Guatemala, Mexico
SUBJECT: Regional cooperation in the field of human settlement.
US POSITION: No
COMMENT: US opposed creation of ECLA intergovernmental committee. No consensus by committee.

(I) COM II/28
SPONSOR: Costa Rica, Guatemala, Honduras
SUBJECT: Methodological research for the inclusion of the patrimony of resources in the system of national accounts.
US POSITION: No
COMMENT: US opposed because of financial implications. No consensus by committee.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ03561

- **Date:** April 24, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** n/a
