---
title: "Benjamin Mendoz-Flores"
author: ""
date: "August 30, 1979"
editor: visual
cable-date: "August 30, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Priority 7964"
cable-info: "Oct-01 Ara-11 Ads-00 Sye-00 Inr-10 Inc-01 Ciae-00 /028 W ------------------019664 301728z /15 P 301653z Aug 79"
cable-subject: "Benjamin Mendoz-Flores"
cable-tags: "ASEC"
cable-ref: "STATE 215721 OF AUGUST 18, 1979"
cable-doc-number: "1979LAPAZ07397"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "n/a"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Police research reveals subject Benjamin Mendoza Meave was born 31 March 32 (vice 21 March 35 as noted Reftel) father Juan Mendoza Gutierrez mother Gregoria Meave Flores, and holds Bolivian personal identify card No. 209908 dated 12 Sept. 58. Police I.D. photo and thumb/index fingerprints being forwarded A/SY by pouch this date.

2. Last known domicile is Calle Sebastian Segurola No. 496, Zona Chijini, La Paz, Bolivia. Neighborhood check reveals his residence no longer exists, having been demolished and replaced by market. Neighbors do not know present whereabouts.

3. Embassy now checking with police in Cochabamba, Bolivia, where subject has in past worked as artist. Will advise if positive information is received.
    Boeker

***

#### Message Attributes

- **Document Number:** 1979LAPAZ07397

- **Date:** August 30, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** n/a