---
title: "Possible Reopening Of Central Obrera Boliviana (Cob)"
author: "Stedman"
date: "August 02, 1974"
editor: visual
cable-date: "August 02, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3817"
cable-info: "Oct-01 Iso-00 Ciae-00 Come-00 Eb-11 Inr-11 Lab-06 Nsae-00 Rsc-01 Sil-01 Dode-00 Pm-07 H-03 L-03 Nsc-07 Pa-04 Prs-01 Sp-03 Ss-20 Usia-15 Drc-01 /115 W --------------------- 082333 R 021610z Aug 74"
cable-subject: "Possible Reopening Of Central Obrera Boliviana (Cob)"
cable-tags: "ELAB, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ04988"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "LABOR RELATIONS, LABOR UNIONS, REORGANIZATIONS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. THE MINISTER OF LABOR HAS STARTED DISCUSSIONS WITH BOLIVIA'S
MAJOR CONFEDERATIONS AND FEDERATIONS ON THE POSSIBILITY OF RE-
OPENING THE CENTRAL OBRERA BOLIVIANA (COB). THIS REPRESENTS A
MAJOR CHANGE IN THE GOVERNMENT'S LABOR POLICY SINCE THE DISESTAB-
LISHMENT OF THE COB HAD BEEN A KEY TACTIC IN THE BANZER REGIME'S
STRATEGY OF KEEPING THE LABOR MOVEMENT DIVIDED.


2. THE MINISTER OF LABOR HAS INDICATED IN A NUMBER OF STATEMENTS
ON THIS ISSUE THAT TO BE ACCEPTABLE TO THE GOVERNMENT THE COB
WOULD HAVE TO BE REORGANIZED AS AN APOLITICAL ORGANIZATION STRICTLY
DEVOTED TO TRADE UNION MATTERS. THERE IS SOME SUPPORT FOR THIS
VIEW AMONG CERTAIN LABOR ORGANIZATIONS WHO BELIEVE THAT THE COB
STATUTES GIVE DISAPROPORTIONATE VOTING STRENGTH TO THE MINERS AND
FACTORY WORKERS. MODERATE TRADE UNIONISTS WOULD ALSO LIKE TO SEE
ORGANIZATIONS NOT STRICTLY TRADE UNION SUCH AS STUDENT GROUPS AND
"FREE PROFESSIONALS" SEPARATED FROM THE COB. THE MINERS
FEDERATION IS, OF COURSE, OPPOSED TO ANY CHANGES IN THE
COB'S STATUTES.


3. COMMENT: THE REOPENING OF THE COB WOULD STRENGTHEN THE
BARGAINING POWER OF THE LABOR MOVEMENT MANYFOLD AND INEVITABLY
ENABLE THE MOVEMENT TO PLAY A MORE EFFECTIVE ROLE AS CRITIC






 021911Z


OF THE ECONOMIC AND SOCIAL POLICIES OF THE GOVERNMENT. IT




                      

                 

SEEMS PROBABLE THAT VARIOUS UNIONS MIGHT ACCEPT SOME CHANGES
IN THE COB'S TRADITIONAL STRUCTURE IF IT MEANT THE DIFFERENCE
BETWEEN HAVING A CENTRAL OR NOT.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04988

- **Date:** August 02, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** LABOR RELATIONS, LABOR UNIONS, REORGANIZATIONS