---
title: "Mutun Iron And Steel"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "January 18, 1979"
editor: visual
cable-date: "January 18, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 4397"
cable-info: "Oct-01 Ara-15 Iso-00 Eb-08 /028 W ------------------011957 201755z /43 R 181318z Jan 79"
cable-subject: "Mutun Iron And Steel"
cable-tags: "BENC, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ00497"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "n/a"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


As Department is aware, resalization of the Mutun project depends entirely on construction of the proposed Bolivia-Brazil gas pipeline. And although pipeline feasibility studies as well as conversations between the Bolivian and Brazilian governments are continuing, for political reasons it is highly unlikely that any final decision to go ahead with the pipeline will be taken this year. Therefore, realistically, we can expect no real progress on the Mutun project until at least late 1979. If, however, any new information on Mutun does surface, it will immediately be reported.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ00497

- **Date:** January 18, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** n/a
