---
title: "[subject not available]"
author: "Stedman"
date: "July 10, 1974"
editor: visual
cable-date: "July 10, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "AmEmbassy Caracas"
cable-info: "Oct-01 Iso-00 Aid-20 Sp-03 Eb-11 Nsc-07 Rsc-01 Ciep-02 Trse-00 Ss-20 Str-08 Omb-01 Cea-02 Come-00 Ciae-00 Dode-00 Inr-10 Nsae-00 Pa-04 Usia-15 Prs-01 L-03 H-03 Xmb-07 Frb-02 Drc-01 /142 W --------------------- 073601 R 101649z Jul 74"
cable-subject: "[subject not available]"
cable-tags: "EFIN, EAID, BL, VE"
cable-ref: ""
cable-doc-number: "1974LAPAZ04455"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "ECONOMIC ASSISTANCE, SPEECHES, LOANS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. PRES BANZER, IN HIS ADDRESS TO NATION ON JULY 8
FOLLOWING SWEARING IN CEREMONY FOR NEW ALL-MILITARY
CABINET, MADE THE FOLLOWING STATEMENT: QUOTE WE ARE
WORKING TO CREATE A NETWORK OF INTERRELATED PRODUCTIVE
POLES IN A HARMONIOUS AND BALANCED PROCESS OF DEVELOP-
MENT AND A FUND TO STIMULATE OUR NATIONAL, ECONOMIC
TAKE-OFF. IN THIS EFFORT, WE EXPECT TO HAVE THE
VALUABLE COOPERATION OF OUR SISTER REPUBLIC OF VENEZUELA.
END QUOTE.


2. THE UNOFFICIAL WORD HERE IS THAT IN ADDITION TO
CONTRIBUTING 500 MILLION DOLLARS TO THE IDB, THE GOV
WILL LEND 50 MILLION DOLLARS TO BOLIVIA FOR A SERIES
OF DEVELOPMENT PROJECTS. ALLEGEDLY, THE TERMS OF
THE LOANS TO BOLIVIA WILL VARY ACCORDING TO THE
NATURE OF THE APPROVED PROJECT.


3. WOULD APPRECIATE RECEIVING ANY COMMENTS YOU CAN
SUPPLY ON THIS ANTICIPATED VENEZUELAN LOAN PROGRAM.






 101815Z


STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04455

- **Date:** July 10, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** ECONOMIC ASSISTANCE, SPEECHES, LOANS
