---
title: "Bid By U S Company For Contract For Aeronautic Exploration For Uranium For: Ara/Bc/B"
author: "Stedman"
date: "August 09, 1974"
editor: visual
cable-date: "August 09, 1974"
cable-from: "Amemdassy La Paz"
cable-to: "SecState WashDC Immediate 3862"
cable-info: "Oct-01 Iso-00 Come-00 Eb-11 Sso-00 Rsc-01 Drc-01 /034 W --------------------- 026353 O 092130z Aug 74"
cable-subject: "Bid By U S Company For Contract For Aeronautic Exploration For Uranium For: Ara/Bc/B"
cable-tags: "ETRN, BEXP, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ05091"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "TRADE PROMOTION, URANIUM, AVIATION REGULATIONS, GEOLOGIC SURVEYS, PROPOSALS (BID)"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. BOB FOWLER OF GEOMETRIC, INC., OF 914 INDUSTRIAL AVENUE, PALO
ALTO, CALIFORNIA WILL CALL MIKE COTTER, ARA/BC/B MORNING AUGUST 10
SEEKING FOLLOWING INFORMATION. FOWLER'S COMPANY MAKING BID TO
ITALIAN STATE ENTERPRISE AGIP FOR AIRBORNE MAGNETIC AND SPECTOMETER
SURVEY UNDER RECENTLY SIGNED CONTRACT BETWEEN AGIP AND GOB FOR
URANIUM EXPLORATION.


2. MANY ANSWERS TO FOWLER'S QUESTIONS REGARDING GOB PERMITS AND
REGULATIONS WILL BE EVIDENT FROM READING OF AGIP/GOB CONTRACT.
EMBASSY HAS BEEN PROMISED COPY BUT TOLD THAT CONTRACT NOT YET
LEGALIZED. OFFICIALS OF BOLIVIAN ACTION AGENCY FOR CONTRACT,
COBOEN, HAVE NOT BEEN AVAILABLE DUE TO SHORT WEEK SINCE AUGUST 5,
6 AND 7 WERE NATIONAL HOLIDAYS. CONTRACT IS LIKELY TO SPELL OUT
REGULATIONS FOR AIRCRAFT AND WORK PERMITS. WE WILL TALK TO
COBOEN OFFICIALS AUGUST 12 AND HOPE THAT THEY CAN PROVIDE INFOR-
MATION REGARDING OXYGEN, AVGAS AND HOUSING AVAILABILITIES AT SITES.


3. IF AVIATION CONDITIONS NOT SPELLED OUT IN CONTRACT, GOB DIRECTOR


OF CIVIL AVIATION MUST APPROVE DOMESTIC FLIGHTS. OUR EXPERIENCE
IS THAT FOR PROVEN SPECIALIZED NEEDS FLIGHT PERMITS READILY GIVEN
AND FAA CERTIFICATIONS RECOGNIZED.








 092224Z


4. PRICE OF AVGAS 100/130 VARIES ACCORDING LOCALITY AND NATIONALITY




                     

                  

OF BUYER. FOR FOREIGN BUYERS (E.E. US)/ PRICE HAS BEEN US$ .82 IN
COCHABAMBA AND US$ .85 IN SANTA CRUZ. PRICE MAY YET BE HIGHER IN
REMOTE AREAS. THERE HAS BEEN RECENT SHORTAGE OF AVGAS WHICH
NOW IMPROVING, BUT IT IS POSSIBLE THAT PRICES MAY SOON
RISE.


5. BOLIVIA HAS NO RPT NO EXCHANGE CONTROLS. TAXES AND IMPORT
DUTIES ARE LIKELY TO BE COVERED IN CONTRACT AND EXCEPTIONS MAY BE
GRANTED TO SUBCONTRACTORS, ESPECIALLY FOR IMPORT OF NEEDED EQUIPMENT.
IF NOT, COMPANIES GENERALLY PAY 25 PER CENT PROFITS TAX AND PERSONAL
INCOME TAXES SCALED. ONE U.S. OIL COMPANY STATES THAT ITS EMPLOYEES
PAY OUT ABOUT ONE-THIRD OF SALARY IN LOCAL TAXES.


6. GOB INSTITUTO GEOGRAFICO MILITAR, GUARTEL GENERAL, LA PAZ, IS
BEST SOURCE FOR TOPGRAPHIC AND PHOTO MAPS. COL JOHN FURRER,
IAGS REP, MAY BE REACHED THROUGH EMBASSY.


7. EITHER PEPE ANTONELLI, KATTAN Y CIA, CASILLA 2694, LA PAZ,
BOLIVIA OR FERNANDO KNAUDT BANZER, MERCANTIL SUDAMERICANA, LTD.,
CASILLA 1185, LA PAZ, BOLIVIA, MAY BE INTERESTED IN SERVING AS
U.S. COMPANY'S REPRESENTATIVES. WE HAVE CONTACTED NEITHER AS YET.


8. EMBASSY WILL CABLE FURTHER DATA AFTER CONVERSATION WITH
COBOEN.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05091

- **Date:** August 09, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** TRADE PROMOTION, URANIUM, AVIATION REGULATIONS, GEOLOGIC SURVEYS, PROPOSALS (BID)
