---
title: "Daily Press Briefing, November 1, 1979"
author: "To That Area. Christopher"
date: "November 02, 1979"
editor: visual
cable-date: "November 02, 1979"
cable-from: "SecState WashDC"
cable-to: "Usdel SecRetary Immediate"
cable-info: "Oct-00 Ads-00 Sso-00 Ss-15 Cco-00 Ara-15 Nea-07 Af-10 H-02 /051 R"
cable-subject: "Daily Press Briefing, November 1, 1979"
cable-tags: "SOPN, OVIP (VANCE, CYRUS R.)"
cable-ref: ""
cable-doc-number: "1979STATE286983"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "PUBLIC DEMONSTRATIONS, GOVERNMENT OVERTHROW, TOSEC, PRESS SUMMARIES, POLITICAL SITUATION, STUDENTS,"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. **Summary:** Briefing centered on Bolivia coup and demonstrations in Iran. Also covered were the reported South African raid into Angola, Rhodesia sanctions and USG meetings with the Patriotic Front, and the Secretary's meeting with the Black Caucus on October 31.

2. Briefing commenced with following statement: "According to our information some military units around La Paz, Bolivia, have taken control of the central area of that city and declared their intention to install an Army Colonel, Alberto Natusch Busch, as President. The attitude of military units elsewhere in the country toward the attempted coup is not clear. Bolivia's Constitutional President, Walter Guevara Arze, and the Commander of the Armed Forces, General David Padilla, have denounced this attempt to change the government by non-constitutional means. The United States is following these events with deep concern and would deplore any disruption in Bolivia's democratic process."

3. Questions centered on whether Secretary Vance delivered a message to Bolivian political figures warning against a coup during his recent trip there. Reston replied, "I want to put that in a positive framework. I think the Secretary emphasized our position in returning to democracy, which we have been seeing in the Andean Region. I think they are aware of our position." Taken questions concerned Colonel Natusch's background, U.S. relations with Bolivia, and diplomatic contacts with other governments in the region.

4. In response to a question on the anti-U.S. demonstration in Tehran, Reston replied: "There was a demonstration. Its purpose apparently was to protest the presence of the former Shah here in the United States. It seems to have been organized by religious groups associated with the regime in Iran. There were about 3,500 demonstrators. They were shouting slogans and placing banners on the walls of the American compound. The demonstration was peaceful and controlled, and at no time did any of the demonstrators enter the Embassy compound. The organizers of the demonstration have instructed their participants not to proceed to the Embassy and to end their demonstration at a place about three miles from the Embassy. That is what the main group did. We don't have any accurate information about the size of the main group. I want to state, with regard to the protection that was afforded to our people and property in Tehran, that the Iranian government met fully its responsibility to provide security for the Embassy in Tehran by augmenting the police elements which normally protect the compound. We, the American government, appreciate the Iranian government's additional steps for assuring the safety of the men and women who work in our Embassy."

5. Related questions focused on whether Iran regime organized the demonstrations and if a group of 3,500 which approached the Embassy were acting according to plan. No response was offered which went beyond guidance in Paragraph 4 above.

6. On the reported South African raid into Angola, Reston replied, "We have been informed by representatives of the Angolan government and have seen press reports of the South African raid into Angola. We have no independent evidence to confirm these reports. If true, however, these reports only emphasize the urgency of obtaining an international settlement for Namibia. As we have stated before, we deplore any acts which contribute to the escalation of violence in the area. We note that Angola has requested a Security Council meeting for today on this matter. I would expect that the Western Contact Group will be making a further statement at that time."

7. On Rhodesia sanctions, Reston went no further than to reiterate support for the British pre-independence proposals. A related question concerned a report that senior Patriotic Front officials were to meet with the Secretary. Reston replied, "Well, as you know, the Secretary is out of the country; he's in Korea. And there is no such meeting scheduled. Let me say that, however--and let me go on background to say this--Mr. Josiah Chinamano of the ZAPU wing of the Patriotic Front and Mr. Edgar Tekere, who is Secretary-General of ZANU, were in Hot Springs, Virginia, last week to attend the Tenth African-American Conference, which is sponsored by the African-American Institute. The Assistant Secretary of State for African Affairs, Mr. Richard Moose, also attended that conference, had an opportunity for an exchange of views with those two particular leaders."

8. A question on the Secretary's meeting with the Black Caucus concerned the subject of that meeting. A posted answer that afternoon read that the Middle East was the primary topic of discussion, although there was one question from a Caucus member which did not pertain to that area.

***

#### Message Attributes

- **Document Number:** 1979STATE286983

- **Date:** November 02, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** PUBLIC DEMONSTRATIONS, GOVERNMENT OVERTHROW, TOSEC, PRESS SUMMARIES, POLITICAL SITUATION, STUDENTS,
