---
title: "Mfm Working Group On Transnational Enterprises"
author: "Brewin"
date: "May 30, 1974"
editor: visual
cable-date: "May 30, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3248"
cable-info: "Oct-01 Iso-00 Eb-11 L-03 Io-14 Sp-03 Ss-20 Ciae-00 Dode-00 Inr-10 Nsae-00 Pa-04 Rsc-01 Usia-15 Prs-01 Come-00 Trse-00 Omb-01 Drc-01 /105 W --------------------- 091784 R 301956z May 74"
cable-subject: "Mfm Working Group On Transnational Enterprises"
cable-tags: "PFOR, EGEN, MFM"
cable-ref: "(A) STATE 111288 (B) STATE 092124"
cable-doc-number: "1974LAPAZ03501"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "FOREIGN MINISTERS MEETINGS, COMMITTEE MEETINGS, WASHINGTON, REGIONAL ORGANIZATIONS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. REFTEL A NOTES THAT BOLIVIA HAS NOT YET REACTED TO U.S.
PROPOSALS REGARDING SITE AND TIMING OF FIRST MEETING OF WORKING
GROUP. EMBASSY DISCUSSED PROPOSAL IN DETAIL WITH OFFICIAL OF
FOREIGN MINISTRY AFTER RECEIPT REFTEL B. OFFICIAL STATED THAT
PROPOSAL SEEMED REASONABLE BUT PROMISED TO RAISE ISSUE WITH
MINISTER AND GIVE US REPLY.


2. PROBABLY DUE TO MINISTRY EFFORTS TO PREPARE FOR MEETING OF
BRASILIAN AND BOLIVIAN PRESIDENTS, EMBASSY WAS NOT AGAIN ABLE
TO TALK TO OFFICIAL UNTIL MAY 29. HE THEN STATED THAT GOB
ACCEPTS WASHINGTON AS SITE FOR MEETING AND ACCEPTS JULY TIMING.
BREWIN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03501

- **Date:** May 30, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** FOREIGN MINISTERS MEETINGS, COMMITTEE MEETINGS, WASHINGTON, REGIONAL ORGANIZATIONS
