---
title: "Bolivia Invited To Attend June, 1974 Opec Conference"
author: "Brewin"
date: "May 31, 1974"
editor: visual
cable-date: "May 31, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3263"
cable-info: "Oct-01 Iso-00 Aec-11 Aid-20 Cea-02 Ciae-00 Ciep-02 Come-00 Dode-00 Eb-11 Fea-02 Fpc-01 H-03 Inr-10 Int-08 L-03 Nsae-00 Nsc-07 Omb-01 Pm-07 Rsc-01 Sam-01 Sci-06 Sp-03 Ss-20 Str-08 Trse-00 Nea-14 Drc-01 Pa-04 Prs-01 Usia-15 /183 W --------------------- 107542 R 311953z May 74"
cable-subject: "Bolivia Invited To Attend June, 1974 Opec Conference"
cable-tags: "ENRG, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ03433"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PRESS COMMENTS, MEMBERSHIP, PETROLEUM, ECONOMIC CONDITIONS, INVITATIONS, MEETINGS, MEETING OBSERVERS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. MIN ENERGY AND HYDROCARBONS STATED TO PRESS ON MAY 30,
BOLIVIA IS INVITED TO ATTEND AS OBSERVER CONFERENCE OF OPEC
SCHEDULED FOR MID JUNE AT QUITO, ECUADOR.


2. SAID VENEZUELA AND ECUADOR ARE ONLY LATIN AMERICAN COUNTRIES
WHO ARE MEMBERS OF OPEC AND THIS IS FIRST STEP FOR BOLIVIA TO
GAIN FULL MEMBERSHIP. ADDED OPEC PRODUCES 53 PERCENT OF
WORLD'S PETROLEUM PRODUCTION, MANAGES 90 PERCENT OF PETROLEUM
EXPORTS AND HAVE 74 PERCENT OF CRUDE WORLD RESERVES.


2. COMMENTED THAT IF BOLIVIA HAD BELONGED TO ORGANIZATION OF
THIS TYPE REGARDING TIN PRODUCTION, BOLIVIA'S ECONOMIC
CONDITION WOULD HAVE BEEN QUITE DIFFERENT.
BREWIN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03433

- **Date:** May 31, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PRESS COMMENTS, MEMBERSHIP, PETROLEUM, ECONOMIC CONDITIONS, INVITATIONS, MEETINGS, MEETING OBSERVERS
