---
title: "Possible Bolivian Interest In Usg Good Offices To Achieve Outlet To The Sea For Assistant Secretary Kubisch From Ambassador"
author: "Stedman"
date: "April 04, 1974"
editor: visual
cable-date: "April 04, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 2734"
cable-info: "Oct-01 Iso-00 Sso-00 /031 W --------------------- 090311 O 042125z Apr 74"
cable-subject: "Possible Bolivian Interest In Usg Good Offices To Achieve Outlet To The Sea For Assistant Secretary Kubisch From Ambassador"
cable-tags: "PFOR BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ02085"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "28 MAY 2004"
cable-concepts: "MEETINGS, WATERWAY ACCESS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. I am detecting some thinking within the Foreign Ministry that it might be propitious for Foreign Minister Guzman to raise with senior US authorities during forthcoming meeting with Secretary Kissinger the suggestion that US help Bolivia achieve an outlet to the sea through the extension of good offices or some form of mediation. This is probably a natural development from the current burst of Bolivian interest in regaining a seacoast and also Bolivian recognition of the diplomatic skills of Secretary Kissinger. I sense some views within the Foreign Ministry that the USG might, for example, ask the foreign ministers of Chile, Peru and Bolivia to meet together on the subject of an outlet to the sea at some time during the forthcoming meeting in Washington.

2. Since I have not had this possibility put to me formally I have not been able to deal with it directly. However, I have used some recent opportunities to restate our present policy of hoping that Bolivia, through diplomatic negotiations with Chile and Peru, can achieve its objective. This is an indirect way of stating that it is not now the policy of the USG to involve itself in this issue. I hope to preclude any formal request for our assistance which might be rejected as this could conceivably cause a very adverse reaction at the present time when all Bolivians are vocalizing an emotional interest in a return to the sea.

3. I would be most appreciative for your views on this subject, especially if you sense that there is any possibility that the USG might consider some form of good offices to assist Bolivia. It would be most helpful if I could have your views by Monday, April 8 as it is quite likely that I will have opportunities, informal and formal, to see senior Ministry officials before their departure for Washington, now tentatively planned for either the 13th or 14th of April.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ02085

- **Date:** April 04, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 28 MAY 2004

- **Concepts:** MEETINGS, WATERWAY ACCESS