---
title: "Proposed Fourth Amendment To The Title I/Iii Pl 480 Agreement Of May 31, 1978 Refs: (A) La Paz 6784; (B) La Paz 7870; (C) State 131738 (May 24, 1978); (D) State 109068; (E) La Paz 10034; (F) State 310295 (G) Blohm-Boeker Telcon December 5"
author: ""
date: "December 05, 1979"
editor: visual
cable-date: "December 05, 1979"
cable-from: "SecState WashDC"
cable-to: "AmEmbassy La Paz Niact Immediate"
cable-info: "Oct-00 Ads-00 Aid-05 Ciae-00 Com-02 Eb-08 Frb-03 Inr-10 Nsae-00 Trse-00 Xmb-02 Opic-07 Sp-02 Lab-04 H-01 Sil-01 Omb-01 Icae-00 Inre-00 Agre-00 L-03 /064 R"
cable-subject: "Proposed Fourth Amendment To The Title I/Iii Pl 480 Agreement Of May 31, 1978 Refs: (A) La Paz 6784; (B) La Paz 7870; (C) State 131738 (May 24, 1978); (D) State 109068; (E) La Paz 10034; (F) State 310295 (G) Blohm-Boeker Telcon December 5"
cable-tags: "EAID, BL"
cable-ref: ""
cable-doc-number: "1979STATE313541"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "PL 480, AMENDMENTS, FOREIGN ASSISTANCE AGREEMENTS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. **The following is the text of message yet undelivered to post regarding the Fourth Amendment to the Title I/III PL 480 Agreement of May 31, 1978.**

2. **Begin quote:** In accordance with GOB requests and Embassy recommendations, and pending receipt NAC clearance and storage/disincentive determination required by Section 401(B), PL 480, you will be authorized septel exchange with GOB note set forth below, accomplishing Fourth Amendment to Title I/III PL 480 Agreement of May 31, 1978.

3. **Purpose of Fourth Amendment is to respond to GOB need for financing for wheat shipments as soon as possible.** Dollar amount allocated this amendment represents first tranche of FY 1980 Title I budget allocation for Bolivia. Balance of FY 1980 budget allocation will be programmed as explained Ref (F). However, during negotiation this amendment it should be noted to GOB representatives that debt arrearage of approximately DOLS 3.0 million, some dating back to November 1977, exists on prior Title I agreements. GOB may encounter USG reluctance to proceed expeditiously with programming further amendments in absence of assurance that steps are being taken to remedy delinquent payments situation.

4. **Specifically, amendment provides DOLS 5.0 million to supply approximately 26,000 metric tons wheat/wheat flour in a Calendar Year 1980 supply period.** Usual marketing requirements are extended through CY 1980 at level previously established for CY 1979 and import period is so amended. Export limitations are also extended for CY 1980. During negotiations you may explain to GOB representatives that CY 1980 supply period does not prohibit GOB from initiating purchases during December, with deliveries to begin as soon as possible after January 1, 1980.

5. **Note that before purchase authorization can be issued, USDA/OGSM must receive operational reporting cable marked Priority and pass Agriculture electronically, as required by Ref C, Para 11 C.** See Ref D for summary of information required.

6. **Following is text draft note (unnecessary words omitted) which you will be authorized exchange with GOB septel.**

Begin Text Note –

Excellency, have honor to refer Agricultural Commodities Agreement signed by representatives of our two governments May 31, 1978, as amended by exchanges of notes dated August 31, 1978 and September 1, 1978, May 2, 1979, and September 13, 1979 and September 24, 1979, and to propose that Part II, Particular Provisions of that agreement be further amended as follows:

A. In Item I, Commodity Table, under appropriate column headings, insert a new line as follows: "Wheat/Wheat Flour (wheat basis) - 1980 - 26,000 - 5.0." On line entitled "Total", delete "DOLS 22.8" and insert "DOLS 27.8."

B. In Item III, Usual Marketing Table, under column headed "Import Period", change "1979" to read "1979 and 1980." Under column headed "Usual Marketing Requirement (metric tons)", change "159,700" to read "159,700 in each year."

C. In Item IV, Export Limitations, Paragraph A, change "United States Calendar Year 1978 and 1979" to "United States Calendar Years 1978, 1979, and 1980."

All other terms and conditions of May 31, 1978 agreement as amended, remain the same.

If foregoing acceptable to your government, propose that this note, together with your reply thereto, constitute agreement between our two governments, effective date your note in reply.

Accept, Excellency, etc.

End Text Note

7. **When notes exchanged, notify Washington by immediate cable tagged EAID, and marked AIDAC and pass Agriculture electronically, and forward documents per 11 FAM 723.7.** Decontrolled upon exchange of notes. End quote. Vance

***

#### Message Attributes

- **Document Number:** 1979STATE313541

- **Date:** December 05, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** PL 480, AMENDMENTS, FOREIGN ASSISTANCE AGREEMENTS
