---
title: "Opic Insurance Operations In Bolivia"
author: "Stedman"
date: "September 06, 1974"
editor: visual
cable-date: "September 06, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 4149"
cable-info: "Oct-01 Ara-16 Iso-00 Eb-11 Come-00 Aid-20 L-03 Ciae-00 Inr-11 Nsae-00 Agr-20 Int-08 /102 W --------------------- 054922 R 061930z Sep 74"
cable-subject: "Opic Insurance Operations In Bolivia"
cable-tags: "EINV,BL"
cable-ref: "LA PAZ 1972: LA PAZ 5513"
cable-doc-number: "1974LAPAZ05806"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "AGREEMENTS, ZINC, INVESTORS, LOAN INSURANCE, FOREIGN INVESTMENTS, CONTRACTS, SUBSIDIARIES, FOREIGN POLICY"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. MANSBACH'S VISIT WAS USEFUL TO US AS IT PROVIDED US WITH OPIC'S
CURRENT THINKING ON ITS OPERATIONS IN BOLIVIA AND SOME ADDITIONAL
INFORMATION ON SPECIFIC CASES.


2. IN A CONVERSATION WITH AMB STEDMAN AND ECOM OFFICERS, MANSBACH
INDICATED THAT OPIC CURRENTLY WAS INTERESTED MAINLY IN LOAN AND
LOAN INSURANCE OPERATIONS, AND ESPECIALLY WAS LIMITING ITSELF TO
THESE OPERATIONS IN THE CASE OF FIRMS EXPORTING 80 PERCENT OF THEIR
PRODUCTION TO THE ANDEAN MARKET AND THEREFORE RAISING THE DECISION
24, ARTICLE 51 SUBROGATION PROBLEM. MANSBACH INDICATED OPIC
LAWYERS WERE CONSIDERING SOMEHOW SEPARATING OPIC INSURANCE CONTRACTS
AND THE NECESSARY FGA'S FROM THEPROVISIONS OF ART. 51, YET PRESER-
VING SUBROGATION RIGHTS UNDER THE BILATERAL AGREEMENTS. THIS MIGHT
BE BASED ON INTERPRETING ART. 51 TO REFER ONLY TO GOVERNMENT
"INSTRUMENTS RELATING TO INVESTMENT" WHILE MAINTAINING THAT OPIC
INVESTMENT INSURANCE CONTRACTS ARE NOT OR WILL NOT BE GOVERNMENT
INSTRUMENTS.MANSBACH SAID THAT OPIC MIGHT HIRE A LOCAL LAWYER
TO LOOK INTO SUCH POSSIBILITIES. WE BELIEVE THAT OPIC CANNOT
HAVE IT BOTH WAYS. IF IT IS A PRIVATE INSURANCE COMPANY, THEN ITS
RIGHTS SHOULD NOT BE SUBROGATED TO USG, EXCEPT PERHAPS BY THE
PROCESSES OF STATE DEPT. ESPOUSAL OF PRIVATE CLAIMS. WE DOUBT,






 062118Z


HOWEVER, THAT THE ANDEAN PACT COMMISSION OR GOB WILL AGREE THAT




                     

                   

ART. 51 REFERS ONLY TO GOVERNMENT INVESTMENT INSTRUMENTS IF THEY
ARE AWARE THAT THE "PRIVATE" INSURER INTENDS TO AVAIL ITSELF OF THE
BENEFITS OF A GOVERNMENT TO GOVERNMENT BILATERAL TREATY.


3. MANSBACH INDICATED THAT OPIC PLANS TO INSURE LOAN OR LOANS TO
NEW JERSEY ZINC (NJZ), A SUBSIDIARY OF GULF AND WESTERN, PERHAPS
SUPPLEMENTED BY A DIRECT OPIC LOAN AND DIRECT INVESTMENT INSURANCE
IN CONCERT WITH A JAPANESE INVESTMENT IN THE MIXED COMPANY NJZ
SEEKS TO FORM. WE RECALLED THAT IN LA PAZ 2284 WE WARNED THAT THE
EMBASSY MIGHT RECOMMEND AGAINST INSURANCE FOR NJZ. WE STATD USG
SHOULD HAVE BIAS AGAINST INSURING INVESTMENTS IN SENSITIVE MINING
SECTOR AND THAT WE DID NOT HAVE SUFFICIENT INFO ON NJZ PLANS TO
PROPERLY EVALUATE SITUATION. IT APPEARED TO US THAT NJZ HAD MADE
ITS MOVES TO BUY GIBRALTAR HUARI-HUARI BEFORE IT COULD HAVE BEEN
ASSURRED OF HAVING OPIC INSURANCE, ESPECIALLY IN VIEW OF THE PARA-
GRAPH OPIC PUT IN ITS REGISTRATION NOTICE OF APRIL 2, 1974 WHICH
PLACES NJZ PROJECT UNDER "LARGE AND SENSITIVE POLICY GUIDELINES"
AND WARNS NJZ THAT ISSUES SHOULD BE DISCUSSED WITH OPIC
AND RESOLVED BEFORE IT PROCEEDS TO INVEST OR COMMIT THE PREDOMINANT
PART OF ITS PROPOSED INVESTMENT. WE REPORTED IN LA PAZ 1972 THAT
NJZ HAD PAID IMPC/GIBRALTAR HUARI-HUARI DEBTS TO BANCO MINERO
TOTALLING US$ 240,000 BEFORE MARCH 28, 1974. IT APPEARS THAT
NJZ'S INTEREST WAS SO GREAT THAT IT MADE THIS PAYMENT ON OR BEFORE
THE DATE OF ITS REQUEST FOR OPIC INSURANCE. REPORTEDLY NJZ ALREADY
HAS INVESTED AT LEAST US$ 1.4 MILLION AND PERHAPS AS MUCH AS US$ 4.4
MILLION IN ITS GIBRALTAR HUARI-HUARI PROJECT. IT SEEMS LIKELY, THEREF
ORE,
THAT OPIC INSURANCE IS NOT ESSENTIAL TO NJZ DECISION TO GO AHEAD
WITH THIS PROJECT.


4. IN RESPONSE TO THESE VIEWS, MANSBACH SAID "ADDITONALITY" NOT
ALWAYS ESSENTIAL AND THAT OPIC NEEDS TO SPREAD ITS RISKS IN SOME
CASES TO SOUND INVESTMENTS THAT MAY NOT BE "ADDITIONAL" DUE TO THE
OPIC INSURANCE INCENTIVE. WE BELIEVE THAT BOLIVIAN MINING SECTOR
IS ONE OF LAST PLACES OPIC SHOULD LOOK FOR DIVERSIFYING INTO SOUND
INVESTMENTS. WE SUSPECT NJZ INVESTMENT WILL BE ECONOMICALLY SOUND,
BUT POLITICALLY RISKY.


5. GULF AND WESTERN ALSO OWNS, THROUGH ITS SUBSIDIARY BROWN & CO.,
KELLGUANI MINE. TOGETHER WITH GIBALTAR HUARI-HUARI, GULF AND






 062118Z


WESTERN COULD RAPIDLY BECOME BIGGEST AND MOST VISIBLE PRIVATE
MINING INTEREST IN BOLIVIA.


6. MINOR POINT IS THAT IMPC/GIBRALTAR HUARI-HUARI HAS ALREADY
INVESTED US$ 1.2 MILLION ORE MORE. OPIC WOULD HAVE TO BE QUITE
CLEAR ON EXACLY WHAT IT WOULD BE COVERING.


7. GIVEN ALL THESE CONSIDERATIONS, WE BELIEVE IT IS IN USG




                   

                   

INTEREST TO OPPOSE OPIC INSURANCE FOR NJZ, AT LEAST UNTIL DETAILED
INFORMATION MADE AVAILABLE TO EMBASSY. CAREFUL DECISION CAN THEN BE
MADE ON BASIS SUCH INFORMATION.


8. MATTER OF INVESTMENTS IN AGRICULTURAL LAND WAS RAISED BY STATE
185136 DURING MANSBACH'S VISIT. AS EMBASSY HAD NOT RECEIVED RESPONSE
TO EARLIER MESSAGES ON STOKES APPLICATION (AS WELL AS TO SOME OTHER
APPLICATIONS), WE SENT LA PAZ 5513 OPPOSING INSURANCE FOR STOKES AT
LEAST UNTIL ISSUES RESOLVED. EMBASSY CONSIDERS AGRICULTURAL LAND TO
BE SECTOR AS SENSITIVE AS MINING IN VIEW LONG STANDING AGRARIAN
REFORM POLICIES AND UNRESOLVED LAND INVESTMENT DISPUTE (APPLEGATE/
YOUNGUIST CASE). WHILE THIS GOVERNMENT HAS DONE NOTHING TO EXTEND
REACH OF AGRARIAN REFORM, IT HAS ALLOWED COFADENA (MILITARY CORPORA-
TION) TO TAKE OVER CAMPO LUMINOSA, ONE OF BOLIVIA'S LARGEST CATTLE
RANCHES WHICH HAD OVERDUE DEBTS WITH BANCO DEL ESTADO. AS POPULATION
PRESSURE MOUNTS IN SANTA CRUZ, CHAPARE BENI AND NORTHERN LA PAZ, WE
EXPECT FURTHER EXTENSION AGRARIAN REFORM WILL BECOME BURNING POLITI-
CAL ISSUE WHICH ALMOST ANY PROSPECTIVE GOVERNMENT LIKELY TO RESOLVE
TO SOME EXTENT IN FAVOR OF BOLIVIAN SMALL FARMER AT EXPENSE OF LARGE
FOREIGN FARMER. MOREOVER, AS WE HAVE NOTED PREVIOUSLY, LAND TITLE
EVEN AMONG LARGE DEVELOPERS APPARENTLY MATTER OF CONTINUAL DISPUTE.
MANSBACH ASKED EMBASSY TO CONSIDER MATTER CAREFULLY TO DECIDE WHETHER
WE WISHED RAISE OBJECTIONS TO INVESTMENTS IN AGRICULTURAL LAND ON
POLITICAL GROUNDS.


9. AFTER CONSIDERATION OF OPIC POSITIONS IN GENERAL ON SIGNIFICIANCE
OF
REGISTRATION NOTES, SUBROGATION AND INVOLVEMENT OF OTHER USG PROGRAMS
IN EFFORTS ARRANGE PAYMENTS TO OPIC INSURED FIRMS IN NATIONALIZA-
TION CASES, AS WELL AS RECENT EXPERIENCE WITH HANDLING APPLICATIONS
COVERING MINING AND AGRICULTURAL LAND INVESTMENTS, WE CONFIRM OUR
EARLIER POSITION THAT THERE SHOULD BE A STRONG BIAS AGAINST INSURING
SUCH INVESTMENTS IN BOLIVIA, BUT WE STILL DO NOT WISH TO CLOSE THE






 062118Z


DOOR COMPLETELY. AS MAJORITY OF "BOLIVIAN" APPLICATION TO OPIC
APPEAR TO BE TWO MOST SENSITIVE AREAS AND AS OPIC PROCEDURES
NOW RESULT IN ALMOST IMMEDIAT AND AUTOMATIC ISSUANCE OF REGISTRA-
TION NOTICE AND AS OPIC BENDS EVERY EFFORT TO GRANT INSURANCE ONCE
REGISTRATION NOTICE ISSUED, WE BELIEVE BEST PROCEDURE TO MEET OUR
POLITICAL AND PROGRAM CONCERNS IN SENSITIVE AREAS, DEFINED AS
MINING AND AGRICULTURAL LAND, WOULD BE ALONG FOLLOWING LINES: 1)
OPIC WOULD ADVISE APPLICANT THAT REGISTRATION NOTICE CANNOT BE
ISSUED UNTIL DETAILED INVESTMENT PROPOSAL PRESENTED TO OPIC AND
OPIC CAN CONSULT WITHIN USG: 2) EMBASSY SHOULD BE PROVIDED WITH
THESE DETAILS AND ALLOWED TO MAKE RECOMMENDATION BEFORE REGISTRA-
TION NOTICE ISSUED: 3) IF INVESTOR ALTERS APROJECT, EMBASSY SHOULD
BE ADVISED SO RECOMMENDATION CAN BE REVIEWED.


10.EMBASSY FULLY REALIZES THAT OPIC CAN DEAL WITH MANY PROBLEMS




                   

                  

BY CAREFUL DRAFTING INSURANCE CONTRACT, BUT SUCH ADJUSTMENT MAY
NOT BE SUFFICIENT IN SOME CASES. WE BELIEVE BEST INTERESTS USG
WILL BE SERVED BY GIVING MOST CAREFUL, CAUTIOUS AND BROAD CONSIDER-
ATION TO INSURING U.S. INVESTMENTS IN SENSITIVE AREAS RATHER THAN
EMPHASIZING OVERCOMING (PERHAPS ONLY SUPERFICIALLY) ANY OBSTACLES
THAT APPEAR AND OBJECTIONS THAT MIGHT BE RAISED.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05806

- **Date:** September 06, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** AGREEMENTS, ZINC, INVESTORS, LOAN INSURANCE, FOREIGN INVESTMENTS, CONTRACTS, SUBSIDIARIES, FOREIGN POLICY