---
title: "Porcine Breeders Representation At Santa Cruz Fair"
author: "Stedman"
date: "August 22, 1974"
editor: visual
cable-date: "August 22, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "Dept Of Agriculture"
cable-info: "Oct-01 Ara-16 Iso-00 Eb-11 Ciae-00 Inr-11 Lab-06 Nsae-00 Pa-04 Rsc-01 Sil-01 Usia-15 Prs-01 Drc-01 /068 W --------------------- 021395 R 221400z Aug 74"
cable-subject: "Porcine Breeders Representation At Santa Cruz Fair"
cable-tags: "EAGR, ETRD, BL"
cable-ref: "(A) A-097 OF MAY 21, 1974 (B) STATE 052574 (C) A-280 OF 12/21/73"
cable-doc-number: "1974LAPAZ05432"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "LIVESTOCK, TRADE PROMOTION, DATA, TRADE FAIRS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. REFTELS DESCRIBE EMBASSY'S PLANNED PARTICIPATION
IN BI-ANNUAL FAIR IN SANTA CRUZ, DYNAMIC CENTER OF AGRICULTURAL
GROWTH IN BOLIVIA'S TROPICAL EASTERN AREA.


2. THERE EXISTS INCIPIENT MARKET FOR PORCINE STOCK IN BOLIVIA.
RON STOVALL, REPRESENTATIVE VIRGINIA PORCINE BREEDERS,
VISITED LA PAZ EARLIER IN YEAR AND HAS HAD CORRESPONDENCE
WITH A TLEAST MAJOR POTENTIAL BUYER.


3. ACTION REQUESTED: USDA CONTACT VIRGINIA BREEDERS AND
ARRANGE FOR THEM TO SEND CATLOGS AND OTHER PROMOTIONAL MATERIAL
THAT CAN BE SHOWN AT EMBASSY-SPONSORED U.S. BOOTH AT FAIR.
PLEASE SEND MATERIAL BY FASTEST MEANS. FAIR BEGINS SEPTEMBER
18.


4.. EMBASSY URGES USDA ASK OTHER SIMILAR ORGANIZATIONS
TO SEND MATERIALS. EMBASSY ALREADY HAS HANDOUTS FROM






 221535Z


USDA & BRAHMIN ASSOCIATION.




                       

               

STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05432

- **Date:** August 22, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** LIVESTOCK, TRADE PROMOTION, DATA, TRADE FAIRS
