---
title: "Uranium Exploration Contract With Italian Firm"
author: "Stedman"
date: "June 28, 1974"
editor: visual
cable-date: "June 28, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3535"
cable-info: "Oct-01 Iso-00 Dode-00 Opic-12 Prs-01 Eb-11 Aid-20 Come-00 Int-08 Trse-00 Xmb-07 Omb-01 L-03 Acda-19 Ciae-00 Inr-10 Io-14 Nsae-00 Nsc-07 Rsc-01 Sci-06 Fea-02 Drc-01 /144 W --------------------- 087257 R 282149z Jun 74"
cable-subject: "Uranium Exploration Contract With Italian Firm"
cable-tags: "ENRG, TECH, EMIN, BL"
cable-ref: "(A) A-034 OF FEBRUARY 18, 1974 (B) LA PAZ 3179 OF MAY 16, 1974"
cable-doc-number: "1974LAPAZ04241"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "URANIUM, EXPLORATION, TREATY SIGNATURE, CONTRACTS, BUSINESS FIRMS, FOREIGN INVESTMENTS, JOINT VENTURES"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. REPRESENTATIVES OF AGIP NUCLEAR, ITALIAN FIRM, AND BOLIVIAN
GOVERNMENT REPORTEDLY WILL SIGN URANIUM EXPLORATION CONTRACT ON OR
ABOUT JULY 4, 1974.


2. ACCORDING TO RELIABLE SOURCE NAMED IN REFTEL, AGIP MUST INVEST
US$ 2,000.000 IN FIRST TWO YEARS OF EXPLORATION AND IF SUCCESSFUL,
ANOTHER US$ 2,000,000 IN FOLLOWING TWO YEARS. BOLIVIA TO HAVE 52
PERCENT PARTICIPATION IN MIXED COMPANY AND AGIP 48 PERCENT. PAR-
TICIPATION COULD INCREASE FOR GOB UP TO 60 PERCENT IF RICH LARGE
DEPOSIT FOUND OR IT COULD DECREASE TO 40 PERCENT IF LOW GRADE HIGH
MINING COST DEPOSIT FOUND. BOLIVIAN GOVERNMENT TO HAVE TOTAL
OWNERSHIP OF URANIUM PRODUCTION AND MAY CHOOSE MARKETS.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04241

- **Date:** June 28, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** URANIUM, EXPLORATION, TREATY SIGNATURE, CONTRACTS, BUSINESS FIRMS, FOREIGN INVESTMENTS, JOINT VENTURES
