---
title: "Reaction To Mexico City Foreign Ministers Meeting Reference: La Paz 1177"
author: "Stedman"
date: "February 28, 1974"
editor: visual
cable-date: "February 28, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2365"
cable-info: "Oct-01 Iso-00 Io-14 Oic-04 Aid-20 Ciae-00 Dode-00 Pm-07 H-03 Inr-10 L-03 Nsae-00 Nsc-10 Pa-04 Rsc-01 Prs-01 Spc-03 Ss-20 Usia-15 Sam-01 Sab-01 Drc-01 /139 W --------------------- 069010 R 281506z Feb 74"
cable-subject: "Reaction To Mexico City Foreign Ministers Meeting Reference: La Paz 1177"
cable-tags: "BL, PFOR"
cable-ref: ""
cable-doc-number: "1974LAPAZ01221"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "PRESS COMMENTS, FOREIGN RELATIONS, FOREIGN MINISTERS MEETINGS, PUBLIC ATTITUDES, FOREIGN POLICY POSITION"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Local reaction to meeting of Foreign Ministers Mexico City thus far limited to statement issued by Foreign Ministry on February 23, and February 25 editorial in leading morning newspaper Presencia. Text of Foreign Ministry statement read as follows: "The delegation of Bolivia proposed today in the conference of Foreign Ministers that the following points should be included in the proposals which are presented to the Secretary of State of the United States of America, Henry A. Kissinger: (1) That in the area of Development Assistance, the United States grant most favorable treatment to the least developed countries, and even more to those nations with geographic limitations, such as a land-locked status. (2) That the United States avoid policies and measures which affect the economies of Latin American states which produce minerals and other basic products. Both suggestions received the unanimous support of the Latin American countries meeting in the Mexican capital. The spokesman of the Foreign Ministers presented the first point to Secretary of State Kissinger, who accepted fully this orientation for inclusion in the program of Development Assistance."

2. Presencia editorial, following up on views quoted in reftel, stated that conference had created "a new spirit in hemispheric relations with the United States." Editorial greets Declaration of Tlatelolco as beginning of "new political order" in which USG will no longer seek to impose unilateral decisions on Latin America. Nonetheless, editorial concludes by warning that such a change cannot be expected to occur suddenly, and calls upon United States to exercise continuing "good will" and "desire to cooperate" with Latin America as proof of its willingness to establish new relationship with the region.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ01221

- **Date:** February 28, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** PRESS COMMENTS, FOREIGN RELATIONS, FOREIGN MINISTERS MEETINGS, PUBLIC ATTITUDES, FOREIGN POLICY POSITION