---
title: "Airlift Of Disaster Relief Supplies For Bolivia"
author: "Stedman"
date: "February 08, 1974"
editor: visual
cable-date: "February 08, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "Uscincso Immediate Niact"
cable-info: "Oct-01 Iso-00 Aid-20 Io-09 Sso-00 Nsce-00 Usie-00 Inre-00 Ciae-00 Inr-10 Nsae-00 Rsc-01 Dode-00 Hew-08 Pa-04 Prs-01 Pm-07 Nsc-10 Spc-03 Sam-01 Ss-20 Scse-00 Sca-01 Drc-01 /117 W --------------------- 107341 O 081959z Feb 74"
cable-subject: "Airlift Of Disaster Relief Supplies For Bolivia"
cable-tags: "EAID, BL"
cable-ref: "STATE 026462 TO LA PAZ REPEATED TO USCINCSO"
cable-doc-number: "1974LAPAZ00874"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "AIR TRANSPORTATION, DISASTER RELIEF, SUPPLIES, FLOOD CONTROL, RELIEF (ASSISTANCE)"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. By separate telegram you will be receiving an information copy of my message to Washington listing those items most urgently needed at this time.
2. I have just received information that flooding in the departments of the Beni and Pando will crest within 24 hours, bringing with it greater damage and more suffering than we have already sustained. Our need for relief supplies grows hourly. To this end, and assuming AID/W concurrence in our list of requirements, I would greatly appreciate whatever action you can take towards getting these supplies loaded upon an aircraft on a priority basis and dispatched to us. Would it not be possible to get the airplane here by noon tomorrow, Saturday?
3. As we are receiving urgent requests from the GOB as to when the airlift will arrive, I would appreciate also your best estimate as to when the airlift will arrive in La Paz. Please give me this estimate as soon as possible via immediate NIACT cable or call via radio to our MILGRP.

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00874

- **Date:** February 08, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** AIR TRANSPORTATION, DISASTER RELIEF, SUPPLIES, FLOOD CONTROL, RELIEF (ASSISTANCE)
