---
title: "Bolivian Tin And Petroleum: Continued Production Declines Likely"
author: ""
date: "September 01, 1979"
editor: visual
cable-date: "September 01, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 7999"
cable-info: "Oct-01 Ara-11 Ads-00 Soe-02 Aid-05 Cea-01 Ciae-00 Com-02 Inc-01 Dode-00 Doe-15 H-01 Inr-10 Int-05 L-03 Nsae-00 Nsc-05 Omb-01 Pm-05 Ica-11 Oes-09 Sp-02 Ss-15 Str-08 Trse-00 Acda-12 /133 W ------------------045180 040100z /64 R 011221z Sep 79"
cable-subject: "Bolivian Tin And Petroleum: Continued Production Declines Likely"
cable-tags: "EMIN, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ07474"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "TIN, PETROLEUM PRODUCTION, EXPLORATION, CORRUPTION, INVESTMENTS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. (Entire text.)

2. **Summary:** A principal slogan of Bolivia's 1952 revolution was "Land to the peasants, the mines to the state." While the effect of land reform on the country's agricultural production has been mixed, nationalization of Bolivia's major mines two and a half decades ago inaugurated an era of inefficiency, bloated payrolls and, far worse, a virtual absence of investment in the search for and development of new deposits. As a result of decades of no exploration nor development of new mines, Bolivian tin production appears now to have entered a period of decline. Furthermore, subsidized prices of petroleum products plus the same historic pattern of long neglecting investment in favor of featherbedding and providing social benefits has brought Bolivia to the verge of becoming a petroleum importing nation. Bolivia's sagging production of oil and tin combine to have a negative impact on Bolivia's economic future. To offer a prospect of long-term success, any GOB economic reform program will have to address the structural problems of the tin and petroleum industries, as well as the immediate task of financial stabilization. End summary.

3. As is well known, with the exception of a predominantly subsistence agricultural sector, Bolivia's visible economy is dominated by mining (17 percent of GDP, 70 percent of exports) and petroleum (4 percent of GDP). However, despite rapidly rising world prices for both commodities, the country's production of each appears to be in secular decline, a problem that must be addressed by any future economic stabilization/reform program. (Bolivia's still weeks-old new government has publicly acknowledged the tin/petroleum problem but, not surprisingly, hasn't yet had time to even propose possible counter-measures.) Because of the obvious relevance the continuing slide in the production of these two key commodities holds for Bolivia's economic future, we have put together a brief discussion of the basic problems facing both subsectors.

4. **Petroleum:** Bolivia's declining oil production (physical output peaked in 1973 and has fallen an average of 11 percent/year since 1976 and dropped a full 10 percent in the first quarter of 1979) is primarily the result of insufficient exploration, the consequence in turn of YPFB's increasingly precarious financial position. (With total debt close to book value assets, the state oil monopoly is rapidly approaching technical insolvency.) And although the reasons for YPFB's monetary difficulties include featherbedding, corruption, mismanagement and a history of excessive wage settlements, the principal problem is the artificially low price structure for its products: for example, 30 cents/gallon for gasoline, 6 cents/gallon for household kerosene. (It costs YPFB approximately $US 21 to produce a barrel of product it sells for less than $12.)

5. Clearly, the obvious first step the GOB should take is a major (at least 100 percent) increase in petroleum product prices. Production would still continue to fall for some time even if prices were raised and exploration sharply accelerated; however, an early price hike and stepped-up exploration would at least be a start. Unless a swap of Bolivia's still excess gasoline for Brazilian kerosene, diesel and fuel oil can be arranged, the impending need to import product will have a substantial negative effect on the GOB's already critical balance of payments situation.

6. There are two additional factors further clouding Bolivia's bleak oil outlook. First is the possibility that despite even an heroic increase in exploration, the country may simply not possess much additional exploitable petroleum. As it is, most of Bolivia's liquid petroleum is actually condensate produced in association with natural gas. To produce more needed liquids from existing wells requires producing more gas. The problem then becomes what to do with the gas--flaring it is wasteful and reinjection is costly. But the third alternative, selling the "excess" gas, is not presently promising. Argentina, Bolivia's only current customer for piped gas (220 MCFD), is not disposed to increase its purchases. And the sale of Bolivian gas to Brazil (via a proposed pipeline from Santa Cruz to Sao Paulo) seems stalled until Bolivia makes the politically controversial decision either to pursue the project or drop it. Without a clear, positive decision on the gas sale to Brazil, Bolivia's long-term prospects to balance its external accounts and meet its debts will remain cloudy.

7. **Tin.** Despite record world tin prices, Bolivia's 1979 tin output is expected to fall several percentage points below the 30,200 metric tons produced last year. As with petroleum, the major cause of declining production is a lack of exploration that goes back at least to 1952, the year the bulk of Bolivian tin properties were nationalized. Still utilizing mines all of which were discovered decades ago, yields from both COMIBOL and many privately owned properties have steadily decreased while costs have continued to rise. The high cost of production could be attacked to a degree by a

***

#### Message Attributes

- **Document Number:** 1979LAPAZ07474

- **Date:** September 01, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** TIN, PETROLEUM PRODUCTION, EXPLORATION, CORRUPTION, INVESTMENTS