---
title: "1979 Human Rights Report: Bolivia Text Of 1979 Human Rights Report For Bolivia Follows: (Begin Text) Introduction"
author: ""
date: "November 28, 1979"
editor: visual
cable-date: "November 28, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 9494"
cable-info: "Oct-01 Ara-11 Ads-00 Sr-04 Io-14 Ciae-00 Dode-00 Nsae-00 Nsce-00 Sso-00 Icae-00 Inre-00 Pm-06 H-01 Inr-10 L-03 Pa-01 Sp-02 Ss-15 Aid-05 Eb-08 Omb-01 Trse-00 Acda-12 /099 W ------------------025443 282036z /41 O 281952z Nov 79"
cable-subject: "1979 Human Rights Report: Bolivia Text Of 1979 Human Rights Report For Bolivia Follows: (Begin Text) Introduction"
cable-tags: "SHUM, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ10216"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "HUMAN RIGHTS, REPORTS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. Located in the heart of South America, land-locked Bolivia achieved its independence August 6, 1825. Since that time political instability has been an impediment to economic and social progress which in turn has resulted in an uneven record in terms of human rights observance. However, this trend began to change in 1977 when President Banzer initiated a liberalization of virtually all major restrictions on human rights, releasing all political prisoners, allowing exiles to return and scheduling elections for July 1978. The momentum of human rights progress has continued for the succeeding two years, with the sole dramatic exception of the violent 15-day rule of coup leader Alberto Natusch in November 1979.

2. The human rights momentum was not checked by the Pereda coup (August 1978) or the Padilla take-over (November 1978). Instead, while representing brief interruptions in the democratization process, both governments contributed to the improving human rights situation: Pereda by abrogating the feared State Security Law, and Padilla by holding in July 1979 perhaps the most democratic elections in Bolivia's history.

3. Since none of the eight presidential hopefuls achieved the needed majority of the popular vote in the July 1979 elections, the Congress selected Senate President Walter Guevara Arze to be interim president with new elections scheduled for May 1980.

4. Guevara's government came to an abrupt end November 1, 1979, when a group of military officers and civilians under the leadership of Army Colonel Alberto Natusch Busch seized the government. Strong popular reaction against the coup and its interruption of the democratic process, resulted in the implementation of press censorship, a state of siege, and martial law. Uncontrolled military elements confronted protesting but unarmed civilians, resulting in the confirmed death of approximately 208 persons, the wounding of 207 others, and the unaccountable disappearance of 124 citizens, now presumed dead. Popular discontent, an unprecedented seven-day strike by the Confederation of Bolivian Workers (COB), and Natusch's repressive measures hastened the demise of his regime.

5. Consequently on November 16 he was forced to resign and was replaced by Chamber of Deputies President Lidia Gueiler according to an agreement reached between the Congress, the COB, and the Armed Forces. President Guevara, who had become a resistance symbol in hiding during the Natusch regime, returned to his former Senate position. Ms. Gueiler is to be Bolivia's interim president until the inauguration on August 6, 1980 of the winner in May elections.

6. Bolivia's dire economic situation will undoubtedly complicate matters. Faced with dwindling foreign reserves and declining production of petroleum and tin, the new government will have to take strong economic measures to return Bolivia to economic solvency.

**Section 1 - Respect for the integrity of the person, including freedom from:**
**A. Torture**

1. The Bolivian Constitution clearly prohibits cruel, inhuman, or degrading treatment. Presidents Padilla and Guevara respected this constitutional guarantee; there were no reports of torture during their brief governments. Allegations of torture during the short-lived Natusch regime remain unsubstantiated, but are currently under investigation by the Permanent Assembly on Human Rights (PAHR).

2. The assembly was also tasked by the Bolivian Congress on November 19 to document all cases of persons killed, wounded, or missing as a result of Natusch's repressive tactics. When completed, these lists of names will be made public, although it is questionable whether such evidence will lead to any trials and convictions in the near future.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ10216

- **Date:** November 28, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** HUMAN RIGHTS, REPORTS