---
title: "Pl-480 Title I Program Reference: State 5916"
author: "Page 02 La Paz 00244 112110z"
date: "January 11, 1974"
editor: visual
cable-date: "January 11, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 1928"
cable-info: "Oct-01 Iso-00 Aid-20 Ciae-00 Come-00 Eb-11 Frb-02 Inr-10 Nsae-00 Rsc-01 Trse-00 Xmb-07 Opic-12 Spc-03 Ciep-02 Lab-06 Sil-01 Omb-01 Iga-02 Agr-20 Str-08 Drc-01 Ss-20 Nsc-10 Sso-00 Nsce-00 Inre-00 Usie-00 /158 W --------------------- 079465 O 112100z Jan 74"
cable-subject: "Pl-480 Title I Program Reference: State 5916"
cable-tags: "EAID, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ00244"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "WHEAT, PL 480 TITLE 1, FLOUR, FOREIGN ASSISTANCE PROGRAMS"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. According Subsec Minind/Com, portion PL-480 wheat that arrived in Matarani already being milled in Arequipa for delivery to Bolivia as flour on grounds that milling capacity La Paz fully utilized but flour still scarce. Not yet clear whether GOB will use same ratio flour to wheat as established under earlier authority or whether GOB will simply pay commission charge.

2. La Paz millers have charged that there is sufficient milling capacity.

3. Stocks of both wheat and flour in La Paz quite low (data being sent Septel). Mission reluctant complain about measure but request Washington guidance. Mission has not repeat not acquiesced in any way with GOB initiative.
Stedman

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00244

- **Date:** January 11, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** WHEAT, PL 480 TITLE 1, FLOUR, FOREIGN ASSISTANCE PROGRAMS
