---
title: "Debt Service On Eximbank And Pl-480 Credits"
author: "Stedman"
date: "August 09, 1974"
editor: visual
cable-date: "August 09, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3860"
cable-info: "Oct-01 Ara-16 Iso-00 Aid-20 Eb-11 Trse-00 Ciae-00 Inr-11 Nsae-00 Rsc-01 Ciep-03 Cea-02 Ss-20 Frb-03 Omb-01 Drc-01 Come-00 Sp-03 L-03 /103 W --------------------- 025870 R 092030z Aug 74"
cable-subject: "Debt Service On Eximbank And Pl-480 Credits"
cable-tags: "EFIN, BL"
cable-ref: "MEMCON OF AUGUST 2, 1974"
cable-doc-number: "1974LAPAZ05089"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "DEBT AGREEMENTS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. FOLLOWING SUGGESTION OF EXJAMIN OF FINANCE QUIROGA,
ADCM RAISED WITH NEW MINFIN CASTILLO POSSIBILITY OF
EMBASSY PARTICIPATING IN REMINDING MINISTRY OFFICIALS


OF NEED TO BEGIN PAPER WORK FOR MAKING DEBT SERVICE
PAYMENTS ON TIME. CASTILLO AGREED TO DO WHATEVER
NECESSARY TO PLACE BOLIVIA IN GOOD CREDIT STANDING
WITH REGARD TO THESE DEBTS. IT WAS AGREED THAT ADCM
SHOULD MEET WITH EXECUTIVE DIRECTOR OF INSTITUTO NACIONAL
DE FINANCIAMIENTO (INDEF) HECTOR ORMACHEA AT LATER TIME
TO WORK OUT MECHANISM.


2. IN MEETING WITH ORMACHEA ON AUG 8, DEBT SERVICE
SCHEDULE WORKED UP BY EMBASSY PRIMARILY FROM MINFIN
SOURCES WAS TENTATIVELY ACCEPTED SUBJECT TO REVIEW BY
BOTH USG AND GOB. ORMACHEA ALSO INVITED ADCM TO
PROVIDE NOTIFICATION TO MINFIN THROUGH ORMACHEA
15 WORKING DAYS IN ADVANCE OF PAYMENT DATE.
ORMACHEA AGAIN NOTED THAT ALL PAYMENTS TO
EXIMBANK HAD BEEN MADE PUNCTUALLY IN 1974.






 092152Z




                   

                  

3. EX-MIN QUIROGA BELIEVED THIS SORT OF MECHANISM
WOULD BE MEANINGFUL HELP DUE TO TURNOVER AND NEGLIGENCE
OF MINISTRY OFFICIALS INVOLVED IN DEBT SERVICE PAPER
WORK. ADCM SUGGESTED TO MINFIN CASTILLO AND ORMACHEA
THAT THEY SHOULD CONSIDER A MORE PERMANENT AND
RELIABLE SOLUTION TO PROBLEM PERHAPS BY AUTHORIZING
CENTRAL BANK TO MAKE DEBT SERVICE PAYMENTS AUTOMATICALLY
ON GOB DEBT EVEN IF TREASUREY TRANSFER NOT RECEIVED IN
TIME. CENTRAL BANK WOULD THEN SIMPLY DEBIT TREASURY
ACCOUNT. ORMACHEA FAVORABLY DISPOSED TO SUGGESTION,
BUT AGREED THAT EMBASSY REMINDER MECHANISM USEFUL
TEMPORARY MEASURE.


4. TENTAVIVELY AGREED DEBT SERVICE SECHEDULE BEING
POUCHED UNDER AIRGRAM FOR WASHINGTON REVIEW.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ05089

- **Date:** August 09, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** DEBT AGREEMENTS