---
title: "Uranium Exploration Contract With Italian Firm"
author: "Stedman"
date: "July 31, 1974"
editor: visual
cable-date: "July 31, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3795"
cable-info: "Oct-01 Iso-00 Eb-11 Come-00 Aec-11 Acda-19 Ciae-00 Inr-11 Io-14 L-03 Nsae-00 Nsc-07 Rsc-01 Sci-06 Feae-00 Dode-00 Pa-04 Usia-15 Prs-01 Sp-03 Aid-20 Opic-12 Int-08 Xmb-07 Omb-01 Trse-00 Pm-07 Drc-01 /183 W --------------------- 064596 R 312047z Jul 74"
cable-subject: "Uranium Exploration Contract With Italian Firm"
cable-tags: "ENRG, TECHN, EMIN, BL,"
cable-ref: "(A) ROME 10223 (B) LA PAZ 4241 (C) LA PAZ 4578"
cable-doc-number: "1974LAPAZ04940"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "URANIUM, EXPLORATION, CONTRACTS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. ON JULY 29 MANUEL D'AGNOLO OF AGIP, SUBSIDIARY OF ITALIAN
STATE ENTERPRISE ENI, SIGNED "OPERATIONS CONTRACT" WITH
BOLIVIAN MINISTER OF MINES ZELAYA AND DIRECTOR OF BOLIVIAN
NUCLEAR ENERGY COMMISSION (COBOEN) ALBERTO SAENZ.


2. AGIP AGREED TO EXPLORE FOR URANIUM "AND OTHER RADIOACTIVE
MATERIALS" IN SIX OF BOLIVIA'S NINE DEPARTMENTS
COCHABAMBA, BENI AND PANDO EXCLUDED) WITH WORK TO FOCUS
PRINCIPALLY IN COROCORO ON ALTIPLANO, LIPEZ, TARIJA AND
SAN JOSE DE CHIQUITOS, SANTA CRUZ. CONTRACTTO RUN FOR 24
YEARS WITH EXPLORATION ANTICIPATED IN FIRST FOUR YEARS.
AGIP AGREED TO SPEND US$ 2 MILLION IN BOLIVIA IN NEXT TWO
YEARS, USE BOLIVIAN TECHNICIANS WHERE POSSIBLE, AND HAVE
ACTIVITIES SUPERVISED BY A JOINT AGIP-GOB BOARD OF CONTROL.








 011257Z


3. ACCORDING TO PRESS REPORTS, IF COMMERCIAL QUANTITIES OF




                        

                 

MINERAL FOUND, AGIP WILL INVEST IN FIELD'S EXPLOITATION.
MINISTER STRESSED TO PRESS THAT COBOEN WILL RETAIN
PROPERTY RIGHTS OVER MINERAL BUT REPORTED STATEMENT THAT
COBOEN WILL PAY AGIP "FOR ITS SERVICES" IN CONCENTRATES
IMPLIES THAT CONTRACT MAY GIVE COMPANY SOME CONTROL
OVER DESTINATION OF MINERAL. PRESS ALSO REPORTED THAT
FORMULA FOR DIVIDING PRODUCTION HAS NOT YET BEEN FIXED
BUT PRINCIPLE WAS ESTABLISHED THAT GOB WOULD RECEIVED
MORE PROPORTIONALLY FROM RICH FIND AND LESS FROM FIELD
MORE DIFFICULT TO EXPLOIT.
(SEE REFTEL B.)
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04940

- **Date:** July 31, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** URANIUM, EXPLORATION, CONTRACTS