---
title: "Establishment Of Narcotics Advisor Position In Usaid/Bolivia"
author: "Stedman"
date: "February 01, 1974"
editor: visual
cable-date: "February 01, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 2136"
cable-info: "Oct-01 Iso-00 Aid-20 Deae-00 Mms-03 Ss-20 Spc-03 Per-05 Abf-01 A-01 Drc-01 Rsc-01 /076 W --------------------- 046737 R 011814z Feb 74"
cable-subject: "Establishment Of Narcotics Advisor Position In Usaid/Bolivia"
cable-tags: "SNAR, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ00692"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "DRUG CONTROL, NARCOTICS, PERSONNEL APPOINTMENTS, PERSONNEL ASSIGNMENTS"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. In order to facilitate coordination with the Bolivians and to avoid the dissipation of authority and effectiveness which too much overlapping of responsibilities engenders, I have assigned clearly defined areas of jurisdiction to the individual members of the Narcotics Committee. In making these assignments, it became obvious to me that at this formative stage in the development of the Bolivian narcotics control effort, we need all the qualified personnel strength we have at the moment to isolate and cope with the problems in this major area of concern. We will not be able to replace or retain one of our key team members for the next fiscal year unless we get a new position.

2. I therefore request your assistance in assuring that an exclusively narcotics-related job is established in USAID/B as of the beginning of FY '75. The embassy will produce a revised NCAP budget for FY '75 incorporating this new cost should it be approved.

3. I do not foresee the need for this new position beyond FY '75. If the need should exist beyond that time, we could then study the matter again.

4. For the coming year, however, we do not want another enforcement officer. Instead, we need to increase our efforts of an advisory nature, our institution building role (including the establishment of a basic narcotics training facility in the Police Academy) and our research capabilities on the production, distribution and consumption of coca leaf during this first, formative year of Bolivia's concerted approach to the narcotics problem. USAID has the kind of man I envision for this role which will give us the kind of clout with the Bolivians that I want to have at this stage in our incipient narcotics relationship.

5. This request is strongly supported by the USAID Mission Director and the embassy's Narcotics Coordinator. The duties of the incumbent of this position will not impinge upon the work of DEA here. The two DEA agents presently on board are going to be fully occupied in the enforcement area, which for the next couple of years will include the responsibility of devising and implementing, in conjunction with the Bolivian Narcotics Director, U.S. Government commodity assistance and budgetary support for the operations of the Enforcement Department of Bolivia's narcotics entity. Stedman

***

#### Message Attributes

- **Document Number:** 1974LAPAZ00692

- **Date:** February 01, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** DRUG CONTROL, NARCOTICS, PERSONNEL APPOINTMENTS, PERSONNEL ASSIGNMENTS