---
title: "Bolivian Officials Responsible For Eastern Development Zone And Related Matters"
author: "Brewin"
date: "June 05, 1974"
editor: visual
cable-date: "June 05, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3300"
cable-info: "Oct-01 Iso-00 Fpc-01 Fea-02 Aec-11 Aid-20 Cea-02 Ciae-00 Ciep-02 Come-00 Dode-00 Eb-11 H-03 Inr-10 Int-08 L-03 Nsae-00 Nsc-07 Omb-01 Pm-07 Rsc-01 Sam-01 Sci-06 Sp-03 Ss-20 Str-08 Trse-00 Pa-04 Prs-01 Usia-15 Agr-20 Xmb-07 Drc-01 /196 W --------------------- 029938 R 051254z Jun 74"
cable-subject: "Bolivian Officials Responsible For Eastern Development Zone And Related Matters"
cable-tags: "BEXP, BMEP, ENRG, EMIN, BL"
cable-ref: "LA PAZ 3356; A-110; STATE 115983"
cable-doc-number: "1974LAPAZ03612"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "DEVELOPMENT PROGRAMS, TECHNICAL ASSISTANCE CONTRACTS, MINING INDUSTRY, GOVERNMENT PERSONNEL"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

1. PRINCIPAL BOLIVIAN OFFICIALS RESPONSIBLE FOR DEVELOPMENT
EASTERN REGIONAL DEVELOPMENT PROGRAM ARE:
MAJ. CARLOS MORALES, GENERAL MANAGER
EMPRESA NACIONAL DE SIDERURGIA (SIDERSA)
MINISTERIO DE MINERIA Y METALURGIA
LA PAZ, BOLIVIA


IG. CARLOS MIRANDA, DIRECTOR
DIRECCION GENERAL DE PETROLEOS
MINISTERIO DE ENERGIA E HIDROCARBUROS
EDIFICIO MINISTERIO DE MINAS, TERCER PISO
LA PAZ, BOLIVIA


ING. ROLANDO PRADA M., GENERAL MANAGER
OR ING. LUIS SALINAS E., PLANNING DIRECTOR






 051600Z


YACIMIENTOS PETROLIFEROS FISCALES BOLIVIANOS (YPFB)




                        

                  

CALLE BUENO S/N
LA PAZ, BOLIVIA


2. ACCORDING TO MAJOR CARLOS MORALES THREE OUT OF TOTAL 49 FIRMS
BEING CONSIDERED TO ACT AS PERMANENT ADVISER OF TYPE AND CONSTRUC-
TION OF IRON REDUCTION PLANT AND TO ADVISE AND ACT AS INSPECTORS
OF OTHER INDUSTRIAL CONSTRUCTION PROJECTS RELATIVE TO DEVELOPMENT
OF EASTERN BOLIVIA, ARE AMERICAN. OTHER SOURCES IN MINMINING
STATE AMERICAN-CANADIAN, WEST GERMAN, AND EUROPEAN MULTINATIONAL
FIRM ARE MOST SERIOUS CONTESTANTS. EMBASSY EXPECTING CONTRACT
TO BE MADE WITH ADVISORY ENGINEERING GROUP AFTER DISBURSEMENT BY
BRAZIL OF US$ 10,000,000 LOAN TO BOLIVIAN GOVERNMENT TO PAY FOR
FEASIBILITY STUDIES ON INDUSTRIAL DEVELOPMENT OF EASTERN BOLIVIA.
EMBASSY HAS NO ADDITIONAL INFORMATPON ON INDUSTRIAL PROJECTS UNDER
CONSIDERATION OTHER THAN RECENT INFORMATION SENT IN REFAIR AND
REFTEL. INDUSTRIAL COMPLEX REPORTEDLY MAY COST FROM US$ 700,000,000
TO US$ 1,200,000,000 INCLUDING 32-INCH GAS PIPELINE, MULTIPURPOSE
8-INCH PIPELINE, IRON-STEEL, CEMENT, AND UREA PLANTS, AND
INFRASTRUCTURE WORKS.
BREWIN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ03612

- **Date:** June 05, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** DEVELOPMENT PROGRAMS, TECHNICAL ASSISTANCE CONTRACTS, MINING INDUSTRY, GOVERNMENT PERSONNEL