---
title: "Farmabol Case"
author: "Stedman"
date: "June 28, 1974"
editor: visual
cable-date: "June 28, 1974"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC 3526"
cable-info: "Oct-01 Ara-16 Iso-00 Come-00 Trse-00 Pm-07 Ciae-00 Inr-10 Nsae-00 Rsc-01 Dode-00 L-03 Opic-12 Drc-01 /062 W --------------------- 076663 R 281930z Jun 74"
cable-subject: "Farmabol Case"
cable-tags: "BDIS, BL"
cable-ref: ""
cable-doc-number: "1974LAPAZ04221"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 JAN 1960"
cable-concepts: "n/a"
---


# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

::: {.cable-meta}
:::


1. CAPT AUGUSTO SANCHEZ, MANAGER OF FANAQUINA, PLANNING TO ARRIVE
WASHINGTON JULY 1. SANCHEZ TOLD EMBOFF THAT TRIP TO U.S. PRINCIPALLY
ON BUSINESS OF ARMED FORCES DEVELOPMENT CORPORATION (COFADENA) BUT HE
WILL BE CONTACTING FARMABOL'S LAWYER, HATHORN, AND HOPES TO MEET
WITH KELJIKAN IN NEW YORK


2. SANCHEZ WILL INDICATE TO THEM DESIRE TO BRING DISUPTE TO CLOSE
BECAUSE OF PROBLEM IT CAUSES FOR FANAQUINA'S FINANCIAL RECORDS. HE
STATES THAT UNLESS OTHER PROPOSAL FORTHCOMING, FANAQUINA WILL HAVE
TO BRING CASE BEFORE BOLIVIAN COURT. HE EXPECTS THAT COURT WOULD
DECIDE THAT FANAQUINA OWES SMALL QMOUNT (ESTIMATED US$4,000) TO
FORMER LESSEES OF FANAQUINA PLANT. AMOUNT WOULD BE DEPOSITED WITH
COURT AND OWNERS WOULD HAVE TO ESTABLISH RIGHT TO RECOVER IT SINCE,
HE CLAIMS, FARMABOL LEGAL STATUS IN BOLIVIA DOUBTFUL.


3. SANCHEZ MAY BE REACHED AT MILITARY ATTACHE'S OFFICE AT BOLIVIAN
EMBASSY, WASHINGTON.
STEDMAN

***

#### Message Attributes

- **Document Number:** 1974LAPAZ04221

- **Date:** June 28, 1974

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 JAN 1960

- **Concepts:** n/a
