---
title: "Walter Guevara Arze, Bolivia's New Interim President"
author: "Paul Boeker, US Ambassador to Bolivia"
date: "August 07, 1979"
editor: visual
cable-date: "August 07, 1979"
cable-from: "AmEmbassy La Paz"
cable-to: "SecState WashDC Immediate 7627"
cable-info: "Oct-01 Ads-00 Ciae-00 Dode-00 Nsae-00 Nsce-00 Sso-00 Icae-00 Inre-00 Pm-05 H-01 Inr-10 L-03 Pa-01 Sp-02 Ss-15 Io-14 Aid-05 Trse-00 Eb-08 Ssc-01 /081 W ------------------110143 070514z /10 O 070430z Aug 79"
cable-subject: "Walter Guevara Arze, Bolivia's New Interim President"
cable-tags: "PINT, PINR, BL"
cable-ref: ""
cable-doc-number: "1979LAPAZ06713"
cable-classification: "UNCLASSIFIED"
cable-declass-date: "01 jan 1960"
cable-concepts: "BIOGRAPHIC INFORMATION, PRESIDENT, INTERIM GOVERNMENT"
---

::: {.cable-meta}
:::

# DEPARTMENT OF STATE TELEGRAM
**UNCLASSIFIED**

2. **Summary:** In electing Walter Guevara Arze, 67, as Bolivia's first constitutionally-elected president in 13 years, the Congress has picked one of Bolivia's most intelligent and attractive moderate politicians. He is widely respected by those outside Bolivia who know him for his rational and direct approach to political problems. One of the founders of the MNR in the 40s, he has not recently been close to Victor Paz and is not a leading insider in that party. Following the 1952 MNR Revolution Guevara served as Foreign Minister (1952-56), Ambassador to France (1956-58) and Minister of Interior (1958-59). Guevara split with Victor Paz in 1959 and formed the Authentic Revolutionary Party, a conservative offshoot of the MNR. In the 1960's he again served as Foreign Minister (1967-68) and as Bolivia's Permanent Representative to the United Nations (1968-71). Following several years of exile in the mid-1970's Guevara returned to Bolivia and allied himself with Paz in both the 1978 and 1979 presidential elections. He was elected Senator from Cochabamba in the July 1979 elections and then President of the Senate from which position he emerged as Bolivia's interim president when the Congress was unable to choose between either of the two leading vote getters, Hernan Siles or Victor Paz. Although he has at times been critical of the US, Guevara is generally considered to be friendly towards the United States. The US should have a close and cooperative working relationship with Guevara. End summary.

3. Guevara was born in the city of Cochabamba on March 12, 1912 and attended primary and secondary school there. After serving in the Chaco War (1932-1935) and being decorated for bravery he graduated from the Law School of the University of San Andres in La Paz. He served as Director of the Miners' Bank (1937) and as a deputy in the Congress (1938) before being named Secretary-General of Government (1943-44), a position with cabinet rank. During the early 1940's Guevara participated, along with Victor Paz and Hernan Siles, in the founding of the MNR. He resigned his cabinet position in 1944 to make a successful bid for a seat in the Congress. After election, however, Guevara chose to accept a scholarship for postgraduate work in sociology at the University of Chicago. He remained in the US until 1946 when, following the overthrow of the government of Gualberto Villarroel, Guevara went into exile in Argentina. He returned to Bolivia in 1949 to engage in underground activities for the MNR. Following the MNR's successful revolution in 1952 Guevara was named Minister of Foreign Relations. Considered a moderate at this time Guevara was forced to resign this position in early 1956 because of a dispute with Juan Lechin, leader of the MNR's left wing. When Hernan Siles Zuazo was elected president in 1956 Guevara was named Ambassador to France and, in 1957, concurrently to Israel. Guevara returned from France in 1958 to enter the Siles cabinet as Minister of Government. He resigned this position in 1959 in a dispute with Paz and Lechin and formed his own conservative offshoot of the MNR, the Authentic Revolutionary Party (PRA).

4. In 1960 Guevara was the PRA's candidate for president of Bolivia. Guevara remained estranged from Paz during the latter's third term (1960-64) and went into exile from 1962 to 1963. He was elected a Senator in the national elections of 1966. From 1967 to 1968 he served as Minister of Foreign Affairs under President Barrientos and in 1968 was named Bolivia's Permanent Representative to the United Nations. He was dismissed in 1971 and returned to Bolivia. In 1974, following some criticism of the Banzer regime's policy toward Brazil, he was exiled to Paraguay. He later went to Caracas where he served as an advisor to Venezuelan President Carlos Andres Perez. Guevara returned to Bolivia in 1978 and patched up his longtime feud with Victor Paz in time to support the latter's campaign for president in 1978. When those elections were annulled and a new round called for July 1979 Guevara again supported Paz. In the elections Guevara was elected to the Senate from Cochabamba. Subsequently, he was elected President of the Senate from which position he became interim president of Bolivia when the Congress was unable to choose between either of the two leading vote getters in the July elections, Hernan Siles or Victor Paz.

5. In his early years Guevara was known as a leftist and in 1944 he publicly admitted that he was a Marxist and Soviet sympathizer. However, he began to move to the right and in the mid-1950's he was considered a moderate and by the 1960's a conservative. When he founded the PRA in 1959 he declared he favored private initiative over economic statism, a responsible and vigorous central government, business-like management of the mining industry, and a labor policy which recognizes that increased productivity is the only non-inflationary source of salary increases. Guevara's views are not believed to have changed significantly since then.

6. Hard-working, responsible, realistic, articulate and very intelligent, Guevara is an able negotiator and parliamentarian who gives meticulous attention to detail. He tends to be somewhat pedantic in his manner and at times approaches questions legalistically. Somewhat inscrutable and reserved on first acquaintance, he responds best to directness and simplicity of manner.

7. Although his strong personal and national pride has sometimes led him to be critical and resentful of the United States, he is generally considered to be friendly toward the US. He speaks good English, in addition to Spanish and French, and in years past was reportedly well-read on matters pertaining to the United States.

8. Guevara has been married twice. His first wife, Lola Anaya de Guevara, died in the mid-1950's. His second wife, Rosa Elena Rodriguez de Guevara, was born in Cochabamba and is 60 years old. He has three sons -- Walter (37) who attended St. Lawrence University, Ramiro (24) and Carlos (30). Moderate in his personal habits, Guevara drinks socially, enjoys puns, and in years past played poker, handball and golf, although he has not been seen on the golf course in the past two years.

***

#### Message Attributes

- **Document Number:** 1979LAPAZ06713

- **Date:** August 07, 1979

- **Classification:** UNCLASSIFIED

- **Declassified:** 01 jan 1960

- **Concepts:** BIOGRAPHIC INFORMATION, PRESIDENT, INTERIM GOVERNMENT